mitodl/open-discussions

.travis.yml
mit_open/settings.py
travis-docker-compose.yml

Fixes #6
Uses docker hub image for travis tests
The tests should now pass

Use docker hub image for travis tests

---

package.json

N/A
Bumps yarn version to fix node-sass issues.
Tests should pass after a fresh `docker-compose build`.

Upgrade yarn

---

docker-compose.yml

N/A
Remove unused reddit docker network
`docker-compose up` should work

Remove reddit docker network from docker-compose.yml

---

README.md

N/A
Adds instructions to the readme to configure local site
Make sure the instructions work for you

Add instructions to the readme for reddit env vars

---

open_discussions/settings.py
requirements.in
requirements.txt

Fixes #28 
Added DRF
No manual testing needed

Add django-rest-framework

---

README.md

Fixes #32 
Updates the readme to have the correct env var prefix
N/A

Update README to OPEN_DISCUSSIONS

---

channels/api.py
channels/api_test.py
channels/apps.py
themes/apps.py

Fixes #34 
Renames themes to channels
The app should start and serve content

Rename themes to channels

---

package.json
static/js/actions/index.js
static/js/actions/post.js
static/js/factories/channels.js
static/js/factories/channels_test.js
static/js/factories/posts.js
static/js/factories/posts_test.js
static/js/factories/util.js
static/js/flow/discussionTypes.js
static/js/lib/redux_rest.js
static/js/reducers/channels.js
static/js/reducers/frontpage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/reducers/posts.js
static/js/reducers/posts_for_channel.js
yarn.lock

none, I did this as initial work for starting on #15 and figured I might as well open as a separate PR.
This sets up reducers for posts, channels, posts-for-channels, and the frontpage. there are also random data generators for relevant things, for testing and development.
tests should pass, code should be reasonably clean.

set up basic front-end data model

---

flow-typed/npm/react-router_v4.x.x.js
static/js/containers/App.js

N/A
Added flow defs for react-router

Added flow defs for react-router

---

static/js/components/PostSummary.js
static/js/components/PostSummary_test.js
static/js/factories/posts.js
static/js/factories/posts_test.js
static/js/flow/discussionTypes.js
static/scss/layout.scss
static/scss/post.scss

N/A
Adds a common post summary component. 
*Note:* this component assumes `created` has been parsed to a moment instance.
Passing tests should be sufficient

Added common PostSummary component

---

open_discussions/templates/base.html
package.json
static/js/components/Card.js
static/js/components/Card_test.js
static/js/components/PostList.js
static/js/components/PostList_test.js
static/js/components/PostSummary.js
static/js/components/PostSummary_test.js
static/js/containers/App.js
static/js/containers/HomePage.js
static/js/lib/maps.js
static/js/lib/maps_test.js
static/js/reducers/channels.js
static/js/reducers/frontpage.js
static/js/reducers/index_test.js
static/js/reducers/posts.js
static/js/reducers/posts_for_channel.js
static/scss/_variables.scss
static/scss/card.scss
static/scss/layout.scss
static/scss/post.scss
static/scss/postlist.scss
yarn.lock

part of #15 
This implements a very basic display of the frontpage posts on the homepage. Here's what it looks like rn:
there is still some styling work to be done, and obviously all the surrounding components that appear in the mockups have not been built yet (the channel list and so on).
If you go to the homepage, you should see something like the screenshot.

frontpage UI work

---

cassettes/channels.views_test.test_create_channel.json
channels/serializers.py
channels/serializers_test.py
channels/views_test.py
open_discussions/urls.py
open_discussions/views.py
static/js/actions/index.js
static/js/components/ChannelSidebar.js
static/js/components/ChannelSidebar_test.js
static/js/components/Loading.js
static/js/components/Loading_test.js
static/js/containers/App.js
static/js/containers/ChannelPage.js
static/js/containers/HomePage.js
static/js/factories/channels.js
static/js/factories/channels_test.js
static/js/flow/discussionTypes.js
static/js/flow/restTypes.js
static/js/lib/api.js
static/js/reducers/channels.js
static/scss/layout.scss
static/scss/sidebar.scss

Part of #26 
Adds the channel listing page.
Go to /channels/something and verify you see the page as shown in the screenshot.
Also go to `/api/v0/channels` and `/api/v0/channels/pics` and verify you see `public_description` in there now. it will probably be empty strings unless you've set it on a sub.

Implement UI for channel page

---

static/js/factories/comments.js
static/js/factories/comments_test.js
static/js/factories/util.js
static/js/flow/discussionTypes.js
static/js/lib/redux_rest.js
static/js/reducers/comments.js
static/js/reducers/index_test.js
static/js/reducers/posts.js

part of what we need for #27 
This adds a comments factory and a comments reducer.
make sure tests pass and the code looks reasonable, there is not any functional change (yet!).

comments factory and reducer

---

static/js/lib/api.js
static/js/lib/api_test.js
static/js/reducers/channels.js
static/js/reducers/index_test.js
static/js/reducers/posts.js
static/js/reducers/posts_for_channel.js

Part of #26
Integrates with the channels and posts APIs
- Ensure you have a subreddit with posts/comments.
- Got to /channel/[channelname] and verify you see the correct data.
(Optional)

Integrate with APIs

---

cassettes/channels.views_test.test_frontpage.json
channels/api.py
channels/api_test.py
channels/urls.py
channels/urls_test.py
channels/views.py
channels/views_test.py

Rebased on #62 
Fixes #51 
Adds a rest API for the front page
Go to `/api/v0/frontpage/`

Added front page API

---

open_discussions/templates/base.html
open_discussions/views_test.py

None
Add missing common bundle
Site should work in production

Add common bundle

---

webpack.config.dev.js

None
Adds configuration for the commons chunk plugin for dev environments
Restart the web server locally and go to the front page

Add commons chunk for dev

---

open_discussions/urls.py
static/js/actions/forms.js
static/js/actions/index.js
static/js/components/admin/ChannelEditForm.js
static/js/components/admin/ChannelEditForm_test.js
static/js/containers/App.js
static/js/containers/admin/AdminPage.js
static/js/containers/admin/CreateChannelPage.js
static/js/factories/channels.js
static/js/factories/channels_test.js
static/js/flow/discussionTypes.js
static/js/flow/formTypes.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/lib/channels.js
static/js/lib/channels_test.js
static/js/lib/form_actions.js
static/js/lib/form_actions_test.js
static/js/lib/url.js
static/js/lib/url_test.js
static/js/reducers/channels.js
static/js/reducers/forms.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/scss/form.scss
static/scss/layout.scss

Fixes #16 
Adds a page to create a channel
Go to http://localhost:8063/manage/channel/new and fill in the form. Verify you're redirected to your new channel.
No validation yet

Add page to create channel

---

README.md

No ticket
Adds some detail to the README
No testing needed

Added detail to documentation

---

open_discussions/urls.py
static/js/Router.js
static/js/actions/forms.js
static/js/components/Card.js
static/js/components/ChannelSidebar.js
static/js/components/ChannelSidebar_test.js
static/js/components/CreatePostForm.js
static/js/containers/App.js
static/js/containers/ChannelPage.js
static/js/containers/CreatePostPage.js
static/js/containers/CreatePostPage_test.js
static/js/entry/root.js
static/js/flow/discussionTypes.js
static/js/global_init.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/lib/posts.js
static/js/lib/posts_test.js
static/js/lib/url.js
static/js/lib/url_test.js
static/js/lib/util.js
static/js/reducers/forms.js
static/js/reducers/posts.js
static/js/util/integration_test_helper.js
static/js/util/test_utils.js
static/scss/createPost.scss
static/scss/layout.scss

Fixes #17 
Adds UI to create a post for a channel
Click the 'Submit a new post' link and fill out the form. You should be able to create URL and text posts.

UI to create a new post

---

hot-reload-dev-server.js

None
Fixes CORS issue with webpack hot reloading
Change a CSS style and observe that the browser adopts the new style without refreshing

Fix hot reloading

---

static/js/components/CommentTree.js
static/js/components/CommentTree_test.js
static/js/components/CreateCommentForm.js
static/js/components/CreateCommentForm_test.js
static/js/containers/CreatePostPage.js
static/js/containers/PostPage.js
static/js/containers/admin/CreateChannelPage.js
static/js/factories/comments.js
static/js/factories/comments_test.js
static/js/flow/discussionTypes.js
static/js/flow/formTypes.js
static/js/reducers/comments.js
static/js/reducers/comments_test.js
static/js/reducers/forms.js
static/js/reducers/forms_test.js
static/js/reducers/index_test.js
static/js/util/integration_test_helper.js
static/scss/comment.scss

Fixes #18 
This adds UI to add comments  in reply to posts and other comments.
Verify you can comment on a post and comment.

Added commenting on posts and comments

---

static/js/containers/ChannelPage_test.js
static/js/containers/CreatePostPage_test.js
static/js/containers/HomePage_test.js
static/js/containers/PostPage_test.js
static/js/util/integration_test_helper.js

none
I noticed we had started adding container tests, but we don't yet have them everywhere. this just adds some very basic tests that the container loads, hits the APIs, etc.
tests should pass, code should make sense.

added very basic tests for the container components

---

static/js/components/PostDisplay.js
static/js/components/PostDisplay_test.js
static/js/components/PostList.js
static/js/components/PostList_test.js
static/js/containers/ChannelPage.js
static/js/containers/HomePage.js
static/js/containers/PostPage.js
static/js/lib/api.js
static/js/lib/redux_rest.js
static/js/reducers/post_upvotes.js
static/js/reducers/post_upvotes_test.js
static/js/util/api_actions.js
static/js/util/api_actions_test.js
static/scss/_variables.scss
static/scss/post.scss

Fixes #70 
Adds upvoting for posts
You should be able to add and remove an upvote on the front, channel, and indidvual post pages.

Integrate UI for upvoting posts

---

static/js/containers/ChannelPage_test.js
static/js/factories/util.js
static/js/reducers/index_test.js

none
I was looking at codecov and noticed there was nothing exercising the `post` functionality for the channel reducer, so I added a thing for that and deleted an unused function.
tests should pass, code should look reasonable

little test coverage improvement

---

README.md

No ticket
Updated README with more accurate setup details (discovered while getting this running locally for Rob)
N/A
Accompanying reddit-config PR: https://github.com/mitodl/reddit-config/pull/12

Updated README with more accurate setup details

---

static/js/containers/HomePage.js

none
this just removes a line which was deleted in #95 and (I think) reincluded in #90 
it should look like this:
not this:

remove accidental change

---

package.json
static/scss/layout.scss
yarn.lock

this adds the bulma framework and imports it
things should look weird?

add bulma, import it

---

package.json
static/js/components/CommentTree.js
static/js/components/CommentTree_test.js
static/js/components/CommentVoteForm.js
static/js/components/CommentVoteForm_test.js
static/js/containers/PostPage.js
static/js/containers/PostPage_test.js
static/js/entry/root.js
static/js/factories/comments.js
static/js/factories/util.js
static/js/flow/discussionTypes.js
static/js/global_init.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/lib/comments.js
static/js/lib/comments_test.js
static/js/lib/util.js
static/js/lib/util_test.js
static/js/reducers/comments.js
static/js/reducers/comments_test.js
static/scss/comment.scss

Fixes #84
Adds UI to upvote or downvote a comment
Click the up or down button next to the comment. If you click a button and it's already highlighted, it should stop being highlighted.
I'm not sure why the score doesn't change. We should look into that at some point with more than one user

Added UI to upvote or downvote a comment

---

package.json
static/scss/layout.scss
yarn.lock

This reverts commit 10973b8fcddfa63f976820cc36b232a1012a9657.
seems like we're not using this, so let's delete it.

Revert "Added bulma for evalutation"

---

open_discussions/permissions.py

N/A
Undoes a :man_facepalming: 
Tests pass

Removed print statement

---

static/js/components/CreateCommentForm.js
static/js/components/CreateCommentForm_test.js

part of #125 
In the mocks the 'reply' textfield for a top-level comment (i.e. a comment replying to a post) is supposed to be always open. Currently, it's not, and you need to click a 'reply' button to open it and start composing a comment.
This refactors the code for rendering the commenting form, and separates it into two separate components, one for comment replies and one for post replies. 
Commenting on posts, replying to comments etc should all work as expected.

refactor comments so post reply is always open

---

static/js/components/CreatePostForm.js
static/js/components/Toolbar.js
static/scss/_variables.scss
static/scss/comment.scss
static/scss/createPost.scss
static/scss/form.scss
static/scss/navigation.scss

fixes #85 
- Fixes some of the button styles, with hover states. 
- Makes the navbar title link to the root directory and the MIT logo link to mit.edu
- Removes the text "Posting to [channelname] in the submit post page.
- Tweaks some of the form styling, and the tab styling.
- Slight change to page background color.
- Other minor tweaks.
See that the styles look correct, and the code is valid.

more style tweaks

---

channels/api_test.py

None
Adds a test to cover configuration of the reddit api client
N/A

Added test for Api constructor

---

app.json

Part of #165 
Adds missing env vars to app.json for deployment
N/A

Added missing vars to app.json

---

app.json

N/A
Sets the default for S3 requried to False
N/A

Fixed app.json to not require S3

---

static/scss/comment.scss
static/scss/post.scss
static/scss/profile-image.scss

This fixes a few layout problems associated with the new profile images in the post details page. Also makes the profile images slightly smaller.
See that the layout looks correct on a phone layout for the post details page.

Responsive tweaks to Profile image and comment layout

---

cassettes/channels.views_test.test_add_subscriber.json
cassettes/channels.views_test.test_detail_subscriber.json
cassettes/channels.views_test.test_remove_subscriber.json
channels/api.py
channels/api_test.py
channels/serializers.py
channels/serializers_test.py
channels/urls.py
channels/views.py
channels/views_test.py

closes #112
Adds add/remove subscriber REST API
Use the API and check the results on the reddit UI

Added add/remove subscriber REST API

---

channels/views.py
channels/views_test.py

None
Fix linting errors due to merges. See https://travis-ci.org/mitodl/open-discussions/jobs/281329771

Fix linting errors

---

channels/api.py

Fixes #186 
Disables praw from checking for updates
Hit the home page and don't see the message to update praw logged

Added flag to not check for praw updates

---

static/js/components/CreatePostForm.js
static/js/containers/CreatePostPage_test.js

closes #207
workaround for this: https://bugzilla.mozilla.org/show_bug.cgi?id=40545
Open the create post page in firefox. You should see stuff in the dropdown menu, be able to make a post, etc.

fix channel select in firefox

---

static/js/flow/discussionTypes.js
static/js/reducers/comments.js

none
just pulls some common stuff from `Post` and `Comment` into a shared type
flow should pass

small refactor to discussion flow types

---

static/js/components/PostDisplay.js
static/js/components/PostDisplay_test.js

closes #213 
tweaks the post authorship display slightly, in-line with the mocks.
make sure what shows up in the UI resembles the mocks linked on the issue, that nothing is broken, etc.

tweak post byline

---

package.json
yarn.lock

None
Upgrades eslint config for no-throw-literal rule
N/A

Upgrade eslint config

---

open_discussions/settings.py

https://github.com/mitodl/micromasters/pull/3615
Fixes location of root logger
See instructions in https://github.com/mitodl/micromasters/pull/3615

Fix root logger location

---

docs/_config.yml
docs/configuration.md
docs/index.md
docs/integration.md
docs/operations.md

N/A
Add docs and sets them up so they'll get compiled with gh-pages for easy access/navigation. Note: needs to get merged to master before that piece works though.
N/A

Added docs with gh-pages style.

---

README.md
RELEASE.rst
docker-compose.yml
docs/_config.yml
docs/configuration.md
docs/index.md
docs/integration.md
docs/operations.md
open_discussions/settings.py
static/js/components/PostDisplay.js
static/js/components/PostDisplay_test.js
static/js/containers/Drawer.js
static/js/lib/url.js
static/js/lib/url_test.js
static/scss/post.scss

Release 0.2.2

---

README.md
travis/Dockerfile-travis-watch
travis/Dockerfile-travis-watch-build
webpack_dev_server.sh

Related to https://github.com/mitodl/micromasters/issues/3651
Uses `yarn install --frozen-lockfile` which errors if an upgrade is needed
N/A

Use yarn install --frozen-lockfile

---

requirements.in
requirements.txt

same thing as https://github.com/mitodl/micromasters/pull/3666

bump psycopg version

---

channels/test_utils.py

None
Adds a try/finally block for slightly more robust test code
This only affects testing code so it's probably not necessary

Use try/finally in context managers

---

Procfile
RELEASE.rst
app.json
channels/api.py
docker-compose.yml
open_discussions/settings.py

Release 0.3.2

---

RELEASE.rst
channels/conftest.py
channels/views_test.py
open_discussions/factories.py
open_discussions/settings.py
profiles/factories.py
profiles/serializers_test.py
profiles/views_test.py

Release 0.3.4

---

cassettes/channels.views_test.test_get_channel.json
cassettes/channels.views_test.test_list_channels.json
channels/factories.py
channels/views_test.py
factory_data/channels.views_test.test_create_channel_nonstaff.json
factory_data/channels.views_test.test_get_channel.json
factory_data/channels.views_test.test_list_channels.json
factory_data/channels.views_test.test_list_subscribers_not_allowed.json
factory_data/channels.views_test.test_patch_channel_nonstaff.json

#333 
This fixes the factory_data serialization so it doesn't error on subsequent runs. It also includes some ancillary changes (e.g. new fixtures in channels/views_test.py) because it was cherry-picked from another WIP branch.
Tests should pass. Delete the affected cassettes and regenerate them and then ensure a second test run passes.

Stabilized factory serialization

---

open_discussions/urls.py
static/js/components/CreatePostForm.js
static/js/containers/App.js
static/js/containers/ContentPolicyPage.js
static/js/lib/url.js
static/scss/content-policy.scss
static/scss/layout.scss

Fixes #314 
Adds the content policy page
Go to the new post page, click on the content policy link. It should go to the content policy page.

Added content policy page

---

static/js/components/CreatePostForm.js
static/js/containers/ContentPolicyPage.js
static/js/containers/CreatePostPage_test.js

closes #343
this just makes a quick change to the page title and the text of one link.
Just make sure the changes show up.

fix content guideline copy

---

static/js/components/ChannelSidebar.js
static/js/components/ChannelSidebar_test.js
static/js/factories/channels.js
static/js/flow/discussionTypes.js

Fixes #365 
Fixes the field used for the about page
Verify that the text shows up in the about panel

Fix field name for channel description

---

RELEASE.rst
cassettes/channels.views_test.test_get_post_stickied.json
cassettes/channels.views_test.test_list_posts_stickied.json
cassettes/channels.views_test.test_update_post_nonmoderator_cant_sticky.json
cassettes/channels.views_test.test_update_post_stickied.json
cassettes/channels.views_test.test_update_post_unsticky.json
channels/api.py
channels/serializers.py
channels/views_test.py
factory_data/channels.views_test.test_get_post_stickied.json
factory_data/channels.views_test.test_list_posts_stickied.json
factory_data/channels.views_test.test_update_post_nonmoderator_cant_sticky.json
factory_data/channels.views_test.test_update_post_stickied.json
factory_data/channels.views_test.test_update_post_unsticky.json
open_discussions/settings.py
static/js/factories/posts.js
static/js/factories/posts_test.js
static/js/flow/discussionTypes.js
static/scss/_variables.scss
static/scss/channel.scss
static/scss/layout.scss

Release 0.5.2

---

channels/conftest.py
channels/serializers.py
conftest.py
open_discussions/settings.py
profiles/views_test.py

Fixes #377 
Changes `stickied` to not be required, fixing the validation issue when creating a post
Create a new post

Make stickied not required

---

RELEASE.rst
open_discussions/settings.py
package.json
static/js/actions/ui.js
static/js/components/ExpandedPostDisplay.js
static/js/components/ExpandedPostDisplay_test.js
static/js/components/material/Snackbar.js
static/js/containers/App.js
static/js/containers/PostPage.js
static/js/containers/PostPage_test.js
static/js/factories/posts.js
static/js/factories/posts_test.js
static/js/flow/discussionTypes.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/lib/channels.js
static/js/lib/redux_rest.js
static/js/reducers/index_test.js
static/js/reducers/post_removed.js
static/js/reducers/post_removed_test.js
static/js/reducers/ui.js
static/js/util/api_actions.js
static/js/util/api_actions_test.js
static/scss/layout.scss
yarn.lock

Release 0.6.1

---

static/js/components/CommentTree.js

N/A
Refactors `CommentTree` to an ES6 class so we don't have to throw a `props` party.
No regressions in tests, should be able to comment, upvote, downvote, edit, etc

Refactored CommentTree to make it classy

---

package.json
yarn.lock

doing this as part of #234 
upgrades redux-hammock to the latest version
Make sure everything is working ok

upgrade the hammock package

---

static/js/actions/moderation.js
static/js/components/CommentRemovalForm.js
static/js/components/CommentRemovalForm_test.js
static/js/components/CommentTree.js
static/js/components/CommentTree_test.js
static/js/containers/PostPage.js
static/js/containers/PostPage_test.js
static/js/factories/comments.js
static/js/factories/comments_test.js
static/js/flow/discussionTypes.js
static/js/lib/util.js
static/js/lib/util_test.js
static/js/reducers/index.js
static/js/reducers/moderation.js
static/js/reducers/moderation_test.js
static/js/util/api_actions.js
static/js/util/api_actions_test.js
static/js/util/integration_test_helper.js
static/scss/comment.scss
yarn.lock

Closes #278 
Adds links and confirmation dialog (on remove only) for removing/adding comments.
- Be sure you don't see these options as a non-moderator user
- Verify that clicking remove and approve does what you would expect

Add comment removal UI

---

test_requirements.txt

None
Fixes pylint bug by pinning a dependency

Pin astroid to fix pylint issue

---

cassettes/channels.views_test.test_create_channel_no_descriptions.json
channels/serializers.py
channels/views_test.py
factory_data/channels.views_test.test_create_channel_no_descriptions.json

Fixes #411 
Make `public_description` optional since we don't need to require it right now
Create a channel via the API gui but don't pass a `public_description`

Changed public_description to be optional on channel creation

---

cassettes/channels.views.reports_test.test_report_comment.json
cassettes/channels.views.reports_test.test_report_post.json
channels/api.py
channels/api_test.py
channels/serializers.py
channels/serializers_test.py
channels/urls.py
channels/views/reports.py
channels/views/reports_test.py
factory_data/channels.views.reports_test.test_report_comment.json
factory_data/channels.views.reports_test.test_report_post.json

Fixes #197
Adds an api for reporting posts and comments to moderators
Go to /api/v0/reports/ and POST a new report (e.g. `{'comment_id': 'ID', 'reason': 'spam'} and verify in the reddit UI that this shows up for your moderator user under the reports.

Added api to report posts and comments (#197)

---

static/images/mit-logo-ltgray-white@72x38.svg
static/js/components/Footer.js
static/js/containers/App.js
static/scss/_variables.scss
static/scss/footer.scss
static/scss/layout.scss

closes #218 
closes #256 
This adds a footer, following the design posted on #256 
Look at the app, and make sure that things look legit. It should look alright on a phone too.

add footer

---

cassettes/channels.views.frontpage_test.test_frontpage_sorted[hot].json
cassettes/channels.views.frontpage_test.test_frontpage_sorted[new].json
cassettes/channels.views.frontpage_test.test_frontpage_sorted[top].json
cassettes/channels.views.posts_test.test_list_posts_sorted[hot].json
cassettes/channels.views.posts_test.test_list_posts_sorted[new].json
cassettes/channels.views.posts_test.test_list_posts_sorted[top].json
channels/api.py
channels/api_test.py
channels/constants.py
channels/factories.py
channels/serializers.py
channels/utils.py
channels/utils_test.py
channels/views/conftest.py
channels/views/frontpage.py
channels/views/frontpage_test.py
channels/views/posts.py
channels/views/posts_test.py
factory_data/channels.views.frontpage_test.test_frontpage_sorted[hot].json
factory_data/channels.views.frontpage_test.test_frontpage_sorted[new].json
factory_data/channels.views.frontpage_test.test_frontpage_sorted[top].json
factory_data/channels.views.posts_test.test_list_posts_sorted[hot].json
factory_data/channels.views.posts_test.test_list_posts_sorted[new].json
factory_data/channels.views.posts_test.test_list_posts_sorted[top].json

Fixes #192 
Adds sorting to the channel and frontpage apis
- Verify the existing frontpage and channels sort exactly the same as master
- Verify you can pass alternative sorting methods to the api directly (e.g. `/api/v0/channels/:channel_name/posts/?sort=top|hot|new`)
Note: you need a decent variety of posts/comments/users to make these sorts sufficiently different

Added sorting to channel and frontpage apis

---

docs/design/email_notification.md
docs/design/index.md
docs/index.md

[Rendered](https://github.com/mitodl/open-discussions/blob/507961a85f944ce20e2d6153ed77d297e1625912/docs/design/email_notification.md)
Design for #450 and #464
Covers common design requirements of both of these tickets.

Proposed design for email notifications

---

static/js/components/admin/CreateChannelForm.js
static/js/components/admin/CreateChannelForm_test.js
static/js/components/admin/EditChannelForm.js
static/js/components/admin/EditChannelForm_test.js
static/js/containers/admin/CreateChannelPage.js
static/js/containers/admin/EditChannelPage.js

I feel like having a `CreateChannelPage` but a `ChannelCreateForm` is a little inconsistent, why not a `CreateChannelForm` instead? So, I'm proposing this change.

me, worrying overmuch about naming

---

open_discussions/settings.py

**_Blocked for merge until we've confirmed rc/prod environments are ready for this to run on a regular basis._**
Fixes #536 
Adds the email tasks to the crontab
We already know these tasks work individually, so just ensure the configuration looks correct and that celery worker will start.

Added email tasks to crontab

---

mail/templates/email_base.html
mail/templates/frontpage/body.html
mail/templates/frontpage/subject.txt

#572
This changes the email subject to be  the text of the first post in the list. 
It also remove the header that says "Open Discussions," and changes the intro text to "Here are some new posts that have been added since you last checked." 
Send emails and see that it works.

Several small changes to email digest

---

channels/api.py
channels/api_test.py

None
Fixes a recurring 401 error @roberthouse54 has been getting. This deletes the relevant tokens and tries one more time to get a client.
Not sure how to reproduce

Fix 401 auth errors

---

static/js/components/Navigation.js
static/js/components/Navigation_test.js
static/scss/navigation.scss

closes #545 
it adds a link to the settings page to the navigation menu
Make sure it shows up, and takes you to the right place!

add a link to the settings

---

mail/templates/email_base.html
mail/templates/frontpage/body.html

Closes #566
Adds a "Read More" button to the digest email that links to the discussions home page
See that it works and displays properly.

Adds a read more button to digest email

---

docker-compose.travis.yml

None
Fix Travis complaining about missing environment variables with Celery
N/A

Add missing environment variable for Travis

---

notifications/notifiers/base_test.py

Fixes #608 
The logic in `BaseNotifier` is actually sound, but when `now_in_utc` returned a time when the hour component was less than 12 hours, the previous 12 hour offset test case that expected `can_notify` to return a certain way returned the opposite. I've updated the test to use a more appropriate time and additionally mock `now_in_utc`
The tests should pass, to be really sure, you'll need to run them between midnight and noon in utc (8pm - 8am EST).

Fix failing test

---

static/scss/createPost.scss
static/scss/embedly.scss

Some minor tweaks to embedly styling, margins, and thumbnail image layout.
Make sure that the thumbnail images for posts do not overflow their container, and that the layout does not break.

embedly styling

---

Aptfile
app.json

- None
- Fix the build on heroku by adding an Aptfile
Once merged, the heroku deployment should work again

Aptfile for heroku

---

static/scss/embedly.scss

closes #757
This PR fixes a CSS issue. I described what the issue is a little bit in the issue.
Make sure you can repro the issue. Here's a soundcloud link which should do the trick:
https://soundcloud.com/guardianbookspodcast/guardian-books-best-short-stories-series-a-christmas-preview
It should block out the whole UI (lol). It should be fixed on this branch.

fix styling for iframe embeds

---

channels/api.py
channels/api_test.py

No ticket
Fixes faulty downvote logic and adds tests. There was a typo that prevented downvotes from being processed
Downvote something, check the request & response
😬

Fixed faulty downvote logic and added tests

---

config/nginx.conf.erb

#763
Hopefully gets rid of the error on login from Touchstone related to the uwsgi port number.
Nothing should break.

Nginx headers for Touchstone

---

static/js/hoc/withForm.js
static/js/hoc/withForm_test.js
static/js/lib/forms.js
static/js/lib/forms_test.js
static/js/lib/redux_props.js
static/js/lib/redux_props_test.js

Prereq to #650 
This adds utilities to avoid boilerplate around how we handle form events. You can look in the aforementioned PR to see how it's used. I did not add any usages of these in this PR to keep scope down.

Make form pages more ergonomic

---

fixtures/reddit.py
search/serializers_test.py

No ticket
Minor refactor for serializer tests that makes use of the reddit object fixtures that were created for a separate feature
`search/serializers_test.py` and `fixtures/reddit.py`
I initially wrote these as part of #739 since there was a serialization bug that wasn't caught due to lack of tests. Then some tests were written and merged into master while that PR was still open. I decided it was best to drop my tests for that PR and open this separately

Minor serializer test refactor

---

app.json

None
Add a couple required environment variables to app.json to get the review build to work
N/A

Add required environment variables to app.json

---

open_discussions/test_utils.py

N/A
Fixes a particular lint error that only happens locally and shouldn't be happening.
Tests should pass locally in this branch, fail on the lint in master

Fixed locally failing lint

---

docker-compose.yml

N/A
Makes stdin work under `uwsgi` when it doesn't
App will start locally

Require uwsgi to honour stdin locally for debugging

---

static/scss/button.scss

none
The new drawer overrode our styling for the submit post button, this just adds an `!important` (yes, I know...) to fix it.
make sure it's blue!

return submit post button color to blue

---

authentication/urls.py

No ticket
Adds logout url back in after accidental removal in #861 
Use the logout link

Added logout url back in after accidental removal

---

package.json
static/js/containers/App.js
static/js/containers/ChannelModerationPage.js
static/js/containers/ChannelPage.js
static/js/containers/ContentPolicyPage.js
static/js/containers/CreatePostPage.js
static/js/containers/PostPage.js
static/js/containers/PostPage_test.js
static/js/containers/ProfileEditPage.js
static/js/containers/ProfilePage.js
static/js/containers/SettingsPage.js
static/js/containers/admin/CreateChannelPage.js
static/js/containers/admin/EditChannelAppearancePage.js
static/js/containers/admin/EditChannelBasicPage.js
static/js/containers/auth/AuthRequiredPage.js
static/js/containers/auth/InactiveUserPage.js
static/js/containers/auth/LoginPage.js
static/js/containers/auth/LoginPasswordPage.js
static/js/containers/auth/PasswordResetConfirmPage.js
static/js/containers/auth/PasswordResetPage.js
static/js/containers/auth/RegisterConfirmPage.js
static/js/containers/auth/RegisterDetailsPage.js
static/js/containers/auth/RegisterPage.js
static/js/lib/util.js
static/js/lib/util_test.js
yarn.lock

Closes #866
Adds post description meta tag to post detail page header.
Replaces `react-document-title` plugin with `react-meta-tags`.
Load a post detail page, use the HTML element inspector to examine the rendered page and verify that the &lt;title&gt; tag == the post title and that there is a &lt;meta&gt; tag with name="description" and content == the post text (up to 300 characters max).

Description metatag

---

static/js/factories/channels.js
static/js/factories/channels_test.js
static/js/flow/discussionTypes.js
static/js/lib/api.js
static/js/lib/redux_rest.js
static/js/reducers/channel_contributors.js
static/js/reducers/channel_contributors_test.js

Part of #864 
Adds reducer and fetch function for contributors
There's no code using this yet

Add reducer and API function for contributors

---

static/js/lib/api.js
static/js/lib/api_test.js
static/js/reducers/channel_contributors.js
static/js/reducers/channel_contributors_test.js
static/js/reducers/channel_moderators.js
static/js/reducers/channel_moderators_test.js

Part of #864 
Adds functions and reducer infrastructure for adding or removing contributors or moderators
There is no UI yet

Add functions to add and remove moderators and contributors

---

cassettes/channels.views.posts_test.test_create_text_post_blank.json
channels/api_test.py
channels/serializers.py
channels/serializers_test.py
channels/views/posts_test.py
factory_data/channels.views.posts_test.test_create_text_post_blank.json

Closes #907 
Makes the body optional when creating a text post (via PostSerializer) on the backend
- Go to http://od.odl.local:8063/api/v0/channels/<your_channel>/posts/ (logged in as a contributor or moderator for that channel)
- Enter the following in the content text area then click the `POST` button:
```{ "title": "My Blank Post" }```
- You should get a valid response, and the JSON should include:
```
{
"text": "",
"title": "My Blank Post",
...
}
```
`channels.serializers.PostSerializer.create`
The reddit api requires that either `text` or `url` not be None, so the serializer will make `text` == an empty string if both `url` and `text` are None

Make text post body optional

---

static/js/reducers/channel_contributors.js
static/js/reducers/channel_contributors_test.js
static/js/reducers/channel_moderators.js
static/js/reducers/channel_moderators_test.js

Part of #864 
Add some logic to remove duplicate moderators and contributors
No front end UI yet

Remove duplicates when adding a new moderator or contributor

---

mail/verification_api_test.py
open_discussions/urls.py
static/js/containers/App.js
static/js/lib/url.js

Fixes #933 
Renames the frontend url
Go to /signup and verify you can complete a registration

Rename /register -> /signup

---

channels/serializers.py
channels/serializers_test.py

Part of #864 
Updates REST API to allow adding moderators and contributors by email address
N/A, no user facing portion yet

Implement adding contributors and moderators by email

---

static/js/components/Embedly.js
static/js/components/Embedly_test.js
static/js/components/ExpandedPostDisplay.js
static/js/components/ExpandedPostDisplay_test.js
static/js/lib/posts.js
static/scss/embedly.scss
static/scss/post.scss

closes #925 
This implements a few tweaks to the embedly display for links (not youtube videos or something like that)
Make a post with something like a nytimes article, or really any random website. Look over the requirements on the issue and make sure everything is handled and that it looks ok.

tweak embedly display

---

static/scss/admin.scss

Fixes #977 
Fixes a CSS regression. It should only apply to the membership pages, not all edit channel pages
View the edit channel appearance and basic pages and verify the cancel and submit buttons look good.

Fix save, cancel button alignment

---

pull_request_template.md

N/A
Adds some checkboxes for the submitter to check for PRs

Added some PR template checkboxes

---

open_discussions/views.py
open_discussions/views_test.py

Fixes #1029 
This adds a redirect to /complete/micromasters/ if you have a JWT token that has the `"provider"` key on it. This causes that JWT to be redeemed for a django session so we can lookup the user correctly in the index view
- First, make sure you're on master for discussions and micromasters
- Make sure in MM, this env var does not have `/complete/micromasters/` in it: `OPEN_DISCUSSIONS_REDIRECT_URL=http://od.dev.local:8063/`
- Login to micromasters and navigate to discussions. You should see a 500 error regarding not being able to find the `User` record.
- Checkout this branch and reload the page, you should see a redirect to /complete/micromasters, then get redirected back to your original page.

Added redirect for new JWT tokens to /complete/provider

---

static/js/hoc/withChannelSidebar.js
static/js/hoc/withCommentModeration.js
static/js/hoc/withForm.js
static/js/hoc/withPostModeration.js
static/js/hoc/withSingleColumn.js
static/js/util/integration_test_helper.js

N/A
Upgrades our HOC to specify `WrappedInstance` (like `connect()`) and updated the integration test helper to traverse those
Tests pass

Added WrappedComponent to our HOCs and taught the helper render how to traverse

---

static/js/components/Toolbar.js
static/js/components/Toolbar_test.js
static/scss/navigation.scss

Fixes #678 
Adds a login button to the top right of the nav
Test that you see/don't see the button if `FEATURE_EMAIL_AUTH` is on/off

Login button on header

---

static/js/factories/channels.js

Fixes #1042 
Fixes possibility of username collisions for our JS moderator and contributor factories
Tests should pass. I don't believe there's a practical was to test this since the probability of hitting this is low.

Fixed contributor and moderator factories for username collisions

---

search/indexing_api.py

none
fixes a typo in the error log
I suppose you could try to generate the error, but it's just a one-character change.

fix typo in error log

---

open_discussions/urls.py

Fixes #1056 
Adds a few names to existing urls to fix an error.

Added well-named urls to urls.py

---

channels/serializers.py
static/images/channel_avatar_default.svg
static/images/channel_banner_default.svg
static/js/components/CropperWrapper.js
static/js/components/ImageUploaderForm.js
static/js/components/ImageUploaderForm_test.js
static/js/components/admin/EditChannelAppearanceForm.js
static/js/components/admin/EditChannelAppearanceForm_test.js
static/js/containers/ChannelAvatar.js
static/js/containers/ChannelAvatar_test.js
static/js/containers/ChannelBanner.js
static/js/containers/ChannelBanner_test.js
static/js/containers/ImageUploader.js
static/js/containers/ImageUploader_test.js
static/js/containers/ProfileImage.js
static/js/containers/ProfileImage_test.js
static/js/containers/admin/EditChannelAppearancePage.js
static/js/containers/admin/EditChannelAppearancePage_test.js
static/js/factories/channels.js
static/js/flow/discussionTypes.js
static/js/hoc/withForm.js
static/js/lib/api.js
static/js/lib/redux_rest.js
static/js/lib/util.js
static/js/reducers/channel_avatar.js
static/js/reducers/channel_banner.js
static/js/util/integration_test_helper.js
static/scss/admin.scss
static/scss/form.scss

Part of #927 
Provides the UI to edit channel avatars and banners
Edit the channel avatar and banner. Note that if you do not click 'Save' the changes should be discarded. (There isn't clear indication of this at the moment.)

Implement uploading channel avatar and banner

---

static/js/components/ProfileForm.js
static/js/components/ProfileForm_test.js
static/scss/form.scss
static/scss/profile.scss

Closes #1049
Makes the profile edit form look more similar to the [Invision design](https://projects.invisionapp.com/share/9EN908ZQPAX#/screens/311617870_Edit_Profile)
Go to the profile edit page and compare it to the Invision design.

Update edit profile form to match design

---

open_discussions/views.py

(Required)
(Required)
(Required)
(Optional)
(Optional)
(Optional)
(Optional)

Fixed redirect on expired JWT

---

authentication/urls.py
channels/models.py
embedly/views_test.py
fixtures/common.py
open_discussions/settings.py
open_discussions/templatetags/render_bundle.py
profiles/models.py
requirements.in
requirements.txt

Fixes #1091 
Updates Django dependency to 2.1 with other minor changes required for that

Upgrade to Django 2.1

---

requirements.in
requirements.txt
test_requirements.txt

N/A
Updates dependencies to newer ones
Make sure you can still send an email (reply to one of your own posts is the easiest way). Can't test newrelic really until it's deployed so we'll trust that newrelic tests their stuff.
(Optional)
(Optional)
(Optional)
(Optional)

Upgrade deps

---

static/js/components/Footer.js
static/scss/navigation.scss

Fixes #1107 
Makes home link full width
Hover over the link

Make home link full width

---

static/js/components/Loading.js
static/js/components/Loading_test.js
static/js/containers/ChannelModerationPage.js
static/js/containers/ChannelPage.js
static/js/containers/HomePage.js
static/js/containers/PostPage.js
static/js/containers/ProfileEditPage.js
static/js/containers/ProfilePage.js
static/js/containers/auth/RegisterConfirmPage.js
static/js/containers/auth/RegisterConfirmPage_test.js

This reverts commit 1556496385b828d771f8c01b91f8b6b2ed6e124e.
see discussion on #1119 
This reverts the bad commit so we can figure out what we want to do later.

Revert "Replace withLoading with Loading component (#1111)"

---

static/scss/navigation.scss

Fixes #1144 
Removes the horizontal scroll on the drawer
Verify you can still show vertically and the horizontal scroll or corner box does not appear.

Fixed overflow scrolling to only be vertical

---

open_discussions/templates/base.html
open_discussions/views.py
open_discussions/views_test.py
package.json
static/js/entry/root.js
static/js/flow/declarations.js
yarn.lock

None
Adds Raven.js to frontend code
In the PR build, go to the homepage and open up the browser console. Type:
var body = document.getElementsByTagName("body")
var script = document.createElement("script")
script.innerHTML = "throw new Error('something unique to make it obviously a test')"
body.append(script)
You should see an exception in the console. If you open up the stack trace of the exception there should be some mention of raven (not sure if this is true for all browsers). Go to Sentry and verify that it caught an error with the error text from a CI environment.

Add Raven.js

---

static/js/components/BackButton.js
static/js/components/auth/LoginGreeting.js
static/js/components/auth/LoginGreeting_test.js
static/js/containers/auth/LoginPasswordPage.js
static/js/containers/auth/LoginPasswordPage_test.js
static/js/containers/auth/LoginProviderRequiredPage.js
static/js/containers/auth/LoginProviderRequiredPage_test.js
static/js/lib/auth.js
static/js/lib/auth_test.js
static/scss/_variables.scss
static/scss/auth.scss

Closes #1084 
Adds a simple back button to the second page of the login flow
Click the back button after entering a valid email address on the login page

Added back button to login pages

---

static/js/components/CanonicalLink.js
static/js/components/CanonicalLink_test.js
static/js/containers/AccountSettingsPage.js
static/js/containers/ChannelModerationPage.js
static/js/containers/ChannelPage.js
static/js/containers/ContentPolicyPage.js
static/js/containers/CreatePostPage.js
static/js/containers/HomePage.js
static/js/containers/PasswordChangePage.js
static/js/containers/PostPage.js
static/js/containers/ProfileEditPage.js
static/js/containers/ProfilePage.js
static/js/containers/SettingsPage.js
static/js/containers/auth/AuthRequiredPage.js
static/js/containers/auth/InactiveUserPage.js
static/js/containers/auth/LoginPage.js
static/js/containers/auth/LoginPasswordPage.js
static/js/containers/auth/LoginProviderRequiredPage.js
static/js/containers/auth/PasswordResetConfirmPage.js
static/js/containers/auth/PasswordResetPage.js
static/js/containers/auth/RegisterConfirmPage.js
static/js/containers/auth/RegisterDetailsPage.js
static/js/containers/auth/RegisterPage.js
static/js/factories/util.js
static/js/global_init.js
static/js/lib/util.js

Closes #1011 
Adds a `<link>` tag with `rel="canonical"` to improve SEO and simplify our analytics ([reference](https://support.google.com/webmasters/answer/139066))
Open up various pages on the site and check that there's a `<link>` tag with `rel="canonical"` and a consistent `href` attribute (URLs with and without a trailing slash should have the same value)

Added link tags with rel=canonical to improve SEO and analytics

---

open_discussions/views.py
open_discussions/views_test.py
static/js/components/CanonicalLink.js
static/js/components/CanonicalLink_test.js
static/js/flow/declarations.js
static/js/global_init.js

No ticket. Fixes a bug from #1158
Fixes the `href` values for our `<link rel="canonical">` tags
Same testing steps as #1158

Fixed canonical link hrefs to use correct site URL (original PR: #1158)

---

open_discussions/management/commands/generate_channel_avatars.py
static/images/channel_avatars/channel-avatar-0.svg
static/images/channel_avatars/channel-avatar-1.svg
static/images/channel_avatars/channel-avatar-2.svg
static/images/channel_avatars/channel-avatar-3.svg
static/images/channel_avatars/channel-avatar-4.svg
static/images/channel_avatars/channel-avatar-5.svg
static/images/channel_avatars/channel-avatar-6.svg
static/images/channel_avatars/channel-avatar-7.svg
static/images/channel_avatars/channel-avatar-8.svg
static/images/channel_avatars/channel-avatar-9.svg
static/js/containers/ChannelAvatar.js
static/js/containers/ChannelAvatar_test.js
static/js/lib/util.js
static/js/lib/util_test.js

Fixes #1128 
Randomizes the channel avatars and adds a script to generate them based off a color list
Create channels with no image (or null values of existing ones) and verify a random one is  selected.
Remove the files in `static/images/channel_avatars/` and run `./manage.py generate_channel_avatars` to ensure they are idempotently regenerated.

Added random channel avatars and script to generate them

---

cassettes/channels.views.moderators_test.test_list_moderators_many_moderator.json
cassettes/channels.views.moderators_test.test_list_moderators_moderator.json
channels/views/moderators.py
channels/views/moderators_test.py
factory_data/channels.views.moderators_test.test_list_moderators_many_moderator.json
factory_data/channels.views.moderators_test.test_list_moderators_moderator.json

Closes #1132 
Places the current user at the top of the moderators list 
Add several users to a moderators list.  Log in as each of those users and go to the moderators list page. "You are a moderator of this channel" should always be at the top of the list.

Always show current user at top of mods list

---

open_discussions/urls.py
static/js/components/PoliciesNavBar.js
static/js/containers/App.js
static/js/containers/policies/ContentPolicyPage.js
static/js/containers/policies/PrivacyPolicyPage.js
static/js/containers/policies/PrivacyPolicyPage_test.js
static/js/containers/policies/TermsOfServicePage.js
static/js/lib/url.js
static/scss/content-policy.scss

Fixes #985 
Adds the TOS and privacy policy pages
Go to /terms-and-conditions and /privacy-statement and verify the content looks right. There are not links to these pages as that's going to be a runtime config change

Added TOS and privacy policy

---

static/scss/post.scss

Closes #1240
What the title says
Check the vote/comment styling and sizing against the designs ([example](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4e7e0a4dc98a7608ee6b5))

Increased size of upvote & comment icons

---

static/scss/channel.scss
static/scss/navigation.scss
static/scss/post.scss

closes #1256 
closes #1244 
closes #1209 
some styling tweaks to address those issues.
- fix the issue with the font not applying in the sidebar
- some spacing and layout fixes in the sidebar
- fix margin with the reports widget thingy
make sure the issues in the attached tickets are addressed

various small styling fixes

---

package.json
static/js/containers/Drawer.js
static/scss/drawer.scss
yarn.lock

Closes #1170
Adds `react-scrollbar` as a dependency and uses that component to wrap the drawer (side nav). This renders a custom scrollbar to the side of the drawer when one is needed
In desktop view, hover over the drawer. If it has enough content, you should see a scrollbar appear. Also check different browser widths to make sure everything renders correctly.

Enabled scrollbar-on-hover behavior for the drawer

---

static/js/components/Footer.js

closes #1177
just adds an `<a>` tag around the logo
make sure that you can click the link, I guess?

make MIT logo in the footer into a link

---

static/js/components/admin/EditChannelAppearanceForm.js
static/js/containers/ChannelBanner.js
static/scss/admin.scss
static/scss/channel-banner.scss
static/scss/channel.scss
static/scss/profile-image.scss

closes #1203 
Some tweaks to the channel settings page to bring it more in line with the mocks.
Check out the channel settings page, referring to the changes requested on the issue. make sure it makes sense!

tweaks to channel appearance form page

---

static/js/lib/fetch_auth.js
static/js/lib/fetch_auth_test.js

Fixes #727 
This remove JWT logic and makes the redirect conditional on whether the `/login/`page is enabled or not.
Turn on/off `FEATURE_ALLOW_EMAIL_AUTH` and verify you see the expected behavior when your session terminates (e.g. go to a private channel and delete your session cookie).

Removed JWT logic and made login url conditional on email auth flag

---

static/js/hoc/withPostModeration.js

fixes #1160 
It makes the text in the dialog more accurate. I decided to skip adding a link to the message, just to keep things simple. 
Remove a post

update remove post dialog to better match behavior

---

authentication/serializers.py
authentication/utils.py
authentication/views_test.py
open_discussions/settings.py
static/js/containers/auth/AuthRequiredPage.js
static/js/containers/auth/AuthRequiredPage_test.js
static/js/containers/auth/LoginPage.js
static/js/containers/auth/LoginPage_test.js
static/js/containers/auth/RegisterPage.js
static/js/containers/auth/RegisterPage_test.js
static/js/flow/authTypes.js
static/js/lib/api.js
static/js/lib/auth.js
static/js/lib/auth_test.js
static/js/lib/fetch_auth.js
static/js/lib/fetch_auth_test.js
static/js/lib/url.js
static/js/lib/url_test.js
static/js/reducers/auth.js

Fixes #709
Adds the next param to support navigating the user back to their destination page after a login.
Logout and try to navigate to a private channel. Login with a user that is in that channel and confirm you end up at that page.

Added support for next param

---

requirements.in
requirements.txt

Bumped django version

---

static/js/components/PostUpvoteButton.js
static/scss/popup.scss

No ticket
Fixes a positioning issue we missed in #1295 
Click the post upvote button as an anonymous user, make sure the prompt shows up where it should

Fixed anonymous user signup prompt for post upvote button

---

static/scss/post-list.scss

closes #1305 
this fixes a few small issues with the styling of the thumbnail and the 'url' icon on the compact post display. check the issue for specifics about what it should address.
check it out at a bunch of screen widths and make sure it looks good.

fix styling of thumbnail and URL icon

---

static/js/components/Dialog.js

Fixes #1218 
This fixes the dialog buttons for the image selection so they don't default to being submit buttons for the `<form>`. There's not a practical way to write tests around this, it's just asserting the intended behavior of those buttons now that we're embedding them in forms in a few places.
Go to the channel appearances tab, click the upload button for avatar, and verify clicking cancel does not redirect you.

Fixes the dialog buttons submitting the form

---

package.json
yarn.lock

add moment as a dependency

---

static/js/containers/HomePage.js
static/js/containers/HomePage_test.js
static/js/lib/ui.js
static/scss/home-page.scss
static/scss/layout.scss

Closes #1242
Adds an intro card to the home page
Check the home page while logged in and not logged in
Not-logged-in design: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b60e6907ed98b73a5440778
Logged-in design:
https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b60e68e8e733e22302777bf

Added home page intro cards for logged in and anonymous users

---

static/js/components/CompactPostDisplay.js
static/js/components/CreatePostForm.js
static/js/components/admin/MembersList.js
static/js/storybook/index.js
static/scss/button.scss
static/scss/create-post.scss
static/scss/link.scss

closes #1314 
closes #1292 
closes #1313
This fixes the link styling for a few little things and changes the button style for the 'Write something' and 'Add a link' buttons on the post creation page.
I also went ahead and added stories for links and buttons to Storybook, so we can easily look at the different button and link styles we have there.
I guess take a look over the linked issues, and make sure that the things identified there are fixed.

link and button styling changes

---

pull_request_template.md

none
adds a screenshot review section to the PR checklist
Does it look like the screenshot? =)
We've noticed that the layout and styling in production has been straying from the mock-ups. To avoid this, we'd like to add extra eyes to the review of anything that affects look and feel.

Added a screenshots section to PR template

---

pull_request_template.md

(Required)
(Required)
(Required)
(Optional)
(Optional)
(Optional)
(Optional)

PR template: add checkbox for mobile screenshots

---

static/js/containers/App.js
static/js/containers/PostPage.js
static/js/hoc/withPostModeration.js
static/js/lib/title.js
static/js/lib/title_test.js

fixes #1354 
find & replace
- Do HTML page titles look right?
- Does the dialog when reporting post/comments no longer mention the site name?
I don't think screenshots are necessary.

'Open Discussions' -> 'Open Learning'

---

static/js/containers/ChannelAvatar.js
static/js/containers/ChannelAvatar_test.js
static/js/containers/ChannelBanner.js
static/js/containers/ChannelBanner_test.js
static/js/containers/ChannelPage.js
static/js/containers/HomePage.js
static/js/lib/util.js
static/js/lib/util_test.js
static/scss/_variables.scss
static/scss/channel-banner.scss
static/scss/channel.scss
static/scss/drawer.scss
static/scss/post-list.scss

Fixes #1327 
Implements channel design tweaks
Make sure the design matches and everything still works
Channel:
Frontpage:
@Ferdi @pdpinch

Channel design updates

---

authentication/serializers.py
authentication/utils.py
authentication/views_test.py
cassettes/authentication.views_test.test_login_register_flows[register_email_not_exists->redeem_confirmation_code->redeem_confirmation_code_twice].json
cassettes/authentication.views_test.test_login_register_flows[register_mm_exists].json
factory_data/authentication.views_test.test_login_register_flows[register_mm_exists].json
static/js/containers/auth/LoginPage.js
static/js/flow/authTypes.js
static/js/lib/api.js
static/js/lib/auth.js
static/js/lib/auth_test.js

Fixes #1363 
Fixes the backend API for when a confirmation link is used twice
Follow the steps to reproduce in the issue and verify you don't see the backend error anymore and instead get an appropriate error message.

Fixed error when trying to use confirmation link a second time

---

static/js/components/CompactPostDisplay.js

Fixes #1385 
This allows pinning link posts types
Verify you get the pin option for link type posts and that it works

Allow link type posts to be pinned

---

package.json
static/js/components/auth/AuthEmailForm.js
static/scss/auth.scss
yarn.lock

Fixes #1347 
Fixes various signup page UI issues:
- Fixed maximum width of for to 304px to match largest width of ReCAPTCHA
- Dynamically scale ReCAPTCHA on resizes and smaller devices
- Renamed the button to "Sign up" and adjusted its width to a pixel value instead of percentage so it doesn't get scrunched on mobile widths
Test the UI at various browser sizes and make sure things look good.

Fixed signup page UI issues

---

search/serializers.py

Closes #1427
Uses `.iterator()` when retrieving profiles for indexing.
Run `docker-compose run web python manage.py recreate_index`, once complete all profiles should be in the ES index.

Use iterator when retrieving profiles

---

Procfile

N/A
Enables newrelic agent on workers
Message me for the command to view this in newrelic

Enabled newrelic for our workers

---

static/js/components/SearchResult.js
static/js/components/SearchResult_test.js
static/js/factories/search.js
static/js/flow/searchTypes.js
static/js/lib/search.js
static/js/lib/search_test.js
static/js/storybook/index.js
static/scss/search.scss

Part of #1316 
Adds search result components and some logic to convert Elasticsearch data to other types to reuse existing components where we can
View the components in storybook
Comment
Post
Profile

Add components for search results

---

requirements.txt

N/A
Upgrades requests to the latest version
Tests should pass, you should be able to poke around the app with nothing breaking

Upgrade requests lib

---

channels/factories.py
search/indexing_api.py
search/indexing_api_test.py
search/serializers.py
search/serializers_test.py
search/tasks.py
search/tasks_test.py

Closes #1368 
- Queries the database instead of reddit to get the channels, posts, and comments to index.
- Adds factories for Django models (Channel, Post, Comment) and refactors existing factory class names for the reddit equivalents to differentiate between them.
- Run `docker-compose run web python manage.py recreate_index`
- Query Elasticsearch to verify that all posts and comments were indexed.

Query database to get lists of channels, posts, comments for indexing

---

notifications/urls.py
profiles/serializers.py
profiles/urls.py
requirements.in
requirements.txt

Fixes #1532
Upgrades DRF to the latest version and fixes regressions/deprecations.
Tests should pass and APIs should still work.
Some key things to test:
- Regular API requests (browse around the app, comment, upvote, submit posts)
- Image uploads (channel banner, avatar, profile image, etc)

Updated DRF to 3.9.0

---

profiles/models.py
profiles/serializers_test.py

Fixes #1522
Modifies the logic used to decide whether or not to update the profile index after changes are made to the `Profile` model object.  When the profile image is changed, `Profile.save` is called 3 times (additional two times are to save medium and small images), which caused the profile ES index doc to get 3 update requests.  
-On master branch, if you upload a new profile image, an error message of `Update By Query API request resulted in 1 version conflict(s)` should show up in your console.
-On this branch, that error message should not occur.
-The profile document in ES should still be updated with your new images (medium and small).

Don't try to update profile index more than once on image change

---

authentication/serializers.py
authentication/views_test.py

Fixes #1568 
Fixes login bug where a user who has registered but has not verified via email could go to the login page and attempt to log in unsuccessfully, but wouldn't see an error message.
1. Register a new email
1. Visit the login page without verifying using that email link
1. Enter that same email
You should see an error message indicating that the email doesn't exist
1. Ideally we would show an error message telling the user that they need to verify via the email link, but we can only determine that state if the user still has the same session active that they used to register the email. If they use a new browser, incognito window, or the session expires, we can't determine that they have registered but haven't verified. In order to keep the error messages consistent, I just opted …

Fixed unverified user login bug

---

static/js/components/ChannelHeader.js
static/js/components/ChannelHeader_test.js
static/scss/channel.scss

Closes #1590
- Makes the channel title in the header a link to the channel page.
- Click the channel title in the header, it should bring you to the channel page.

Make channel title in header a link

---

static/js/components/ChannelHeader.js
static/js/components/ChannelHeader_test.js
static/js/containers/App.js
static/js/containers/ChannelPage.js
static/js/containers/ChannelPage_test.js
static/js/hoc/withChannelHeader.js
static/js/hoc/withChannelSidebar.js
static/js/lib/url.js
static/js/lib/url_test.js

This reverts commit 661f5e11f280480272943f3ab51171edf1cd07f9.
Reverts #1617 
Reverts the mobile widget work

Revert "Implement mobile widget view (#1617)"

---

requirements.in
requirements.txt

N/A
Updates the `elasticsearch` dependency.
You should be able to `./manage.py recreate_index` and use search and other features without any breakages.

Upgrade elasticsearch lib

---

test_requirements.txt

Fixes #1647 
Pegs the version of python-lazy-fixture to 0.4.2
Unit tests should pass

Peg python-lazy-fixture to 0.4.2

---

static/js/components/ExternalLogins.js
static/js/components/auth/TouchstoneLoginButton.js
static/js/components/auth/TouchstoneLoginButton_test.js
static/js/containers/auth/LoginPage.js
static/js/containers/auth/RegisterPage.js

Fixes #1624 
Adds the next parameter to the touchstone button
Try to navigate to a private channel and verify the next parameter is in the touchstone button url

Fixed next param for touchstone

---

static/js/components/widgets/WidgetInstance.js
static/scss/widget.scss

Part of #1653 
CSS tweaks for the manage widget component
Nothing should break. Look over the checkboxes in the issue and the zeplin mockup and make sure everything generally looks right (see also drag handle discussion). The "nice to have" section will be a separate PR

Widget CSS tweaks

---

static/js/containers/CreatePostPage.js
static/js/containers/CreatePostPage_test.js

closes #1687
this fixes an issue with the form reset logic we have on the create post page. basically, there are a few cases where, when the user switches between channels, we want to reset the input values for the form, either because the current input isn't valid on the new channel or because the new channel offers the user an option which isn't present on the previous channel.
The particular issue this is fixing is a situation where we wanted to be resetting the form but we were not. The situation is:
- the user navigates to `/create_post/`
- the user clicks on 'Write an Article'
- the user fills in the article and title
- the user selects a channel which allows text and link posts, but not article posts
- the user submits the form
on `master` right now this will fail to clear the …

fix an issue with resetting the create post form

---

cassettes/channels.views.subscribers_test.test_add_subscriber_forbidden.json
channels/api.py
channels/views/subscribers_test.py
factory_data/channels.views.subscribers_test.test_add_subscriber_forbidden.json

Fixes #1536 
Part of #1662 
This wraps several api methods in transactions to ensure our database has a consistent view of reddit and vice-versa and updates are rolled back correctly int he event of an error.
The tests should pass and the application should not break.

Update subscriber/moderator/contributor APIs to be atomic

---

static/js/components/CreatePostForm.js
static/js/containers/CreatePostPage.js

closes #1702
this makes some copy changes (see issue)
look on the issue and make sure the listed changes have all been made on the create post page. make sure that the changes didn't result in any weird spacing issues or w/e.

some copy changes for create post page

---

search/tasks.py
search/tasks_test.py

Fixes #1724 
Ensures that profiles are always indexed in the same order (by user id)
Tests should always pass on travis

Fix flaky test

---

static/js/containers/App.js

No ticket - fixes a bug in #1426 
Fixes a bug in #1426 
Click to a profile page, then click back and forth between the posts and comments tabs, make sure everything loads

Fixed bug with #1426 (post/comments feed on profile page)

---

static/js/components/AddLinkMenu.js
static/js/components/PasswordChangeForm.js
static/js/components/PostList.js
static/js/components/ReportCount.js
static/js/components/UserMenu.js
static/js/components/admin/CreateChannelForm.js
static/js/components/admin/EditChannelNavbar.js
static/js/components/admin/MembersNavbar.js
static/js/components/auth/PasswordResetConfirmForm.js
static/js/components/auth/PasswordResetForm.js

none
this is just a simple refactor of some class-based components to be stateless components instead. I did this a while ago and forgot about the branch until now.
There's some basic optimizations that React can make when using stateless components that should make us prefer them unless we need the things we get from classes (having methods to separate out more complicated functionality, using `this.state`, etc).
I'd say make sure that all of the components that were changed over are working as they should, and that the refactor to a stateless component didn't mess anything up code-wise.

refactor some class-based components to be stateless components

---

README.md

N/A
Adds an example command for running storybook locally
Verify the example command works

Added storybook command to readme

---

Dockerfile-node
package.json

none
just bumps our node and yarn versions. I grabbed the latest version of `yarn` and the latest stable release of Node.
I think we want to make sure that the build works on travis and on heroku, so I'll set up a PR build.

bump yarn and node version

---

static/js/components/ArticleEditor.js
static/js/components/EmbedlyCard.js
static/js/components/EmbedlyCard_test.js
static/js/components/widgets/UrlWidget.js
static/js/components/widgets/UrlWidget_test.js
static/js/components/widgets/WidgetField.js
static/js/components/widgets/WidgetField_test.js
static/js/components/widgets/WidgetInstance_test.js
static/js/components/widgets/WidgetList_test.js
static/js/factories/widgets.js
static/js/lib/embed.js
static/js/lib/embed_test.js
widgets/serializers/react_fields.py
widgets/serializers/url.py
widgets/views_test.py

Fixes #1510 
Uses the embedly card API to render embedly widgets. The actual rendering is done by the embedly platform; this PR just injects HTML into the DOM with the appropriate CSS class.
Edit widgets, make sure they look fine. Try out many different embedly sources. Comment if you see any source which produces a strange looking UI.
Widget dialog
Widget rendering in sidebar

Implement embedly widget

---

channels/tasks.py
channels/tasks_test.py

N/A
Switches the backpopulate to fetching submission one-by-one instead of the faster but unreliable /api/info method previously used. The previous method did not return all submissions for an unknown reason.
Run `./manage.py backpopulate_posts` and verify is succeeds.

Switched backpopulate_posts to a more reliable submission fetch

---

docs/rfcs/0001-caching-system.md

[Rendered](https://github.com/mitodl/open-discussions/blob/rfc/0001-caching-system/docs/rfcs/0001-caching-system.md)
RFC for #1749 
Adds an RFC for how to approach caching third party data

RFC: Caching system for third party data

---

static/js/containers/CourseSearchPage.js
static/js/containers/SearchPage.js

None
Removes two TODO comments which aren't relevant anymore

Remove TODO comments

---

docs/rfcs/0003-search-ui.md

[Rendered](https://github.com/mitodl/open-discussions/blob/rfc/search-ui/docs/rfcs/0003-search-ui.md)
#1719 
#1720 
#1397 
Adds an RFC for an elasticsearch UI framework

Search UI RFC

---

docs/rfcs/0004-enhanced-facets.md

[Rendered](https://github.com/mitodl/open-discussions/blob/7fd27be8591cc7194559966dd282e407bb266173/docs/rfcs/0004-enhanced-facets.md)
#1887 
Adds an RFC for enhancing course search facets

RFC for enhanced search facets

---

Dockerfile
runtime.txt
travis/Dockerfile-travis-web

N/A
Upgrades the version of Python used for running the application
Ensure that the test suite is successful on Python 3.6.8
runtime.txt
The currently specified version is deprecated and has been replaced with a new minor version

Updated Python runtime version

---

requirements.in
requirements.txt

N/A
Periodic upgrade of dependency
Tests should pass and the app should run

Upgraded urllib3

---

profiles/api_test.py

none, just fixing a flaky test I just introduced
see above
if tests pass and the code looks reasonable we're good

fix a flaky one

---

Procfile

N/A
Enables the workers to use pgbouncer
N/A, will verify in environments

Added workers to pgbouncer

---

requirements.in
requirements.txt

N/A
Periodic bump of dependency
App should run and still be functional

Periodic bump of drf

---

yarn.lock

just a little upgrade of some dependencies.
app should work, tests should pass, etc.

small JS dependency upgrade

---

static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/scss/profile.scss

closes #2026
this tweaks the styling for the profile page, to match the mockups, along the lines of what is in #2026
make sure that the profile looks like what's on the issue!

fix profile styling

---

yarn.lock

no ticket
builds were failining (e.g. https://travis-ci.org/mitodl/open-discussions/jobs/544313644) because of a error being thrown by `caniuse` and `browserslist`. I upgraded the packages that depend on them to get rid of the error.
make sure the app boots and works alright, build should pass as well, haha

upgraded some dependencies

---

course_catalog/views_test.py

closes #1837 
Adds tests to increase test coverage on `course_catalog.views`
Run the tests

Add tests for course_catalog.views

---

static/js/components/Card.js
static/js/components/CourseCarousel.js
static/js/components/CourseCarousel_test.js
static/scss/_variables.scss
static/scss/course-carousel.scss

part of #1997 
basically, this PR updates the styling for the titles of the carousels and updates the controls for the carousels themselves on the course home page to be in-line with the mockups. Note that this doesn't include re-doing the cards in the carousel, I was going to do that in one PR but I'm splitting that part out to keep the PRs small.
In particular, the buttons for the carousel are updated to match the design. they should also only appear if you can actually move the carousel - like if you're on the first page of items there shouldn't be a button on the left. Likewise, if you're at the end there shouldn't be a button on the right.
check out the course home page and make sure it looks alright and the controls behave as you'd expect.

updates to the styling of the course carousel

---

.github/ISSUE_TEMPLATE/config_change_template.md

none 
just adding a configuration change issue template, same as the one in mitxpro
Does [it look ok?](https://github.com/mitodl/open-discussions/blob/16f0ed0cc0e30032da1006fe9a76ba029400381b/.github/ISSUE_TEMPLATE/config_change_template.md)

add config_change_template

---

course_catalog/task_helpers.py
course_catalog/utils.py

Addresses #2068 
Checks for none-ness in get_course_url to fix `sync_and_upload_edx_data`
Run course_catalog.tasks.sync_and_upload_edx_data(force_overwrite=True)

Addresses #2068 

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/conftest.py
course_catalog/migrations/0020_course_availability.py
course_catalog/tasks.py
course_catalog/tasks_test.py

N/A
The methods in this module are more in line with what we put in api.py, so I've renamed it

Renamed course_catalog.task_helpers to course_catalog.api

---

course_catalog/factories.py
course_catalog/serializers_test.py
course_catalog/signals_test.py
course_catalog/views_test.py
requirements.txt
search/serializers_test.py

Pre-req for #2116 
Updates the course_catalog factories to generate more thorough data out of the box (e.g. `CourseFactory.create()` will give you a course with runs (if it's not an OCW course).
Tests should still pass and you should be able to create an MITx course and see that it has runs:
```
from course_catalog.factories import *
course = CourseFactory.create(is_mitx=True)
```
(Optional)
(Optional)
(Optional)
(Optional)

Updated course_catalog factories to be generate more data out of the box

---

requirements.in
requirements.txt

N/A
Periodic version bump
App should run and not error

Upgrade django

---

test_requirements.txt

N/A
Pins `pytest` dependencies to last working version
`docker-compose build`
`docker-compose run web pytest`

Pin pytest deps

---

static/js/actions/ui.js
static/js/components/SearchFacet.js
static/js/components/SearchFacet_test.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/_variables.scss
static/scss/search.scss

part of #2161 
this restyles the facets to match the mockups. basically:
- new text styles
- clicking the title opens and closes the facet list
...that's about it, haha. I left off of this PR the restyling of the currently selected facets, just to keep the PRs smaller.
go to the course search page and make sure that the facets that you see are like they are on the mockups.

styling tweaks to the facets

---

static/js/components/CourseCarousel.js
static/js/components/CourseCarousel_test.js
static/js/components/CourseSearchbox.js
static/js/components/CourseSearchbox_test.js
static/js/components/CourseToolbar.js
static/js/containers/CourseIndexPage.js
static/js/containers/CourseIndexPage_test.js
static/js/factories/learning_resources.js
static/js/global_init.js
static/js/hooks/util.js
static/js/hooks/util_test.js
static/js/lib/constants.js
static/js/lib/test_utils.js
static/js/store/configureStore.js
static/js/util/integration_test_helper.js
static/scss/_variables.scss
static/scss/course-carousel.scss

closes #2179
this does some styling tweaks to the course home page. also while I was fiddling with this component I refactored it to use the react-redux and redux-query hook APIs, and rewrote the tests to be tests of the full component.
make sure the styling fixes on the issue have all been satisfactorily implemented, and that it looks good and so on.
make sure all the code makes sense and everything.
mobile is pretty sad rn but this is what it looks like:

restyle the course home page

---

search/api.py
search/api_test.py
search/indexing_api.py
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/factories/search.js
static/js/lib/search.js
static/js/lib/search_test.js

Closes #2212 
Adds facets for 'Offered By' and "Prices'
Go to `/courses/search/` and try out the new facets.
Note: the default behavior on search results is to show the lowest available price, which is often $0.  So even if you select only 'Paid' for the cost facet, lots of results will still display 'Free'.

Facets for price and offered by

---

static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/lib/constants.js
static/js/lib/search.js

Closes #2236 
Fixes 'Offered By' subtitle on course cards.
All the cards on the courses home page should have populated 'Offered By' values.

Fix 'Offered By' display

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py

Closes #2305 
Adds loader functions for videos
Run this code:
```python
from course_catalog.constants import *
from course_catalog.etl import loaders
data = {
"video_id": "abc",
"platform": PlatformType.ocw.value,
"title": "video 1"
}
loaders.load_video(data)
```
Then verify your video shows up in course search.
Calling this again with `"published": False` in the data should remove the record from search results

Added loader code for videos

---

course_catalog/constants.py
package.json
static/js/components/CreateUserListDialog.js
static/js/components/CreateUserListDialog_test.js
static/js/components/NewCoursesWidget_test.js
static/js/components/UserListCard.js
static/js/lib/constants.js
static/js/lib/queries/user_lists.js
static/js/lib/queries/user_lists_test.js
static/js/lib/test_utils.js
static/js/lib/validation.js
static/js/lib/validation_test.js
static/js/pages/UserListPage.js
static/js/pages/UserListPage_test.js
static/scss/create-user-list-dialog.scss
static/scss/layout.scss
static/scss/user-list-page.scss
yarn.lock

closes #2312
this implements a form dialog for creating UserLists. it has:
- a form, with Formik, for putting the values
- a validating function for validation that all the required inputs are their
- a redux-query mutation for actually creating the list
- a button to show it on the UserList index page (`/courses/lists/`)
that's about it!
If you go to `/courses/lists` you should see a 'Create New List' button. This should open a dialog with a form where you can create a list, just to your liking.
In particular, check that the validation is working correctly and that your new list gets added to the list after you save it.

add UI for creating User Lists

---

requirements.in
requirements.txt

(Required)
(Required)
(Required)
(Optional)
(Optional)
(Optional)
(Optional)

add pyyaml to requirements

---

course_catalog/etl/youtube.py
course_catalog/etl/youtube_test.py

https://github.com/mitodl/open-discussions/issues/2359)
This pr updates youtube video import to fetch data from the uploads playlist to get around the 500 video limit for video search by channel
`YOUTUBE_CONFIG_FILE_LOCATION=https://raw.githubusercontent.com/mitodl/open-video-data/8e4e73a1ee894a347a299a40c3a8b311e6a8fd5a/youtube.yaml`
in your env file. Then run
```
from course_catalog.etl.pipelines import *
youtube_etl()
```
5986 OCW videos and 53 MITx videos should be imported and searchable in the UI
(Optional)
(Optional)
(Optional)
(Optional)

use youtube playlist item call to get around search limit

---

course_catalog/serializers_test.py

N/A
Fixes a test that broke after merging with master

Fix serializer test

---

course_catalog/serializers.py
course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

Related to #2395
Provides an API endpoint for retrieving topics
- Go to `http://od.odl.local:8063/api/v0/topics`, you should get a response that includes all the `CourseTopic`s  in your database
- Go to `http://od.odl.local:8063/api/v0/topics/<topic_id>`, you should get a response that includes the name and id of that `CourseTopic`

Topics endpoint API

---

.flowconfig
course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views_test.py
package.json
static/js/components/AddToListDialog_test.js
static/js/components/LearningResourceCard.js
static/js/components/Select.js
static/js/components/Select_test.js
static/js/components/UserListCard_test.js
static/js/components/UserListFormDialog.js
static/js/components/UserListFormDialog_test.js
static/js/factories/learning_resources.js
static/js/flow/discussionTypes.js
static/js/flow/formTypes.js
static/js/lib/queries/topics.js
static/js/lib/queries/topics_test.js
static/js/lib/url.js
static/js/lib/util.js
static/js/lib/validation.js
static/js/pages/UserListsPage_test.js
static/scss/create-user-list-dialog.scss
yarn.lock

Closes #2395 
- Adds a multi-select field for topics on the UserListFormDialog
- Create new userlists with and without topics
- Edit userlists - change, add, remove topics

Topics select field for the UserListFormDialog

---

app.json
course_catalog/etl/youtube.py
course_catalog/etl/youtube_test.py
course_catalog/management/commands/backpopulate_youtube_data.py
course_catalog/tasks.py
course_catalog/tasks_test.py
open_discussions/settings.py

https://github.com/mitodl/open-discussions/issues/2376
Adds a task and command for pulling transcripts for youtube videos
- Run the task
- Run the command
`./manage.py backpopulate_youtube_data transcripts `- fetch transcripts for all videos that currently have a blank transcript
- Supported options are:
`--created_after` - Minimum date for video created_on for videos included in the job
`--created_minutes` - Maximum age in minutes (based on created_on) for videos included in the job
`--overwrite` - Re-fetch transcripts for videos with existing transcript
(Optional)
(Optional)
(Optional)
(Optional)

transcripts tasks

---

static/js/components/Select.js
static/js/components/Select_test.js

Fixes #2429
- Lets a user remove the only topic in the topic select field.
- Add 1 topic in the UserListFormDialog
- Click the 'x' on that topic to remove it.  It should disappear.

fix Select component when removing last selection

---

course_catalog/views.py
course_catalog/views_test.py
static/js/lib/queries/videos.js
static/js/lib/queries/videos_test.js
static/js/lib/url.js
static/js/pages/CourseIndexPage.js
static/js/pages/CourseIndexPage_test.js

https://github.com/mitodl/open-discussions/issues/2428
This pr creates a carousel that displays new videos (by update date on youtube) on the /courses page
Create some videos in your local database. Navigate to the /courses view. There should be a section for new videos.
(Optional)
(Optional)
(Optional)
(Optional)

new videos view

---

static/js/components/UserListFormDialog.js
static/js/components/UserListFormDialog_test.js
static/js/lib/validation.js
static/js/lib/validation_test.js

Closes #2432 
- Makes 'Subjects' a required field on the UserListFormDialog
- Submit the form with no subjects selected, you should get a validation error.
- Submit the form with 4 subjects selected, you should get a validation error.
- Submit the form with 1-3 subjects selected, you should not get a validation error.

Require at least 1 subject for lists/paths

---

static/js/components/UserListFormDialog.js
static/scss/create-user-list-dialog.scss

closes #2457
this implements the new design for the userlist form on mobile.
make sure that the userlist dialog works as normal on desktop, and that it is now newly usable on mobile.

implement mobile display of userlist dialog

---

static/js/components/AddToListDialog.js
static/js/components/AddToListDialog_test.js

Closes #2481
Fixes #2481
- Make a few lists
- Check a few lists on the AddToListDialog then close
- Reopen the dialog and uncheck some of the boxes

Fix bug unchecking lists

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/lib/learning_resources.js

closes #2467
this makes a small change so that we display the courses in a program when the program is open in the learning resource drawer.
get a program together, and make sure that the items in that program show up in the drawer.

display program courses in the learning resource drawer

---

static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/flow/discussionTypes.js
static/scss/learning-resource-card.scss

closes #2497
makes the switch from the "star" icon to a "bookmark" icon.
make sure that you see an icon which looks like what's shown in the designs. make sure that it shows up correctly for items that are favorites / in a list and for those that are not.

switch from star to bookmark icon for favorites/userlist menu button

---

static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/scss/learning-resource-card.scss

https://github.com/mitodl/open-discussions/issues/2525
This creates individual links for each offered by in the search page when there are multiple. 
Find or create a learning resource with multiple offered by values. Verify that there is a separate link for each offeror to filter the search results
(Optional)
(Optional)
(Optional)
(Optional)

fix offered by link

---

package.json
yarn.lock

none
just upgrades webpack to the latest stable release
the app should build in dev and prod (or prod-like) environments. nothing should be weird.

upgrade webpack version

---

static/js/lib/search.js
static/js/lib/search_test.js

Reverts mitodl/open-discussions#2541

Revert "sort default results in search page"

---

Dockerfile
requirements.in
requirements.txt
runtime.txt

None
Upgrades to Python 3.7 and upgrades Celery and other dependencies which do not support 3.7 at the present version
Nothing should break. Site should load fine and tests should all pass

Upgrade celery, use Python 3.7 in docker

---

Dockerfile
runtime.txt

Reverts part of mitodl/open-discussions#2592
There is some extra work to fix tests which needs to be done. In the meantime this PR will be reverted to avoid blocking other PRs.

Revert "Upgrade celery, use Python 3.7 in docker"

---

course_catalog/api.py
course_catalog/api_test.py

https://github.com/mitodl/open-discussions/issues/2258
Currently, OCW course data is overwritten with data for each run that is indexed. Consequently if an old run is re-indexed after a newer one, the data for the course is overwritten with data from the older run. One way this is currently noticeable is some OCW courses missing thumbnails, since older course runs often don't have a thumbnail. 
Set 
OCW_UPLOAD_IMAGE_ONLY=True
in your .env file
Run 
```
sync_ocw_courses(course_prefixes=['PROD/18/18.310/Fall_2013/18-310-principles-of-discrete-applied-mathematics-fall-2013/', 'PROD/18/18.310/Fall_2004/18-310-principles-of-applied-mathematics-fall-2004/'], blacklist=[], force_overwrite=True, upload_to_s3=True)
```
on master. Search for "Principles of Applied …

don't overwrite ocw course with old run data

---

requirements.in
requirements.txt

Increases ocw-parser version to include
https://github.com/mitodl/ocw-data-parser/pull/27

bump ocw data parser verison

---

docker-compose.yml

https://trello.com/c/1KnhFWrP/64-anonymous-access-to-user-profiles
Pin a couple docker container versions so that everybody is on the same version
Site should load

Pin redis and nginx versions

---

requirements.in
requirements.txt

https://trello.com/c/9OpOdht0/45-extract-course-thumbnails-in-addition-to-course-images
https://trello.com/c/qiCvN0U8/90-add-thumbnail-to-mobile-course
Updates ocw-data-parser to parse `thumbnail_image_src` and `thumbnail_image_description`
Run
```
sync_ocw_courses(course_prefixes=["PROD/12/12.001/Fall_2013/12-001-introduction-to-geology-fall-2013/"],blacklist=[], force_overwrite=True, upload_to_s3=True)
```
Go to the `12-001-introduction-to-geology-fall-2013` folder in the S3 bucket you set up to upload files to locally (probably open-learning-course-data-ci) and check that the `_master.json` file is uploaded and contains `thumbnail_image_src` and `thumbnail_image_description` fields

update ocw-data-parser version to 0.5.0

---

docs/reddit-migration/considerations/reddit-ids.md
docs/reddit-migration/considerations/sorting.md
docs/reddit-migration/readme.md
docs/reddit-migration/strategy/cleanup.md
docs/reddit-migration/strategy/reads-and-writes.md
docs/reddit-migration/strategy/schema.md

[Rendered](https://github.com/mitodl/open-discussions/blob/nl/reddit-migration-docs/docs/reddit-migration/readme.md)
N/A
This PR is a set of markdown docs of my recommendation for how to migrate away from reddit

Initial proposal for reddit migration work

---

course_catalog/views.py
course_catalog/views_test.py

Fixes #2716 
Changes code to handle `Content-Type: text/plain' requests sent by AWS SNS.
* Add `FEATURE_WEBHOOK_OCW=True` to your .env file
* Add `OCW_WEBHOOK_KEY=<some_string>` to your .env file
* Via Postman or similar tool, post this data to the new endpoint `../api/v0/ocw_webhook/?webhook_key=<OCW_WEBHOOK_KEY>` **and make sure to set `Content-Type: text/plain`**:
```
{
"Records": [
{
"s3": {
"object": {
"key": "PROD/6/6.003/Fall_2011/6-003-signals-and-systems-fall-2011/0/1.json",
}
}
}
]
}
```
* In the celery log you should soon see `Received task: course_catalog.tasks.get_ocw_courses`
* After a delay of at least 120 seconds, you should see `Task course_catalog.tasks.get_ocw_courses[<uid>] succeeded`

Handle text/plain requests for OCW webhook

---

search/api.py
search/api_test.py
search/indexing_api.py
static/js/lib/search.js
static/js/lib/search_test.js
static/js/pages/SearchPage.js
static/js/pages/SearchPage_test.js

git generated revert fo https://github.com/mitodl/open-discussions/pull/2740

Revert "Suggested Terms in Channel Search"

---

course_catalog/admin.py
course_catalog/models.py

no ticket
^^ what it says
should be sections in the admin now

Podcasts: add podcasts, podcast episodes to the admin

---

static/js/lib/queries/podcasts.js
static/js/lib/test_utils.js
static/js/lib/url.js
static/js/pages/PodcastFrontpage_test.js

no ticket
just circling back to add some basic tests for the `PodcastFrontpage` component
tests should pass

add basic tests for podcast frontpage component

---

course_catalog/etl/podcast.py
course_catalog/etl/podcast_test.py

https://github.com/mitodl/open-discussions/issues/2802
This pr adds error catching in the case of a rss file that does not contain the expected data
Set OPEN_PODCAST_DATA_BRANCH=master in your .env file
Run `docker-compose run web ./manage.py backpopulate_podcast_data`
The task should run successfully and the logs should contain `Error parsing podcast data from https://www.mitforumcambridge.org/feed/podcast/`

error catching for unparsable rss file

---

static/js/lib/queries/podcasts.js

just saw a stray `console.log`, I think introduced in #2849

remove stray console.log

---

static/js/hooks/test_util.js
static/js/hooks/util_test.js

no ticket
I just noticed that these were either not being tested or were being tested in a weird way, so I went ahead and added a few tests using some of the strategy I came up with for testing hooks when developing the podcast drawer stuff (#2854).
tests should pass, code should make sense.

add test coverage for a few utility hooks

---

course_catalog/views.py
course_catalog/views_test.py

Fixes #2830 
Fixes a bug where published podcasts which have no episodes were being omitted from the list. Instead we want to filter podcast episodes from `episode_count` while leaving the podcast in the list.
Mark all `PodcastEpisode` as unpublished for a particular published `Podcast`. You should not see it at `/api/v0/podcasts/` on master but you should see it on this PR, with `"episode_count": 0`

Change queryset to show empty podcasts

---

static/js/pages/PodcastFrontpage.js

closes #2886
get rid of the word 'Series'
just check that the copy looks good

Podcasts Series -> Podcasts

---

static/js/pages/PodcastFrontpage.js

Closes https://github.com/mitodl/open-discussions/issues/2850
Updates the page title at /podcasts to be "Podcasts | MIT Open Learning"
Visit /podcasts, verify that the title has changed.

Update Podcasts page title

---

.pre-commit-config.yaml
.secrets.baseline
README.md

Closes #2858
Install config files to run the `detect-secrets` hook via `pre-commit`
- Installs a pre-commit hook during `docker-compose build` that will run before every commit
- run `pip install pre_commit detect-secrets`
- run `pre-commit install`
- `git add` an `.env`-like file with fake (but realistic) AWS credentials in it
- `git commit -a -m 'test' ` should generate an error list of bad things it finds in the added file, and the commit should be aborted.
- Replace the contents of the file with safe random text, then run `git commit -a -m 'test'` again, it should work.

Precommit hooks

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/scss/learning-resource-drawer.scss

This reverts commit 363c96d2f52e62fba48ae00ee6bd4e336ea4a710.

Revert "add link in drawer from podcast episode to all episodes"

---

search/indexing_api.py
search/serializers.py
search/serializers_test.py

https://github.com/mitodl/open-discussions/issues/2917
This pr updates the elastic search index to add "audience" and "certificate" which will be used to create new search facets.
Run `docker-compose run web ./manage.py recreate_index`
Ensure that the index changes don't break the current code

index changes for new filters

---

course_catalog/constants.py

Part of #2955 
- Adds another topic mapping to the existing set
- `./manage.py backpopulate_see_data` and verify the topic gets mapped

Added new topic mapping to SEE

---

RELEASE.rst
app.json
course_catalog/api.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/tasks.py
course_catalog/tasks_test.py
course_catalog/utils.py
course_catalog/utils_test.py
course_catalog/views.py
course_catalog/views_test.py
open_discussions/settings.py
search/tasks.py
search/tasks_test.py

N/A
This PR renames references of "blacklist" to "blocklist". See:
https://tools.ietf.org/id/draft-knodel-terminology-00.html
It was a vanilla refactor in an editor, so passing tests should be sufficient. I'll be tweaking the environment variables manually as needed to ensure the repo rename doesn't cause errors.

Rename blacklist -> blocklist

---

requirements.in
requirements.txt

None
Updates ocw-data-parser dependency to the latest version
The site builds properly and tests pass, `backpopulate_ocw_data` runs properly

Update ocw data parser

---

requirements.in
requirements.txt

None
Updates ocw-data-parser to 0.8.0
Tests should pass, and you should be able to run ocw import

Update ocw-data-parser to 0.8.0

---

static/js/components/IntroCard.js
static/js/components/IntroCard_test.js
static/js/pages/HomePage.js
static/js/pages/HomePage_test.js

none
Just saw a little method on HomePage.js that's totally self-contained - thought, why not pull that out? So I did :laughing: 
compare the homepage on master to this branch, everything should be identical w/r/t to the little card that we show above the home page post list.

small refactor: pull method on HomePage.js out as component

---

static/js/components/ExpandedPostDisplay.js
static/js/components/ExpandedPostDisplay_test.js

no ticket
basically just refactors `ExpandedPostDisplay` to be a function-based component instead of a class-based one. This is a step along the road to a bigger refactor that will remove a lot of excess and redundant code between `ExpandedPostDisplay` and `CompactPostDisplay` and hopefully make this whole part of the site a lot more straightforward.
But as-is this is basically just move code around.
There should be no regressions of anything relating to the post page - you should be able to upvote, downvote, edit, remove, etc etc.

refactor expanded post display

---

static/js/components/TruncatedText.js
static/js/components/TruncatedText_test.js

closes https://github.com/mitodl/open-discussions/issues/3046
Fixes the bug with the read more/less control.
Follow the instructions in the ticket to verify that there is a bug with the read more control in the master branch. Follow the instructions again in this branch to verify that the bug has been fixed

fix read more

---

package.json
requirements.in
requirements.txt
yarn.lock

Closes #3016 
Closes #2776 
Closes #2777 
Closes #2778
Closes #2779 
Closes #3017
Updates dependencies
Test should still pass, app should still work

python and JS upgrades

---

channels/serializers/comments.py
channels/serializers/posts.py

N/A
Spam checks only on content changes
- Try updating posts and comments, it should be spam checked again
- Upvoting a post or comment should not trigger spam check

Only spm check if the post or comment text changes

---

requirements.txt
test_requirements.txt

None
This pr fixes the requirements version conflicts that are preventing travis from running
Verify that the app and the tests still work. Verify that `backpopulate_ocw_data` runs since the change affects ocw-data-parser dependencies

fix requirements

---

requirements.in
requirements.txt

None
This pr pins the version for `requests` and updates `urllib3` so travis can run
Verify that both the app and the tests still work

fix urllib3

---

requirements.in
requirements.txt

None
Updates ocw-data-parser to 0.10.0
Tests should pass, and you should be able to run ocw import

update ocw-data-parser to 0.10.0

---

requirements.in
requirements.txt

Closes #3161 
Upgrades the ocw-data-parser to 0.11.0
- Tests should pass

use latest version of ocw-data-parser

---

docs/rfcs/0005-video-resources.md

[Rendered](https://github.com/mitodl/open-discussions/blob/mb/rfcresourcevideo/docs/rfcs/0005-video-resources.md)
#3155
RFC for completing #3156

Youtube video resource RFC

---

requirements.in
requirements.txt

N/A
Upgrades Pillow to the latest
Run the app, image uploads should still work

Upgrade pillow to 7.2.0

---

package.json
static/js/factories/search.js
static/js/pages/CourseSearchPage_test.js
yarn.lock

https://github.com/mitodl/course-search-utils/issues/7
this upgrades the course-search-utils version to address an issue where three search request were inadvertently being made on load. (see the issue above for details).
confirm you can repro the issue, then confirm it's fixed here.

upgrade course-search-utils

---

profiles/views.py
profiles/views_test.py

https://github.com/mitodl/open-discussions/issues/3088
Removed comments and and posts should no longer be visible from the user profile
Create some comments and posts with a non-moderator user
Mark them as spam and remove them using the management command (instructions here: https://github.com/mitodl/open-discussions/pull/3153)
Go to `http://localhost:8063/profile/<user id>` The posts and comments shouldn't be visible

dont show removed comments and posts in profile

---

requirements.in
requirements.txt

https://github.com/mitodl/ocw-data-parser/issues/50
This pr updates the ocw data parser version
```
get_ocw_courses(course_prefixes=["PROD/2/2.611/Fall_2006/2-611-marine-power-and-propulsion-fall-2006/"], blocklist=[], force_overwrite=True , upload_to_s3=True)
```
Should produce the following alert messages:
```
[2020-10-27 18:07:29] ERROR 1 [ocw_data_parser.ocw_data_parser] ocw_data_parser.py:467 - [c1edf1b32f8e] - Could not load binary data for file ef9780ba832dd6c46e5a8d2e58fb30ab_16pa6B_engine.pdf in json file None for course 2-611-marine-power-and-propulsion-fall-2006
[2020-10-27 18:07:29] ERROR 1 [ocw_data_parser.ocw_data_parser] ocw_data_parser.py:467 - [c1edf1b32f8e] - Could not load binary data for file …
```

update ocw parser

---

Procfile

https://github.com/mitodl/open-discussions/issues/3188
Updates the celery invocation in Procfile to fix 
https://github.com/mitodl/open-discussions/pull/3206
Not sure

fix procfile for celery queues

---

pylintrc
scripts/test/js_test.sh

N/A
Fixes recent test failures
Tests should pass below.

Fix test issues

---

course_catalog/models.py

closes https://github.com/mitodl/open-discussions/issues/3217
Defines __str__  for Course objects
```
Course.objects.last().__str__()
```
should display the course title

define __str__ for course

---

requirements.in
requirements.txt

N/A
Upgrades ocw-data-parser to 0.20.0
Tests should pass.
You can import a sample OCW course and make sure it works correctly, for example:
```python
sync_ocw_courses(
course_prefixes=["PROD/18/18.212/Spring_2019/18-212-algebraic-combinatorics-spring-2019/"], 
blocklist=[], 
force_overwrite=True, 
upload_to_s3=True
)
```

Upgrade ocw-data-parser to 0.20.0

---

Procfile

What are the relevant tickets?
https://github.com/mitodl/open-discussions/issues/3203
What's this PR do?
Updates the celery invocation in Procfile to fix
https://github.com/mitodl/open-discussions/pull/3254

add new queue to procfile

---

package.json
yarn.lock

none
I recently upgraded some dependencies in redux-hammock (https://github.com/mitodl/redux-hammock/pull/31). This just bumps us up to that version here.
We're using redux-hammock for a bunch of rest APIs still, mainly in the code for creating posts, channels, etc. So I think exercising various features with posts like voting, commenting, editing, etc are a good idea. There aren't any code changes really in this new version of redux-hammock, basically just dependency upgrades, but still we should check thoroughly.

upgrade to the latest version of redux-hammock

---

notifications/api.py
notifications/api_test.py

None
While testing https://github.com/mitodl/open-discussions/pull/3257 on rc
https://sentry.io/organizations/mit-office-of-digital-learning/issues/2179853828/?project=216201&referrer=slack
occured because the micromasters api user (od_mm_rc_api ) is set as a moderator on reddit but doesn’t have a moderator ChannelGroupRole in our database and thus didn't get a moderator NotificationSetting created by the backpopulate job. This prevented other moderators for the channel from receiving a notification email since the notification creation job failed on this user.
This pr updates the code to skip over the misconfigured moderator, log an error, and then continue the job for other moderators for the channel.
Add two moderators to a channel. Turn on moderator notifications for the channel and …

add try catch around finding notification setting

---

requirements.in
requirements.txt

Related to #3315
Updates ocw-data-parser to 0.24.0
In a shell, run:
```python
sync_ocw_courses(course_prefixes=["PROD/6/6.730/Spring_2003/6-730-physics-for-solid-state-applications-spring-2003/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
It should complete without errors and the run's `raw_json` field should have a `course_feature_tags` section.

Upgrade ocw-data-parser to 0.24

---

course_catalog/migrations/0083_course_feature_tags.py

N/A
Fixes a migration conflict.  Also adds a chunked iterator to head off any potential memory issues on CI/RC.

Fix migration conflict

---

course_catalog/api_test.py

None
Fixes a test which wasn't running

Fix test which wasn't running

---

notifications/api.py
notifications/api_test.py

none
Fixes 
https://sentry.io/organizations/mit-office-of-digital-learning/issues/2182103124/?environment=production&project=216201&query=is%3Aunresolved
Normally when a user is added as a moderator a moderator NotificationSetting is created. The od_mm_prod_api user was added as a moderator programmatically and does not have this setting. This PR creates a new moderator NotificationSettings if something went wrong and one wasn't created when the user was added as a moderator.
1)Turn on moderator notifications for a moderator and channel. 
2)Make a post in the channel.
3)Run
```
send_unsent_email_notifications()
```
4)Verify that the moderator received a notification
5) Find the NotificationSetting with `'notification_type'='moderator_posts'` for the user …

fix notifications setting error

---

requirements.in
requirements.txt

closes https://github.com/mitodl/open-discussions/issues/3369
This updates the ocw data parser
Run
```
sync_ocw_courses(course_prefixes=["PROD/5/5.08J/Spring_2016/5-08j-biological-chemistry-ii-spring-2016/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
Course.objects.order_by('updated_on').last().course_feature_tags
```
the result should be
```
['Lecture Videos',
'Recitation Videos',
'Problem Sets with Solutions',
'Exams with Solutions']
```

OCW data parser 0.27.0

---

course_catalog/api_test.py
course_catalog/etl/loaders.py
course_catalog/serializers.py

This reverts commit b7046254a1fff7c34908bc88a260a884b5c4c08f.
This PR reverts https://github.com/mitodl/open-discussions/pull/3378/files
We need to update raw ocw data before this pr can be merged

Revert "fix salutation"

---

.github/workflows/ci.yml

N/A
Fixes the CI build on github
Tests should pass, nothing should break

Run apt-get update for ci build

---

static/js/pages/ChannelPage_test.js
static/js/pages/PostPage_test.js

None
Addresses a flaky test suite by increasing its timeout

Add timeout to address flaky test

---

requirements.in
requirements.txt

Related to https://github.com/mitodl/ocw-data-parser/pull/152
Updates ocw-data-parser in order to gracefully handle certain subtitle exceptions we weren't catching before
I'm not sure that the `physics` course addressed by the PR is included on open-discussions, so I don't think you can manually test this

Upgrade ocw-data-parser

---

requirements.in
requirements.txt

N/A
This PR updates `ocw-data-parser` to 0.35.0, which adds parsing of the `text` property on embedded media.
- Install the new version by spinning up open and rebuilding your docker containers to install the latest dependencies and make sure you are set up for S3 access
- Run `backpopulate_ocw_data` with the `--course-url-substring` argument to limit to one course and make sure the course successfully backpopulates

ocw-data-parser 0.35.0

---

requirements.in
requirements.txt

N/A
Hopefully fixes heroku builds by updating feedparser
Unit tests should pass

Upgrade feedparser to fix heroku build failure

---

README.md

Fixes some formatting in the readme.
Check the readme formatting on this branch. If...you want to.

fix some formatting in the readme

---

frontends/infinite-corridor/src/api/fields/factories.ts
frontends/infinite-corridor/src/api/fields/hooks.ts
frontends/infinite-corridor/src/api/fields/interfaces.ts
frontends/infinite-corridor/src/api/fields/urls.ts
frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.test.tsx
frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.tsx
frontends/infinite-corridor/src/pages/admin/EditFieldBasicForm.test.tsx
frontends/infinite-corridor/src/pages/admin/EditFieldBasicForm.tsx
frontends/infinite-corridor/src/pages/admin/EditFieldPage.test.tsx
frontends/infinite-corridor/src/pages/admin/EditFieldPage.tsx
frontends/infinite-corridor/src/scss/form.scss
frontends/infinite-corridor/src/test-utils/index.tsx
frontends/ol-forms/package.json
frontends/ol-forms/src/components/SelectField.test.tsx
frontends/ol-forms/src/components/SelectField.tsx
frontends/ol-forms/src/components/SortWrapper.tsx
frontends/ol-forms/src/components/SortableItem.test.tsx
frontends/ol-forms/src/components/SortableItem.tsx
frontends/ol-forms/src/components/SortableSelect.test.tsx
frontends/ol-forms/src/components/SortableSelect.tsx
frontends/ol-forms/src/components/index.ts
frontends/ol-search-ui/src/factories.ts
yarn.lock

Closes #3677
Adds a form for specifying the lists and featured list for a field channel.
- Adjust the following in your .env file:
```
OPEN_DISCUSSIONS_HOSTNAME=od.odl.local
ENABLE_INFINITE_CORRIDOR=True
```
- Go to `../learn/`, and use the bookmark icons on items to create new public lists and add courses to each of them (make sure you choose "Public" for privacy level when creating new lists).
- Create some fields if you don't have any:
- Go to `/api/v0/fields/` and post something like this JSON to create one:
```
{
"name": "physics",
"title": "Physics"
}
```  
- Go to `../infinite/fields/<field_name>/manage/`
- You should see a form with "Featured List" and "Lists" inputs.  If your field already has values for these, they should be visible here.
- Use the inputs to …

Basic field edit form (add/remove/sort lists)

---

Aptfile
apt.txt
requirements.in
requirements.txt

Closes #3618 (hopefully)
- Upgrade python-saml to the latest version
- Adds additional packages to the apt files (Aptfile, apt.txt)
Tests should pass, SAML via SSOCircle should still work (as described in README).

Heroku-22 compatibility

---

app.json

N/A
Fixes non-breaking typo in app.json for new ELASTICSEARCH_REPLICA_COUNT env var.
N/A
(Optional)
(Optional)
(Optional)
(Optional)

fix: Nonbreaking typo in app.json for new ES  env var.

---

frontends/infinite-corridor/src/pages/DemoPage.test.tsx
frontends/infinite-corridor/src/pages/DemoPage.tsx
frontends/infinite-corridor/src/scss/demopage.scss
package.json
yarn.lock

https://github.com/mitodl/open-discussions/issues/3909
This pr adds appzi surveys to allow users to rate the search results from the demo ui
Go to http://localhost:8063/infinite/demo. Make a search. You should see a button asking you to rate your results

demo ui surveys

---

frontends/infinite-corridor/src/pages/DemoPage.tsx
frontends/infinite-corridor/src/scss/demopage.scss
frontends/infinite-corridor/src/scss/header.scss
frontends/infinite-corridor/src/scss/main-search.scss
frontends/infinite-corridor/src/scss/theme.scss
frontends/ol-search-ui/src/components/SearchInput.tsx
frontends/ol-util/src/components/MITLogoLink.tsx

https://github.com/mitodl/open-discussions/issues/3909
Bilal's designs are here https://www.figma.com/proto/zyQTnhYbid1DT5ZaS7MCu6/MIT-Open?page-id=2133%3A11108&node-id=2133-11162&viewport=-526%2C475%2C1&scaling=min-zoom&starting-point-node-id=2133%3A11109
This pr updates styles for the demo ui
Go to http://localhost:8063/infinite/demo
Check that the ui looks good and looks like the designs

demo ui css

---

channels/tasks.py
course_catalog/api.py
course_catalog/api_test.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/management/commands/backpopulate_edx_data.py
course_catalog/management/commands/backpopulate_micromasters_data.py
course_catalog/management/commands/backpopulate_mitxonline_data.py
course_catalog/management/commands/backpopulate_ocw_data.py
course_catalog/management/commands/backpopulate_ocw_next_data.py
course_catalog/management/commands/backpopulate_oll_data.py
course_catalog/management/commands/backpopulate_prolearn_data.py
course_catalog/management/commands/backpopulate_xpro_data.py
course_catalog/management/commands/backpopulate_youtube_data.py
course_catalog/management/commands/delete_courses.py
course_catalog/migrations/0035_courses_to_runs.py
course_catalog/serializers.py
course_catalog/views.py
course_catalog/views_stafflist_test.py
course_catalog/views_test.py
course_catalog/views_userlist_test.py
open_discussions/celery.py
profiles/management/commands/retire_user.py
search/indexing_api.py
search/indexing_api_test.py
search/management/commands/remove_course_hits_with_no_database_record.py
search/task_helpers.py
search/task_helpers_test.py
search/tasks.py
search/tasks_test.py

Closes #3907 
Renames all search index functions from `delete_*` to `deindex_*`
All tests should pass.
Function names are the only changes in this PR.

Rename search index functions, delete->deindex

---

open_discussions/settings.py
open_discussions/settings_celery.py
open_discussions/settings_course_etl.py
open_discussions/settings_test.py

Closes #3939 
Moves some settings (course catalog ETL and celery) into separate files because the main `settings.py` file was at the 1000-line limit.
Tests should pass, app should start up

Split up settings into multiple files

---

frontends/infinite-corridor/package.json
frontends/infinite-corridor/src/App.tsx
frontends/infinite-corridor/src/api/fields/hooks.ts
frontends/infinite-corridor/src/api/learning-resources/hooks.test.tsx
frontends/infinite-corridor/src/api/learning-resources/hooks.ts
frontends/infinite-corridor/src/api/learning-resources/search.test.tsx
frontends/infinite-corridor/src/api/learning-resources/search.ts
frontends/infinite-corridor/src/api/learning-resources/util.test.tsx
frontends/infinite-corridor/src/api/learning-resources/util.ts
frontends/infinite-corridor/src/api/widgets/hooks.ts
frontends/infinite-corridor/src/components/Header.test.tsx
frontends/infinite-corridor/src/example-request-mocks.test.ts
frontends/infinite-corridor/src/libs/react-query.test.tsx
frontends/infinite-corridor/src/libs/react-query.ts
frontends/infinite-corridor/src/pages/HomePage.tsx
frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.test.tsx
frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.test.tsx
frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.tsx
frontends/infinite-corridor/src/pages/resource-lists/ManageListDialogs.test.tsx
frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.test.tsx
frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.tsx
frontends/ol-forms/src/components/FormDialog.test.tsx
frontends/ol-search-ui/src/util.tsx
frontends/ol-util/src/test-utils/ControlledPromise.test.ts
frontends/ol-util/src/test-utils/ControlledPromise.ts
frontends/ol-util/src/test-utils/index.ts
jest-shared-setup.ts
yarn.lock

#3981 
This PR updates react-query to v4. See code comments for specific changes.
There should be no change in behavior. I recommend testing...
- `/infinite/search`
- `/infinite/lists` ... try creating/editing a list. Updates should be visible.
- **Definitely try sorting items:**
- Create a learning path at `/infinite/lists` if you don't have one already. Populate it with some items via the bookmark icon on search page / home page learning resource cards
- View the details page for the learning path. _Details page navigable from `/infinite/lists`_
- Click "Reorder" and try changing the item order. Re-ordering should be smooth. Items **should not snap back briefly** when released.

Update react query

---

search/api.py

#3999 
This PR brings over the conditional that was erroneously left in the service, rather than client, PR.
Have master locally, index. pull this, attempt to search using teh API (either on a page or using an API post).
1. pull master, reindex
2. pull this branch, attempt search locally (using API endpoint)
3. pull the branch with teh 7 service (which will have this branch merged into it)
4. reindex local again (verify can reindex)
5. test search on 7
Start indexing on master now lol
Why did this test ok? This conditional only kicks off on the es7 service because of the structure change of the RETURN which we don't get without integration testing, so in the testing and deploy of the 7 client, we did not see it until the SERVICE was updated.

Change search conditional to fix the 7.10-related error

---

requirements.in
requirements.txt

Update newrelic for heroku

---

requirements.in
requirements.txt

Closes #4090 
- Upgrades ipython and jedi
- Modifies `requirements.in` to be up to date with renovate's direct changes to requirements.txt
- Run `docker-compose build web`
- Run docker-compose run --rm web python manage.py shell
- Type `from course_catalog.` then press Tab for auto-complete suggestions
- You should get suggestions and no error statements

Fix ipython auto-complete error msg

---

authentication/views.py

https://github.com/mitodl/ol-infrastructure/issues/1825
When you visit http://od.odl.local:8063/logout or click "Sign out" from the user menu, you will be redirected to Keycloak and automatically logged out without having to perform any additional actions.
http://od.odl.local:8063/logout should resolve to a 404 page if the user is not authenticated.
This PR requires:
1. Keycloak configured with your local environment.
2. An Open Discussions account which was registered with a Keycloak account.
3. `FEATURE_KEYCLOAK_ENABLED=True` in your .env file.
1. Log into Open Discussions.
2. Navigate to http://od.odl.local:8063/logout
3. You should expect to be redirected to Keycloak and shown a screen indicating that you have been logged out.
4. Verify that you are logged out of Keycloak and Open …

Logout user from Keycloak without confirm page - Client logout flow

---

keycloak_user_export/management/commands/migrate_users_to_keycloak.py

Fixes #4258 
This switches the user migration command to use `Profile.name` instead of the fields on `User`. It attempts to split the name on the first whitespace, if it can't, then it defaults to empty strings (the current behavior). In the latter case the user will be prompted to fill these in on their first login to keycloak.
Run the script against your keycloak instance.

Update keycloak migration script to populate the user's name from `Profile`

---

keycloak_user_export/management/commands/migrate_users_to_keycloak.py

Closes https://github.com/mitodl/hq/issues/5560
- Adds the fields `fullName` and `emailOptIn` to the data sent to keycloak.
- Removes passing `firstName` and `lastName` as we're not using those.
- Fixes an error if the keycloak group path isn't passed.
You should be able to run the command `./manage.py migrate_users_to_keycloak ADMIN_USER ADMIN_PASSWORD admin-cli ADMIN_CLIENT_SECRET`

Added fields to keycloak export

---

keycloak_user_export/management/commands/migrate_users_to_keycloak.py
keycloak_user_export/management/commands/tests/test_migrate_users_to_keycloak.py

Fixes https://github.com/mitodl/open-discussions/issues/4377
The existing `chunks` function has a quirk because internally when `iter()` is called on a query set (as `chunks` does), django evaluates the entire query set. In production this means it loads all 300k users into memory and the process gets killed. I think we didn't realize this because we typically only use `chunks` to load a list of ids which happen to have fit into memory historically.
I started to implement a queryset-friendly version of `chunks`, however since the command is mutating the user records so that they're excluded from the query on the next loop this didn't work correctly and caused it to skip every other batch because the underlying data shifted. I think this also probably would've caused the prefetches to be …

Fix chunk iteration in user migration command
