static/js/components/ChannelHeader.js
static/js/components/ChannelHeader_test.js
static/js/components/ChannelNavbar.js
static/js/components/ChannelNavbar_test.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/ChannelAboutPage.js
static/js/containers/ChannelAboutPage_test.js
static/js/containers/ChannelPage.js
static/js/containers/ChannelPage_test.js
static/js/containers/ChannelRouter.js
static/js/containers/PostPage.js
static/js/containers/PostPage_test.js
static/js/containers/SearchPage.js
static/js/containers/SearchPage_test.js
static/js/containers/admin/EditChannelAppearancePage.js
static/js/containers/admin/EditChannelAppearancePage_test.js
static/js/containers/admin/EditChannelBasicPage.js
static/js/factories/channels.js
static/js/flow/discussionTypes.js
static/js/hoc/withChannelHeader.js
static/js/hoc/withCommentModeration.js
static/js/hoc/withPostModeration.js
static/js/lib/api/channels.js
static/js/lib/channels.js
static/js/lib/routing.js
static/js/lib/url.js
static/js/lib/util.js
static/js/util/form_actions.js
static/js/util/integration_test_helper.js

closes #1778 
closes #1623
This provides the frontend portion of the channel about page. That includes a new page, facilities to edit an save the about field on the channel, and a refactor of the channel routing logic to facilitate both adding a new page and removing some redundancy.
Make sure that all routes under `/c/channelName` work correctly and there are no regressions anywhere (I did some pretty extensive testing but there is a chance I missed something).
Ensure that, if you're a moderator user, you see an 'about' thing in the channel-level navbar.
if you go there you should be able to edit your channel's about document.
If you're not a moderator user you shouldn't see the link for the moderator page on channels which do not have the document saved, and you should see it on those …

add channel about page frontend

---

static/js/components/CommentForms.js
static/js/components/CommentForms_test.js
static/js/components/CreatePostForm.js
static/js/components/CreatePostForm_test.js
static/js/containers/CreatePostPage.js
static/js/containers/CreatePostPage_test.js
static/js/flow/discussionTypes.js
static/js/lib/api/posts.js
static/js/lib/posts.js
static/js/lib/posts_test.js
static/js/lib/validation.js
static/js/lib/validation_test.js

closes #1682
This adds validation to the post editing on the post detail page. You should be able to trigger a validation message showing up by either:
- editing an article post to be empty
or
- making a verrrryyy long (more than 40000 characters) post
Editing a post should work as before. Creating posts should work normally and there should be no regressions there. All flows for creating posts should be tested: all post types, switching between post types, switching between channels which disallow different post types, etc.
(Optional)
(Optional)

add validation to post edit form

---

requirements.in
requirements.txt

Updates ocw-data-parser version to introduce fix for this issue ["Large foreign media files"](https://github.com/zagaran/ocw-data-parser/issues/7) into course_catalog for `open-discussions`
Updates `ocw-data-parser` to `0.2.2` to handle large foreign media files (by chunking)

Updates ocw-data-parser version to fix large file memory issue with uploading large files to S3 in course_catalog 

---

Procfile
docker-compose.yml
open_discussions/settings.py
open_discussions/test_utils.py
open_discussions/test_utils_test.py
requirements.in
requirements.txt
scripts/heroku-release-phase.sh
widgets/serializers/rss.py
widgets/serializers/rss_test.py

Fixes #1749 
Based on RFC #1835 
This PR adds caching to RSS feed data. It does so on a per-url basis while allowing multiple RSS widget instances with the same URL to utilize the same cache because they may only differ by number of items shown.
- Run the app, ensure the `external_asset_cache` table is created
- Hit a page with an RSS feed, ensure a record shows up in the table for it
- Put a `raise Exception()` in `_fetch_rss_entries` and hit that page again. The exception should not get raised
- Edit the widget and change the rss feed url. Ensure after saving that you see the new feed items.
- Create a new RSS widget and ensure everything works for that too

Cache RSS widget feed data

---

static/js/components/auth/PrivateRoute.js
static/js/components/auth/PrivateRoute_test.js
static/js/containers/App.js
static/js/lib/api/fetch_auth.js
static/js/lib/api/fetch_auth_test.js
static/js/lib/auth.js
static/js/lib/auth_test.js

Fixes #1710 
- Fixes bug where anonymous users could access the create post page
- Adds a new `Route` component that auto-redirects if a user is not logged in (`PrivateRoute`)
As an anonymous user, try to navigate to `/create_post/` and `/create_post/<some_channel_name>`. Both should redirect you to the login page with the right `next` param
- `PrivateRoute` implementation inspired by [this example](https://reacttraining.com/react-router/web/example/auth-workflow)
- `/create_post/<some_channel_name>` already redirected before this PR, but `/create_post/` didn't. That was kind of by accident. If a channel name existed in the URL, you would get redirected to login since the API call to fetch channel info is implemented with `fetchJSONWithAuthFailure`. If you didn't have the channel name in …

Fixed anonymous create post page bug

---

course_catalog/management/commands/backpopulate_edx_data.py
course_catalog/tasks.py
course_catalog/tasks_test.py
open_discussions/settings.py

Addresses this issue ["export edX discovery API response to S3"](https://github.com/mitodl/course-catalog/issues/51)
Adds functionality to export edx courses into json format and upload it to s3
`course_catalog/tasks.py`

Adds functionality to export edx courses into json format and upload it to s3

---

static/js/lib/validation.js
static/js/lib/validation_test.js

fixes a bug in #1852
I should have `&&`-ed where I should have `||`-ed :woman_facepalming: 
Make sure you can reproduce the issue. 
- open the post creation form and go to create an article. 
- type in just one line of text
- try to submit, you should incorrectly get a validation error saying it's empty
then this branch should fix that issue.

fix article validation

---

requirements.in
requirements.txt

N/A
This PR upgrades the `ocw-data-parser` dependency to pick up the logging fix [here](https://github.com/zagaran/ocw-data-parser/pull/8).
- Run `./manage.py backpopulate_ocw_data` and it should function the same as master.

Bumped ocw-data-parser version

---

static/js/containers/PostPage.js
static/js/containers/PostPage_test.js

Fixes #1765 
Fixes #706 
Fixes the dialog not closing bug and also refactors tests on PostPage. There should be new tests for the bug and other related functionality.
Delete a comment. Click the accept button on the confirmation dialog. The comment should be deleted and the dialog should disappear.

Fix comment dialog dialog bug and refactor PostPage_test

---

static/js/hoc/withPostList.js
static/js/hoc/withPostList_test.js

closes #1841 
This PR evicts the current post list after the user has made a request to toggle the pinned state of a post. This will force the UI to show the 'true' state of the post list after the pinned state is updated.
There was a difficulty before because of some of the logic relating to the pagination. This sidesteps modifying or changing that logic by just clearing the whole post list, so we use what we get back from the API directly, instead of trying to figure out in which cases we want to merge the new post list into the existing one and in which cases we want to overwrite it.
Pagination and loading on the channel page should work as normal. If you pin a post you should see a spinner for a sec while the post list refreshes, and then you should see that the newly-pinned post is …

update the channel post listing after pinning / unpinning a post

---

static/js/components/EmbedlyCard.js
static/js/components/widgets/UrlWidget.js
static/js/lib/embed.js
static/js/lib/embed_test.js

Fixes #1856 
Adds an embedly hook to add CSS to hide a title for embedly card iframes in widgets
Add an embedly widget. You should not see the title (see images below)
Before:
After:

Hide embedly title for embedly widgets

---

course_catalog/constants.py
course_catalog/factories.py
course_catalog/task_helpers.py
search/indexing_api.py
search/serializers.py
search/serializers_test.py

Closes #1898 in conjunction with PR #1900.
Note: this PR merges code into the branch that PR #1900 is asking merging into `master`.
Code is split into two separate PRs on Peter's request.
Adds content population for newly added `availability` Course field on import and includes the content for Elasticsearch indexing via `ESCourseSerializer`
One question for the reviewer:
Should values for the `Course.availability` field be enforced at the database-level via a "choices" field parameter populated by the values of`course_catalog/constants/AvailabilityType` enum? 
Position of the author: I would typically prefer enforcement from an enum (and thus giving me a guarantee on the range of values I as a developer can expect from the database), but I ultimately opted to not enforce it at the …

populates and indexes new Course field `availability`

---

static/js/components/ArticleEditor.js

none
Just a little tweak that occurred to me (which I probably should have done before!).
The `ArticleEditor` component can get a little bit heavy sometimes and lead to some noticeable UI sluggishness when editing, I think because the `editor.getData()` method is a little bit expensive, and in our current setup we call that method on each keystroke. I just added the lodash `debounce` function to reduce that to once every 250ms, which makes it feel a lot more responsive to me.
I think go to the article post editor on master and just confirm that it sometimes feels a little sluggish when editing, especially if you're typing fast you should sometimes notice that the UI doesn't quite keep up with your input.
then check out this branch and confirm that it's better.

fix article post UI sluggishness

---

static/js/components/CourseToolbar.js
static/js/components/CourseToolbar_test.js
static/js/components/HamburgerAndLogo.js
static/js/components/HamburgerAndLogo_test.js
static/js/components/MITLogoLink.js
static/js/components/MITLogoLink_test.js
static/js/components/Toolbar.js
static/js/components/Toolbar_test.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/lib/url.js
static/js/lib/url_test.js

Closes #1889
Modifies `App` to use a different toolbar and no channel drawer for url's starting with `/courses`
- Go to `/courses/search`.  There should be no drawer at any width, no menu icon to display the drawer, and the toolbar should display the title "MIT Open | Courses" This title should consist of two links - one to the root url, the other to `/courses/` (which will be the course index page in another PR).  The toolbar should still have a working profile icon.
- Go to any other page, the channel drawer and toolbar should look and behave the same as always.
I'm guessing that the course index page URL will be `/courses/`, if not then this PR will need to be tweaked to the correct value.

Different toolbar and no channel drawer for courses

---

static/js/components/CompactCourseDisplay.js
static/js/components/CompactCourseDisplay_test.js
static/js/components/ExpandedCourseDisplay.js
static/js/lib/courses.js
static/js/lib/courses_test.js

Closes #1901
Shows the minimum price ("Free" if 0) instead of the maximum price.
- Search for courses.  Almost all of them should show "Free" for price in the compact and expanded course views.
- Search for "Basic Circuit Analysis" with the "Current" Availability facet checked.  The minimum price for one of the top results should be $9.99
The `maxPrice` function in `static/js/lib/courses.js` is no longer used, but I left it there in case we decide in the future to show a price range instead.

Show min price instead of max price for courses

---

static/js/components/SearchFilter.js
static/js/components/SearchFilter_test.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/flow/searchTypes.js
static/scss/search.scss

Closes #1887
Adds buttons below the text input field for each active facet filter, along with a 'Clear all filters' link.
Each button should remove the specified facet from the search filter.
The 'Clear all filters' link should remove all facets and text input from the search.
- Run a search with some facets selected and some search text.
- There should be buttons below the text input field for each selected facet.
- Click the 'x' on some of these buttons.  The appropriate facets should be unchecked and the search results should update.
- Click 'Clear all filters'.  All the facets should be unchecked and the text input should be cleared.  Search results should update accordingly.

Buttons to clear facets

---

static/js/components/CompactCourseDisplay.js
static/js/components/CompactCourseDisplay_test.js
static/js/components/CourseCarousel.js
static/js/components/CourseCarousel_test.js
static/js/containers/CourseSearchPage.js
static/js/factories/courses.js
static/js/factories/search.js
static/js/flow/discussionTypes.js
static/js/flow/searchTypes.js
static/js/lib/constants.js
static/js/lib/courses.js
static/js/lib/courses_test.js
static/js/lib/search.js
static/js/lib/search_test.js

Closes #1910
Closes #1861
Displays course availability based on the `Course` model's availability field, rather than start and end dates.  In particular, changes the `courseAvailability` function and renames it to `availabilityLabel`.  This function will now replace "Archived" with "Prior", "Current" with "Available Now", and display other availabilities as is.
Go to `/courses/search`.  The search results and facet choices should show these availabilities: Available Now, Prior, Upcoming, Starting Soon.  Select the 'Available Now' or 'Prior' facet and verify that they still work correctly.

Label course availability by model field instead of dates in UI

---

static/js/components/SearchFacet.js
static/js/components/SearchFacet_test.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/flow/searchTypes.js
static/js/lib/search.js

Fixes #1917 
Fixes #1923
Adds a `currentFacetGroup` property to `CourseSearchPage` to track which group of facets was most recently changed and what facets are contained therein, along with a new `mergeFacetOptions` method to determine which facets should be sent to the `SearchFacet` component.
- Within the 'Availability' group, select "Starting Soon".  The other Availability facets should continue to display without changes in counts, but "OCW" should disappear from the "Platform" group.
- Select "Available Now" in the "Availability" group.  The other Availability facets should continue to display without changes in counts, and "OCW" should reappear in the "Platform" group.
- Choose both "OCW" and "MITx" in the "Platform" group.  Then unselect "Available Now" from "Availability".  "OCW" …

Modify facet behavior within/between groups

---

static/js/components/ChannelHeader.js
static/js/components/PageBanner.js
static/js/components/SearchTextbox.js
static/js/components/admin/EditChannelAppearanceForm.js
static/js/containers/ChannelBanner.js
static/js/containers/ChannelBanner_test.js
static/js/containers/ChannelRouter.js
static/js/containers/CourseIndexPage.js
static/js/containers/CourseIndexPage_test.js
static/js/containers/admin/EditChannelBasicPage_test.js
static/js/hoc/withChannelHeader.js
static/js/lib/url.js
static/scss/admin.scss
static/scss/channel-banner.scss
static/scss/channel.scss
static/scss/course-index-page.scss
static/scss/layout.scss
static/scss/search.scss

closes #1800 
this adds a cover image to the top of the course index page. for now it is just showing the fallback background color and gradient that we show on the channel page when the no channel cover image has been set.
To implement this I refactored the styling for the channel cover image into reusable components so we could share the implementation with the course index page. So check that the channel header looks good and is working correctly on all the pages where it is present (channel page, post page, channel settings, etc).
also check that it is display correctly on the course index page. nothing should be weird!
also the search box on the channel index page should work correctly. if you type in a query and hit enter it should redirect you over to the course search page, and …

add cover image to course index page

---

course_catalog/task_helpers.py
course_catalog/task_helpers_test.py

**As part of merging this PR, an manual action should be performed: 
Remove the Course instances for the six courses of interest as well as their Elasticsearch index objects. (alternatively, set their instance Course.published to False)**
Closes #1930 
This PR prevent "deleted" Courses by being ingested again at the next data sync with a code change to course_catalog.task_helpers
To test, after the code change, we can perform a sync and see if the courses of interest get synced again.

Addresses issue #1930

---

static/js/containers/ChannelPage.js
static/js/hoc/withPostModeration.js

closes #1926 
this makes it so that after you click 'remove post' on a post in the channel index page the post listing will be cleared and then refreshed. this will make it so that the removed post goes away after you click, instead of the current behavior where it just sticks around forever.
go to a channel where you're a moderator and make a post. then remove the post from the post list (not from the post detail page). after you confirm that you want to remove the post, you should see the post list refresh, and the removed post should no longer be there.
it might be good to also confirm that you can reproduce the issue on `master`.

refresh post list after removing a post (from channel index page)

---

config/nginx.conf
config/nginx.conf.erb

This is from an email request
We need to be able to handle a redirect from the lemelsonx.mit.edu domain to a specific channel in open so this redirect will serve that purpose. We will update the DNS to be a cname of open.mit.edu so that anyone who goes to that endpoint will wind up where we want them to.
Use a Charles proxy to override the DNS for lemelsonx.mit.edu to point to the CI domain for open

Added a redirect rule to handle traffic to the lemelsonx subdomain

---

config/nginx.conf
config/nginx.conf.erb

N/A
Adds a redirect for themove.mit.edu to a discussions channel
Testing locally, add an `/etc/hosts` entry for the app that points themove.mit.edu at localhost

Added redirect for handling themove.mit.edu

---

static/js/containers/ChannelSettingsLink.js
static/js/containers/ChannelSettingsLink_test.js

closes #1947
this hides the 'manage widgets' button in the moderator settings menu (from the little gear icon) when the user is on the post detail page (keeps it everywhere else).
If you're on the channel page or the channel settings page you should still see the 'manage widgets' button in the settings dropdown. on the post detail page it should be absent.

hide 'manage widgets' button in settings dropdown on post page

---

profiles/api.py
profiles/api_test.py
search/indexing_api.py
search/serializers.py
search/serializers_test.py
static/js/components/Picker.js
static/js/components/Picker_test.js
static/js/containers/ChannelMembersPage.js
static/js/containers/ChannelMembersPage_test.js
static/js/flow/searchTypes.js
static/js/lib/picker.js
static/js/lib/search.js
static/js/lib/search_test.js
static/scss/channel-member-page.scss

closes #1941 
this adds sorting to the channel members page, currently it just lets you pick between sorting based on the members' names and when they joined the channel.
If you go to the channel member page you should see options for switching the sort. it should change it in a way that makes sense - so the people should be alphabetically sorted with the name option, and the people should be sorted so that the most recently added to the channel are at the top with the channel join date option.
You'll need to run the `recreate_index` command to put the new info into the index.

add sorting for the members page

---

open_discussions/app_tests.py

N/A
Adds a test to ensure app.json is parsable and has certain keys, this will avoid a recurring issue where we don't catch this because heroku only executes it for new apps

Added test for app.json validity

---

static/js/actions/ui.js
static/js/components/Navigation.js
static/js/components/NavigationItem.js
static/js/components/NavigationItem_test.js
static/js/components/SubscriptionsList.js
static/js/components/SubscriptionsList_test.js
static/js/containers/Drawer.js
static/js/containers/Drawer_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/_variables.scss
static/scss/drawer.scss
static/scss/layout.scss

closes #1952
this PR changes the desktop drawer UI to match what is in the mockups (see the linked issue for details). basically currently, when you're on desktop the drawer hides and shows itself by sliding off to the left, this changes things so that instead it's 'hidden' form is like a compact version of itself.
I also changed it so that the drawer defaults to it's closed state on desktop, so the drawer doesn't take up quite so much space by default. 
I think just click around and make sure it works well. In particular you should verify the following:
- on the desktop the drawer should expand out to be wider when you hover your mouse over it and then contract again when you mouse out of it
- on the desktop if you click the hamburger button the drawer should open and then stay open …

refactor desktop drawer to collapse instead of hiding itself

---

app.json
docs/design/email_notification.md
notifications/api.py
notifications/api_test.py
notifications/tasks.py
notifications/tasks_test.py
open_discussions/settings.py

Part of #1985 
This PR tries to make our frontpage email sending more resilient by making the following changes:
- Updates the cron tasks to generate a bunch of subtasks to walk batches of the eligible users rather than trying to walk all users in one task.
- The idea here is that this reduces the scope of a failure to a retry of a small subset of users and improves parallelism on the send (so it hopefully doesn't take several hours)
- This will also help this task tolerate heroku restarts and OOM-killing better
- Each of these batches have extra task flags set to ensure celery doesn't preemptively acknowledge them (`acks_late`) or acknowledge them when the worker gets stopped / killed (`reject_on_worker_lost`)
- It also adds some configuration knobs for a few things:
- `rate_limit` for …

Improved resilience and sending speed of frontpage notifications

---

course_catalog/data/professional_programs.json

part of #1979 professional ed metadata
Adds an occasionally-updated json file that maps course keys to program metadata. This is used to augment course metadata when it's imported from the edX course catalog API .
For now, this is just for an eyeball-review of the data structure. Presumably there will be additional PRs with code and tests that use this data. 
See https://docs.google.com/document/d/1UtVeoeXaWfv887t_ZoTcDRhzwZRguZD6sn8ltQELP4M/edit?ts=5cbde991#heading=h.235cvdpv81v4

add professional programs data

---

open_discussions/settings.py
requirements.in
requirements.txt
widgets/admin.py
widgets/serializers/rss.py
widgets/serializers/rss_test.py

Fixes #1982 
- Fixes the RSS widget so it doesn't cause the entire API to fail if an invalid RSS url is input or the url becomes invalid after a successful save.
- Adds `WidgetList`and friends to django admin
- Verify django admin works within reason (`position` needs to be maintained manually and there is no validation of the configuration)
- Verify that if you enter an invalid url (through django admin) that the widget list returns, but with an empty list.

Fix RSS widgets for invalid urls and add admin ui for them

---

static/js/components/SubscriptionsList.js
static/scss/drawer.scss
static/scss/layout.scss

closes #1994
closes #1998
This takes care of two things. The first is adding a css transition to animate the change between the expanded and compact state (for the desktop drawer). 
For this I just did a css transition of 500ms on the `width` property. I also changed the styling slightly to deal with things getting a little squished while the animation was planing. Basically, before we had the `.mdc-drawer--persistent` div, and the `.mdc-drawer__drawer` inside of that, and both of those changed their width when the open / closed state was toggled. I changed it around so that `.mdc-drawer__drawer` is always the full width, but `.mdc-drawer--persistent` has `overflow: hidden` so we don't see the full width of that div when the drawer is compacted.
I also changed how the navigation subtitles …

add animation to the drawer opening and closing

---

static/scss/widget.scss

closes #1877
just a few little css tweaks to make it obvious that links in the markdown widget are, you know, links
make a markdown widget with a link in it, and confirm that it looks like a link. should be blue, should underline on hover.

fix styling of links in 'markdown' widget

---

static/js/containers/ChannelRouter.js

closes #2005
This adds the channel navbar (the thing that shows 'Home', 'About', etc) to the post detail page. It looks like when the element was added there was an inconsistency in the design mockups, some showing it on the post detail page and some not, so that might be why it was inadvertently not added to the post detail page. 
click around on the all the channel sub pages, and make sure that the channel navbar shows up when you expect it to and, like, works and stuff, haha.
it should show up on the post detail page in particular.

add channel navbar to post detail page

---

static/js/components/widgets/UrlWidget.js
static/js/components/widgets/UrlWidget_test.js
static/js/components/widgets/WidgetEditDialog.js
static/js/containers/App_test.js
static/js/containers/ChannelPage.js
static/js/containers/ChannelPage_test.js
static/js/containers/admin/EditChannelBasicPage_test.js
static/js/containers/admin/EditChannelModeratorsPage_test.js
static/js/factories/widgets.js
static/js/flow/widgetTypes.js
static/js/lib/html.js
static/js/lib/html_test.js
static/js/lib/util.js
static/js/lib/util_test.js
static/js/lib/validation.js
static/js/lib/validation_test.js
static/scss/widget.scss
widgets/serializers/react_fields.py
widgets/serializers/url.py
widgets/views_test.py

closes #1951 
This changes the URL widget so that the user can enter custom html embed code for embedding content from Twitter. This is because standard embeds from Twitter with embedly aren't so good for some pages, and some users would like to be able to use publish.twitter.com to make custom embeds to include on their channels.
Basically, now there are two fields on the embed widget, a URL field and a 'custom html' field. The URL field works as before. The 'custom html' field lets you put in some twitter embed code. There's validation to make sure that the content is only from twitter and also that the user only fills out the url field or the custom html field, not both.
Make sure that your existing URL widgets work ok with this code.
Then make sure you can make a new URL widget, using …

add option for custom html on URL widgets

---

static/scss/layout.scss

none
small tweak to the drawer animation. I wanted to have a transition on the `.content` div as well, so that when the drawer opened or closed the change in size in the content div would be animated as well. I goofed though and forgot that we don't set the `width` property on `.content`, but we change it's size by changing the amount of `padding-left`. This corrects the `transition` property on `.content` so that the change in width for the content animates nicely along with the drawer opening and closing.
open and close the drawer a few times on master, and observe how although the drawer itself is animated the width change for the pages content isn't smooth. then check out this branch and observe the fancy animation.

fix drawer open / close animation

---

static/scss/channel.scss

closes #1843
this fixes a small rendering bug that we had with the channel navbar. previously, it was rendering too tall on mobile and it looked weird (see screenshots below). this fixes the issue.
check out this branch and confirm that the channel navbar now looks as it should everywhere, on both desktop and mobile.
before, on mobile:
with the fix, mobile:
desktop:

fix rendering height of channel navbar on mobile

---

static/scss/widget.scss

none, follow on change from #2004 
this makes the help text on the URL widget form 11px instead of 14px.
Just check out the branch and make sure it looks like what's in the screenshots below I suppose.

fix under text font size

---

mail/templates/email_base.html

Fixes #2002 
Updates the logo in the emails to be linked via static assets, which should be configured as cloudfront in ci/rc/prod. 
Unfortunately, we can't test cloudfront locally, so you'll need to just verify the emails still render ok:
- Go to http://od.odl.local:8063/__emaildebugger__/ and verify that the emails still render the logo correctly

Fix email url to go through static assets

---

requirements.in
requirements.txt

#2010
Updates ocw data parser in requirements to use version that removes certain fields from master_json
Manually run the ocw sync, and check that the master_json files do not have 'course_owner' or 'mit_id' fields.

Remove fields from OCW course master_json files

---

static/js/lib/api/api.js
static/js/lib/api/api_test.js
static/js/lib/api/widgets.js
static/js/lib/api/widgets_test.js
static/js/reducers/widgets.js
static/js/util/integration_test_helper.js

more work on #1667 
just splits the widget-related API functions out into a separate file, like we've already done for a number of other files.
make sure that the changes look reasonable and all frontend widget-related activities work as normal.

split out widget API stuff from the big `lib/api/api.js`

---

static/js/components/ChannelNavbar.js
static/js/components/Grid.js
static/js/components/Grid_test.js
static/js/containers/SearchPage.js
static/js/hoc/withSidebar.js
static/js/lib/util.js
static/scss/channel.scss
static/scss/layout.scss
static/scss/post.scss

closes #2016
- increases desktop width of the two-column layout from 960px to 1440px
- changes from 8 / 4 column setup to 7 / 5
- adds padding to the top of the widget list, so it lines up visually with the first card in the post list
check out the branch and make sure that it looks alright and everything is usable and so on. check on mobile too.

grid width / layout tweaks

---

static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/containers/CreatePostPage_test.js

closes #1924 
also closes #1991 (I got too frustrated by build failures haha)
this fixes an issue with the infinite scroll on the course search page. basically, the issue was that we had two different types of loading states, one which was triggered by scrolling down and one triggered by changing the search text or the selected facets. In the case of the latter we want to reload the whole result UI, clear the old results, and start from scratch, but in the former case we want to show the already-fetched results while the infinite scroll component takes care of the loading indicator at the bottom. But our existing code only dealt with the latter case, and didn't distinguish the former adequately (there is more explanation of this on the issue if this is not clear).
So to fix it I basically …

fix course search page loading behavior

---

static/js/hoc/withSidebar.js
static/scss/layout.scss

this closes #2022 
this changes the width of the overall grid to 1100px and goes back to an 8 / 4 column split.
check out the branch and make sure everything looks good on mobile and desktop.

tweak the post page grid and column widths

---

package.json
static/js/store/configureStore.js
yarn.lock

none
this adds redux-localstorage and configures it to persist the value for `ui.showDrawerDesktop` to the localstorage. this will persist the value that the user sets, and when the app loads next the saved value will be used to set the initial state for the app. this means that if the user prefers to have the drawer open on desktop it will be 'sticky' between full page refreshes.
confirm it works as described above and nothing else is broken!

persist desktop drawer open / close value to localStorage

---

static/js/components/CourseToolbar.js
static/js/containers/App.js
static/scss/_variables.scss
static/scss/course.scss
static/scss/navigation.scss

part of #1997
this changes the label in the couse-page-specific top bar to be in-line with the new designs. I also did a slight refactor in how we figure out when to show the course top bar vs the top bar for the rest of the site.
go to the homepage, things should look normal. then go to `/courses`, you should see something like the screenshots below. make sure it looks ok on mobile and so on.

changes to course page top bar

---

course_catalog/factories.py
course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

#2057
This PR adds views, serializers, factories, and tests for the new course catalog models.
Create courses, bootcamps, programs, and learning paths, and then navigate to the relevant pages.
`api/v0/[courses|bootcamps|programs|learningpaths]`

Serializers, views, factories, and tests for course_catalog models

---

static/js/components/NavigationItem.js
static/js/components/SubscriptionsList.js
static/js/containers/Drawer.js
static/scss/drawer.scss
static/scss/layout.scss

no ticket, but follow-on from #2000 
This modifies the drawer again to be more in-line with the behavior that exists for gmail. Basically, this changes a few things about how the hover-over version works:
- now only opening / closing with the hamburger button causes the rest of the page to move. if you hover over the drawer expands, but the content on the rest of the page doesn't move.
- I also added a slight delay only for the hover-over open. I noticed that gmail has this - it prevents the animation from starting if you just quickly mouse in and then out, which can prevent some unsightly animation flashing. you can see how this looks in the gif below.
- I also added a very slight box-shadow to the right edge of the desktop drawer, just to add a slight visual indicator for where the edge …

drawer open/close animation tweak

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

_This is PR is intended to start the conversation around how the frontend and backend will interact to create the feature of users being able to favorite learning resource objects and displaying search results as favorited or not. Ideally, a user can favorite and unfavorite an item in real-time and have that be quickly reflected in their Favorites list_
Questions:
- How can we display whether a Search result is favorited or not?
- How do we populate the "My Favorites" list on the home page? Does the content from Elasticsearch, or does it come from an backend endpoint? If course/etc data comes from Elasticsearch, do we make ES queries for each favorited object?
- Would endpoint that takes in `object_id, object_type` pairs and returns true/false whether it is a favorite of the current user …

Add endpoints for users to favorite and view favorited items

---

search/api.py
search/api_test.py

N/A
Fixes broken search for anonymous users
Search for courses and search for posts/comments, while logged in and anonymously.  There should be no errors either way.

Fix search query for anonymous users

---

static/scss/drawer.scss

none
This fixes a few small styling issues with the drawer. 
the first is an issue that crops up with long channel titles, like this one on production:
basically it shouldn't be all wonky. and also, the left edge of the channel titles is supposed to be aligned with the 'Compose' and 'Home' text.
I also fixed a weird behavior with the `transition-delay` property I had set.
create a channel with a long title and make sure it doesn't totally break everything. also make sure the drawer looks alright and feels like it should to use.

fix a few drawer styling issues

---

channels/admin.py

Fixes #2093 
Hides `allowed_post_types` in django-admin. Unfortunately `BitField` is broken under django 2.1+, and pending either migration away from this or a new release of the library being cut, this is the quickest fix. This field can still be updated in the react app by a channel moderator.
Go to django admin for a channel and verify you can make changes.

Ignore allowed_post_types from django-admin

---

app.json
course_catalog/api.py
course_catalog/api_test.py
course_catalog/factories.py
course_catalog/management/commands/backpopulate_edx_data.py
course_catalog/management/commands/backpopulate_ocw_data.py
course_catalog/serializers.py
course_catalog/tasks.py
course_catalog/tasks_test.py
open_discussions/settings.py
test_json/test_mitx_course01.json
test_json/test_mitx_course02.json

- Closes #2115
- Adds an overlooked setting to api.json and settings.py (`MAX_S3_GET_ITERATIONS`)
Imports MITx data into both `Course` and `CourseRun` objects.
- Set required .env variables (you can copy from heroku CI):
```
EDX_API_URL
EDX_API_CLIENT_ID
EDX_API_CLIENT_SECRET
OCW_*
```
- Run `docker-compose run web python manage.py backpopulate_edx_courses --delete`
- Verify that `Course` objects with `platform=mitx` were created, and each of these courses have at least 1 `CourseRun` object.
- Verify that the `Course` objects have associated `CourseTopic` objects, and that the `CourseRun` objects have associated `CourseInstructor` and `CoursePrice` objects.
- Go to `http://od.odl.local:8063/courses/search`, there should be results for MITx platform courses, and they should display almost …

Import courses and course runs for MITx

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/serializers.py
course_catalog/serializers_test.py

Closes #2122
Adds course runs to the `CourseSerializer`
Go to `http://od.odl.local:8063/api/v0/courses/<course_id>` for an MITx course and an OCW course.  The returned JSON for the MITx course should include all the data for the course runs.  The JSON for the OCW course should be an empty list.

Include course runs in CourseSerializer

---

course_catalog/factories.py

N/A
Changes `CourseTopicFactory.name` and `CoursePriceFactory.price` to sequences in order to make certain each one is unique, otherwise the expected counts may not always equal the actual counts and tests will intermittently fail.
Run `docker-compose run web pytest course_catalog/serializers_test.py` 5 or 6 times, there should be no failures.

Make topic and price sequences again in tests

---

search/indexing_api.py
search/serializers.py
search/serializers_test.py

Fixes #2116 
Expands course indexing to also include course runs
- Run `./manage.py recreate_index`
- Verify the search page is still as functional as `master`
- You should also see nested `course_runs` data coming back in `_source` on the results
- Try running a query to find courses with specific course runs. An example one is provided in this PR:
```
curl --header "Content-Type: application/json" \
--request POST -s \
--data "$(cat test_json/es/2015_course_runs.json)" \
http://localhost:9101/local_all_default/_search | jq
```

Index course runs under courses

---

static/js/containers/CourseIndexPage.js
static/js/containers/CourseIndexPage_test.js
static/js/containers/CourseSearchPage.js
static/js/lib/queries/learning_resources.js

closes #2092
This adds a very basic display of the favorites to the course home page, along the same lines as what we already do for the other lists of courses on that page. The design for what this will look like is not finalized yet, so I did not want to go ahead and implement a different design for this than what we use for the existing carousels - when it is finalized I'll circle back to implement the favorites-specific design.
Go to the course home page and make sure your favorites show up there! that's it.

course home favorites

---

static/js/components/CourseCarousel.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/SearchResult.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/lib/constants.js
static/js/lib/search.js
static/scss/_variables.scss
static/scss/course-carousel.scss
static/scss/course.scss
static/scss/learning-resource-card.scss

closes #2160 
closes #2159 
this implements the new design for the course cards, including the list and grid views.
go to the course home page. you should see the new design for the cards int he course carousels. then navigate to the course search page. all functionality should be there, and you should be able to choose between the 'grid' and 'list' views. the ui should match the mockups pretty well (although some things like the filters up top haven't been updated yet)

change out course card UI

---

course_catalog/api_test.py
course_catalog/serializers.py

N/A, related to #2123
Removes CourseRunSerializer lines that made best_start_date and best_end_date read-only
```
docker-compose run web python manage.py backpopulate_edx_data --overwrite
```
- any course runs with a non-null `enrollment_start/end`, `start/end_date`, or `semester` and `year` should have a populated `best_start/end_date`

Make sure best date fields are writable in serializer

---

static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js

closes #2180
this fixes an issue with the facets on the course search (see the attached issue) where they were basically not as responsive as they should be. In particular, if the user clicked a number of facets at the same time a search request was fired off for each one, which led to some laggyness in the UI (and probably some unnecessary load on the elasticsearch). We only care about the last request, so I just debounced this to we'll wait until the user stops interacting to fire off the request.
I think just check out `master` first and confirm you can kind of reproduce the issue as described. then check out this branch and make sure it fixes it and isn't, idk, weird or something.

fix facet responsiveness issue

---

flow-typed/npm/moment_v2.x.x.js
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/SearchResult.js
static/js/containers/CourseSearchPage.js
static/js/factories/learning_resources.js
static/js/flow/discussionTypes.js
static/js/flow/searchTypes.js
static/js/lib/constants.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/lib/search.js
static/js/lib/search_test.js

Closes #2162
- Sends the selected availability facets (if any) to the `LearningResourceCard` card component
- Adds functions for determining the best run/availability to display
- Select 'Available Now' facet only, all the results should show 'Available Now'
- Select 'In the next year' only, results should show a mix from 'In the next week' to 'In the next year'
- Select 'Available Now' and 'In the next year', results should show a mix from 'Available Now' to 'In the next year'.  
- Select 'Programs' and 'Learning Paths' facets, they should all be 'Available Now'

Show most relevant availability for search result

---

course_catalog/admin.py

Closes #2126 
Adds `CourseRun` inlines to `Course` in admin
Adds `CourseRun` section to admin
- View a `Course` and a `Bootcamp` in django admin, there should be a list of runs at the bottom.
- Go to `/admin/course_catalog/courserun/`

Add CourseRun to Django Admin

---

static/js/components/SearchFacet.js
static/js/components/SearchFacet_test.js
static/js/components/SearchFilter.js
static/js/components/SearchFilter_test.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/scss/_variables.scss
static/scss/search.scss

closes #2161
this restyles the display for the filters that the user currently has selected on the course search page. it basically moves the display into the left-hand column, adjusts some styling to match the new mockups, etc. nothing too major!
go to the course search page and make sure that the display matches what's shown in the mockups (see the linked issue).

restyling active search filter list

---

.eslintrc
package.json
static/js/components/CourseCarousel.js
static/js/components/CourseCarousel_test.js
static/js/components/LearningResourceCard_test.js
static/js/components/SearchFacet_test.js
static/js/containers/CourseIndexPage.js
static/js/containers/CourseIndexPage_test.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/containers/HomePage_test.js
static/js/containers/SearchPage_test.js
static/js/factories/learning_resources.js
static/js/lib/queries/bootcamps.js
static/js/util/integration_test_helper.js
yarn.lock

follow-on from #2168
when I upgraded eslint and some related packages there was, at the time, a bug in the latest version of babel-eslint that broke the parsing for the `no-unused-vars` rule. basically, it caused it to have tons of false positives, marking a lot of stuff that was fine incorrectly as an unused variable. because of this I had to disable the rule to get the build to pass.
Anyway, that issue has now been fixed in the latest version of the package, so I updated to that. this let me re-enable the rule. I also fixed all of the unused variable errors that we'd accumulated in the meantime while the rule was turned off, which was a surprisingly large amount!
tests should pass, code should look good.

upgrade babel-eslint

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/components/LearningResourceCard.js
static/js/components/SearchResult.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/js/containers/LearningResourceDrawer.js
static/js/flow/discussionTypes.js
static/js/flow/searchTypes.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/reducers/ui.js
static/scss/course.scss

Closes #2124 
- Sends the most relevant course run id (if any, based on availability facets) to the drawer, where that run's info will be displayed (start date, price, instructors).  
- Adds a dropdown to the drawer allowing the user to select another course run (which will again update the drawer info shown).
- Does not restyle the dropdown to match the design, I'm assuming that restyling is a separate PR.
Do some course searches, with variations on the availability facets used.  Click on one of the search results to open the drawer.  The run shown in the drawer by default should be the best match for the availabilities selected.  There should be a dropdown at the top where you can choose different runs, and doing so should update the start date, instructors, and prices shown in the …

Display the most relevant course run, with dropdown, in course drawer

---

open_discussions/settings.py

Fixes #2213 
Adjusts the catalog import crontabs to run starting in the morning
`docker-compose up` and check the output that celery ran and set the scheduled tasks, you should see output like this:
```
celery_1   | [2019-09-13 18:45:17,939: INFO/Beat] beat: Starting...
celery_1   | [2019-09-13 18:45:17,965: INFO/Beat] Scheduler: Sending due task evict-expired-access-tokens-every-1-hrs (channels.tasks.evict_expired_access_tokens)
celery_1   | [2019-09-13 18:45:17,978: INFO/MainProcess] Received task: channels.tasks.evict_expired_access_tokens[15afc846-12f2-4525-b695-c3c9487aa860]  
celery_1   | [2019-09-13 18:45:17,980: INFO/Beat] Scheduler: Sending due task send-frontpage-digests-every-1-days (notifications.tasks.send_daily_frontpage_digests)
celery_1   | [2019-09-13 18:45:17,982: …
```

Adjust cron job times

---

static/js/components/Loading.js
static/js/containers/CourseSearchPage.js
static/js/containers/CourseSearchPage_test.js
static/scss/channel.scss

part of #2167
basically this just deletes the little "top bar" that was previously shown in the course search. this was there because we were previously just using the same loader that we use for the post lists (e.g. on a channel or on the home page). I made a separate one just for the course search which doesn't have that top bar.
note that this only addresses getting the loader in shape for the 'list' view - I'll circle back with a separate PR to address the 'grid' view loader.

fix course search "list" loader

---

static/js/containers/NewCoursesWidget.js
static/js/containers/NewCoursesWidget_test.js
static/js/lib/test_utils.js

none, just a quick little refactor.
just a little refactor to bring it in line with how we use the same APIs on the course home page (so we're not doing it two different ways in different places)
the new and upcoming courses widget on the home page should work as normal, code should look reasonable.

refactor the 'new courses widget' to use hooks

---

static/js/components/CourseCarousel.js
static/js/components/Loading.js
static/js/containers/CourseIndexPage.js
static/js/containers/CourseIndexPage_test.js
static/js/containers/CourseSearchPage.js
static/js/lib/search.js
static/js/util/integration_test_helper.js
static/scss/course-carousel.scss
static/scss/learning-resource-card.scss

closes #2224
closes #2167
this implements a "grid" style loader for the course search page and also implements a "carousel" style loader for the course home page (to show while the couse information to populate the carousels is being fetched)
go the course home page. ensure that at all browser widths a carousel style loader is shown that mimics the size and placement of UI elements in the fully loaded page.
then go the course search page. ensure that if you switch to a grid view and change a facet you see a 'grid' loader that looks like the UI that eventually loads.
carousel loader:
search page:
mobile:

add 'grid' style loader to the course search and course home pages

---

static/js/components/LearningResourceCard_test.js

N/A
Makes sure 'offered_by' is not null when testing the topics section of the LearningResourceCard
Run `npm run-script coverage static/js/components/LearningResourceCard_test.js`, there should be no errors

Fix occasionally failing test for LearningResourceCard

---

static/js/containers/CourseSearchPage.js
static/scss/learning-resource-card.scss

none
this does a few little tweaks to styling and layout on the course search page.
- removes the 'course catalog' text from the top banner
- changes the widths of the two columns on the course search page. in the 'list' view we do 4 columns for the facets and 8 for the results, and in the 'grid' view we do 3 columns for the facets and 9 for the results.
- restyles the 'list' view of the card so that the way that the text and spacing is done is more consistent for learning resources that have a one or two line title (among other things).
check out hte course search page and make sure everything works alright and looks good. if you switch between the list and grid views you should see that the proportion of space allocated to the facets vs the results changes (from 4/8 in the list view to …

some search page styling tweaks

---

search/serializers.py
search/serializers_test.py
static/js/lib/search.js
static/js/lib/search_test.js

Based off PR #2232 
Closes #2220
- Adds a `coursenum` field to course and bootcamp search docs, based on course_id
- Makes that field searchable and boosts it.
- Import edx courses if you haven't already (`manage.py backpopulate_edx_data`)
- Recreate the index if you already imported the courses
- Search for "18.06", the first result should be "Linear Algebra"
- Search for "6.002x", the first result should be "Circuits and Electronics"

Add course number to the search index and boost it in queries

---

static/js/lib/search.js
static/js/lib/search_test.js

Closes #2221
Modifies the ES query to properly search nested fields.
Search for the names of certain professors who teach courses, using full name or just last name.  The top results should include courses with runs taught by them.

Search nested fields including instructors

---

course_catalog/etl/xpro.py
course_catalog/etl/xpro_test.py

Closes #2248 
Populates best_start_date and best_end_date fields for xpro course runs during import.
- Set `XPRO_CATALOG_API_URL=http://docker.for.mac.host.internal:8053/api/programs/` (osx)
- Run `course_catalog.tasks.get_xpro_data`
- Verify that imported xPro course runs have correctly populated `best_start_date` and `best_end_date` fields

Populate best date fields during xpro import

---

static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js

closes #2217
fixes the pluralization for "Subject" in the learning resource card. in particular:
- if there are no topics we don't show that line
- if there's one topic we say "Subject - "
- if there's multiple topics we say "Subjects - "
make sure that the above works as advertised

fix pluralization of 'subject' on learning resource card

---

search/serializers.py

N/A
`search.serializers_test.test_es_course_serializer` occasionally [failed](https://travis-ci.org/mitodl/open-discussions/jobs/592215558) because the order of course runs wasn't always the same.  This PR adds a default sort order to the `ESCourseRun` serializer.
Run python tests a few times, they shouldn't fail.

Fix an intermittent test failure

---

static/js/components/CourseFilterDrawer.js
static/js/components/CourseFilterDrawer_test.js
static/js/components/CourseSearchbox.js
static/js/components/CourseSearchbox_test.js
static/js/components/PageBanner.js
static/js/components/ResponsiveWrapper.js
static/js/components/ResponsiveWrapper_test.js
static/js/components/SearchFacet.js
static/js/components/SearchFacet_test.js
static/js/hooks/util.js
static/js/lib/constants.js
static/js/pages/CourseIndexPage.js
static/js/pages/CourseSearchPage.js
static/js/util/integration_test_helper.js
static/scss/button.scss
static/scss/course-filter-drawer.scss
static/scss/course-searchbox.scss
static/scss/course.scss
static/scss/layout.scss
static/scss/learning-resource-card.scss
static/scss/search.scss

closes  #2103
this PR implements mobile view for the course search and course home page. in particular, there are two main things I'm doing here:
- fixing the facets, so that only mobile you have to click a little button to open them (they take over the screen when they're open)
- fix the display of the search bar and the top banner on mobile
test it out at a bunch of screen widths, both on the course home page and on the course search page, to make sure things look ok and that they are working well. I think it should all be good as far as the responsive stuff.

course search mobile view

---

static/js/components/PageBanner.js
static/scss/course-searchbox.scss

none, fix for a layout bug I introduced in #2250
I made this sad thing happen:
so I fixed it. the issue was that I changed some of the styling for the top banner components (which are shared between channel page, course search page, and post page) to accomodate the mobile UI for the course search page, but didn't realize that part of the display for the post page had been negatively impacted.
check out the branch and make sure it fixes the issue above, and that the display for the course search page isn't negatively affected by the fix.

fix a layout bug introduced in 2250

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/serializers.py
course_catalog/tasks.py
course_catalog/tasks_test.py

Fixes #2125 
Updates indexing code to delete documents from the Elasticsearch index which are unpublished
First, start on master. Make sure you have up to date OCW data, or run `./manage.py backpopulate_ocw_data` if not. Go to `/courses/search?q=linear%20algebra` and there should be some Linear Algebra courses available. Click on each one from the top of the list until you get to one whose instructor is "Gilbert Strang". Click the "As Taught in" dropdown and verify that there are three years: 2002, 2005, and 2010. Select '2002' and click 'Take Course on OCW'. You should get a 404 page.
Run `./manage.py backpopulate_ocw_data --skip-s3 --overwrite`. This will take many hours and you may need to run it overnight. After it finishes, go back to the course search and look for the same course as …

Remove OCW courses from search if they are unpublished

---

course_catalog/etl/micromasters.py
course_catalog/etl/micromasters_test.py

Fixes #2281 
Updates micromasters ETL transformation to handle new fields added
Make sure `MICROMASTERS_CATALOG_API_URL` is set properly.
Open a Django shell and run:
from course_catalog.etl.pipelines import *
programs = micromasters_etl()
Go to `/api/v0/catalog/` on your micromasters instance and then verify that:
- `programs` in the shell matches the programs in the catalog API
- For a program run `[topic.name for topic in program.topics.all()]` and verify that the topics match the catalog API
- Run `[instructor.full_name for instructor in program.runs.first().instructors.all()]` for some `program` and verify that the instructors match the catalog API output
- Run `program.runs.first().start_date` (and `end_date` and `enrollment_start`) and verify that they match
- Finally, verify that …

Add instructors, topics, and program prices to micromasters ETL transform

---

course_catalog/admin.py
course_catalog/etl/xpro.py
course_catalog/etl/xpro_test.py
course_catalog/models.py
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/lib/search.js
test_json/xpro_programs.json

Closes #2256 
- Imports xPro program topics and instructors
- Makes program instructors searchable
- Enables autocomplete for topics, instructors fields in django admin
- Set `XPRO_CATALOG_API_URL` to an instance of xpro with programs that have instructors and prices.
- Run `course_catalog.tasks.get_xpro_data()`
- Verify that the imported xpro programs have the correct topics, and the program runs have correct instructors and prices.
- Go to `courses/search` filter by program, and search for a particular instructor you know is in a program.  That program should be at the top of results.
- Click on one of those programs, the instructors and topics should be shown in the drawer.

Import xPro program topics and instructors

---

static/js/components/SearchFacet.js
static/js/components/SearchFacet_test.js

closes #2287
This PR fixes a small UI weirdness, which is that currently we show the show more / show less UI for any search facet where we have more than 5 options. Thus, if there are six options there is a strange case where clicking "show more" only causes you to see one more option...
Anyhow, this fixes the issue by changing things around so that we now only show this UI if the list of options is a bit longer, currently 15. Maybe we want just 10 instead? idk, up for debate. But anyhow, with this change that UI should only be shown for our longer option lists, namely the subjects, and shouldn't be used for any of the others.
Make sure that the behavior described above is there and that I haven't introduced any bugs, haha.

only show/hide course search facet options when there are a lot of them

---

static/scss/search.scss

none
this just makes a small CSS tweak that @abdulkdawson requested. basically, we just want to apply the same style to our facet options on `:hover` that we currently applying when they're checked / selected.
If you go to the course search page and hover your cursor over an option it should turn blue, haha. that's it!

apply text style on hover to facet options

---

static/js/lib/search.js
static/js/lib/search_test.js

Closes #2293 
Modifies ES search query so that it returns no results if a text query like 'sdhfjsdhfksdjfhsk' has no matches.
Make sure search returns expected matches:
- "6.002x" returns "Circuits and Electronics" MITx course as 1st result
- "Aerospace Engineering" returns a course with that in the title as 1st result
- "Capozzola" returns a MITx course with Christopher Capozzola as instructor
- "sjdkfjslfkjsldfkjsdlfks" returns nothing
The text clauses had to be added to the ES query twice: in the original location (which adjusts the result scores based on closeness of match but doesn't exclude non-matching results), and in the "filter -> must" query (which excludes non-matching results but does not score the results returned).
Also boosted some additional fields (title, short …

Don't show any results if no text matches are found

---

static/js/components/Grid.js

none
this fixes a little issue with the `Cell` component - basically, it uses a `setState` call and a `resize` event listener to ensure that the component is responsive. the issue, though, is that currently on master this event listener is added, and the old one remove, on, uh, every single render :woman_facepalming: 
so basically I fixed it to set the event listener on mount and remove it on unmount. checkout the docs for the `useEffect` hook for details: https://reactjs.org/docs/hooks-reference.html#useeffect
basically, the hook looks like this:
```js
useEffect(() => {
someSideEffect()
}, [ props ])
```
where the second argument (the array) is an array of props which should re-trigger the effect when they change. so if you pass a `[]` as that argument that indicates the effect should …

fix a bug with the Cell component

---

static/js/components/SearchFacet.js
static/js/components/SearchFacet_test.js

closes #2298
closes #2318
this simply hides a search facet on the course search page if there aren't any options for that facet, so that the user isn't presented with an option they can't do anything with.
this also ensures that when a facet is collapsed we don't accidentally show the "View Less" / "View More" UI.
play around and make sure that the behavior described above works and there are no weird bug.

hide empty facets

---

static/js/Router.js
static/js/components/CourseToolbar.js
static/js/components/UserListCard.js
static/js/components/UserListCard_test.js
static/js/components/UserMenu.js
static/js/lib/queries/user_lists.js
static/js/lib/queries/user_lists_test.js
static/js/lib/redux-query.js
static/js/lib/redux_query.js
static/js/lib/test_utils.js
static/js/lib/url.js
static/js/pages/App.js
static/js/pages/CourseIndexPage_test.js
static/js/pages/UserListPage.js
static/js/pages/UserListPage_test.js
static/js/store/configureStore.js
static/js/util/integration_test_helper.js
static/scss/button.scss
static/scss/course.scss
static/scss/layout.scss
static/scss/user-list-card.scss

closes #2310
this adds a relatively basic page for showing the user lists (of all types) that a user currently has. it adds:
- a link from the search page
- the page itself
- a query for fetching it
- a UserListCard component for rendering basic info about the lists in a list format (a list of lists...)
go to `/courses/lists` and make sure there are no errors! if you don't have any user lists you'll have to make some in the admin or the console. then, they should show up here. in particular:
- you should see the basic information about them
- it should use the cover image for the first course on the list for the cover image for the list as a whole

add list view page

---

course_catalog/factories.py
search/api.py
search/api_test.py
search/constants.py
search/indexing_api.py
search/indexing_api_test.py
search/serializers.py
search/serializers_test.py
search/task_helpers.py
search/task_helpers_test.py
search/tasks.py
search/tasks_test.py
static/js/factories/learning_resources.js
static/js/factories/search.js
static/js/flow/discussionTypes.js
static/js/lib/constants.js
static/js/lib/search_test.js

Closes #2307 
- Adds `VideoResource` as an indexed object type
- Adds task helper methods for #2305 
- Refactored identical implementations of `index_profiles`, `index_bootcamps`, etc into a common `index_items`
Create one or more `VideoResource`s:
```python
from course_catalog.factories import VideoResourceFactory
from search.task_helpers import upsert_video
vr1 = VideoResourceFactory.create()
upsert_video(vr1)
vr2 = VideoResourceFactory.create()
```
Ensure the only first one shows up in the search page and facets work as expected.
Then you can reindex: `./manage.py recreate_index` and ensure both videos show up now.

Added VideoResource indexing

---

course_catalog/etl/pipelines.py
course_catalog/etl/pipelines_test.py
course_catalog/etl/youtube.py
course_catalog/etl/youtube_test.py

Closes https://github.com/mitodl/open-discussions/issues/2304
This pr creates a transform function for normalizing youtube video data and adds a youtube pipeline
```
from course_catalog.etl import youtube
from toolz import compose
pipeline = compose(youtube.transform, youtube.extract)
g = pipeline()
next(g)
```
should step through the videos in the channels in YOUTUBE_CONFIG_FILE_LOCATION displaying normalized data for one video at a time
```
from course_catalog.etl.pipelines import *
youtube_etl()
```
should pull all the videos in the channels in YOUTUBE_CONFIG_FILE_LOCATION and save them in the database
(Optional)
(Optional)
(Optional)
(Optional)

Video data transform

---

static/js/components/CourseSearchbox.js
static/js/components/CourseSearchbox_test.js
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/components/Grid.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/LearningResourceDrawer.js
static/js/components/LearningResourceDrawer_test.js
static/js/factories/learning_resources.js
static/js/hooks/util.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/pages/CourseIndexPage.js
static/scss/card.scss
static/scss/learning-resource-card.scss

part of #2294 
this does a series of tweaks to the course search page:
- remove extra dollar sign from course price (only on the card, not in the drawer)
- values in the card description for platform, topic, etc should be links to a search for that value (e.g. clicking the 'Math' subject on a course should take you to a search for the 'Math' subject')
- only the favorite button in the bottom row of the card should have a 'link' cursor
- cards all over the site should have a hover state, where a box-shadow shows up (see designs)
- course home page search 'magnifying glass' icon should redirect to search with the text the user has entered (currently this behavior happens when you hit the enter key but not when you click the little icon)
- change home page link text from "View All" to …

course search tweaks

---

static/js/components/CourseToolbar.js
static/js/components/CourseToolbar_test.js

none
we should be hiding the 'My Lists' button in the course navbar when the user is anonymous, so this does just that.
make sure that the button doesn't show up when you're anonymous, and that it doesn't show up when you aren't.

hide 'my lists' button in course navbar when the user is anonymous

---

course_catalog/permissions.py
course_catalog/permissions_test.py
course_catalog/views_test.py
static/js/components/LearningResourceCard.js
static/js/pages/CourseSearchPage.js

Fixes #2340 
- Tweaks permissions so you can favorite another person's public lists and learning paths
- Create a public learning path and public list as user A and reindex so they're included in search results.
- Log in as user B and try to favorite then unfavorite both.

Fix favoriting of lists and paths

---

static/js/components/UserListCard.js
static/js/components/UserListCard_test.js
static/js/lib/queries/user_lists.js
static/js/lib/queries/user_lists_test.js
static/scss/user-list-card.scss

closes #2353
this adds a dropdown menu to the UserListCard component. Currently in the dropdown there's only one option, 'Delete', which opens a confirm dialog to let you delete the list.
make sure that the above works as it should. you should be able to open and close the dialog, cancel, etc. when you actually confirm your list should be deleted, and it should disappear from the list of lists on the userlist index page.

add ability to delete UserLists

---

static/js/components/CourseCarousel.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/SearchResult.js
static/js/components/UserListCard.js
static/js/components/UserListCard_test.js
static/js/lib/url.js
static/js/pages/App.js
static/js/pages/CourseIndexPage.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js
static/js/pages/UserListDetailPage.js
static/js/pages/UserListDetailPage_test.js
static/js/pages/UserListsPage.js
static/js/pages/UserListsPage_test.js

closes #2364
this adds a user list detail page, a `/courses/lists/:id/`, which displays the learning resources in a list. here's what I implemented:
- add a link from the user list index to this detail page
- add a learning resource drawer to the detail page so you can inspect the items in your list
- add the user list membership dialog too, so you can edit the lists a learning resource is in from that page as well
- make the learningresourcecard self-contained as far as it's "open drawer" callback is concerned
that's about it.
make sure that the above works as advertised. you should also confirm that the learning resource drawer still opens normally from the search and from the homepage, as it did before.

add userlist detail page

---

static/js/components/UserListCard.js
static/js/components/UserListCard_test.js
static/js/components/UserListFormDialog.js
static/js/components/UserListFormDialog_test.js
static/js/flow/discussionTypes.js
static/js/pages/UserListsPage.js
static/js/pages/UserListsPage_test.js

closes #2370
adds the ability to edit the list metadata (title, description, etc).
go to the lists index page. if you click on the little 'three dots' menu you should see an "Edit" button. this should let you edit the list with no problems. List creation should be as normal.
different dialog title when creating:
versus when saving:
the menu option for opening the dialog:

add the ability to edit user lists

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views.py
course_catalog/views_test.py
search/task_helpers.py
search/task_helpers_test.py

Closes #2347 
- Updates the search index whenever user lists & learning paths are created, updated, or deleted.
Add, update, and delete both user lists and learning paths.  Verify that the changes are reflected in search.

Search index updates for user lists

---

static/js/components/UserListCard.js
static/js/components/UserListCard_test.js
static/js/lib/constants.js
static/js/lib/queries/learning_resources.js
static/js/pages/App.js
static/js/pages/CourseIndexPage.js
static/js/pages/FavoritesDetailPage.js
static/js/pages/FavoritesDetailPage_test.js
static/js/pages/UserListsPage.js
static/js/pages/UserListsPage_test.js
static/scss/user-list-page.scss

closes #2351
this adds two things:
- on the user lists page we now show the favorites as a userlist
- from there you can navigate to `/courses/lists/favorites`, which shows a list of your favorites
make sure that the above works. you should be able to also view, in the learning resource drawer, the items in the favorites list, and edit which lists they are members of, from `/courses/lists/favorites`.
(Optional)

add entry for the favorites as a userlist

---

open_discussions/views.py
open_discussions/views_test.py
static/js/components/AddToListDialog.js
static/js/components/AddToListDialog_test.js
static/js/factories/learning_resources.js
static/js/factories/livestream.js
static/js/factories/search.js
static/js/flow/declarations.js
static/js/flow/discussionTypes.js
static/js/global_init.js
static/js/lib/queries/user_lists.js
static/js/lib/queries/user_lists_test.js
static/js/pages/UserListsPage.js
static/js/pages/UserListsPage_test.js

Closes #2382 
Filters out any lists in `state.entities.userLists` that are not authored by the current user
- As user A, search for user lists or learning paths and favorite 1+ that are authored by user B
- Go to the "My Lists" page, the recently favorited lists by user B should not show up here
- Click the star on any resource card to open the 'Add to List' dialog, only your own lists should show up here as well.

Filter out unauthored lists on UserListsPage and AddToListDialog

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views.py
course_catalog/views_test.py

- Partially address #2378
- When requesting a list of UserLists, returns a simplified response via a UserListItem serializer that contains only the essential properties needed to maintain existing functionality (favoriting, adding/remove items to list, etc).
- The 'My Lists' page should still work as before but load faster
- You should still be able to add/remove items in a list, un/favorite items, create/delete lists, view list details

Simplified serializers for UserListView list response

---

static/js/pages/UserListDetailPage.js
static/js/pages/UserListDetailPage_test.js
static/scss/user-list-page.scss

none, just a quick thing that got left off
if the user has set a description on their userlist this adds a little display of that description on the detail page (`/courses/lists/${id}`).
create a userlist which does not have a description and confirm that the detail page doesn't render a `p.list-description`.
create one with a description (or edit the first one to have a description) and confirm you can see it on the detail page.

add a display of the userlist description to the userlist detail page

---

course_catalog/serializers.py
course_catalog/views_test.py
docs/learning_resources.md
static/js/components/AddToListDialog.js
static/js/components/AddToListDialog_test.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/factories/learning_resources.js
static/js/flow/discussionTypes.js
static/js/flow/searchTypes.js
static/js/lib/constants.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/lib/queries/user_lists.js
static/js/lib/queries/user_lists_test.js
static/js/pages/CourseSearchPage.js
test_requirements.txt

Closes #2358
- Fills in the 'favorited' star on a `LearningResourceCard` if the resource is in one of the user's lists. 
- Click the 'star' icon on a resource (both on the search results page and the learning home page).  Add it to a list but don't favorite it.  The star should get filled in.  Remove it from the list and the star should revert back.

Show a filled-in star when a resource is in a user's list

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views_test.py

Partially addresses #2395 
Supports changing the topics in a list on creation/update via API
- Go to `http://od.odl.local:8063/api/v0/lists`
- Enter the following data and post it to create a new list with topics:
```
{
"topics": [{"id": <valid_topic_id>}, {"id": <valid_topic_id>}],
"title": "A new list with topics",
"short_description": "short description",
"privacy_level": "private",
"list_type": "userlist"
}
```
- a new list should be created with the topics you selected
- Go to `http://od.odl.local:8063/api/v0/userlists/<new_userlist_id>/`
- Set the patch data to include a different topic or no topic at all, for example:
```
{"topics": [{"id": <different_topic_id>}]}
```
or
```
{"topics": []}
```
- The userlist's topics should be updated when the data is patched.
- If you don't …

Support topics CRUD in UserList API

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py

Fixes #2403 
Fixes a `KeyError` caused by `load_video_channel` `pop`ing values off the dict

Fixed KeyError in etl loaders

---

static/js/components/AddToListDialog.js
static/js/components/AddToListDialog_test.js
static/js/components/Dialog.js
static/js/components/Dialog_test.js
static/js/components/ProfileImage_test.js
static/scss/dialog.scss
static/scss/layout.scss
static/scss/user-listitem-dialog.scss

closes #2357
this adds a button in the "add to list" dialog which lets you create a new list.
basically, it just opens the existing form we have for creating userlists.
Try it out and make sure there are no weird edges. you should be able to:
- add and remove a list from an existing list (i.e. no regression)
- clicking the 'Create New List' button should open the dialog
- canceling that dialog should just show you the 'add to list' dialog again
- you should be able to successfully create a new list
- that list should show up in the 'add to list' dialog immediately
I think that's about it. Just make sure it all makes sense and works properly.

add option to create new list from "add to list" dialog

---

course_catalog/serializers.py
scripts/repl.js
static/js/components/CourseCarousel.js
static/js/components/CourseCarousel_test.js
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/LearningResourceDrawer.js
static/js/components/LearningResourceDrawer_test.js
static/js/components/SearchResult.js
static/js/components/SearchResult_test.js
static/js/components/UserListCard.js
static/js/factories/learning_resources.js
static/js/flow/discussionTypes.js
static/js/lib/learning_resources.js
static/js/pages/FavoritesDetailPage.js
static/js/pages/FavoritesDetailPage_test.js
static/js/pages/UserListDetailPage.js
static/js/pages/UserListDetailPage_test.js
static/scss/course.scss

closes #2266
this makes the learning resource drawer (which we use on the course search) able to display information about user lists and learning paths.
Go to the search page and click on a learning path or user list. The drawer should open with details about that user list.

display user list in LR drawer

---

search/connection.py
search/indexing_api.py
search/indexing_api_test.py

N/A
Improves efficiency of indexing by reusing verified connections. Prior to this, the connections were validated but immediately invalidated by a call to `get_active_aliases` which was in turn calling `get_conn` in a manner that it cleared the verified state. This code modifies `get_active_aliases` to instead accept a connection as an argument rather than getting its own. This way whether the connection is verified or not depends on the calling code.
- Run `./manage.py recreate_index`
- Create a post and a comment, ensure they show up in search
- Modify the post and comment and ensure their modified values are searchable

Update get_active_aliases to reuse connection so verification doesn't thrash

---

static/js/components/AddToListDialog.js
static/js/components/AddToListDialog_test.js

Fixes #2414
Prevents users from adding lists to each other (List 1 in List 2 and List 2 in List 1)
- Create List 1
- Create List 2
- Click the List 2 'favorite' star and add it to List 1
- Click the List 1 star, List 2 should be excluded from the checkbox list

Prevent users from adding lists to each other

---

static/js/components/CropperWrapper.js
static/js/components/ImageUploaderForm.js
static/scss/profile-image.scss

closes #2328
this just fixes the width of the image upload dialogs on the channel appearance settings page. there are two dialogs, one for setting the channel avatar and another for setting the channel banner.
go to a channel settings page and make sure the dialogs for uploading those two images are the right width and so on.

fix channel image upload dialog widths

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views.py
course_catalog/views_test.py
static/js/components/AddToListDialog.js

Fixes #2410 
Fixes #2421 
Also should improve performance
- Restricts usage of the SimpleUserListSerializer and SimpleUserListItemSerializers to the `content_data` field of UserListItemSerializer items.  This should fix the above issue while still streamlining the size of the api lists response (though not quite as much as before).
- Create 'simple' serializers for courses, bootcamps, and programs too that exclude runs, to be used for item.content_data
- Reduces n+1 queries
- Go directly to a URL for a specific list that contains 1+ lists.  Reload the page a few times. It should load every time.  On master branch it will occasionally fail to load, if the `api/v0/userlists` response comes after the `api/v0/userlists/<id>` response.
- "My Lists" should still display your lists
- Creating …

Adjust resource item serializers

---

search/serializers.py
static/js/lib/search.js
static/js/lib/search_test.js

Fixes #2420 
- Adds `transcript` to the elasticsearch serializer
- Adds `transcript` to the fields the frontend queries the text search on
Update a video's transcript with some unqiue value:
```python
v = Video.objects.first()
v.transcript = "uniqueword"
v.save()
```
- `./manage.py recreate_index`
- Go to the search page and search for your unique transcript value, you should see that as the only result

Added transcripts to searchable fields

---

package.json
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/SortableList.js
static/js/components/widgets/WidgetList_test.js
static/js/lib/queries/user_lists.js
static/js/pages/UserListDetailPage.js
static/js/pages/UserListDetailPage_test.js
static/js/util/integration_test_helper.js
static/scss/learning-resource-card.scss
static/scss/user-list-page.scss
yarn.lock

path of #2311
this adds an option to the user list detail page to both edit the list details (like the title and so on) and also to reorder the items in the list.
try out the functionality added and see if it breaks, haha. make sure the UX makes sense and is relatively clear to the user.

add sorting of items in a userlist / learning path

---

app.json
open_discussions/settings.py
open_discussions/settings_test.py

- Fixes #2453 
Sets `DISABLE_SERVER_SIDE_CURSORS=True` by default unless overridden in .env
Nothing should break locally or on CI/RC, especially queries using `.iterator()`
```
from django.db import connections
connections["default"].settings_dict.get('DISABLE_SERVER_SIDE_CURSORS')
```
should return True by default, or False if `OPEN_DISCUSSIONS_DB_DISABLE_SS_CURSORS=False` in your .env file
https://code.djangoproject.com/ticket/28062

Set DISABLE_SERVER_SIDE_CURSORS=True by default

---

course_catalog/serializers.py

- Partially addresses #2459 
Gets rid of n+1 queries on 'UserListItem.content_type` when retrieving userlist API results
Make sure you have some userlists with items.
Try both:
http://od.odl.local:8063/api/v0/userlists
http://od.odl.local:8063/api/v0/userlists/<list_id>
and check the console, you should not see any warnings about n+1 queries

Get rid of n+1 query on content_type.name

---

static/scss/course.scss

closes #2438 
adds a visual separator between items in the userlist when we display them in the drawer.
look at a userlist from the search page and make sure it looks alright

add visual separation to items shown in the userlist drawer

---

flow-typed/npm/react-router-dom_v5.x.x.js
open_discussions/urls.py
static/js/components/UserMenu.js
static/js/lib/url.js
static/js/lib/url_test.js
static/js/pages/App.js
static/js/pages/App_test.js
static/js/pages/CourseIndexPage.js
static/js/pages/CourseIndexPage_test.js
static/js/pages/CourseSearchPage.js
static/js/pages/FavoritesDetailPage.js
static/js/pages/LearnRouter.js
static/js/pages/UserListDetailPage.js
static/js/pages/UserListDetailPage_test.js

closes #2360 
this changes all the `/courses` URLs to be `/learn`, so from `/courses/search` to `/learn/search`, `/learn/lists`, etc.
I also pulled all the relevant routes into a separate new component call the `LearnRouter`. this means we can also mount components for all those subpages, so we can render like our dialogs and stuff at that one place instead of all over the place.
This will hopefully in the future, after refactoring the search state, let us pull the learn banner out to one place as well.
Extensively test all the course search sub-site and any places that links to it. I am pretty sure I got all of the links, but I could have missed something when grepping. so just click around and try to find any broken / weird links. To clarify, though, I also added a redirect from …

change "/courses" urls to "/learn"

---

static/js/pages/LearnRouter.js

N/A
Fixes a routing condition where the url `/learn/lists/favorites` also matches on `/learn/lists/:id`, the latter of which fails because "favorites" is an invalid list id
Go to `/learn/lists/favorites` on master, confirm the page fail to load. Do this on this branch, the page should load

Fixed routing for /learn/lists/favorites

---

static/js/actions/ui.js
static/js/components/CourseCarousel_test.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/LearningResourceDrawer.js
static/js/components/LearningResourceDrawer_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/course.scss

closes #2440
This refactors how we control what is shown in the `LearningResourceDrawer`. Previously we basically set an object ID and object type, and then we'd use those to fetch the right object, and then we'd show it. This worked for opening and looking at one object, but it broke down a little when it came to navigating to a new object from the initial one. The specific problem is that if you click in you can't get back to the object you we're looking at before without closing the whole drawer and opening and navigating again.
We need to support this use-case well because the user can do this from a userlist or a learning path.
Anyhow, to fix this I changed it so it works on the basis of a history object, which we store in the `ui` reducer. It's just an array, and this is how it …

add history navigation to drawer

---

static/js/components/CompactPostDisplay_test.js
static/js/components/LearningResourceDrawer_test.js
static/js/components/TruncatedText.js
static/js/components/TruncatedText_test.js
static/js/lib/test_utils.js

one part of #2466 
Currently when the `TruncatedText` component is used with the `showExpansionControls` prop we always show the 'read more' / 'read less' controls, regardless of whether any content has been hidden by the `Dotdotdot` component. This changes things so that we only show the expansion controls in the case where they can, you know, do something ^_^
In order to do this I had to figure out how to tell when the text was being truncated. Basically, this is being done with a div with `overflow: hidden` on it, and the `Dotdotdot` component doesn't have a way to pass in a callback or something to get out whether or not it's done the truncated.
So what I had to do was get a ref to the div used by `Dotdotdot` and then look at some of it's properties. Basically if the `scrollHeight`, …

fix display of read more / read less on TruncatedText component

---

static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

Fixes #2487 
Returns null instead of the search result as the overrideObject in the CourseSearchPage's 'getFavoriteOrListedObject' function if the object can't be found in react state.
Run some course searches when logged out and logged in, the subjects should display on the result cards, and when logged in any of your favorite/listed items should still be starred.

Fix search result subject display

---

static/js/lib/queries/learning_resources.js
static/js/lib/queries/learning_resources_test.js

none
fixes a small bug with one of our selectors. basically, we sometimes return a getter wrapped with `_.memoize` to be able to access things in the store based on prop values. the problem with `learningResourceSelector` is that we return a memoized function of two arguments, `objectId` and `objectType`. But `_.memoize` only uses, by default, the first argument as the cache key for memoization, so if we did this:
```js
const getter = useSelector(learningResourceSelector)
const obj1 = getter(1, LR_TYPE_VIDEO)
const obj2 = getter(1, LR_TYPE_COURSE)
```
we'd be in a bad situation because `obj1` and `obj2` would be the same object :scream: 
this is because when we called `getter` the second time it would only look at the first argument to figure out whether to return a cached value or not, …

fix a small bug with learningResourceSelector

---

static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/scss/learning-resource-card.scss

part of #2434
this just implements the visual parts of #2434, basically hiding more of the information in the learning resource cards when we're doing the reorder.
go and reorder your lists, make sure the UI looks like what's shown in the design.

restyle reordering UI for learning paths

---

course_catalog/etl/youtube.py

We recently had the video import task fail silently on RC because YOUTUBE_DEVELOPER_KEY was missing. This pr adds an error log  
Remove YOUTUBE_DEVELOPER_KEY in your env file
run
```
get_youtube_data()
```
There should be en log message letting you know that YOUTUBE_DEVELOPER_KEY is not set

Log an error for YOUTUBE_DEVELOPER_KEY

---

course_catalog/etl/youtube.py
course_catalog/etl/youtube_test.py
test_json/youtube/channels.list.0.json
test_json/youtube/playlistItems.list.2.json
test_json/youtube/playlistItems.list.3.json
test_json/youtube/playlists.list.2.json
test_json/youtube/playlists.list.3.json
test_json/youtube/videos.list.3.json
test_json/youtube/videos.list.4.json

https://github.com/mitodl/open-discussions/issues/2472
We will add a` id: wildcard option` to playlists to make it possible to download and make user lists for all playlists in a channel without listing each playlist in the config report individually. We will also add a ignore flag to ignore a playlist
For example:
```
channel_id: some_channel
playlists:
- id: playlist1
create_user_list: false
- id: playlist2
ignore: true
-id: wildcard
create_user_list: true
```
Will add all videos in the playlists in the channel except playlist2 to search and create user lists for every playlist except playlist1 and playlist2
Set
```
OPEN_VIDEO_DATA_BRANCH=format-change-2472
```
in your .env file.
Run 
```
from course_catalog.etl import pipelines …
```

Add all other playlists option to config

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/LearningResourceCard.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js

https://github.com/mitodl/open-discussions/issues/2500
This pr updates the ui to display all the offered by values if there are multiple
Find or create a learning resource with multiple offered by values. Verify that all the offered by values are displayed in the UI
(Optional)
(Optional)
(Optional)
(Optional)

display all learning reasourse offered bys

---

static/js/global_init.js

none
fixes an issue with mocking out the HTMLElement `scrollHeight` and `offsetHeight` attributes. Basically, these attributes are checked by the `TruncatedText` component to see whether there's overflow and therefore determine when it makes sense to show a `show more / show less` button. Issue is that these values weren't being mocked globally, but instead piecemeal in certain test files. Other files actually required the values to be mocked, and were indirectly getting the mock because of execution order of the tests but, if those files were run separately, the mock wouldn't be there and it would cause an `InvarientViolation`.
One such file is `static/js/components/ExpandedLearningResourceDisplay_test.js`
to fix I just added a call to the mock function to our `global_init.js` file, …

mock out HTML height attrs globally

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/youtube.py
course_catalog/etl/youtube_test.py

https://github.com/mitodl/open-discussions/issues/2523
This PR allows us to set a custom title for the user list created for a youtube playlist in open-video-data 
Set
```
OPEN_VIDEO_DATA_BRANCH=format-change-custom-list-name
in your .env file.
```
Run
```
from course_catalog.etl import pipelines
pipelines.youtube_etl(channel_ids="UCPonD0FH2WNnEXyTsYiLWMw")
```
from the shell.  This should create three user lists. Two with the youtube list name, "Entrepreneurship 101: Who is Your Customer? - All Videos from Our MIT Online Course" and  "Entrepreneurship 102: What Can You Do for Your Customer? - All Videos from Our MIT Online Course", and one with a custom name "Custom List Name Bootcamps"
(Optional)
(Optional)
(Optional)
(Optional)

allow specifying list name in config file

---

channels/api.py
channels/api_test.py
course_catalog/api.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/youtube.py
course_catalog/etl/youtube_test.py
course_catalog/serializers.py
course_catalog/views.py
course_catalog/views_test.py
profiles/models.py
profiles/serializers_test.py
search/task_helpers.py
search/task_helpers_test.py
search/tasks.py
search/tasks_test.py

Fixes #2518 
Converts create and update indexing methods to take a primary key value and pass it to the task to index, instead of serializing the data then sending it to the task. This should cut down on the amount of data in each task redis is keeping track of. 
- For videos, run youtube ETL task (backpopulate youtube data)
- User list: create a user list and verify that 
- Courses/programs: xpro integration (backpopulate xpro data)

Update indexing methods to reduce data sent to and from redis via celery 

---

search/api.py
static/js/lib/search.js
static/js/lib/search_test.js
static/js/lib/util.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

Based on #2510, that one should be reviewed/merged first.
Fixes #2499
Supports quoted search terms
- Search for `mechanical engineer` without double quotes.  You should get X results back that match either` mechanical` or `engineer` or both
- Search for `"mechanical engineer"` with the double quotes.  You should get less than X results back that match `mechanical engineer`
- Search for `mechanical enginr` without quotes.  You should get Y results back that match `mechanical`
- Search for `"mechanical enginr"` with the double quotes.  You should get 0 results back and a suggestion `Did you mean "mechanical engineer"`

Supported double-quoted search terms

---

app.json
course_catalog/api.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/tasks_test.py
course_catalog/utils.py
course_catalog/utils_test.py
open_discussions/settings.py
search/tasks.py
search/tasks_test.py

Fixes #2492 
- Retrieves a list of blacklisted ids from a URL and sets those courses as `published=False` during import, skips them during a full recreate_index.
- Make a gist with a text file containing a list of some edx course id's you've already imported, one per line.
- Set `BLACKLISTED_COURSES_URL` to the raw URL for that file in your .env file
- Run `recreate_index`.  Those courses should be removed from the index.
- Delete those course and import them again (`backpopulate_edx_data`).  They should be assigned `published=False`

Dont publish/index blacklisted courses

---

static/js/components/CourseSearchbox.js
static/scss/course-searchbox.scss

https://github.com/mitodl/open-discussions/issues/2498
This PR adds an icon to dismiss search text from the search box on the learning resource search page when the search box is not empty. This clears the search results
Go to the learning resource search page. Verify that an X icon appears when there is text in the search box and clicking the icon clears both the search text and the search filter

allow user to dismiss search text

---

static/js/components/LearningResourceCard.js
static/scss/learning-resource-card.scss

https://github.com/mitodl/open-discussions/issues/2496
Currently, when there is no course topic for a learning resource the course card is shorter in the grid view. This pr fixes that issue
Verify that the search page looks good in both grid view and list view. Verify that when the offered by and/or subject is missing for a learning resource, the course card is the same height as other course cards.
(Optional)
(Optional)
(Optional)
(Optional)

ensure course cards have the same height

---

channels/views/posts_test.py

None
Fixes some incorrectly used assert calls. Due to the mock, something like `assert mock.called_once()` will always return true, since `called_once` is assumed to be a mock function too.

Fix a few typos in tests

---

static/js/components/CommentTree.js
static/js/components/CommentTree_test.js
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/components/ShareTooltip.js
static/js/components/ShareTooltip_test.js
static/js/hooks/learning_resources.js
static/js/lib/url.js
static/js/lib/url_test.js
static/js/pages/CourseIndexPage.js
static/js/pages/CourseIndexPage_test.js
static/scss/learning-resource-drawer.scss

closes #2435
this PR sets us up for allowing the user to share learning resources via a link. There are two components:
- on the learning home page we now look for URL params on startup which, if present, are used to open the learning resource drawer
- in the learning resource drawer there is now a "share" button, which opens a little popup (the same one we use for posts and comments) which has the URL for the course home page with the right URL parameters in it.
make sure that different learning resources work right! all learning resources should be supported.

share learning resources

---

app.json
conftest.py
fixtures/elasticsearch.py
open_discussions/settings.py
open_discussions/settings_test.py
search/__init__.py
search/api.py
search/api_test.py
search/apps.py
search/connection.py
search/indexing_api.py
search/indexing_api_test.py
tox.ini

Fixes #2534 
This improves performance by removing extraneous requests to validate a connection. We end up making requests to validate that all of the indexes exist, but actually only assert that at least one exists, which isn't a particularly useful property because it doesn't really guarantee us anything.
I also noticed that `elasticsearch_dsl.connections` internally caches the connections which is the exact same thing `get_conn` is doing. So I moved configuration code into a `configure_connections` which is now called from the `ready()` function of the app. I modified `get_conn` to return the default connection and removed `get_conn` calls where the default behavior would've been to use the default connection anyway. That means only code dealing with the indicies APIs uses `get_conn` …

Improve ES performance by not validating connection for read operations

---

static/scss/picker.scss

closes #2450
this just fixes an issue where on the post sort picker a scrollbar was showing up unnecessarily.
check out master, go to a channel page, see the scrollbar. then check out this branch and see it disappear! amazing!
(Optional)
(Optional)
before:
after:

fix scrollbar on post sort picker

---

static/scss/learning-resource-card.scss

closes #2543
this fixes the height for the "list view" learning resource cards when reordering. I think this was an unintentional effect of https://github.com/mitodl/open-discussions/pull/2532
go to the edit page for a learning path. reorder it, and confirm that the cards get shorter when you're in the reordering mode.
before:
after:

fix card height for the learning path reorder UI

---

search/serializers.py
search/serializers_test.py

This adds created_on to the elasticsearch index so that there is no downtime when
https://github.com/mitodl/open-discussions/pull/2541
is merged.
Recreate your elasticsearch index. Make sure it does not break

add created_on to elasticsearch

---

static/js/components/LearningResourceCard.js
static/scss/course-carousel.scss
static/scss/learning-resource-card.scss

**List View**
**Grid View:**
**List View**
**Grid View**
https://github.com/mitodl/open-discussions/issues/2539
For the list view:
The course card should expand so that the course title can take up as many lines as needed
For the grid view:
The course card should have space for three lines for the title (instead of two as was the case previously). This accommodates almost all the titles with a full page window. After three lines the course title is cut off.
Go to the list and grid views for search results and make sure that the course title looks good

prevent course title from being cut off

---

static/js/components/UserListFormDialog.js
static/js/lib/constants.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js

closes #2546
changes the copy from 'User List' to 'Learning List'
make sure that the artist formerly known as 'user list' is no longer known as 'user list'
I think I got every occurence but I could have missed one.

user list -> learning list

---

static/js/lib/search.js
static/js/lib/search_test.js

https://github.com/mitodl/open-discussions/issues/2494
Sorts results in the search page by price and date added when there is not text search set.
Recreate your elasticsearch index, since created_on data is added for learning resources in this PR
Verify that search results with no text are sorted by price then created on
Verify that search results with text filters are not changed

sort default results in search page

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js

https://trello.com/c/3pwqV3ev/38-open-similar-learning-resources-by-default-for-videos-courses-in-drawer
this PR basically makes it so that the "Similar Learning Resources" panel is always open for all learning resources except for lists and programs. We want to leave those two out because they have the course list, so it's gets a little crowded for them.
Confirm that for user lists, learning paths, and programs the "Similar..." panel is not open by default. Then confirm that it is for everything else.

auto open the "Similar..." panel for some learning resources

---

static/js/hooks/learning_resources.js
static/js/lib/url.js
static/js/lib/url_test.js

https://trello.com/c/tnkosY3B/36-user-friendly-sharing-urls
just changes the name of some URL params.
test out the sharing feature and make sure it works as before. The params should now be `lr_id` and `type` instead of `drawerObjectID` and `drawerObjectType`

change URL params for LR sharing to be more readable

---

course_catalog/api.py
course_catalog/etl/ocw.py
course_catalog/tasks.py
course_catalog/tasks_test.py
requirements.in
requirements.txt

Closes #2568
- Uses rapidjson to read/write JSON
- Checks if the course needs updating before parsing all the course JSON files.
- Chunks up the import task into multiple parallel celery tasks
- Sets course published status based on whatever runs currently exist.
If you haven't already imported all the OCW data and want to get this over with without waiting for 90K files to upload to S3 (this still takes a long time), run this:
- `manage.py backpopulate_ocw_data --skip-s3`
If you already have most/all of the OCW data, you can just run:
- `manage.py backpopulate_ocw_data`
Running the import from scratch (no OCW courses present) is still going to take many hours to process all courses and upload their files.
If all courses are already imported, running time to check for changes is:
This …

Chunk up OCW import task and use rapidjson to speed up processing

---

search/indexing_api.py
search/indexing_api_test.py

None
Refactors indexing code to allow calling code to construct the iterable of documents instead of passing in a serializer function
Run recreate_index and verify that no errors happened and the results look fine

Refactor index_items

---

search/indexing_api.py
search/serializers.py
search/serializers_test.py

Fixes https://github.com/mitodl/open-discussions/issues/2494
I am breaking up the PR for the sorting order in the default search page into two PRs so there is no downtime when it is released. This PR adds `minimum_price` and `default_search_priority` to the elasticsearch index. https://github.com/mitodl/open-discussions/pull/2571
updates the search query.
Recreate your elasticsearch index. The script should not break and the course search UI should still look and work the same as before after it runs

Additional index updates for default search

---

static/js/lib/search.js
static/js/lib/search_test.js

Fixes https://github.com/mitodl/open-discussions/issues/2494
Sorts results in the search page by price, then resource type, then date added when there is not text search set. 
Courses and programs should come before videos and user lists in the search when they have the same cost
Recreate your elasticsearch index
Verify that search results with no text are sorted by price, then resource type , then created on
Verify that search results with text filters are not changed

Sort default search results

---

Dockerfile
authentication/serializers.py
requirements.in
requirements.txt
runtime.txt
tox.ini

None
Changes the python version used in the docker container and runtime.txt to 3.7. Other package upgrades were made to fix deprecation warnings. Since we are using Django 2.x I think `user.is_authenticated` and `user.is_staff` should always be properties so we don't need to use the helper method from python-social-auth, which was causing deprecation warnings.
Go to Travis and verify that the output shows that Python tests are running, and that they are passing.
We should remove tox and use pytest directly, similar to how we have it set up on mitxpro. See this PR: https://github.com/mitodl/mitxpro/pull/44

Upgrade to Python 3.7

---

course_catalog/api.py
course_catalog/tasks_test.py

N/A?
Runs `OCWParser.upload_all_media_to_s3` before `digest_ocw_course`, because the parser updates the course JSON while doing so (including thumbnail URL).
Run `manage.py backpopulate_ocw_data --overwrite` and let it run for a little bit until at least some OCW courses are (re-)imported.  Check that the imported courses have a non-blank thumbnail.

Fix blank thumbnails for OCW courses

---

app.json
course_catalog/etl/deduplication.py
course_catalog/etl/deduplication_test.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/pipelines.py
course_catalog/etl/pipelines_test.py
course_catalog/tasks_test.py
course_catalog/utils.py
course_catalog/utils_test.py
open_discussions/settings.py

https://github.com/mitodl/open-discussions/issues/2219
This pr merges course runs from duplicate courses. The course with the most relevant run is displayed. The most relevant run is
1) A current run, if available
2) If there is no current run, the upcoming run that starts the soonest
3) If there is no current or upcoming  run, the archived run that started the most recently
Set 
DUPLICATE_COURSES_URL=https://gist.githubusercontent.com/abeglova/5dfb0717c6c54edc6e0f5e0d5287e620/raw/bc77456780bd66ee98bcf4fa1653e6ef03bcdccc/gistfile1.yml
in your .env file
run 
```
get_mitx_data()
```
There should be only one MITx course with the following title and the search page should link to a run with the following start date:
"Discrete-Time Signal Processing" - Aug …

dedupe mitx courses

---

interactions/serializers.py
interactions/serializers_test.py

Fixes #2606 
This changes the popular content serializer to filter out items that no longer exist. This can happen when the resource gets deleted, but the interaction data doesn't get deleted before that table has a `GenericForeignKey` relation which does not support cascaded deletes from the referenced record.
- In `master`, ensure you have some popular items showing up in `/learn` or that you're seeing the 500 error from that response.
- If you're not seeing that error, delete a resource that shows up in that list so that you do
- Checkout this branch and verify the error is fixed

Fixed bug with missing popular resources

---

static/js/lib/search.js
static/js/lib/search_test.js

Closes #2605 
Adds `{"score_mode": "avg"}` to the child document subquery of ES course searches.
Assuming you already have imported some OCW courses and content files:
- search for `point of intersection` or some other phrase found in course pdf's or html pages.
- check the `_score` values for the search results, they should not all equal `1` and they should always be returned in the same order.
- as you scroll through the results you shouldn't see any dupes.

Assign a score to child document results

---

config/nginx.conf.erb

https://trello.com/c/PrRZFPAx/60-redirect-discussionsodlmitedu-to-openmitedu
It will redirect requests on the old discussions.odl.mit.edu domain to their corresponding paths on open.mit.edu.
Users may encounter old discussions.odl.mit.edu links to private channels. When they try to access them, the "next" login flow fails and, even though they can log in with micromasters, they don't end up on the correct page (whether a post or channel).
I think we can probably test it in CI or staging by using `curl` and setting the `Host` HTTP header to `discussions.odl.mit.edu`. Another way would be to add an entry in one's `hosts` file to fake `discussions.odl.mitl.edu`. In either case, we'd be looking for redirect response.

Redirect discussions.odl.mit.edu to open.mit.edu

---

profiles/views.py
profiles/views_test.py

https://trello.com/c/1KnhFWrP/64-anonymous-access-to-user-profiles
Allows anonymous access to the profile API and the related posts and comments API for profiles
As a logged out user view a profile page. You should not be redirected to a login page.

Allow anonymous users to view the profile page and related posts and comments

---

course_catalog/etl/deduplication.py
course_catalog/etl/deduplication_test.py
course_catalog/management/commands/print_course_duplicates_yaml.py

https://github.com/mitodl/open-discussions/issues/2611
This pr creates a script to generate and print updated duplicate course yaml
Set DUPLICATE_COURSES_URL=https://gist.githubusercontent.com/abeglova/5dfb0717c6c54edc6e0f5e0d5287e620/raw in your .env file
Run
```
docker-compose run web ./manage.py print_course_duplicates_yaml
```
Verify that duplicate courses yaml is generated and printed in the terminal and that the `course_id` values from the DUPLICATE_COURSES_URL are preserved in the new yaml file

script to generate duplicate courses yaml

---

course_catalog/api.py
course_catalog/api_test.py

Fixes #2617 
Inserts the correct attribute value in the error message, and adds a test for that message.
N/A

Fix error reporting when OCWSerializer is invalid

---

course_catalog/serializers.py
course_catalog/serializers_test.py

N/A
Makes `raw_json` write-only in `LearningResourceRunSerializer`
Go to `http://od.odl.local:8063/api/v0/popular-content/` - the JSON should not include `raw_json` in the runs.

raw_json should be write-only on LearningResourceRunSerializer

---

static/js/pages/CourseIndexPage.js
static/js/pages/CourseIndexPage_test.js

Fixes #2690 
This switches the loading ui from a single set of loaders to a per-carousel loader layout.
Go to /learn, each loader should complete independently of each other rather than waiting for all requests to complete.

Updated /learn to have per-carousel loaders

---

channels/membership_api.py
channels/membership_api_test.py

Fixes #2694
Catches and logs a `ProfileDoeNotExist` exception for a channel when running `update_memberships_for_managed_channels` 
- Create a user without a profile or delete a user's existing profile
- Create a new `ChannelMembershipConfig` in django admin; add a moira list that includes the user, and select several managed channels to associate it with.
- Look for error messages about a missing profile for each selected channel in the console.

Log ProfileDoesNotExist exceptions when updating channel memberships

---

.eslintrc
static/js/components/CourseFilterDrawer.js
static/js/components/CourseFilterDrawer_test.js
static/js/components/CourseSearchbox.js
static/js/flow/searchTypes.js
static/js/lib/course_search.js
static/js/lib/course_search_test.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js
static/js/pages/admin/EditChannelAppearancePage_test.js

closes #2333
this PR basically refactors how we store the search state for the course search page so that the params in the URL are the sole source of truth for the filters and so on.
right now in master these things are sort of stored in two places - in the URL bar and in the component state for the `CourseSearchPage` component. We have some sort of weird logic for syncing them, and for getting param values from the url bar on startup.
This makes it so that a few things (like incremental vs full-refresh searching) are driven off of values kept in component state while filters and all that stuff are driven purely off of the URL bar. I think this makes it simpler - hopefully you agree!
There should be no regressions in user experience or behavior on the course search page. things should …

refactor course search state to be driven off of URL

---

course_catalog/etl/ocw.py
course_catalog/etl/ocw_test.py

Fixes #2682 
Uses the file extension of the URL to detemine file type, and passes that info to tika
TBD

Use file extension to inform tika about file type for OCW ingestion

---

static/js/lib/search.js
static/js/lib/search_test.js

https://github.com/mitodl/open-discussions/issues/2714
This PR removes the fuzzy search parameter from channel search queries. Fuzzy search produces results that are too broad. For example profiles matching "Curt" and "Murat" were returned in a search for "curated", which was de-stemmed to "curat" by elasticsearch
Create a new post titled "Outside the box"
Create a new post titled "I like foxes" 
Searching for "Fox" in http://localhost:8063/search/ should not return the second post but not the first.

remove fuzzy search

---

moira_lists/moira_api.py
moira_lists/moira_api_test.py

Fixes #2730 
Filters out blank/null moira lists names in `moira_api.query_moira_lists()`
Sign up or log in as a user who is not on any moira lists.  If on master, there will be an exception in the celery logs and a moira list with a blank name will be created (delete it from the shell).  On this branch, there shouldn't be an exception and a blank moira list should not be created.

Filter out blank/null moira list names

---

static/js/lib/url.js
static/js/lib/url_test.js

Fixes #2727
Changes URL hostname function to tolerate URLs which don't start with a https
Find a post. In the database change `post.url` to remove the `http` part at the beginning, leaving only `www.mit.edu` for example. Run `search.indexing_api.index_posts([post.id])`. Find a search phrase for the post. On master you should see the screen become blank with a console error when searching for that phrase, but on this PR it  should work fine.

Make frontend URL parsing more resilient

---

search/api.py
search/api_test.py
search/indexing_api.py
static/js/lib/search.js
static/js/lib/search_test.js
static/js/pages/SearchPage.js
static/js/pages/SearchPage_test.js

https://github.com/mitodl/open-discussions/issues/2721
This PR updates the code to display suggestions in the channel search when there are no hits for a search term, similar to the ones in the learning resource search
Create 5-6 comments and posts with the word "robot" 
Go to http://localhost:8063/search/ and search for "robo". Verify that "robot"  is returned as a suggestion and clicking the link searches for "robot" .
Also verify that the channel search still works for terms for which there are hits and that the learning resource search still works as expected as well

Suggested Terms in Channel Search

---

search/api.py
search/api_test.py
search/indexing_api.py

https://github.com/mitodl/open-discussions/issues/2721
This PR makes the index changes necessary for adding suggestions to the channel search. It contains the back end changes from 
https://github.com/mitodl/open-discussions/pull/2740, which was reverted to avoid downtime durning the release.
Run run the elastic-search reindex script
Verify that both the channel search and and the learning resource search still work as expected

index changes to support suggestions in channel search

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/factories.py

https://github.com/mitodl/open-discussions/issues/2725
This playlist deletes the userlist associated with the playlist when a playlist is removed from open-video-data
Set `OPEN_VIDEO_DATA_BRANCH=ab/test-playlist-delete`
Run `docker-compose  run web python manage.py backpopulate_youtube_data fetch --channel-id UCPonD0FH2WNnEXyTsYiLWMw` 
There should be a new user list called "Final Pitches" that is created
Set `OPEN_VIDEO_DATA_BRANCH=master`
Run `docker-compose  run web python manage.py backpopulate_youtube_data fetch --channel-id UCPonD0FH2WNnEXyTsYiLWMw` again
The user list named "Final Pitches" should be deleted

unpublish userlists for removed playlists

---

static/js/components/ContentToolbar.js
static/js/components/ContentToolbar_test.js
static/js/lib/url.js
static/js/pages/App.js
static/js/pages/App_test.js
static/scss/course.scss

part of #2722
this gets the navbar set up for `/podcasts`. basically I:
- renamed the current `CourseToolbar` to `ContentToolbar`, reflecting the fact that we want to use the same styling on `/learn` and `/podcasts`
- changed the routing in `<App.js>` so that we render the `ContentToolbar` on `/learn` and `/podcasts` and the normal navbar elsewhere
- adding some `<Route>`-based logic in the navbar component (`<ContentToolbar>`) to change the branding text based on which part of the site you're in ('LEARN' vs 'PODCASTS')
the normal navbar should show up everywhere on the discussions side.
On `/learn` and its sub-routes you should see the same behavior as master.
If you visit `/podcasts` you should see the same navbar as on `/learn` but with the prominent branding text and link changed.

Podcasts: set up navbar for /podcasts

---

course_catalog/factories.py
course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

Fixes #2763 
Adds `/api/v0/podcasts/recent/` to list recent podcast episodes
Populate some podcast episodes then go to `/api/v0/podcasts/recent/` and verify that it looks right. The `last_modified` value should start with the most recent and go backward in time.

Add recent podcasts API

---

static/js/lib/search.js
static/js/lib/search_test.js
static/js/pages/SearchPage.js
static/js/pages/SearchPage_test.js

https://github.com/mitodl/open-discussions/issues/2721
This pr contains the front end changes from https://github.com/mitodl/open-discussions/pull/2740, which was reverted to avoid downtime after the deploy.
It should not be merged until https://github.com/mitodl/open-discussions/pull/2751 is deployed and the index is updated
This PR updates the code to display suggestions in the channel search when there are no hits for a search term, similar to the ones in the learning resource search
Create 5-6 comments and posts with the word "robot" 
Go to http://localhost:8063/search/ and search for "robo". Verify that "robot"  is returned as a suggestion and clicking the link searches for "robot" .
Also verify that the channel search still works for terms for which there are hits and that the …

add suggestions to channel search

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py

https://trello.com/c/0ARYsgZ7/303-fix-podcast-episode-unpublish
There is a bug in the podcast data import that sets published=False for all episodes. This fixes the bug.
Run `docker-compose run web ./manage.py backpopulate_podcast_data`
Verify that the newly created/updated episodes have published=True
Create an episode that is not in the rss file for a podcast
```
podcast = Podcast.objects.first()
episode = PodcastEpisode.objects.create(podcast=podcast, title="new", episode_id = "new", published=True)
```
Run
Run `docker-compose run web ./manage.py backpopulate_podcast_data` again. Verify that the new episode is no longer published but all other episodes are.

fix unpublish code for podcast episodes

---

course_catalog/views.py
course_catalog/views_test.py
static/js/components/PodcastEpisodeCard.js
static/js/components/PodcastEpisodeCard_test.js
static/js/factories/podcasts.js
static/js/flow/podcastTypes.js
static/js/lib/queries/podcasts.js
static/js/lib/queries/user_lists.js
static/js/lib/url.js
static/js/pages/App_test.js
static/js/pages/PodcastFrontpage.js
static/scss/_variables.scss
static/scss/button.scss
static/scss/card.scss
static/scss/podcasts.scss

part of #2722 
This basically adds a placeholder display for podcasts and an initial implementation of the 'recent episodes' UI.
Currently the 'Follow' button doesn't do anything, and the podcasts and episodes can't yet be opened in the drawer (we can add once the search UI is done).
either import the podcast data (with the `backpopulate_podcast_data` management command) or create some fake podcasts. then visit `/podcast` and you should see a nice display of episodes!
for the podcasts themselves it is currently just a placeholder of displaying the title.
note that this mobile UI is very provisional, I will do a second follow-up PR to get this to be in line with the designs (but the screenshot shows not that much work is needed I think):

add "recent episodes" UI to podcast frontpage

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views.py
static/js/factories/podcasts.js
static/js/flow/podcastTypes.js

None
Fixes slow performance in podcasts API due to a large amount of data being provided. The nested episodes are the largest piece of the REST API and they're not needed so they are removed from the results.
Populate some podcast data. Then go to `/api/v0/podcasts/` and make sure it feels reasonably snappy.

Remove nested episodes from podcasts API to improve performance

---

static/js/components/ContentToolbar.js
static/js/components/ContentToolbar_test.js

closes #2793
fixes a little issue where the 'my lists' link is still shown on `/podcasts` even if the `COURSE_UI` feature is disabled.
disable `COURSE_UI` and enable `PODCAST_FRONTPAGE` and then visit `/podcasts`. You shouldn't see the 'my lists' link up in the top bar.
if you have `COURSE_UI` enabled it should be there.

hide 'my lists' when on `/podcasts`

---

static/js/components/PodcastCard.js
static/js/components/PodcastCard_test.js
static/js/pages/PodcastFrontpage.js
static/scss/podcasts.scss

part of #2722 
this adds 'podcast cards' which show all of our podcasts on the `/podcasts` 'front page'.
currently it just fetches all of them in one big request that returns everything. Obviously this is not ideal! I think we should re-paginate the API and then add an infinite scroll here probably (see #2795).
if you've imported podcasts into your dev env you should be able to visit `/podcasts` and see a card for each podcast in a grid below the 'recent episodes' display. clicking them doesn't do anything yet :smile: 
mobile UI has not been optimized yet:

add podcast cards

---

course_catalog/serializers.py
course_catalog/views.py
course_catalog/views_test.py
static/js/factories/podcasts.js
static/js/flow/podcastTypes.js

Fixes #2806 
Adds `episode_count` to podcasts API, which is the count of all published episodes for that podcast
Go to `/api/v0/podcasts` and verify that the numbers make sense. You should be able to mark an episode `published=False` in the database and see the count for that podcast decrease by 1.

Add episode_count field to episodes REST API

---

course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

Fixes #2809 
- Adds `/api/v0/podcastepisodes/` to list all podcast episodes
- Adds `/api/v0/podcastepisodes/:number/` to get information about a podcast episode by id
Go to `/api/v0/podcastepisodes/:number/` for a podcast episode and verify that it looks fine. If the podcast episode is not published, or if the episode is published but the podcast is not, you should get a 404 error instead.

Podcast episodes detail view

---

app.json
course_catalog/etl/podcast.py
course_catalog/etl/youtube.py
open_discussions/settings.py

https://github.com/mitodl/open-discussions/issues/2801
Add authentication to github api requests 
Create a personal access token following these steps:
https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
Set GITHUB_ACCESS_TOKEN in your .env file to the token you created.  Also set OPEN_PODCAST_DATA_BRANCH=ab/test-ingest Verify that 
docker-compose run web ./manage.py backpopulate_podcast_data and
docker-compose run web ./manage.py backpopulate_youtube_data
both work

Use github access token for authentication

---

course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

Fixes #2813
Adds `/api/v0/podcasts/:number/episodes/` to list all serialized episodes for a given podcast id
Go to the endpoint and verify that the episodes match what you expect to see. Unpublished episodes should not be included in the list.

Add episodes per podcast view

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/pipelines.py
search/task_helpers.py
search/task_helpers_test.py
search/tasks.py
search/tasks_test.py

Closes #2791 
Indexes podcasts and podcast episodes upon ingestion
One way to test this would be to follow the logic of the test cases, e.g.: 
```python
podcast = PodcastFactory.build()
podcast_data = model_to_dict(podcast)
load_podcast(podcast_data)
```
After that example, you should see a new podcast in the ES index

Added podcast indexing upon ingestion

---

course_catalog/etl/podcast.py
course_catalog/etl/podcast_test.py
test_html/test_podcast.rss

https://github.com/mitodl/open-discussions/issues/2797
This pr updates podcast ingestion to use the podcast image for podcast episodes that do not have their own image
set `OPEN_PODCAST_DATA_BRANCH=ab/test-ingest`
run `docker-compose run  web ./manage.py backpopulate_podcast_data`
Verify that all podcast episode objects have image_src set

use podcast image when podcast episode image is missing

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/podcast.py
course_catalog/etl/podcast_test.py

https://github.com/mitodl/open-discussions/issues/2825
This pr makes the `offered_by` field in the podcast config file in open-podcast-data optional
Set OPEN_PODCAST_DATA_BRANCH=master
Run `docker-compose run web ./manage.py backpopulate_podcast_data`. It should run successfully.
Go to 
`http://localhost:8063/api/v0/podcastes/` and `http://localhost:8063/api/v0/podcastepisodes/`. Verify that the data looks good.
Create a new offered_by record for a podcast and podcast episode.
```
ob, _ = LearningResourceOfferor.objects.get_or_create(name='Not in config file')
podcast  = Podcast.objects.last()
podcast_episode = PodcastEpisode.objects.last()
podcast.offered_by.add(ob)
podcast.save()
podcast_episode.offered_by.add(ob)
podcast_episode.save()
```
Verify …

make config offered_by field optional

---

static/scss/audio-player.scss

https://github.com/mitodl/open-discussions/issues/2841
Fixes issues with the width of the inner container for the audio player
Run the player and make sure the content is not overflowing outside the container.  It's easiest to see on mobile, see the screenshots below.
The issue:
How it should look:

Fix audio player width

---

course_catalog/serializers.py
course_catalog/serializers_test.py
course_catalog/views.py
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/components/LearningResourceDrawer.js
static/js/components/LearningResourceDrawer_test.js
static/js/components/PodcastCard.js
static/js/components/PodcastCard_test.js
static/js/components/PodcastEpisodeCard.js
static/js/components/PodcastEpisodeCard_test.js
static/js/components/PodcastPlayButton.js
static/js/factories/learning_resources.js
static/js/factories/podcasts.js
static/js/flow/podcastTypes.js
static/js/hooks/podcasts.js
static/js/hooks/podcasts_test.js
static/js/hooks/test_util.js
static/js/lib/constants.js
static/js/lib/queries/learning_resources.js
static/js/lib/queries/podcasts.js
static/js/lib/queries/user_list_items_test.js
static/js/lib/url.js
static/js/pages/App.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js
static/scss/learning-resource-drawer.scss
static/scss/podcasts.scss

part of #2722 
adds basic support for podcasts and podcast episodes to our learning resource drawer.
you should be able to open any podcast or podcast episode in the drawer, the display should be adequate. you should be able to start playing an episode from the drawer.
(Optional)

Podcast / PodcastEpisode drawer support

---

static/js/actions/audio.js
static/js/components/AudioPlayer.js
static/js/components/AudioPlayer_test.js
static/js/components/PodcastEpisodeCard.js
static/js/components/PodcastPlayButton.js
static/js/hooks/audio_player.js
static/js/hooks/audio_player_test.js
static/js/lib/redux_selectors.js
static/js/reducers/audio.js
static/js/reducers/audio_test.js

Closes https://github.com/mitodl/open-discussions/issues/2842
Apple Webkit based browsers (Safari & literally all browsers on iOS) disallow programmatically starting playback of audio or video without user interaction.  This PR takes the amplitudejs init code out of the AudioPlayer component itself and moves it to own own hook.  This way, this callback can be executed directly from a click handler to initialize the player and start playing the audio directly.
Aside from tests passing, you should be able to visit `/podcasts` in Safari and click "Play" on a podcast.  The player should load and audio should automatically start playing.
Not a GIF, but I thought this was relevant:

Audio player Safari / Apple Webkit fix

---

static/js/components/PodcastEpisodeCard.js
static/js/components/PodcastEpisodeCard_test.js
static/scss/podcasts.scss

part of #2722 
adds the publish date to the `PodcastEpisodeCard`
the `last_modified` date should be showing up on the episode cards, formatted like on the designs.

add date to podcast episode

---

static/js/hooks/learning_resources.js
static/js/hooks/learning_resources_test.js
static/js/hooks/test_util.js
static/js/lib/url.js
static/js/lib/url_test.js
static/js/pages/CourseIndexPage.js
static/js/pages/CourseIndexPage_test.js
static/js/pages/PodcastFrontpage.js
static/js/pages/PodcastFrontpage_test.js

closes #2856
this makes it so that podcasts and podcast episodes will share "over" the podcast frontpage (`/podcasts`) instead of the learn page (`/learn`). non-podcast things should behave as before.
confirm that sharing of other learning resources works as normal. then confirm that podcast share links point to the `/podcast` page instead of `/learn.

fix podcast share URL

---

static/js/components/Drawer.js
static/js/components/Drawer_test.js
static/js/components/LearningResourceDrawer.js
static/js/hooks/audio_player_test.js
static/js/lib/redux_selectors.js
static/js/pages/App.js
static/js/reducers/audio_test.js
static/scss/audio-player.scss

None at the moment
Adds redux selectors to check if the audio player is currently loaded, then implements them on the classes that have outermost container UI elements; `App.js`, `Drawer.js` and `LearningResourceDrawer.js`.  When the audio player is active, a class is added to the outermost elements that adds bottom padding based on the value of the audio player height sass variables.  This would all be much simpler if CSS4 was released, because we could just use the `:has` selector to only apply a rule to an outer element that contains a `:not(.hidden)` `.audio-player-container-outer`.  This is the best way to do it right now, from what I can tell.
Go to /podcasts and click play on one of the episodes.  When the audio player loads, you should be able to scroll to the bottom of the page …

Audio player padding adjustments

---

static/scss/audio-player.scss

Closes https://github.com/mitodl/open-discussions/issues/2866
Sets the z-index on the outer container of the audio player to be above everything else.
Go to /podcasts on mobile (or in the mobile simulator) and click one of the recent episode cards.  Click play within the card, and the audio player should now show up on top.

Audio player Z index fix

---

course_catalog/views.py
course_catalog/views_test.py
static/js/components/Card.js
static/js/components/Card_test.js
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/components/LRDrawerPaginationControls.js
static/js/components/PaginatedPodcastEpisodes.js
static/js/components/PaginatedPodcastEpisodes_test.js
static/js/components/PodcastEpisodeCard.js
static/js/components/PodcastEpisodeCard_test.js
static/js/components/UserListItems.js
static/js/lib/queries/podcasts.js
static/js/lib/url.js
static/js/util/integration_test_helper.js
static/scss/card.scss
static/scss/podcasts.scss

closes #2856 
this adds support for showing the list of episodes on a podcast, in a paginated form. it re-uses the same styling as the existing display we have for userlist items for now.
Navigate to `/podcasts`. You should be able to open a podcast in the drawer and see a list of the episodes in the podcast. for a podcast with a lot of episodes (like 'the ai podcast') you should be able to freely page forward and back through the episodes.
also you should be able to play podcast episodes from the drawer, and clicking on the title (or elsewhere) on the podcast episode card should then focus that card. you should then be able to use the 'back' button as normal to return to the podcast.

add episode list to podcast drawer

---

static/js/babelhook.js
static/js/components/AudioPlayer.js
static/js/components/PodcastPlayButton.js
static/js/components/PodcastPlayButton_test.js
static/js/hooks/audio_player.js
static/js/lib/constants.js
static/js/lib/redux_selectors.js
static/js/reducers/audio.js
static/scss/podcasts.scss

closes #2878
this makes it so that after you've started playing a podcast the 'play' button (in the episode card or the drawer) will change to a 'pause' button.
I also added some overall tests to the `PodcastPlayButton` to make sure it does what we want.
Make sure it works as advertised.
Podcast playing state should be synchronized between the player, the drawer, and the card. You should be able to play/pause anywhere and the update should be reflected everywhere right away

pause / play podcast from the PodcastPlayButton

---

static/scss/audio-player.scss

Closes https://github.com/mitodl/open-discussions/issues/2844
Prevents highlighting of buttons (and all text) within the audio player with the `user-select: none` CSS rule.  The buttons were not actually receiving focus when clicking them repeatedly, they were being highlighted because the material icons we are using technically count as text that can be highlighted.  The CSS rule prevents this from happening.
Open the audio player and rapidly click any of the buttons.  Click and drag across the player.  Nothing should be highlighted.

Prevent focus of buttons in the audio player

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/scss/learning-resource-drawer.scss

closes #2881
^^ see the PR title :smile: 
if you open a podcast episode in the drawer you should see a link to 'View All Episodes' which should open the podcast itself in the drawer.

add link in drawer from podcast episode to all episodes

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js

no ticket, @abdulkdawson asked me to make this change
hide 'share' button on podcasts, podcast episodes in drawer
when a podcast or episode is open in the drawer the share button should not be there, otherwise, it should be there for courses and whatnot.

hide 'share' button on podcasts, podcast episodes in drawer

---

package.json
static/js/components/material/Snackbar.js
static/scss/snackbar.scss
yarn.lock

Closes https://github.com/mitodl/open-discussions/issues/2784
Replaces our custom Snackbar component with the RMWC wrapped equivalent, but still tied to our redux state in the same way.  Our component has also been converted to a hook.
Go to the settings page and change your notification settings.  You should get a snackbar message confirming the change.

Snackbar update

---

static/js/components/LearningResourceDrawer.js
static/js/components/LearningResourceDrawer_test.js
static/js/util/integration_test_helper.js

fixes one part of the issue in #2883
see the issue, this fixes the 2nd issue:
"opening the drawer, scrolling down, closing the drawer, and re-opening, on a podcast or pair of podcasts which do not trigger the first issue, can leave the drawer scrolled down because we do not scroll the drawer content to top when it closes"
A good podcast to test with is the one called 'BioGenesis'.
Check on master that if you:
- open that podcast
- scroll the drawer down a little bit
- close the drawer
- re-open it
the drawer should be at the scroll position you left it at when you closed it.
then check out this branch, and confirm that the drawer is always scrolled to the top for that podcast.
_Note that there are other podcasts for which this wont work!_ Go read the issue, but basically when podcasts …

fix drawer scrolling issue

---

search/api.py
search/api_test.py
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

https://github.com/mitodl/open-discussions/issues/2864
This pr updates the learning search ui to have a single category for the podcast and podcast episode types. Selecting "podcasts" in the search returns both podcasts and podcast episodes.
run `docker-compose run web ./manage.py backpopulate_podcast_data` if needed. 
Go to the learning search. The "Podcast" type should have 963 entries, which is the combined number of podcasts and podcast episodes. Filtering for "Podcast" should return both types of podcast resources

combine podcast and podcast episode

---

static/js/factories/learning_resources.js
static/js/lib/queries/interactions.js
static/js/lib/queries/interactions_test.js
static/js/lib/queries/learning_resources.js
static/js/lib/queries/learning_resources_test.js

https://github.com/mitodl/open-discussions/issues/2915
When a learning path is a popular resource it breaks the /learn page. This fixes the issue. 
Pick a learning path and click on it in http://localhost:8063/learn/search enough times so it becomes a popular resource for you locally. Verify that http://localhost:8063/learn/ loads and displays the learning path under popular resources

fix popular resourses learning path

---

search/api.py
search/api_test.py
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/lib/search.js
static/js/lib/search_test.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

https://github.com/mitodl/open-discussions/issues/2864
https://github.com/mitodl/open-discussions/issues/2823
This pr updates the learning search ui to have a single category for the podcast and podcast episode types and for learning list and learning path types. Selecting "podcasts" in the search returns both podcasts and podcast episodes and selecting "learning lists" returns both learning lists and learning paths
create a few learning lists and paths if needed
The "Learning Lists" type should have whatever the combined number of learning lists and learning paths is.
Text search should return both learning lists and learning paths objects

combine  userlist learning path in search

---

static/scss/podcasts.scss

closes #2883
this just sets a `min-height` on the div that we use to show `offered_by` on the podcast cards to ensure that the podcast card heights are the same, regardless of whether the `offered_by` field is filled in or not.
all my podcasts locally have `offered_by` filled-in, so what I did is just edit the HTML directly in the dev tools to confirm the issue (i.e. delete the text inside of `div.row.podcast-author`) , and then check out this branch to confirm it fixes it.

even out the height of podcast cards

---

search/api.py
search/api_test.py
static/js/components/CourseFilterDrawer.js
static/js/components/CourseFilterDrawer_test.js
static/js/lib/course_search.js
static/js/lib/course_search_test.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js
static/js/lib/search.js
static/js/lib/search_test.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

https://github.com/mitodl/open-discussions/issues/2918
This removes cost and availability facet filters from the search page.
Go to http://localhost:8063/learn/search. There should be no cost or availability filters. Text search and the remaining filters should continue to work as expected.  Cost and availability should still be displayed the same way as it was previously in learning resource cards. This will be updated in a future pr.

remove cost and availability facets

---

search/serializers.py
search/serializers_test.py

https://github.com/mitodl/open-discussions/issues/2862
This pr updates the podcasts serializer so facet filters appear for podcasts in the learning research search
Run `docker-compose run web ./manage.py recreate-index`
Go to http://localhost:8063/learn/search?type=podcast. Verify that there are facet filters in the sidebar.

fix facets for podcasts

---

course_catalog/tasks.py

N/A
This ensures the subtasks for the ocw sync don't acknowledge until it completes
Run `./manage.py backpopulate_ocw_data --skip-s3` and verify it executes correctly

Ensure ocw subtasks don't ack until task completes

---

course_catalog/etl/mitpe.py
course_catalog/etl/mitpe_test.py
course_catalog/utils.py
course_catalog/utils_test.py

N/A
- Adds handling for the `January IAP` semester so that courses that only have runs during that semester get updated.
- Updates MIT Professional Ed ETL to allow updating of course information even in there are no active "runs" on the catalog page (i.e. courses that either have a blank or "TBD" date)
- Run `./manage.py backpopulate_mitpe_data` and `./manage.py backpopulate_ocw_data`
- Verify the search page still works

Fix a few ingestion issues for OCW/MITPE

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py

Fixes #2946
This modifies topic loading so that if topics aren't passed in the extracted/transformed data, no changes to topics are made. This ensures micromasters courses (that have no topics in the MM catalog api) don't override the corresponding mitx course topics.
- Verify the bug in master:
- `./manage.py backpopulate_edx_data` + `./manage.py backpopulate_micromasters_data`
- Filter to MicroMasters courses and verify they have no subjects
- Verify the fix in this branch:
- `./manage.py backpopulate_edx_data` + `./manage.py backpopulate_micromasters_data`
- Filter to MicroMasters courses and verify they have now have subjects

Fixed loading topics when not defined by the input data

---

course_catalog/migrations/0072_podcastepisode_episode_link.py
static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/js/factories/podcasts.js
static/scss/learning-resource-drawer.scss

Closes https://github.com/mitodl/open-discussions/issues/2927
This adds a "View Episode Details" link next to the `PodcastPlayButton` in the `ExpandedLearningResourceDrawer`.  If the `PodcastEpisode` has an `episode_link` property set, this is used as the `href` property, otherwise the parent `Podcast`'s `url` property is used.
Go to the podcasts page and view any podcast.  The "View Episode Details" link should render, and if you click it it should take you to either of the destinations detailed above.
An example of a `PodcastEpisode` without an `episode_link`:
MIT Catalysts - Sudeb Dalai

Podcast drawer "view episode details" link

---

static/js/components/ExpandedLearningResourceDisplay.js

Hotfix for https://sentry.io/organizations/mit-office-of-digital-learning/issues/1680848461/?environment=rc&project=216201&query=is%3Aunresolved
Hotfixes an issue I caused by rendering a selector in a conditional.
Run the site, click on a PodcastEpisode within a Podcast's drawer where indicated in the screenshot below.  The app should not crash.
(Optional)

hook issue hotfix

---

course_catalog/constants.py
static/js/lib/constants.js

Part of #2955
- Renames usages of "xPro" to "xPRO"
- Remaps MIT PE `Radar` subject to `Electrical Engineering`
- Run in a shell:
```python
from course_catalog.models import LearningResourceOfferor
LearningResourceOfferor.objects.filter(name="xPro").delete()
```
- `./manage.py backpopulate_mitpe_data` and `./manage.py backpopulate_xpro_data`
- You should now see a single `xPRO` option in the Offered By facet
- You may or may not see a PE course titled "Build a Small Radar System", if you don't, that's expected/ok, if you do, it should only have the "Electrical Engineering" subject.

Fix the xPRO offered by value

---

search/api.py
search/api_test.py

https://github.com/mitodl/open-discussions/issues/2935
It sorts the type facet by bucket size to match other facets
Go to learn/search. The `Learning Resource` bucket should be sorted.

sort type facet

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/LearningResourceDrawer.js
static/js/components/PodcastCard.js
static/js/components/PodcastCard_test.js
static/js/components/PodcastEpisodeCard.js
static/js/components/PodcastEpisodeCard_test.js
static/js/components/PodcastPlayButton.js
static/js/components/PodcastPlayButton_test.js
static/js/hooks/audio_player.js
static/js/pages/PodcastFrontpage.js
static/scss/podcasts.scss

Closes https://github.com/mitodl/open-discussions/issues/2960
This adds keyboard navigation / audio playback control to the podcasts page.  
Go to `/podcasts` and use only the keyboard to:
Use the Enter key to "click" on elements focused in a web browser.

/podcasts keyboard accessibility

---

static/js/components/PodcastFooter.js
static/js/pages/PodcastFrontpage.js
static/scss/podcasts.scss

closes #2907 
this adds a footer to `/podcasts`, following the designs, which has both mobile and desktop styling.
I think the main thing is to play around with the device width and make sure it works well at all widths.

add footer to podcast page

---

static/js/components/search/SearchFacetItem.js

https://github.com/mitodl/open-discussions/issues/2971
There was a small regression preventing checked facets from being highlighted in the sidebar. This fixes it
Go to /learn/search. Search facets that are checked should have key text that is larger and blue.

fix checked facet highlight

---

static/js/components/PodcastCard.js
static/js/components/PodcastCard_test.js
static/scss/podcasts.scss

closes #2966 
sets a min-height on the podcast author div and clamps it to two lines of text.
I also noticed that the border-radius was accidentally removed from the podcast cards, so I added that back.
make sure that the issue isn't causing any podcast cards to be of different height.

fix another podcast card height issue

---

static/js/pages/UserListDetailPage.js

closes https://github.com/mitodl/open-discussions/issues/2973
This changes the button text for completing a learning list reorder to "Save" from "Stop sorting Learning Path" 
Go to /learn/lists/
Select a learning path
Click "Reorder Learning Path"
The button to stop reordering should say "Save"

change reorder text

---

course_catalog/etl/constants.py
course_catalog/etl/csail.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/micromasters.py
course_catalog/etl/mitpe.py
course_catalog/etl/ocw.py
course_catalog/etl/pipelines.py
course_catalog/etl/pipelines_test.py
course_catalog/etl/see.py
course_catalog/etl/utils.py
course_catalog/etl/xpro.py
course_catalog/etl/youtube.py

Fixes #2961 - was causing video topics to not load completely
Part of #2955 
- Removes `course_catalog.etl.utils.log_exceptions` - this was a minor ergonomic improvement to writing code but a huge ergonomic detriment to testing it
- Fixes the course deduplication code to query on `platform` since otherwise it may select a course from a different platform. In practice we saw this happen between OCW + MITx courses
- Fixes a race condition (#2961) in writing out topic data. I solved this by adding transactions and taking locks on the parent resource.
- Verify you're seeing a course that doesn't appear in the API response. Message me for some examples.
- Run `./manage.py backpopulate_xpro_data` and ./manage.py backpopulate_edx_data`, they should succeed and you should see the course get …

Various fixes for ETL loading bugs

---

static/js/components/LearningResourceCard.js
static/js/components/LearningResourceCard_test.js
static/js/components/LearningResourceIcon.js
static/js/components/search/SearchFacetItem.js
static/js/components/search/SearchFacet_test.js
static/js/lib/constants.js
static/scss/layout.scss
static/scss/learning-resource-card.scss
static/scss/learning-resource-icon.scss
static/scss/search.scss

closes https://github.com/mitodl/open-discussions/issues/2979
This adds tooltip descriptions to the open content, professional content and certificate icons on learning resource cards
Go to /learn/search. Verify that there is a tooltip when you hover over the icons on the card

add tooltips to learning resource card

---

app.json
course_catalog/serializers.py
course_catalog/views_test.py
moira_lists/moira_api.py
open_discussions/settings.py
open_discussions/views.py
open_discussions/views_test.py
static/js/components/UserListFormDialog.js
static/js/components/UserListFormDialog_test.js
static/js/flow/declarations.js
static/js/global_init.js

Closes #2824 
- Adds `STAFF_MOIRA_LISTS` .env setting (moira lists of users who can create public learning paths/lists).
- Adds a validation function to `UserListSerializer` to ensure that only users in the above moira lists (or django staff/super users) are allowed to create public learning lists.
- On the front end UserListFormDialog, hides the privacy options and sets the default to 'private' if the user is not on the moira lists.
- Set `STAFF_MOIRA_LISTS` to include at least one moira list and create a user whose MIT email is on that list (and not a staff or superuser).
- Log in as that user and verify that you can create public lists and see the privacy options on the form.
- Log in as a staff or superuser and you should still be able to create public lists.
- Log in as a user who is …

Restrict creation of public lists

---

course_catalog/serializers.py
course_catalog/serializers_test.py
search/api.py
search/api_test.py
static/js/components/ExpandedLearningResourceDisplay.js
static/js/hooks/learning_resources.js
static/js/lib/queries/learning_resources_test.js
static/js/pages/LearnRouter.js

closes #2871
this PR fixes the issue with items in the 'similar items' panel in the LR drawer not showing up as favorited / added to a list when they have been.
I found an issue that was unexpected: although the individual APIs for all of our learning resources have an `is_favorite` boolean field on them, for some reason in the favorites API this field is not present on the objects in the response. So to fix it I made a change to the favorite item serializer to insert the field manually.
go to the course search and open up an item in the drawer. favorite one of the items in the 'similar items' panel. if you reload the page and open the drawer for that same item you should see the 'favorite' icon filled-in for the item you favorited (or added to a user list).
Another way to test is to look …

fix favorite / not favorite display for 'similar items' in LR drawer

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py

Part of #2955 
This PR fixes an issue where different ETL processes were nulling out data the other one was populating, specifically:
- `video_topics_etl` was nulling out `offered_by` relations
- `youtube_etl` was nulling out `topics` relations
Run the following tasks and ensure they don't overwrite unrelated data.
```python
from course_catalog.etl import pipelines
pipelines.youtube_etl()
pipelines.video_topics_etl()
```

Fix video loading of offerors and topics

---

static/js/components/LRDrawerPaginationControls.js
static/js/components/PaginatedPodcastEpisodes_test.js

fix a small issue Brian pointed out to me
fix an off-by-one error in how we figure out when to disable the 'Next' button on the pagination controls for lists of learning resources displayed in the LR drawer.
First confirm the issue. Get the latest podcast data and check out 'Chalk Radio'.
You should see that the episodes list fills the first page, but that the next button is enabled. clicking it should show you a blank page - in other words, the next button is enabled when it should be disabled.
Then check out this branch and confirm it fixes it.

fix off-by-one error in drawer pagination

---

search/api.py
search/api_test.py
static/js/components/search/CourseFilterDrawer.js
static/js/components/search/CourseFilterDrawer_test.js
static/js/flow/searchTypes.js
static/js/lib/search.js
static/js/lib/search_test.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

https://github.com/mitodl/open-discussions/issues/2975
This pr updates the facet filters so that the available selectors for each facet are filtered by the values in other facets but not that facet. 
Go to the learn/search page.
Select a facet option. 
Refresh the page. 
The facet options available should not change.

fix facet filters

---

course_catalog/etl/podcast.py
course_catalog/etl/podcast_test.py

https://github.com/mitodl/open-discussions/issues/2999
Trims whitespace when importing topics
Set `OPEN_PODCAST_DATA_BRANCH=ab/test` in your .env file
Run docker-compose run web ./manage.py backpopulate_podcast_data
Verify that a topic named  '       Biology' isn't created

trim topics white space

---

static/js/components/PodcastCard.js
static/js/components/PodcastCard_test.js
static/scss/podcasts.scss

closes https://github.com/mitodl/open-discussions/issues/3001
Adds the episode count to podcast cards
Go to the /podcasts page. Verify that episode counts are displayed in the card and the styling looks good

add episode count to podcast card

---

static/js/lib/constants.js
static/js/lib/learning_resources.js
static/js/lib/learning_resources_test.js

https://github.com/mitodl/open-discussions/issues/2984
There is currently a bug in the code that preferentially selects runs with no start or end date as the best run (due to how we set default dates). This fixes it.
If there is currently a course with "Invalid date" in your local app, this should fix it. Otherwise create one by picking a course with a certificate then running
```
from search import task_helpers
run = course.runs.last()
run.best_start_date = None
run.best_end_date = None
run.save()
task_helpers.upsert_course(course.id)
```
The course should have "Invalid date" in the card in the master branch but not this branch

do not select run with missing dates as best run

---

course_catalog/urls.py
course_catalog/views.py
course_catalog/views_test.py

closes https://github.com/mitodl/open-discussions/issues/3004
This limits the podcast episodes in the recent list on the /podcasts page to one episode per podcast
Check if you have multiple episodes from the same podcast in the recent episodes list on the /podcasts page when you run the app with the master branch.  If not, update the `last_modified` date on a podcast episode so that you do have multiple episodes from the same podcast in the list. 
Run the code in this branch. You should no longer have more than one episode per podcast in that list.

limit to one recent episode per podcast

---

course_catalog/data/ucc-topic-mappings.csv
course_catalog/etl/xpro.py
course_catalog/etl/xpro_test.py
test_json/xpro_courses.json
test_json/xpro_programs.json

Fixes #2992 
This adds a mapping for xPro topics into OCW topics based on a csv
- Run `./manage.py backpopulate_xpro_data` on master, observe that you get new, unmapped topics for xPro courses.
- Run the same command on this branch, the new topics should go away and be mapped to existing ones instead.

Added xPro topic mapping

---

test_requirements.txt

Pins isort==4.3.21 in order to have the tests pass.
Build should not break.

fix isort version

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/podcast.py
course_catalog/etl/podcast_test.py
test_html/test_podcast.rss

https://github.com/mitodl/open-discussions/issues/3019
There is a bug in the loader so elasticsearch is not updated when an episode is marked as no longer published.  Also, we generate episode ids based on the url, which can change instead of the guid which is not supposed to change. This fixes both those issues.
Run `docker-compose run web ./manage.py backpopulate_podcast_data`. Verify that there are not duplicate episodes in /learn/search

fix podcast etl

---

course_catalog/etl/pipelines.py
course_catalog/etl/pipelines_test.py

closes https://github.com/mitodl/open-discussions/issues/3028
ProgramLoaderConfig is set incorrectly for micromasters causing the update job to error. This fixes the issue.
`docker-compose run web ./manage.py backpopulate_micromasters_data` should run without throwing an error

fix micromasters loader bug

---

static/js/components/ExpandedLearningResourceDisplay.js
static/js/components/ExpandedLearningResourceDisplay_test.js
static/scss/learning-resource-drawer.scss
static/scss/podcasts.scss

closes #2928
this just adds a link to the podcast home page to the LR drawer.
Open up a podcast and ensure that you get a link to the home page!

add link to podcast page to LR drawer

---

static/js/components/CompactPostDisplay.js
static/js/components/CompactPostDisplay_test.js
static/js/components/ExpandedPostDisplay.js
static/js/components/ExpandedPostDisplay_test.js
static/js/components/PostList.js
static/js/components/PostList_test.js
static/js/components/PostUpvoteButton.js
static/js/components/PostUpvoteButton_test.js
static/js/components/ProfileContributionFeed.js
static/js/components/ProfileContributionFeed_test.js
static/js/components/SearchResult.js
static/js/hoc/withPostList.js
static/js/hoc/withPostList_test.js
static/js/pages/PostPage.js
static/js/pages/SearchPage.js
static/js/util/api_actions.js
static/js/util/api_actions_test.js

none
the way we do post voting is sort of a mess right now. We have one component called a `PostUpvoteButton` which has responsibility for _rendering_ the button, but responsibility for declaring the callbacks is external to it. So anywhere we're display a post we have to pass a `toggleUpvote` function in to `ExpandedPostDisplay` and `CompactPostDisplay` so that they can then pass that down to the `PostUpvoteButton`. Because we show posts in a variety of places (home page, channel page, post page, profile contribution feed, search results...) this is wicked messy and leads to needlessly passing callbacks down the component tree.
So I refactored `PostUpvoteButton` so that it manages its own callback without external dependencies. This means that all it needs as a prop is a `Post` - …

[refactor] consolidate post voting

---

static/scss/drawer.scss

closes #3049
this basically changes the `min-height` property set on the `.navigation` div in the drawer. we set this in order to force the footer to be down at the bottom of the page, but the way we were doing it doesn't account for the height of the audio player. I changed it around so that we're subtracting the audio player height from that `min-height` value when the audio player is open.
Go to `/podcasts` or the course search to start playing a podcast, then navigate to the home page by clicking the 'MIT Open' text in the top bar. You should not see the 'before' state shown in the screenshot below.
before:
after:

fix issue where 'footer' in nav drawer was covered by audio player

---

app.json
channels/serializers/comments.py
channels/serializers/posts.py
channels/spam.py
channels/spam_test.py
channels/task_helpers.py
channels/task_helpers_test.py
channels/tasks.py
channels/tasks_test.py
channels/views/comments_test.py
channels/views/posts_test.py
docker-compose.yml
fixtures/common.py
open_discussions/settings.py
requirements.in
requirements.txt

Part of #3062
(Required)
- Create an account for [Akismet](https://akismet.com/)
- Change your plan to "Personal", which requires a wordpress.org account
- Configure a new site with a blog url (I used `<username>.github.io` since that's something i control)
- Add the access key and blog url to `.env` under `AKISMET_API_KEY` and `AKISMET_BLOG_URL`
- Verify you can create a post with reasonable content (try copy/pasting content from production)
- Verify a post with spammy content is removed after the async task fires
The async task with a delay is necessary because we need to remove the psot after reddit's own async tasks which update the channel/frontpage listings.

Added spam checking to posts and comments (#3062)

---

static/js/components/CommentVoteForm.js
static/js/components/CommentVoteForm_test.js
static/js/components/ProfileContributionFeed.js
static/js/pages/PostPage.js
static/js/reducers/comments.js
static/js/reducers/comments_test.js
static/js/util/rest.js

closes #221 (from 2017!)
partially addresses #748
this PR fixes a few issues with comment voting. namely:
- now instead of failing and blowing up the UI (see #748) when a comment vote fails 
- I also fixed the optimistic update behavior for the comment vote to immediately reflect what the score on the comment will be *after* the user's vote is applied.
if you have a comment on your local reddit that is older than 6 months you can use that to test this, else you can apply the following patch:
```patch
diff --git a/channels/views/comments.py b/channels/views/comments.py
index be8e5af0..d1fbfe43 100644
--- a/channels/views/comments.py
+++ b/channels/views/comments.py
@@ -209,6 +209,7 @@ class CommentDetailView(APIView):
def patch(self, request, *args, **kwargs):  # pylint: …
```

fix a few issues with comment voting

---

package.json
static/js/components/AddToListDialog.js
static/js/components/CourseSearchbox.js
static/js/components/CourseSearchbox_test.js
static/js/components/Dialog.js
static/js/components/Grid.js
static/js/components/LearningResourceCard.js
static/js/components/UserListFormDialog.js
static/js/components/UserListItems.js
static/js/components/UserMenu.js
static/js/components/search/CourseFilterDrawer.js
static/js/components/search/FilterableSearchFacet.js
static/js/components/search/SearchFacetItem.js
static/js/components/search/SearchFilter.js
static/js/pages/CourseSearchPage.js
yarn.lock

closes https://github.com/mitodl/open-discussions/pull/3059
The /learn and /learn/search pages should be accessible via the keyboard using tab.
Currently the only actions that should still be not accessible through the keyboard are the share link and the login tooltip on the favorite link. It is not possible to use tab to access the inside of tooltips. Let me know if  you notice anything else.
Go to the he /learn, /learn/search and user list pages and verify that you can access the content without using your mouse.
`Tab` moves through focusable elements on the page
`Shift + tab` moves through focusable elements backwards
`Enter` interacts with the focusable elements
`Space` checks and unchecks checkboxes
To reorder items in  learning paths: use `Space` to pick up a learning resource, …

make learn pages tababble

---

static/scss/drawer.scss

closes #3060
this adds padding to the `.scrollarea-content` div in the nav drawer to ensure you can always scroll down to see all of the content in it when the podcast player is open.
make sure you can scroll to see the footer with the podcast player open. all other stuff should be normal across the site.
before:
after:

fix another padding issue with the drawer

---

cassettes/channels.views.posts_test.test_get_removed_post[None-404].json
cassettes/channels.views.posts_test.test_get_removed_post[client_user1-404].json
cassettes/channels.views.posts_test.test_get_removed_post[client_user2-200].json
channels/proxies.py
channels/views/posts.py
channels/views/posts_test.py
docker-compose.override.yml
factory_data/channels.views.posts_test.test_get_removed_post[None-404].json
factory_data/channels.views.posts_test.test_get_removed_post[client_user1-404].json
factory_data/channels.views.posts_test.test_get_removed_post[client_user2-200].json
open_discussions/templates/400.html
open_discussions/templates/403.html
open_discussions/templates/404.html
open_discussions/templates/base.html
open_discussions/templates/index.html
open_discussions/templates/react.html
open_discussions/templates/social.html
open_discussions/urls.py
open_discussions/urls_test.py
open_discussions/views.py
open_discussions/views_test.py
profiles/views_test.py

Fixes #2785 
This adds a server-side 404 page for removed posts for non-moderator users, to ensure that for search engines and anyone else don't see this content perpetually. Also covered 400/403 errors just in case since they were a quick win.
- Remove a post in a public and/or private channel
- You should still be able to view the post as a moderator
- As a logged in user you should get a 404 page
- As an anonymous user you should get a 404 page for the public post
Intentionally not handled here:
- 500 error pages: not in scope and a bit of effort
- Anonymous users trying to view a removed private post

Added server-side 404 page for posts

---

course_catalog/views.py

none
Removes authentication from the podcast rss
Verify that the http://localhost:8063/podcasts/rss_feed loads for both logged in and logged out users.
Unfortunately that was the case for me locally before this change as well. Is there anything else I need to make the page available without a login?

remove podcast rss authentication

---

app.json
course_catalog/etl/podcast.py
open_discussions/settings.py

closes https://github.com/mitodl/open-discussions/issues/3112
This pr limits the number of episodes displayed in the aggregated feed at /podcasts/rss_feed to the value of RSS_FEED_EPISODE_LIMIT with a default of 10  
Go to http://localhost:8063/podcasts/rss_feed. Verify that the number of episodes is caped to RSS_FEED_EPISODE_LIMIT most recent ones

limit rss feed episodes

---

app.json
course_catalog/views.py
open_discussions/settings.py

http://localhost:8063/podcasts/rss_feed
This pr caches the rss feed so that it will load faster. The default cache time is set to 15 minutes
Go to http://localhost:8063/podcasts/rss_feed. The page takes a second or two to load initially. On subsequent loads, it should load immediately.

add cache to rss page

---

package.json
static/js/components/AudioPlayer.js
static/js/components/Comment.js
static/js/components/CommentReportDialog.js
static/js/components/CommentVoteForm.js
static/js/components/LearningResourceCard.js
static/js/components/LearningResourceDrawer.js
static/js/components/TruncatedText.js
static/js/components/UserListItems.js
static/js/components/search/FilterableSearchFacet.js
static/js/hooks/comments.js
static/js/hooks/learning_resources.js
static/js/lib/posts.js
static/js/lib/queries/user_list_items.js
static/js/pages/ChannelMembersPage.js
yarn.lock

none
this just updates to the latest version of our eslint configuration, which adds the react-hooks preset. this allows the linter to find a lot of issues where the logic of hooks is being violated - it found a bunch of callbacks which did not have their dependencies properly specified, for instance, which could lead to bugs related to stale data inside the closure of the callback.
there aren't really any code changes - the only things are renaming some things so that the linter knows they are hooks and turning off rules in a few, specific places. so I think just read through it and make sure things look good, and possibly do a quick smoke test of the app to make sure I didn't break anything.

upgrade eslint config, fix errors

---

authentication/views.py
authentication/views_test.py
docker-compose.yml
open_discussions/test_utils.py
open_discussions/test_utils_test.py

Fixes #3095 
Fixes the password reset views so the password reset flow works again
Run through a full password reset workflow (fill out the form, click the link in the resulting email, and use the password change form)
Sooo due to a naming issue, our two Djoser test cases were not being run. It looks like something changed in the Djoser internals which broke our functionality that overrides it, and this wasn't caught because of said test cases being unrecognized 😬

Fixed password reset

---

static/js/components/ArticleEditor.js
static/js/components/auth/AuthEmailForm.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js
static/js/util/integration_test_helper.js

None
Attempts to fix a race condition by mocking out debounce to execute without a delay during testing. I can't reproduce this locally but here it is on travis: https://travis-ci.com/github/mitodl/open-discussions/jobs/378453509#L2728
Nothing should break. For user-facing code, I only changed the imports to use `_` instead of importing debounce directly to make mocking easier.

Mock debounce to try to fix flaky tests

---

static/js/components/Grid.js
static/js/components/SearchResult.js
static/js/components/SearchResult_test.js
static/js/components/search/CourseFilterDrawer.js
static/js/hooks/learning_resources.js
static/js/hooks/util.js
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js
static/js/util/integration_test_helper.js

no ticket, but basically to accomplish the same thing I did here: https://github.com/mitodl/hugo-course-publisher/pull/190 for the OCW search.
this removes the automatic search behavior, so that the user has to manually trigger the search instead via the enter key.
I also found a few performance issues on the page and diagnosed those, adding `React.memo` to fix.
also refactored `CourseSearchPage` from class-based to functional component.
This touched a lot of parts of the search, so please test it exhaustively. Facets should all work, should be able to change text search, clear facet values, etc etc.

fix course search textbox behavior

---

static/js/components/Footer.js
static/js/components/PodcastFooter.js
static/scss/drawer.scss

Fixes #3142 
Adds a couple of links to the footer on the drawer and the podcast page
Click the links and verify that you go to https://accessibility.mit.edu

Add accessibility links to footers

---

channels/admin.py

closes https://github.com/mitodl/open-discussions/issues/3136
This pr adds author and post/comment information to the spam check admin
Go to http://localhost:8063/admin/channels/spamcheckresult
Verify that you see information about the post/comment and author info

add post and comment information to spam check admin

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/management/commands/delete_non_courses.py

Closes #3148
- Skips processing of an OCW course if the prefix starts with one of the prefixes in `course_catalog.constancts.NON_COURSE_DIRECTORIES`
- On master, run `course_catalog.api.sync_ocw_courses(course_prefixes=["PROD/biology"], blocklist=[], force_overwrite=True, upload_to_s3=True)` - the course will be processed and master_json written to S3.
- On this branch, run `python manage.py delete_non_courses`.  You should see a message about a biology master.json file being deleted.
- On this branch run `course_catalog.api.sync_ocw_courses(course_prefixes=["PROD/biology"], blocklist=[], force_overwrite=True, upload_to_s3=True)` again - this time the course should not be processed (`Non-course folder, skipping: PROD/biology`)

Don't sync an OCW course if it's in the NON_COURSE_DIRECTORIES list

---

channels/admin.py

NA
Fixes https://sentry.io/organizations/mit-office-of-digital-learning/issues/1901469218/?project=216201&query=is%3Aunresolved
https://github.com/mitodl/open-discussions/pull/3150 breaks the spam check admin for Link posts which have text=None 
Either create a link post with a non-moderator user or just set text=None for the content_object of one of your existing spam check results. 
Go to http://localhost:8063/admin/channels/spamcheckresult/
The page should load

fix spam check admin

---

channels/factories/models.py
channels/management/commands/reclassify_spam.py
channels/spam.py
channels/tasks.py
channels/tasks_test.py

closes https://github.com/mitodl/open-discussions/issues/3100
This pr adds a management command for reclassifying posts and comments incorrectly marked as spam or not marked as spam by akismet
Go to http://localhost:8063/admin/channels/spamcheckresult/
If you don't have a spam check result for a post and a comment create a post and comment with a non-moderator user to generate some
`docker-compose run web ./manage.py reclassify_spam --spam --post-id <object id of post> --comment-id <object id of comment>`
Should mark the SpamCheckResults as spam and hide the posts/comments in the discussions ui
`docker-compose run web ./manage.py reclassify_spam --ham --post-id <object id of post> --comment-id <object id of comment>`
Should mark the SpamCheckResults as not spam and make the post/comment …

add spam management commands

---

course_catalog/etl/podcast.py
test_html/test_podcast.rss

None
The podcast import scrip breaks for timestamps with abbreviated timezones (example GMT) instead of hour offset timezones. This fixes the issue
run `docker-compose run web ./manage.py backpopulate_podcast_data` verify that the episodes for MISTI Radio are imported

fix podcast date parsing

---

search/api.py
search/api_test.py

I need to do this for https://github.com/mitodl/hugo-course-publisher/issues/217
this adds the `department_name` field to 
I think just read the code and make sure it makes sense? not sure exactly how this could be tested manually. you could try using `/api/v0/search` and adding a `department_name` facet to your search I suppose.

add the department_name field to search aggregation transform

---

requirements.in
requirements.txt

Related to https://github.com/mitodl/hugo-course-publisher/issues/240
This PR updates open-discussions with the latest version of ocw-data-parser which includes properties related to publishing / retirement dates.
Spin up open and parse an OCW course.  It should install 0.12.0 during setup and master JSON should now include:
- `last_published_to_production`
- `last_unpublishing_date`
- `retirement_date`

update ocw-data-parser to 0.12.0

---

search/api.py
search/api_test.py

this is required for a PR on OCW (https://github.com/mitodl/hugo-course-publisher/pull/267) to work
this is to address this issue: https://github.com/mitodl/hugo-course-publisher/issues/216
In order to add the level facet I needed to add a transform for its aggregation into `search/api.py`
You could check out the hugo-course-publisher PR linked above and ensure that it works with this change.

add support for the level facet to course search

---

docker-compose.yml
open_discussions/celery.py

closes https://github.com/mitodl/open-discussions/issues/3188
Adds a separate queue for spam tasks. Since the spam queue should have fewer items, spam tasks will run sooner.
add
```
import time
@app.task
def sleep(seconds):
time.sleep(seconds)
```
to `course_catalog/tasks.py`
Fill the celery queues with default priority tasks by running
```
for i in range(0,1000):
sleep.delay(15)
```
from the shell
`docker-compose run web ./manage.py reclassify_spam --spam --post-id <object id of post>`
should still run fairly quickly and if you create a post or comment with a non-moderator account a `check_post_for_spam` job should run to create a SpamCheckResult record
All other celery tasks will be queued behind the sleep jobs and will not run until those finish

speparate celery queue for spam checks

---

.github/workflows/ci.yml

none
this just adds back a call to `npm run fmt:check` to our JS CI check, which was I think unintentionally omitted from https://github.com/mitodl/open-discussions/pull/3204
The build should pass.

add fmt:check to CI

---

cassettes/channels.views.comments_test.test_get_removed_comment[None-404].json
cassettes/channels.views.comments_test.test_get_removed_comment[comment_writer-200].json
cassettes/channels.views.comments_test.test_get_removed_comment[staff_user-200].json
cassettes/channels.views.comments_test.test_get_removed_comment[user-404].json
channels/views/comments.py
channels/views/comments_test.py
factory_data/channels.views.comments_test.test_get_removed_comment[None-404].json
factory_data/channels.views.comments_test.test_get_removed_comment[comment_writer-200].json
factory_data/channels.views.comments_test.test_get_removed_comment[staff_user-200].json
factory_data/channels.views.comments_test.test_get_removed_comment[user-404].json

https://github.com/mitodl/open-discussions/issues/3087
This adds a server-side 404 page for removed comments for non-moderator users
Make a comment as a non-moderator user
Get the share url for the comment it should be something like `http://localhost:8063/c/public_channel/5/i-like-robotics/comment/3/`
Mark the comment as spam using 
`docker-compose run web ./manage.py reclassify_spam --spam --comment-id <object id of comment>`
Go to the comment url. You should be able to see the comment as a moderator but get a 404 as a non-mderator or anonymous user

404 for removed comments

---

course_catalog/management/commands/backpopulate_ocw_topics.py
course_catalog/tasks_test.py
course_catalog/utils.py
course_catalog/utils_test.py

Partially addresses https://github.com/mitodl/hugo-course-publisher/issues/308
- Imports level 3 OCW topics (specialities)
- Provides a backpopulate_ocw_topics command
Run `python manage.py backpopulate_ocw_topics` - it should work and additional topics should be created, show up in the topic facet, and be searchable (the number depends on how many OCW courses you've imported).

Import OCW level 3 topics (specialities)

---

search/serializers.py
search/serializers_test.py

Closes #3211 
Excludes unpublished runs from the ES course serialiser and lists published runs in reverse order by best_start_date
Import the following runs:
```python
get_ocw_courses(course_prefixes=[
"PROD/18/18.01/Fall_2003/18-01-single-variable-calculus-fall-2003/", 
"PROD/18/18.01/Fall_2005/18-01-single-variable-calculus-fall-2005/", 
"PROD/18/18.01/Fall_2006/18-01-single-variable-calculus-fall-2006/"
], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
Search for class "18.01" and check the response JSON.  It should include 2 runs, with 2006 before 2005.

ES Course serializer should exclude unpublished runs and list them in order

---

channels/api.py
channels/api_test.py

Closes #3119 
If the reddit API function to determine if a user is a channel moderator raises a Forbidden error, then return False.
- Create a spam post in a private channel as user # 1 (contributor, not moderator)
- If it isn't auto classified as spam by akismet, manually spamify it with `docker-compose run web ./manage.py reclassify_spam --spam --post-id <post_id>`
- Log in as user # 2 (who should also be a contributor to the above channel).  Go to the URL for the spam post created in step 1.  You should get a 404 page.  On master you should get a 500 error.

Return False if reddit API is_moderator call raises a Forbidden error

---

static/scss/search.scss

none, but see https://github.com/mitodl/hugo-course-publisher/issues/337
(we have the same issue over here)
this just makes a small styling change to deal with a text overflow issue on longer filter names.
Normally the filters were display here aren't quite long enough to trigger the issue, but we're doing department name over in OCW and that is long enough. But I figured we should fix the styling here too so we're "future proofed"
To repro the issue you need to just edit the text node inside of the `.active-search-filter` to be long enough to trigger the problem. Then confirm checking out this branch fixes it (see screenshots below for reference).
before:
after:

fix styling of long search filters in course search

---

channels/tasks.py
channels/tasks_test.py

closes https://github.com/mitodl/open-discussions/issues/3199
Currently the reclassify spam management command breaks for moderator comments which do not have a SpamCheckResult. This fixes the issue
Create a comment and post with a moderator account
run
`docker-compose run web ./manage.py reclassify_spam --spam --comment-id <id>  --post-id <id>`
there should not be an error

fix reclassify spam for moderator comments

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/conftest.py
course_catalog/tasks_test.py

Closes #3263 
- Always uploads an OCW course's parsed JSON to S3 even if it is unpublished.  
Import the course, then check the parsed JSON file on S3 to make sure it has an unpublished date and the file was recently modified.
```python
import json
sync_ocw_courses(
course_prefixes=["PROD/18/18.783/Spring_2015/18-783-elliptic-curves-spring-2015/"], 
upload_to_s3=True, 
force_overwrite=True, 
blocklist=[]
)
s3 = boto3.resource("s3").Bucket(settings.OCW_LEARNING_COURSE_BUCKET_NAME)
course_json = s3.Object('18-783-elliptic-curves-spring-2015/18-783-elliptic-curves-spring-2015_parsed.json')
print(course_json.last_modified)
print(json.loads(course_json.get()['Body'].read())["last_unpublishing_date"])
```

Upload OCW course JSON to S3 regardless of publish state

---

course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py

Closes #3261 
Sets a course to unpublished if it has no runs.
- On master, run `manage.py backpopulate_edx_data` (use the same `EDX_` env variables as on RC).
- Wait for all indexing tasks to finish (will take longer than the command above).
- Search courses for 'app inventor'.  There will be 2 results for "MIT App Inventor Certification Exam – Level 1".  One of them will work correctly (clicking it will show details in the drawer), the other will not (blank drawer, 404 API call).
- Switch to this branch, run `manage.py backpopulate_edx_data` again, and wait for indexing to finish.
- Repeat the search.  There should be only 1 "MIT App Inventor Certification Exam – Level 1" result and its link should work correctly.

Do not publish courses without runs

---

docker-compose.yml
notifications/api.py
notifications/api_test.py
notifications/tasks.py
notifications/tasks_test.py
open_discussions/celery.py

closes https://github.com/mitodl/open-discussions/issues/3203
Digest email generation is time consuming and not time sensitive.  This pr moves digest email tasks to a separate queue to prevent them from blocking other tasks. Notification emails letting users know there are comments on their posts and letting moderators know about new posts in their channels are time sensitive and will remain in the default queue.
Verify the new queue exists with
```
from open_discussions.celery import app
app.control.inspect().active_queues()
```
Verify that both digest and comment notification still works by making a some posts and comments, verifying that your user gets both daily digests and comment notifications, then running
```
send_daily_frontpage_digests() …
```

separate digest email queue

---

widgets/serializers/rss_test.py

Closes #3275 
Sorts test entries by reverse date, as the tested function does, to make sure they are always in the same order.
Run `pytest -vv widgets/serializers/rss_test.py` at least a few times, it should always pass.

Ensure test_url_widget_serialize sorts entries by reverse date

---

course_catalog/api.py

Closes #3281
Passes the S3 bucket name to OCWDataParser on initialization, to prevent an error from being logged (and perhaps prevent incorrect values in the parsed JSON).
Run `sync_ocw_courses(course_prefixes=["PROD/2/2.04A/Spring_2013/2-04a-systems-and-controls-spring-2013/"], blocklist=[], upload_to_s3=True, force_overwrite=True)`
There should not be a "Please set your s3 bucket name" error logged.

Pass bucket name to ocw parser on initialization

---

app.json
open_discussions/settings.py
requirements.in
requirements.txt

closes https://github.com/mitodl/open-discussions/issues/3284
This pr allow approving CORS domains using regex to allow ocw-www domains to be allowed to make cross origin http requests
Run xpro. From the javascript console run
`fetch("http://localhost:8063/api/v0/frontpage/", { credentials: "include" })`
confirm that you get a CORS error.
Add `CORS_ALLOWED_ORIGINS=['http://localhost:8053']` to your open-discussions env file. Run the command again. The fetch should succeed.
Remove `CORS_ALLOWED_ORIGINS` from your env file.  Set `CORS_ALLOWED_ORIGIN_REGEXES=['^http://localhost:\d+$']`.
Run the fetch command again. It should succeed again

update django-cors-headers to allow regex

---

static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js

Closes #3286 
Ignores quotes, case, and special characters when comparing a search suggestion to the search text.
Perform a search included a search term in quotes with a colon in between words, that only returns 1 result, like "Fiction: Great Books!" On https://discussions-rc.odl.mit.edu/learn/search?q=%22Fiction%3A%20Great%20Books%21%22 the suggested search term "fiction great books" will display.  On this branch, the suggested search term should not display.  Change the search term to "Fiction: Great Boos!" and it should display.

Don't show suggestion if it is effectively the same as search text

---

notifications/management/commands/populate_notification_settings.py

None
The populate_notification_settings job currently ignores the --inactive flag
Update a user to be inactive and delete notifications for that user
```
from notifications.models import NotificationSettings
user = User.objects.last()
profile = User.profile
profile.last_active_on = None
profile.save()
NotificationSettings.objects.filter(user=user).delete()
```
Run
`docker-compose run web ./manage.py populate_notification_settings`
Notification settings should not be created for the user
Run
`docker-compose run web ./manage.py populate_notification_settings --inactive`
Now notification settings should not be created for the user

fix inactive setting

---

mail/templates/moderator_posts/body.html

closes https://github.com/mitodl/open-discussions/issues/3301
This pr removes the "read more" button from moderator post notifications.
Make sure moderator notifications are turned on for a channel you moderate and for your user. Make a post in the channel.
Run 
```
send_unsent_email_notifications()
```
you should get a notification. It should not have a button with "Read More" on it

remove read more button

---

requirements.in
requirements.txt

None
This PR updates the `ocw-data-parser` dependency from 0.20.0 to 0.23.0.
Run `sync_ocw_course` manually and make sure the course is properly synced with no errors.

update ocw-data-parser to 0.23.0

---

channels/serializers/posts.py
channels/tasks.py
channels/tasks_test.py

closes https://github.com/mitodl/open-discussions/issues/3308
This pr updates moderator notifications to only send notifications for posts that are not automatically marked as spam and removed by akismet.
Log in as a moderator. Make a post in the channel you moderate.
Log in as a non-moderator. Make one spammy post and one non-spammy post. Verify that your posts are marked  as intended at http://localhost:8063/admin/channels/spamcheckresult/. Copy spam/non-spam comment text from production if needed.
Run
```
send_unsent_email_notifications()
```
from the command line. You should receive notifications for posts made by the moderator and posts that are not marked as spam. You should not receive a notification for posts marked as spam automatically

do not send moderator notifications for posts marked as spam automatically

---

static/js/hoc/withChannelTracker.js
static/js/hoc/withChannelTracker_test.js

https://github.com/mitodl/open-discussions/issues/3316
This fixes a bug in https://github.com/mitodl/open-discussions/pull/3319 which causes an error if a channel has a tracking id
set but GA_G_TRACKING_ID is not set.
Remove GA_G_TRACKING_ID from your env file. 
Set a tracking id for a channel from the channel admin. 
Click around the channel. Verify that you do not see errors.

check for gtag in channel tracker

---

channels/serializers/channels.py
channels/serializers/channels_test.py
static/js/components/admin/EditChannelBasicForm.js
static/js/components/admin/EditChannelBasicForm_test.js
static/js/flow/discussionTypes.js
static/js/lib/api/channels.js
static/js/lib/channels.js
static/js/lib/channels_test.js
static/js/lib/validation.js
static/js/lib/validation_test.js
static/js/pages/admin/EditChannelBasicPage.js
static/js/pages/admin/EditChannelBasicPage_test.js

closes https://github.com/mitodl/open-discussions/issues/3305
(Required)
This pr adds the ga_tracking_id property to the channel management ui
Go to http://localhost:8063/manage/c/edit/<channel>/basic/
Ensure that you can set and unset the tag

expose ga tracking id to moderators

---

requirements.in
requirements.txt

upgrades ocw-data-parser to 0.25
Run `sync_ocw_courses(course_prefixes=["PROD/6/6.730/Spring_2003/6-730-physics-for-solid-state-applications-spring-2003/"], blocklist=[], force_overwrite=True, upload_to_s3=False)`
It should complete without errors

update ocw data parser

---

course_catalog/api.py

Fixes a typo I spotted in `log.exception` where a second set of paratheses made the argument a tuple.
Probably not worthwhile to test manually

Fix typo in logging exception

---

static/js/util/withTracker.js
static/js/util/withTracker_test.js

https://github.com/mitodl/open-discussions/issues/3335
The automatic pageview metric in gtag.js (implemented in https://github.com/mitodl/open-discussions/pull/3319) doesn't pick up everything we consider a page view. This pr turns off automatic pageviews and sends manual pageviews instead.
Set GA_G_TRACKING_ID in your .env file. You can use G-B0EKT59MQF for testing
Go to the network tab in developer tools and search for the tag.
You should see calls to https://www.google-analytics.com with the tag when you click around the app.

manually send gtag events

---

requirements.in
requirements.txt

upgrades ocw-data-parser to 0.26.0
Run 
```
from course_catalog.api import sync_ocw_courses
sync_ocw_courses(course_prefixes=["PROD/6/6.730/Spring_2003/6-730-physics-for-solid-state-applications-spring-2003/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
It should complete without errors

ocw-data-parser version 0.26.0

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/factories.py
pytest.ini
search/api.py
search/api_test.py
search/constants.py
search/indexing_api.py
search/serializers.py
search/serializers_test.py
test_requirements.txt

- Closes #3343 
- Fixes backpopulate_ocw_files command
Adds "resource_type" to OCW `ContentFile` docs in Elasticsearch, based on the course section that the ContentFile falls under (if any), and includes it in aggregations.
- Reindex (`python manage.py recreate_index`)
- Most importantly, nothing should break afterward in open.
- Spin up `ocw-www` with `SEARCH_API_URL` pointing to your local open instance and try resource search, it should still work, and hits should include `resource_type` (though many of them might have a value of "Other")
- Using postman or curl send a POST request to http://localhost:8063/api/v0/search/ with this body:
```
{
"from": 0,
"size": 10,
"post_filter": {
"bool": {
"must": [
{
"bool": {
"should": [
{
"term": {
"object_type.keyword": "resourcefile"
}
}
]
}
}, …
```

Add resource_type to ES index for ContentFiles

---

channels/serializers/channels.py
channels/serializers/channels_test.py

closes https://github.com/mitodl/open-discussions/issues/3349
This pr fixes the bug preventing updates to channel appearance when ga_tracking_id is null for the channel
Set ga_tracking_id to null for a channel. Go to `http://localhost:8063/manage/c/edit/<channel>/appearance/`. Verify that you can make changes.

fix channel settings

---

static/js/hoc/withChannelTracker.js
static/js/hoc/withChannelTracker_test.js

closes https://github.com/mitodl/open-discussions/issues/3362
This pr fixes sentry error which occurs if window.gtag is loaded but window.google_tracking_manager isn't. I'm not 100% sure why users get in that state. 
Set GA_G_TRACKING_ID in your .env file. You can use G-B0EKT59MQF for testing.
Set the GA tracking id for a channel from the admin (http://localhost:8063/admin/channels/). You can use G-BEM7JCXH4D for testing.
Click to the test channel to make sure both the channel tracker and the main tracker are loaded. You should see calls to https://www.google-analytics.com/g/collect with  G-BEM7JCXH4D when you look at the channel's views but not other views.
run `delete window.google_tracking_manager` from the console
Click around the site, both in the channel and outside it. You should …

fix google_tag_manager sentry error

---

search/api.py
search/api_test.py
static/js/components/LearningResourceDrawer.js
static/js/components/LearningResourceDrawer_test.js

none 
This pr fixes https://sentry.io/organizations/mit-office-of-digital-learning/issues/2311151869/?project=216201&query=is%3Aunresolved
`api.search.find_similar_resources()` errors when a ContentFile object is returned as a similar resource.
Also, the podcasts page makes calls to fetch similar resources even though that data is never used.
This fixes both those issues.
Go to http://localhost:8063/podcasts/ 
Click on a podcast. Then click on a podcast episode.
You shouldn't see any network calls to `similar/`
Go to http://localhost:8063/learn/search
Click on a few learning resources
You shouldn't see network calls to `similar/` error

fix similar items error

---

course_catalog/api_test.py
course_catalog/etl/loaders.py
course_catalog/serializers.py

closes https://github.com/mitodl/open-discussions/issues/3375
This pr stores the correct salutation in the full_name field for OCW course instructors
Run
```
sync_ocw_courses(course_prefixes=["PROD/8/8.01/Fall_2016/8-01sc-classical-mechanics-fall-2016/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
Go to \learn\search and find the "Classical Mechanics" course on OCW
Verify that the instructors field is
```
Prof. Deepto Chakrabarty, Dr. Peter Dourmashkin, Prof. Anna Frebel, Dr. Michelle Tomasik, Prof. Vladan Vuletic
```

fix salutation

---

package.json
static/js/pages/CourseSearchPage.js
static/js/pages/CourseSearchPage_test.js
yarn.lock

Related to https://github.com/mitodl/ocw-www/issues/94
Related to https://github.com/mitodl/course-search-utils/pull/17
Previously the search page would replace the URL when a change was made, like a facet being clicked or text being entered in a textbox. This changes that behavior to push changed onto the browser stack, and correctly handle back and forwards buttons in the browser
This is waiting on merging https://github.com/mitodl/course-search-utils/pull/17 first. Once that merges and is published, this PR will point at the updated version.
See instructions in https://github.com/mitodl/course-search-utils/pull/17

Add to history stack on changes to search UI, and support back button

---

course_catalog/serializers.py

While testing 
https://github.com/mitodl/open-discussions/pull/3378
on rc I saw this error:
https://sentry.io/organizations/mit-office-of-digital-learning/issues/2386847463/events/0271f9f2dbf24ecb8b241733c62f5575/?project=216201
This occurs when the is one OCW course with the salutation set and another where it is not set for the same instructor 
```
CourseInstructor.objects.get_or_create(first_name='Emma', last_name='Teng', full_name=None)
CourseInstructor.objects.get_or_create(first_name='Emma', last_name='Teng', full_name='Prof. Emma Teng')
sync_ocw_courses(course_prefixes=["PROD/21G/21G.030/Fall_2005/21g-030-east-asian-cultures-from-zen-to-pop-fall-2005/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
``` …

fix to salutation pr

---

open_discussions/celery.py

None
The current code queuing frontpage notifications in a separate celery queue was broken. This fixes the issue.
add
```
import time
@app.task
def sleep(seconds):
time.sleep(seconds)
```
to `course_catalog/tasks.py`
Fill the celery queues with default priority tasks by running
```
for i in range(0,1000):
sleep.delay(15)
```
from the shell run
```
send_daily_frontpage_digests.delay()
send_unsent_email_notifications()
```
You should receive a notification email before the sleep tasks finish running
You may need to delete some EmailNotifiation objects if you run this multiple times

fix to digest email task queue

---

package.json
yarn.lock

none, fixing an issue from #3407
downgrade react-dotdotdot to 1.2.3, because the newer version doesn't work.
If you look at search on RC you'll see that the labels on facets aren't showing up, like this:
You should see the same thing locally on the main branch. If you check this out it should fix it.

downgrade the react-dotdotdot package

---

Procfile
app.json

None.  
Celery workers on 2x machines run out of memory. This sets the max concurrency on the celery worker to 4 instead of 8. extra_worker, which is currently running on a larger machine is not affected.
I don't think it's possible to test this locally. I will test the PR thoroughly  once it's on RC

set celery worker concurrency

---

.github/workflows/ci.yml

N/A
Updates github action ci.yml to allow codecov to fail softly.
Github actions should succeed, especially if the codecov upload fails.

Allow codecov upload to fail

---

requirements.in
requirements.txt

Related to https://github.com/mitodl/ocw-data-parser/issues/141
Upgrades ocw-data-parser to include a change which adds support for archived versions
Rebuild the docker container. In a Django shell run:
from course_catalog.api import sync_ocw_courses
course_prefixes = [f"PROD/1/1.011/Spring_{year}/1-011-project-evaluation-spring-{year}/" for year in [2003, 2005, 2011]]
sync_ocw_courses(course_prefixes=course_prefixes, blocklist=[], force_overwrite=True, upload_to_s3=False)
course = Course.objects.get(url__endswith="1-011-project-evaluation-spring-2011")
run = course.runs.first()
print(run.raw_json["is_update_of"])
You should see `['62c63b2702affad73ae56cec96eeb2bc']`

Upgrade ocw-data-parser for archived versions

---

course_catalog/api.py
course_catalog/management/commands/backpopulate_ocw_data.py
course_catalog/tasks.py

Fixes #3449 
Adds a `--course` argument to backpopulate only courses which match the prefix string. This is meant to make it easier for developers to backpopulate only specific courses that they are working on, to avoid the hours-long process of backpopulating the whole catalog.
- Run `./manage.py backpopulate_ocw_data --course 6-890-algorithmic --overwrite --skip-s3`. It should take about 5 minutes.
- In a shell, find the `LearningResourceRun` for that course via `Course.objects.get(url__contains='6-890-algorithmic').runs.first()`. The `updated_on` value should be close to the current date and time.

Add course argument to filter backpopulate_ocw_data

---

course_catalog/api.py
course_catalog/api_test.py

https://github.com/mitodl/open-discussions/issues/3464
Since course images are stored on S3, running `backpopulate_ocw_data` with upload_to_s3=False currently clears course thumbnails. We want to keep existing image_src data if a course already exists in our database and `backpopulate_ocw_data` is run with upload_to_s3=False
Run
```
sync_ocw_courses(course_prefixes=["PROD/6/6.901/Fall_2005/6-901-inventions-and-patents-fall-2005/"], blocklist=[], force_overwrite=True, upload_to_s3=True)
sync_ocw_courses(course_prefixes=["PROD/6/6.901/Fall_2005/6-901-inventions-and-patents-fall-2005/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
Verify that
```
Course.objects.order_by('updated_on').last().image_src
```
is …

dont overwrite image_src when upload_to_s3=False

---

course_catalog/api.py
course_catalog/api_test.py
course_catalog/management/commands/backpopulate_ocw_data.py
course_catalog/tasks.py
course_catalog/tasks_test.py
course_catalog/views.py
course_catalog/views_test.py

https://github.com/mitodl/open-discussions/issues/3460
This PR makes ocw backpopulate jobs resilient to worker shut downs by setting `acks_late=True` and passing a `start_timestamp` to the task avoid re-importing the same courses after a restart
Run
```
docker-compose run web ./manage.py backpopulate_ocw_data --course 6-890-algorithmic --overwrite
```
The job should succeed and
```
Course.objects.get(url__contains='6-890-algorithmic').runs.first().updated_on
```
should be updated to today
Run
```
from datetime import datetime, timedelta
run = Course.objects.get(url__contains='6-890-algorithmic').runs.first()
new_updated_on = run.updated_on + timedelta(days=10)
LearningResourceRun.objects.filter(pk=run.pk).update(updated_on=new_updated_on)
```
Run 
``` …
```

make ocw backpopulate restartable

---

course_catalog/views.py
course_catalog/views_test.py

none
https://github.com/mitodl/open-discussions/pull/3465/files introduced a bug in the ocw webhook. This fixes it
Set OCW_WEBHOOK_KEY to something in your .env file
Using postman or similar post to 
`localhost:8063/api/v0/ocw_webhook/?webhook_key=key`
with body
```
{
"Records": [
{
"s3": {
"object": {
"key": "PROD/2/2.611/Fall_2006/2-611-marine-power-and-propulsion-fall-2006/0/1.json"
}
}
}
]
}
```
You should get a 200 response.
Since `force_overwrite=False` on the webhook task, it won't actually update the course since the course didn't change on s3. 
You can temporarily set `force_overwrite=True` in line 405 in `course_catalog/views.py` and push to the webhook again. Then updated_on for the course should be updated.

fix ocw webhook

---

course_catalog/api.py
course_catalog/management/commands/backpopulate_ocw_data.py
course_catalog/tasks.py
course_catalog/tasks_test.py
requirements.in
requirements.txt

Closes #3500 
Adds a `--force-s3` option to the `backpopulate_ocw_data` command which will parse/upload JSON to S3 for OCW courses even if they have been previously been imported from OCW Studio.  It should not make any changes to the database or search index for the courses.
- Run `docker-compose build` to get the latest version of ocw-data-parser
- Find an OCW course that has already been imported from OCW Studio (`ocw_next_course=True`) or import one if you don't have any (via `backpopulate_ocw_next_data` command).  For example, `18-06-linear-algebra-spring-2010`
- Run `manage.py backpopulate_ocw_data --overwrite --force-s3 --course-url-substring 18-06-linear-algebra-spring-2010`
- When it's done, run this in a shell and verify that it has the following keys: metadata_contributor_list, …

Option to force S3 uploads of OCW data via ocw-data-parser

---

course_catalog/etl/loaders.py
course_catalog/etl/ocw_next.py
course_catalog/etl/ocw_next_test.py
search/indexing_api.py
search/indexing_api_test.py
test_json/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/resources/3play_file/data.json

closes https://github.com/mitodl/open-discussions/issues/3507
This pr fixes some issues with the resource search
Run docker-compose run web ./manage.py backpopulate_ocw_next_data  --course-url-substring 14-01-principles-of-microeconomics-fall-2018 --overwrite
In ocw-hugo-themes set 
SEARCH_API_URL=http://localhost:8063/api/v0/search/
and run `npm run start:www`
In the resource search search for "Lecture 23: Market Failures I: Externalities" 
Verify that you see a video result
Verify that the (non-working) link goes to http://localhost:3000/courses/14-01-principles-of-microeconomics-fall-2018/resources/lec-23-market-failures-i/

content file fixes

---

requirements.in
requirements.txt

This reverts commit 72ac837fd5ee89f8dabee42646f54f0012d757ba.
This  dependabot commit breaks login and celery jobs. I am reverting it so rc is working again

Revert "Bump celery from 4.3.0 to 5.2.2"

---

static/js/lib/search.js
static/js/lib/search_test.js
static/js/lib/util.js
static/js/lib/util_test.js

Closes #3521 
Replaces 'fancy' double quotes (`“”`) with normal double quotes (`""`) in search text.
These two searches should return the same results:
http://localhost:8063/learn/search?q=%E2%80%9Cmechanical%20engineers%E2%80%9D
http://localhost:8063/learn/search?q=%22mechanical%20engineers%22
and the result count should be lower than for this search without any double quotes:
http://localhost:8063/learn/search?q=mechanical%20engineers
Also repeat the first two with `mechical enginer`  as the text inside quotes. They should return no results and suggest `"mechanical engineers"` with quotes.

Recognize fancy double quotes for phrase search

---

course_catalog/etl/ocw_next.py
course_catalog/etl/ocw_next_test.py
test_json/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/resources/video/data.json

https://github.com/mitodl/open-discussions/issues/3511
This PR populates video thumbnails in resource search
Set
OCW_NEXT_LIVE_BUCKET=ocw-content-live-qa
Run `docker-compose run web ./manage.py backpopulate_ocw_next_data --course-url-substring 14-01-principles-of-microeconomics-fall-2018 --overwrite`
Run ocw-hugo-themes search locally with SEARCH_API_URL=http://localhost:8063/api/v0/search/
Search for "microeconomics" in the the resource search. Verify that the videos coming from course 14.01 have thumbnails

fix video thumbnails in search

---

course_catalog/api_test.py
course_catalog/etl/loaders.py
course_catalog/serializers.py
course_catalog/utils.py
course_catalog/utils_test.py
test_json/test_instructors_data.json

Closes https://github.com/mitodl/open-discussions/issues/3524
- Adds a new util: `parse_instructors` in `course catalog` which parses instructors.
- Updates `serializers` in `course catalog` to use this newly added util
- Adds a test to verify that this util works as expected.
- Setup open-discussions locally.
- Checkout to this branch
- run `manage.py backpopulate_ocw_next_data ... ` for any course which has instructors with first, middle, and last names.
- Verify that full name includes first, middle, and last name.

fix: fetching and storing instructor's full name

---

course_catalog/management/commands/backpopulate_ocw_data.py

N/A
Fixes the command when no list of sites is specified
Run without `--course-url-substring`

Fix backpopulate_ocw_data command without site list

---

course_catalog/api_test.py
course_catalog/serializers.py
course_catalog/serializers_test.py
search/api.py
search/api_test.py

closes https://github.com/mitodl/open-discussions/issues/3550
This pr updates open-discussions to use the department field to populate OCW next departments.
Run
```
docker-compose run web ./manage.py backpopulate_ocw_next_data  --course-url-substring 21w-755-writing-and-reading-short-stories-spring-2012 --overwrite
```
Run ocw-hugo themes www locally with SEARCH_API_URL=http://localhost:8063/api/v0/search/
Verify that when you filter for Comparative Media Studies/Writing course 21w-755-writing-and-reading-short-stories-spring-2012 is shown in the search

fix department import

---

course_catalog/views.py
course_catalog/views_test.py

Closes #3561 
Modifies the `WebhookOCWNextView` code to remove unpublished OCW-Next courses from the search index.
- Find the `run_id` an existing OCW-Next course run in your local instance, import one if necessary.
- Run `curl -X POST -d  '{"webhook_key": "<settings.OCW_NEXT_SEARCH_WEBHOOK_KEY>","unpublished": true,"site_uid": "<run_id>","version": "live"}'
- Verify that the run's `Course.published` value is `False` and the course  no longer shows up in search results.
Related to https://github.com/mitodl/ocw-studio/issues/1164 and its linked RFC

Remove unpublished OCW courses from search index

---

frontends/infinite-corridor/package.json
frontends/infinite-corridor/webpack_if_prod.sh
frontends/open-discussions/package.json
frontends/open-discussions/webpack_if_prod.sh
scripts/run-django-dev.sh

Followup to #3593 
Goal is to fix the deploy error here: https://github.com/mitodl/open-discussions/runs/7094209264?check_suite_focus=true#step:3:35012
This fixes the package.json postinstall script for open-discussions. Previously,
- the script only ran if node_env was not dev
- it referenced an incorrect yarn workspace name
Now it runs in prod and dev and does not reference the workspace at all. Running in dev seems OK since it only runs on install anyway.
The reason this slipped through review / my testing is: the build error was only visible if you were installing with node_env was set to something non-empty and not development. I believe in my testing I probably installed in dev mode, then ran the build script directly.
Delete node modules and run `docker compose run --rm watch yarn …

fix yarn postinstall script

---

package.json

Should fix deploy failure on heroku.
Heroku was building the frontend at least twice, and the final build was post devDependency pruning, and it was failing since  `@swc/core` had been pruned.
This PR moves all js `devDependencies` to `dependencies`...  `open-discussions` already had this, but I previously moved some shared dependencies (though, apparently, not very many) to root dev deps.  So, this restores the "everything in dependencies" status quo.
We should deploy it to heroku :/ 
Here's an excerpt from the heroku logs https://dashboard.heroku.com/apps/odl-open-discussions-rc/activity/builds/90f6e1bb-68bb-4328-a650-233d88d7ccc6 :
```
-----> Installing dependencies
Running 'yarn install' with yarn.lock
...
-----> Build
Running build (yarn)
...
➤ YN0000: [open-discussions]: webpack …
```

Fix deploy...no devdeps, only dependencies

---

Dockerfile
frontends/open-discussions/src/components/ContentToolbar.js
frontends/open-discussions/src/components/ContentToolbar_test.js
frontends/open-discussions/src/pages/App.js
frontends/open-discussions/src/pages/App_test.js

Closed #3631 
Changes the behavior of `course_ui_enabled` so that if `False`, it only hides the "Learn at MIT" section on the home page.  The `/learn` urls should always be accessible now regardless of the setting.
- Set `FEATURE_COURSE_UI=True` in your .env:
- Go to the discussions home page, there should be a `Learn at MIT` section on the right.
- Go to `../learn` and `../learn/search`, they should be reachable and have the expected content.
- Set `FEATURE_COURSE_UI=False` in your .env:
- Go to the discussions home page, there should not be a `Learn at MIT` section on the right.
- Go to `../learn` and `../learn/search`, they should be reachable and have the expected content.

Change behavior of course_ui_enabled flag

---

frontends/open-discussions/scss/search.scss
frontends/open-discussions/src/components/search/SearchFacetItem.js

None
Upgrading react-dotdotdot broke using react-dotdotdot to clamp to a single line. This is easily done with css instead
Go to learn/search. You should see facet labels and facet labels that are too long to fit on one line should be truncated. If you don't have any resources with facet labels which are too long to fit on one line, you can create some by running backpopulate_podcast_data

fix facet label

---

frontends/ol-util/src/hooks/useSearchParams.test.tsx
frontends/ol-util/src/hooks/useSearchParams.ts

None
Fixes a bug in `useSearchParams`
Tests should pass... `useSearchParams` was not causing the component to re-render when url search params changed. See the code comment.
I came across this bug in `useSearchParams` today... since it could possible affect @mbertrand @abeglova, I made a separate PR for it.

fix useSearchParams

---

frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.tsx
frontends/infinite-corridor/src/scss/combined.scss
frontends/infinite-corridor/src/scss/form.scss

#3672 
(Required)
Check that these all look reasonable:
The cause of this issue was CSS selectors targeting elements without classes, things like:
```css
input[type="text"] {
border: 1px solid red;
}
```
Which applies a border to all text inputs. This CSS also has reasonably height specificity (element + attribute type; that's more specific than a single class). The fact that this is more specific than a single class makes it reasonably likely to conflict with external libraries that do (some) styling on their own.
And it does, for example, this turns our MUI searchbar input into:
(note: MUI's input + adornments, e.g., buttons / icons, is not actually a single input field).
Anyway.... This PR makes the form-related CSS selectors apply only to fields with class `.form-field` 
**Before**: …

Fix styling conflicts: remove some classless tag selectors

---

frontends/ol-util/src/components/PageBanner.tsx

Fixes https://github.com/mitodl/open-discussions/issues/3675
This PR restores the original `z-index: -1` that was in `BannerContainer`, and updates `PageBanner` (which is only used in infinite-corridor) to achieve the goal of that change in a different way.
- check that channel titles are visible in open-discussions (not infinite-corridor)
- check that the searchbar at http://cac.od.odl.local:8063/learn has an "Explore" button below it
- Check that http://cac.od.odl.local:8063/infinite/fields/your_file_name has a title and that its text can be selected

Fix open discussions channel header issue

---

frontends/infinite-corridor/src/components/FieldMenu.test.tsx
frontends/infinite-corridor/src/components/FieldMenu.tsx
frontends/infinite-corridor/src/pages/FieldPageSkeleton.tsx
frontends/infinite-corridor/src/pages/urls.ts
frontends/infinite-corridor/src/scss/fieldpage.scss

Closes #3686 
Adds a dropdown menu in the field banner with a link to the edit page.
- Go to any field page logged in as a staff user.  There should be a gear icon on the right side of the banner.  Click on it and you should see a dropdown with an 'Edit Field' link.  Click on that and you should end up on the edit page for the field.
- Go to the same edit page logged in as a normal user or anonymously.  The gear icon should not be visible.
--------------

FieldChannel banner menu dropdown

---

search/views.py
search/views_test.py

Closes #3690 
Handles non-numerical status codes returned from Elasticsearch transport errors

Handle non-numerical status codes from elasticsearch

---

jest.config.ts
package.json
yarn.lock

None
This PR adds [`jest-watch-typeahead`](https://www.npmjs.com/package/jest-watch-typeahead), which adds live filtering to jest pattern matches. (See screenshots below). This is the package that Create React App uses to achieve the live filtering functionality.
1. Run `docker compose run --rm watch bash`
2. Run `yarn run jest --watch`
3. When the tests start running, press "p"
4. Start typing a filename
5. Matching files should show.. You can use arrow keys to select a particular file.
**Before:**
**After:**

Use jest-watch-typeahead to get live file matches in jest runner

---

package.json
scripts/run-watch-dev.sh

https://github.com/mitodl/open-discussions/issues/3691
This PR ensures that all projects have been build before the dev servers starts.
For context:
- `yarn run build` would build the all the local packages in using yarn's `--topological` flag, which says to build dependencies before dependents
- Previously, `yarn run start-dev` (which `docker compose up` uses) would start watching all the projects concurrently. Since they all start concurrently, sometimes `ol-search-ui` would try to build before its dependents and fail. 
Run `docker compose up`. Webpack should eventually finish building and you'll be able to visit infinite corridor.
You can use
```
docker compose logs --follow --no-log-prefix  --tail 1000 watch
``` 
to monitor the build with less clutter.

Remove transient errors in start-dev

---

course_catalog/etl/mitx_test.py
course_catalog/etl/openedx.py
course_catalog/etl/openedx_test.py
test_json/test_mitx_course.json

Closes #3731
For openedx-based courses (Open Learning Library, MITx courses on EdX) - set `published=False` if no runs for a course have a status of `published`.
- Copy `EDX_API_`  values from heroku prod to your local .env file. 
- Run `heroku run python manage.py backpopulate_edx_data`
- Using django admin or shell, check that the courses with `platform=mitx` have `published=True` if any of their runs in the `raw_json` have `status: "published"`; or `published=False` otherwise (example: course with `url=https://courses.edx.org/courses/MITx+8.370.3x_review/course/`)
(Optional)
Ideally it would be good to test with `backpopulate_oll_data` too for Open Learning Library courses, but the .env authorization values we have for those are no longer valid and it may take some time to get new …

Set published=False for openedx courses if no runs are published

---

course_catalog/etl/edx_shared.py
course_catalog/etl/edx_shared_test.py
course_catalog/etl/mitxonline.py
course_catalog/etl/mitxonline_test.py
course_catalog/etl/utils.py
course_catalog/etl/utils_test.py
course_catalog/etl/xpro.py
course_catalog/etl/xpro_test.py
course_catalog/tasks.py
course_catalog/tasks_test.py

Closes #3740
Refactors the course file syncing for xpro to use the same function as for mitxonline - expecting individual course tarballs on S3 instead of a bundled tarball containing all courses.
- Set `XPRO_` and `MITX_ONLINE_` .env values to the same as on RC.  Ditto for `AWS_`.
- Run `backpopulate_xpro_data` followed by `backpopulate_xpro_files`.  Both should succeed.  
- Check that you have some `LearningResourceRun` objects and `Course` objects with `platform=xpro`, as well as numerous `ContentFile` objects with `run__platform=xpro`
- Run `backpopulate_mitxonline_data` followed by `backpopulate_mitxonline_files`.  Both should succeed.
- Check that you have some `LearningResourceRun` objectss and `Course` objects with `platform=mitxonline`, as well as numerous `ContentFile` objects …

Refactor xpro course file sync

---

frontends/infinite-corridor/src/libs/mui.ts
frontends/infinite-corridor/src/scss/combined.scss
frontends/infinite-corridor/src/scss/mui.scss
frontends/infinite-corridor/src/scss/theme.scss
frontends/ol-search-ui/assets/learning-resource-card.scss
frontends/ol-search-ui/assets/learning-resource-drawer.scss
frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.tsx
frontends/ol-search-ui/src/components/LearningResourceCard.tsx
frontends/ol-search-ui/src/components/ShareTooltip.tsx
frontends/ol-search-ui/src/components/TruncatedText.tsx

#3754 
This PR gets updates some styling in the LearningResourceDrawer:
- get rid of some hard-coded colors so that the theme colors are used
- use mui buttons for "Share" and "Take Course"... nicer alignment
- use mui tooltip for share tooltip; improve some alignment within the share tooltip
- gets rid of some CSS that wasn't being used for anything. 
View the learning resource drawer and make sure it looks good and is using the navy color we use elsewhere.

More consistent drawer styling

---

requirements.in
requirements.txt

Fixes #3767 
Upgrades openssl
Copy settings for `MIT_WS_CERTIFICATE` and `MIT_WS_PRIVATE_KEY` from heroku RC into your .env, but as one-liners (I can send you the formatted values via keybase).
Run the following, you should not get an ssl exception:
```python
from moira_lists.moira_api import *
get_moira_client()
```

Fix moira by updating openssl

---

course_catalog/etl/loaders_test.py
search/task_helpers.py
search/task_helpers_test.py

Closes #3815 
Uses bulk delete on all of a course run's content files instead of individual deletes (for the search index)
Removes the function to delete individual content files from the search index (no longer called from anywhere)
If you don't have any xpro courses locally, run both the following:
```
manage.py backpopulate_xpro_date
manage.py backpopulate_xpro_files
```
The last one may take a while.
If you have xpro courses but no content files, run them in reverse order.
`backpopulate_xpro_data` should finish within a couple minutes either way.
Also try this to mimic removing a recently unpublished course from the search index:
```python
from course_catalog.models import Course
from search.task_helpers import delete_course
course = …
```

Always bulk delete content files from search index

---

course_catalog/management/commands/backpopulate_edx_files.py
course_catalog/management/commands/backpopulate_mitxonline_files.py
course_catalog/management/commands/backpopulate_ocw_files.py
course_catalog/management/commands/backpopulate_xpro_files.py

Closes #3820 
Adds `type=int,` to the optional `chunk_size` argument specification and sets the default to the same as defined in settings.
Run any or all of the modied mgmt commands, with and without a `--chunk-size` parameter.  They should all start without errors (you don't need to wait for them to finish), assuming all the required .env settings are configured with the same values as on RC: 
```
XPRO_LEARNING_COURSE_ACCESS_KEY=
XPRO_LEARNING_COURSE_SECRET_ACCESS_KEY=
XPRO_LEARNING_COURSE_BUCKET_NAME=
XPRO_CATALOG_API_URL=https://xpro.mit.edu/api/programs/
XPRO_COURSES_API_URL=https://xpro.mit.edu/api/courses/
OCW_CONTENT_ACCESS_KEY=
OCW_CONTENT_SECRET_ACCESS_KEY=
OCW_CONTENT_BUCKET_NAME=
OCW_LEARNING_COURSE_BUCKET_NAME=
MITX_ONLINE_BASE_URL=https://mitxonline.mit.edu/ …
```

Fix mgmt commands for importing content files

---

.github/workflows/ci.yml
package.json

Should help with #3691 
Post install is a script yarn runs automatically after install. I believe we do not need this and it is contributing to our overbuilding.
- We don't need it in dev because run-watch-dev.sh runs build.
- I believe we don't need it on Heroku because the buildpack runs "build" directly if found. (https://github.com/heroku/heroku-buildpack-nodejs/blob/5917461b195feea3b67571f39bfdcdf2c0e5c25d/lib/dependencies.sh#L108)
This really needs to be tested on Heroku. But you could check locally that:
1. `docker compose up` builds the app.
On `docker compose up`, we build too often:
1. Once after `yarn install` if there have been changes since your last install
2. Twice with `run-watch-dev.sh`:
1. Once at the start,
2. then again when entering watch mode
This should eliminate …

Remove yarn postinstall script

---

course_catalog/constants.py
course_catalog/etl/utils_test.py

Closes #3840
Adds additional file types that should be sent to tika for text extraction
-Set the following to the same values as RC in your .env file (along with AWS creds):
```
MITX_ONLINE_BASE_URL
MITX_ONLINE_COURSES_API_URL
MITX_ONLINE_PROGRAMS_API_URL
MITX_ONLINE_LEARNING_COURSE_BUCKET_NAME
```
- Run the following command:
```
manage.py recreate_index --all   # if you don't already have a search index
manage.py backpopulate_mitxonline_data
```
- Run the following in a shell:
```
from course_catalog.etl.edx_shared import sync_edx_course_files
from django.conf import settings
from course_catalog.models import Course
course_id = Course.objects.get(course_id="course-v1:MITxT+10.50.CH02x").id
sync_edx_course_files(settings.MITX_ONLINE_LEARNING_COURSE_BUCKET_NAME, "mitxonline", [course_id]) …
```

Add more valid text file types

---

frontends/ol-search-ui/src/components/LearningResourceCard.tsx
frontends/ol-search-ui/src/util.tsx
frontends/open-discussions/src/components/LearningResourceCard.js
frontends/open-discussions/src/components/LearningResourceCard_test.js
frontends/open-discussions/src/lib/learning_resources.js
frontends/open-discussions/src/lib/learning_resources_test.js

closes [3842](https://github.com/mitodl/open-discussions/issues/3842)
Swaps both the ol-search-ui and open-discussions front end repos off using best_start_date and onto start_date as best_start_date is often enrollment date and a mismatch... and misnomer.
search for courses in open-discussions/learn/search and compare against the database to find preferably courses with mismatched best_start_date and start_date - I would recommend:
- 1 that is currently running with past dates
- 1 that is currently running with future dates
- 1 that is currently running only
- 1 that ran in the past without future dates
- 1 that ran in the past but has future dates
- 1 that runs in the future only
The selected "best run" should be the one expected which would be:
- Currently running (today's date is …

Learn search results list dates are different than default drawer details dates

---

course_catalog/etl/edx_shared.py
course_catalog/etl/utils.py
course_catalog/etl/utils_test.py
search/tasks.py
search/tasks_test.py

Closes #3860
- Uses boto's `Bucket.download_file()` function to save edx archives to a temporary file, instead of reading the entire file into memory before saving to disk.
- Uses `yield` to return file content one by one instead of all at once in a single list
- Fixes the omission of mitx and mitxonline from file content index recreation
- Places a try-catch block around the parsing of "verticals" content via `XBundle`.  A handful of mitxonline tar archives raise an exception here due to "external entities" in an html file, that was preventing the rest of the archive from being processed.
- Set these to the same as production in your .env file:
```
MITX_ONLINE_BASE_URL
MITX_ONLINE_COURSES_API_URL
MITX_ONLINE_PROGRAMS_API_URL
MITX_ONLINE_LEARNING_COURSE_BUCKET_NAME
```
- Delete any …

More efficient download and processing of edx content archives

---

frontends/open-discussions/src/components/LearningResourceCard_test.js
frontends/open-discussions/src/factories/learning_resources.js
frontends/open-discussions/src/lib/constants.js
frontends/open-discussions/src/lib/learning_resources.js

#3863 
~This PR changes the date format on learning resource cards to the same format we use most places—`MMMM D, YYYY`. Previously, the format had `DD` so single-digit days would display as `04`, etc. See screenshots.~
This PR updates the `DISPLAY_DATE_FORMAT` constant. **We were previously using this constant only in tests.** Now we use it also as the format for generating dates. 
View a learning resource card on `/learn` that has a date. It should look the same as it did before.

fix flaky test: use standard date format for cards

---

course_catalog/filters.py
course_catalog/filters_test.py
course_catalog/views.py
open_discussions/settings.py

updates https://github.com/mitodl/open-discussions/issues/3868 
- one more PR will work out the last 2 filters:  certificates and upcoming/new/featured
This adds a filterset to courses, as a start, which will allow the use of django-filters on the `/api/v0/course/` endpoint using kwargs for:
- `offered_by` (to satisfy the need to filter by "micromasters" courses as in the original issue) - the available values of which can be found in the constants [here](https://github.com/mitodl/open-discussions/blob/bc117402290d48930b70fbadf0068b966f8d85dd/course_catalog/constants.py#L7).
- audience (to satisfy the need to filter by professional courses) - this adds a filter method to filter down platform by professional or open offerings which align with the `PROFESSIONAL_COURSE_PLATFORMS` found in …

2 New API filters for new open - offered_by and audience

---

course_catalog/etl/edx_shared.py
course_catalog/etl/edx_shared_test.py
course_catalog/etl/loaders.py
course_catalog/etl/utils.py
course_catalog/etl/utils_test.py
course_catalog/etl/xpro.py
course_catalog/etl/xpro_test.py
course_catalog/tasks.py
course_catalog/tasks_test.py
fixtures/aws.py

Related to #3860 
Make some modest improvements to memory usage for edx content processing tasks (max docker memory usage is reduced by about 200 MB).
Run any or all the following.  If you monitor memory with docker stats, the celery memory usage should rarely go above 1 GB.  Not sure if that is enough to prevent dyno restarts on heroku though, that will need to be tested there.
```
manage.py backpopulate_mitxonline_files  # run backpopulate_mitxonline_data first to import courses if necessary
manage.py backpopulate_xpro_files  # run backpopulate_xpro_data first to import courses if necessary
manage.py backpopulate_edx_files  # run backpopulate_edx_data first to import courses if necessary
```

More improvements in memory usage for edx content archive processing

---

Procfile

Related to #3860 
Increases concurrency for the `extra_worker_performance` celery worker from the default (2, == # CPU's) to 4, because there seems to be a backlog building on RC after switching to this dyno type.
Once it is on RC, the celery redis queue size should start going down more quickly.
```python
import os
import redis
from urllib.parse import urlparse
url = urlparse(os.environ.get("REDISCLOUD_URL"))
r = redis.Redis(host=url.hostname, port=url.port, password=url.password)
r.llen("default")
```

Set concurrency=4 (2x CPU) for the celery extra_worker_performance dyno

---

frontends/open-discussions/src/components/CompactPostDisplay.js
frontends/open-discussions/src/components/CompactPostDisplay_test.js
frontends/open-discussions/src/pages/PostPage.js

closes https://github.com/mitodl/open-discussions/issues/3824
This removes the comment count from post and front pages since the number is inaccurate due to spam removed and deleted comments
Open those pages and be sure the comment count is gone and the styling isn't completely broken.
[local open](http://od.odl.local:8063/)
The issue gives context - there is a fix, but it would likely cause load issues at scale. For now, we're removing the comment count until reddit is removed.

Remove comment count from discussions

---

course_catalog/etl/mitxonline.py
course_catalog/etl/openedx.py
course_catalog/etl/xpro.py

closes https://github.com/mitodl/open-discussions/issues/3915
Changes over from strptime to dateutil.parse to make the dates that we're grabbing from external sources less rigid in case of another change
run backpopulate management commands
Run them once before to see them fail. I will mention that edx commands are currently disallowed due to API error from us testing it being broken.
If you have existing data, make sure you don't see any doubling of courses or runs.
found while reviewing https://github.com/mitodl/open-discussions/pull/3899/files

Modify date parsing to be less rigid

---

.secrets.baseline
Procfile
docker-compose.yml
open_discussions/celery.py
open_discussions/settings.py

Related to #3860 
Reduces the celery schedule of edx contenfile ingestion tasks from daily to weekly, and runs them in a separate queue, which is only processed by the performance worker or 2x workers.
Run the following, it should complete successfully:
```
manage.py backpopulate_edx_files
```
Edx course archives are saved to S3 every day with distinct daily keys, even if nothing changes.  Ideally, only courses with new/updated content should be archived to S3, and then subsequently processed by open-discussions.  For now, this PR reduces the frequency of those processing tasks.

Run edx content file tasks weekly in a separate queue

---

course_catalog/constants.py
course_catalog/etl/loaders.py
course_catalog/etl/loaders_test.py
course_catalog/etl/utils.py
course_catalog/etl/utils_test.py

Closes https://github.com/mitodl/open-discussions/issues/3927
Omits `ContentFile` handling (`load_content_files`) from the common `load_run` ETL function for edx courses, because that should be handled in a separate task.
Copy values for RC `MITX_ONLINE_*` settings into your .env
If you don't already have mitxonline courses/runs:
- Run `manage.py backpopulate_mitxonline_data`
If you don't already have  mitxonline published `ContentFiles`:
- Run `manage.py  backpopulate_mitxonline_files`
Once you do have published mitxonline courses, runs, and `ContentFiles`:
- Run `manage.py  backpopulate_mitxonline_data` again
You should still have published ContentFiles (`ContentFile.objects.filter(run__platform="mitxonline", published=True)`)

For edx platforms, do not handle content files as part of course ETL

---

notifications/notifiers/frontpage.py
notifications/notifiers/frontpage_test.py

closes #3876
This PR changes that podcast episode logic to use the `last_modified` datetime instead of `created_on`. `last_modfied` is set during import of the podcast data to the date of `pubDate` which should be a more accurate representation of podcast releases rather than using the date we import it, `created_on`. In the current implementation, the user gets a larger amount of podcast notifications than expected.
Run daily notification task without having run one prior, should pick up all episodes. Then, you can make some new podcast episodes, make some with modified date before that notification went out (so... that datetime - 1day) and some after that went out (that datetime + any amount of time). Rerun. Should only see the second set of podcast episodes in the notification.
Really, …

Podcast frontpage notifications

---

test_requirements.txt

None
This PR removes `codecov` pypi package, since it no longer exists https://pypi.org/project/codecov/.
Codecov is changing its github integration; the python package no longer exists. Our action works for now, but we probably need to update to the App at some point. (https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mitodl)
Check that CI passed and Codecov made a comment 📣

Remove discontinued codecov package

---

search/indexing_api.py
search/indexing_api_test.py

Closes https://github.com/mitodl/open-discussions/issues/3949
When calculating the length of a document for indexing, uses the `default=str` kwarg to force anything that can't be serialized into a string (like datetime objects) - this happens for some profiles who are channel members.
- Tests should pass
- If you remove the `default=str` option added to `json.dumps()` in this PR, the new test will fail.
- If you have users who are members of a discussion channel (requires reddit), running `manage.py recreate_index --profiles` should work on this branch (and fail on master).

Fix profile bulk indexing

---

docker-compose.yml
requirements.in
requirements.txt

Updates https://github.com/mitodl/open-discussions/issues/3494
This PR upgrades our local client and service to 6.8.2 in preparation for the upgrade to ES 7.
Run test suite and go through to use the course catalog and post endpoints to search using postman or tool of your choice. 
Rerun indices using the management commands (I would backpopulate data & files and then recreate indices for at least one of our sets of data). 
Make sure `/learn/search` and post pages (when posts exist) work.
Prod service is already 6.8

Upgrade Elasticsearch to 6.8.2

---

frontends/infinite-corridor/src/App.tsx
frontends/infinite-corridor/src/components/LearningResourceCard.spec.tsx
frontends/infinite-corridor/src/components/LearningResourceCard.tsx
frontends/infinite-corridor/src/pages/user-lists/AddToListDialog.test.tsx
frontends/infinite-corridor/src/pages/user-lists/AddToListDialog.tsx
frontends/infinite-corridor/src/test-utils/index.tsx
package.json
yarn.lock

#3938 
This PR adds [`@ebay/nice-modal-react`](https://github.com/eBay/nice-modal-react) (see below) and uses it to manage the "Add to list" dialog. This fixes #3938 
1. Go to any list page http://od.odl.local:8063/infinite/lists/LIST_ID or favorites page `http://cac.od.odl.local:8063/infinite/lists/345` 
2. Click bookmark on any list item. Remove it from the current list. Modal should stay open. If you re-add it to the list, you should see it appear in the background (if your list is short enough).
**tldr:** I am proposing to use a new library, [`@ebay/nice-modal-react`](https://github.com/eBay/nice-modal-react), to help manage modals, especially modals that can be opened from several places in the app. It's small, simple and has no dependencies. It seems reasonably maintained. …

Use single modal for "Add to list..." -> fix premature close

---

frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.test.tsx
frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.tsx
frontends/ol-search-ui/src/util.test.ts
frontends/ol-search-ui/src/util.tsx
frontends/open-discussions/src/components/ExpandedLearningResourceDisplay.js
frontends/open-discussions/src/components/ExpandedLearningResourceDisplay_test.js
frontends/open-discussions/src/lib/util.js
package.json
yarn.lock

#3957 *A course clearly in spanish displaying "English" as its language, because the course did not specify a language and "English" was our default.*
This PR changes our Learning Resource displays (card, drawer) to not show "English" as the default course language. If a run has no language specified, then no language row is displayed in course info section.
1. **no language specified**:  At http://od.odl.local:8063/infinite or http://od.odl.local:8063/infinite/search, click on a card title. Most resources have no language specified, so clicking any of them should be fine.
- In network tab, check the API response for the resource details. In "runs"  property, check that no language is specified.
- Check that no language is displayed in the learning resource drawer
2. **Language is …

Do not display "English" as default language on resources

---

frontends/infinite-corridor/src/example-request-mocks.test.ts
frontends/infinite-corridor/src/test-utils/mockAxios.ts

None directly; this PR fixes a test that broke when I started work on #3981 
This PR fixes how `setMockResponse` works with promises.
CI tests should pass.
We often make mock API requests in our UI tests. We occasionally make assertions about the UI while the request is pending— the time between request & response. One such test is:
https://github.com/mitodl/open-discussions/blob/84e5ba5ed9af4552014a38de39e7670ff6ebab83/frontends/infinite-corridor/src/pages/user-lists/ItemsListing.test.tsx#L161
In these scenarios, we need to be able to set a mock response **and** control when the response resolves. 
While working on #3981, the aforementioned test broke. The reason turned out to be that in "manual resolution" scenarios, `setMockResponse` was responding too early. I do not entirely …

improve setMockResponse manual response resolution

---

frontends/infinite-corridor/package.json
frontends/infinite-corridor/src/api/learning-resources/search.ts
frontends/ol-search-ui/package.json
frontends/open-discussions/package.json
frontends/open-discussions/src/lib/api/api.js
frontends/open-discussions/src/lib/api/api_test.js
frontends/open-discussions/src/pages/CourseSearchPage.js
frontends/open-discussions/src/pages/CourseSearchPage_test.js
frontends/open-discussions/src/pages/SearchPage.js
frontends/open-discussions/src/pages/SearchPage_test.js
yarn.lock

This should be tested with https://github.com/mitodl/course-search-utils/pull/52
Once that PR is merges I will update this pr to point to course-search-utils on npm and not the branch
closes https://github.com/mitodl/open-discussions/issues/3964
This pr updates course-search-utils so that both the selected types and the types that should be shown in the aggregation are passed to buildSearchQuery 
Run https://github.com/mitodl/open-discussions/pull/3987/files#diff-b95387fcdedc9cb7b3c27edce0e5e71aeecf6b46f42278b7e4c61f05c313796b verify that the resource type facet on both learn search and infinites search now work the same as other facets and you can select more than one resource type
Verify that open discussions channel search still works. The dropdown to select "profile" "comment" or …

fix resource type facet

---

search/indexing_api.py
search/indexing_api_test.py
search/tasks.py
search/tasks_test.py

Closes #3978 
- Retries switching indices if any request errors occur while doing so (typically because the indices are being snapshotted)
- Deleted orphaned indices & aliases if the reindex fails
- On the master branch, modify `search.tasks.index_programs` to always raise an exception:
```python
try:
raise Exception("oops")
except (RetryException, Ignore):
...same as before
except:
...same as before
```
- Run `manage.py recreate_index --programs` 4 or 5 times.  It should fail each time.
- In a shell, run the following, there should be multiple indices for `program` returned, one with a reindexing alias.
```python
from search.indexing_api import *
get_conn().indices.get_alias(index="*")
```
- Switch to this branch and redo all the above (but you only have to run `recreate_index …

Delete orphaned indices after a failed reindex

---

renovate.json

https://github.com/mitodl/open-discussions/issues/4050
This fixes a typo introduced in #4034 
Check that this branch passes with renovate validation with `npx --package renovate renovate-config-validator`:
```
git checkout master
git pull
npx --package renovate renovate-config-validator
git checkout cc/fix-renovate
npx --package renovate renovate-config-validator
```

fix renovate configuration typo

---

.github/workflows/ci.yml

#4020 
This PR updates our github actions to resolve some [deprecation warnings](https://github.com/mitodl/open-discussions/actions/runs/5134607216) we have been getting.
- Observe that the tests are running and passing on CI, both JS and Python
- Observe that the cache is used... See the "pip install" and "yarn install" steps.
**NOTE:** The caches will only be used on the *second* run of github actions one this PR. From [About caching workflow dependencies](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#about-caching-workflow-dependencies):
> Workflow runs can restore caches created in either the current branch or the default branch (usually main)
Since the caching is different for this branch vs master, the first run of actions did not hit …

Resolve Github Action Deprecation Warnings

---

docker-compose.yml

updates https://github.com/mitodl/open-discussions/issues/3494
This PR changes the local docker-compose and ci files to use OpenSearch rather than Elasticsearch to match production once Mike updates the service on prod.
Pull local, `docker compose build` - this will not be a migration or upgrade to your current container, but rather will build a new one. Once that is done, make sure you can populate and index data and files.
You CAN do a local export and import to protect your data if you would like to preserve it, but this is not necessary to test. 
This is the last (local) step in the migration off of Elasticsearch.

OpenSeach Local Service

---

frontends/open-discussions/package.json

None
This PR re-alphabetizes `frontends/open-discussions/package.json`.
**Question:** Why is this necessary?
**Answer:** Currently, whenever `docker compose up` or install JS dependencies, you'll notice an edit to `frontends/open-discussions/package.json` even though you didn't touch it.
**Question:** Why did this happen?
**Answer:** Renovate quirk:
1. Whenever you `yarn install` (e.g., on docker compose up) or `yarn add <package-name>`, yarn alphabetizes the package.sjon file.
2. Recently, renovate replaced dependency `babel-eslint` with `@babel/eslint-parser` (the newer version is a package scoped to babel org).
3. I'm not entirely sure how renovate goes about editing files, but it did not re-alphabetize the package.json dependencies. 
As long as CI passes, don't bother.

re-alphabetize open-discussions/package.json

---

docker-compose.yml

Closes #4155
Updates the tika entrypoint to the correct jar version in docker-compose.yml
- Run `docker-compose up`, check the log for tika entries, you should not see any errors about the tika jar file not being found
- Run `docker-compose run --rm web python manage.py backpopulate_mitxonline_files` (assuming you have previously run `backpopulate_mitxonline_data` and have appropriate `MITXONLINE_` settings in your .env) - tika should parse the content without errors.
Bad renovate, bad

Update docker-compose entrypoint for tika to point to the correct version

---

renovate.json

Related to #4150 
This PR groups CKEditor updates together. CKEditor packages should, in general, be updated together. (See https://ckeditor.com/docs/ckeditor5/latest/updating/guides/updating-ckeditor-5.html) 
CKEditor is not included in Renovate's default monorepo list: https://docs.renovatebot.com/presets-monorepo/
Validate the configuration change: `npx --package renovate renovate-config-validator`

Configure Renovate: Group CKEditor Updates

---

frontends/infinite-corridor/package.json
frontends/infinite-corridor/src/entry/root.tsx
yarn.lock

#4124 
This PR adds Sentry to new frontend pages.
1. In your `.env` file, set `SENTRY_DSN=https://005a98ba45c3472dbb4c12405d814557@o48788.ingest.sentry.io/216201` *It's not secret*
2. Add something like `<button type="button" onClick={()=>{throw new Error('oh no')}}>Break the site</button>` into `frontends/infinite-corridor/src/components/Header.tsx`. *Or anyway; but the button is easy to find in the header*.
3. Click the button.
4. Visit https://mit-office-of-digital-learning.sentry.io/issues/?environment=dev&project=216201&query=is%3Aunresolved&referrer=issue-list&sort=date&statsPeriod=1h and look for your error. *That's this project, sorted by date, for dev environment*.
5. Remove SENTRY_DSN from your .env file so as not to send unnecessary stuff to sentry.
**Note:** You may notice …

Add sentry to new frontend pages

---

infinite_example/views.py

Followup to #4160
This PR adds the `SETTINGS` values to needed by #4160 
1. In your `.env` file, set `SENTRY_DSN=https://005a98ba45c3472dbb4c12405d814557@o48788.ingest.sentry.io/216201` *It's not secret*
2. Add something like `<button type="button" onClick={()=>{throw new Error('oh no')}}>Break the site</button>` into `frontends/infinite-corridor/src/components/Header.tsx`. *Or anyway; but the button is easy to find in the header*.
3. Click the button.
4. Visit https://mit-office-of-digital-learning.sentry.io/issues/?environment=dev&project=216201&query=is%3Aunresolved&referrer=issue-list&sort=date&statsPeriod=1h and look for your error. *That's this project, sorted by date, for dev environment*.
5. Remove SENTRY_DSN from your .env file so as not to send unnecessary stuff to sentry.

expose sentry env vars

---

frontends/open-discussions/package.json
frontends/open-discussions/src/components/IntroCard.js
frontends/open-discussions/src/components/IntroCard_test.js
frontends/open-discussions/src/components/LoginTooltip.js
frontends/open-discussions/src/components/LoginTooltip_test.js
frontends/open-discussions/src/components/UserMenu.js
frontends/open-discussions/src/components/UserMenu_test.js

#3781 
This PR removes the signup options from the user flow in Open Discussions to mitigate spam.
As a logged out user, make sure that you can not find a signup link. Should still be able to go to /signup by typing it in or clicking a link. Also, make sure the UI still looks ok.

Remove signup options from the UI

---

frontends/open-discussions/src/pages/auth/LoginPage.js
frontends/open-discussions/src/pages/auth/LoginPage_test.js

#3781; a followup to #4196  
Removes signup link from login page.
1. Visit `/login`. There should be no link to the signup page.

remove signup link from login page

---

app.json
authentication/backends/ol_open_id_connect.py
open_discussions/settings.py
poetry.lock
pyproject.toml

https://github.com/mitodl/open-discussions/issues/4225
Adds OpenID Connect functionality to Open Discussions which allows for authenticating users via Keycloak.
You will need a Keycloak account configured for https://sso-qa.odl.mit.edu/realms/olapps .  You should be able to create your account by visiting https://sso-qa.odl.mit.edu/admin/olapps/console/#/ .
1. Add the following to your .env file
```
SOCIAL_AUTH_OL_OIDC_OIDC_ENDPOINT=https://sso-qa.odl.mit.edu/realms/olapps
OIDC_ENDPOINT=https://sso-qa.odl.mit.edu/realms/olapps
SOCIAL_AUTH_OL_OIDC_KEY=ol-open-discussions-local
SOCIAL_AUTH_OL_OIDC_SECRET=<REQUEST_FROM_PR_AUTHOR>
AUTHORIZATION_URL=https://sso-qa.odl.mit.edu/realms/olapps/protocol/openid-connect/auth
ACCESS_TOKEN_URL=https://sso-qa.odl.mit.edu/realms/olapps/protocol/openid-con …
```

4225: Keycloak OIDC integration

---

authentication/urls.py
authentication/views.py
authentication/views_test.py
open_discussions/authentication.py
open_discussions/settings.py

https://github.com/mitodl/open-discussions/issues/4227
Adds a REST API endpoint (`http://od.odl.local:8063/api/v0/auth/<email>/` which can receive the GET and POST calls expected from the Keycloak plug-in described here: https://github.com/daniel-frak/keycloak-user-migration#prerequisites---rest-endpoints-in-the-legacy-system
Adds an override to `TokenAuthentication` in order to allow for the `Authorization` header to use "Bearer <YOUR_TOKEN_KEY>" instead of the OOTB "Token <YOUR_TOKEN_KEY>".
This has been tested with the plugin using the instructions provided here: https://github.com/daniel-frak/keycloak-user-migration#launching-and-configuring-the-example
1. Using this branch, run ./manage.py migrate in order to add the Auth Token models.
2. Create a token for your staff user by going …

4227: configure keycloak user migration plug in - REST API

---

frontends/open-discussions/src/pages/AccountSettingsPage.js
frontends/open-discussions/src/pages/AccountSettingsPage_test.js

https://github.com/mitodl/open-discussions/issues/4236
When `FEATURE_KEYCLOAK_ENABLED=True` is set as an environment variable, and a user is logged in, the http://od.odl.local:8063/settings/account page should always display that the user is logged in via MIT Open along with a link to the change password page in Keycloak.
1. Define the required Keycloak environment variables: https://github.com/mitodl/open-discussions#keycloak-configuration
2. Log in to Open Discussions using your Keycloak account.
3. Navigate to http://od.odl.local:8063/settings/account and verify that the page matches the screenshots below.
4. Click the "Change password" link.  Verify that you are redirected to the Keycloak account settings - signing in page.

Account settings page should always display forgot password option (Keycloak enabled)

---

course_catalog/views.py
course_catalog/views_test.py

https://github.com/mitodl/mit-open/issues/406 
Allows the OCW webhook to handle multiple sites at a time.  Produces more verbose/helpful output messages.
Set `OCW_NEXT_WEBHOOK_KEY=key` in your .env file
Try the following POST requests to `http://localhost:8063/api/v1/ocw_next_webhook/` , they should all work, kick off `get_ocw_next_courses` tasks, and return a helpful message in the response.
```
{
"webhook_key": "key",
"prefixes": 
"courses/esd-04j-frameworks-and-models-in-engineering-systems-engineering-system-design-spring-2007/, courses/18-657-mathematics-of-machine-learning-fall-2015/",
"version": "live"
}
```
```
{
"webhook_key": "key",
"prefixes":  [
"courses/esd-04j-frameworks-and-models-in-engineering-systems-engineering-system-design-spring-2007/", …
```

Handle multiple prefixes in ocw webhook endpoint

---

keycloak_user_export/management/commands/migrate_users_to_keycloak.py

https://github.com/mitodl/open-discussions/issues/4250 & https://github.com/mitodl/open-discussions/issues/4249.
Updates the Keycloak user migration script:
1. Removes functionality for migrating the user's password.
2. Adds functionality to specify a Keycloak group that any migrated users will be added to.
3. Adds functionality to only migrated Django user records with an specified associated social-auth provider, and no associated social-auth record for the "ol-apps" provider.
Updates Keycloak user migration script documentation: https://docs.google.com/document/d/17tJ-C2EwWoSpJWZKjuhMVgsqGtyPH0IN9KakXvSKU0M/edit?pli=1#heading=h.ds1pmqw8dg34
The following scenarios should be repeatable.
1. All Django user records without an associated social-auth record for the "ol-apps" provider have a …

4249: remove code from user migration script for importing credentials

---

frontends/open-discussions/scss/podcasts.scss
frontends/open-discussions/src/components/PodcastFooter.js

closes https://github.com/mitodl/hq/issues/3986
Adds a disclaimer saying that the views expressed in podcasts do not necessarily represent the view of MIT
Go to http://localhost:8063/podcasts/
Verify that the disclaimer is visible and looks good
Desktop
Mobile

add podcast disclaimer

---

Dockerfile
apt.txt
docker-compose.yml

N/A
This PR switches poetry over to installing project dependencies via virtualenv, which avoids a build error that was happening:
<details><summary>Stacktrace</summary>
```
9.668   ChefBuildError
9.668
9.668   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
9.668
9.668   Traceback (most recent call last):
9.668     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
9.668       main()
9.668     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
9.668       json_out['return_val'] = hook(**hook_input['kwargs'])
9.668                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9.668     File …
```

Switch poetry over to using virtualenvs

---

course_catalog/constants.py

https://github.com/mitodl/hq/issues/4855
This PR removes a RES (Supplemental Resources) constant from OCW departments.
This will be tested at RC.

Remove RES constant from OCW departments

---

authentication/management/commands/validate_user_emails.py

N/A
This fixes an issue with the error handling - `json()` was returning a `dict` which was throwing an error trying to print to stdout, `text` returns a plain string.
Set `MAILGUN_KEY` to a bad value and run `./manage.py validate_user_emails start`. You should see an error response like this printed:
```
401 Client Error: Unauthorized for url: https://api.mailgun.net/v4/address/validate/bulk/email-validation-1734013131-1
{"message":"Invalid private key"}
```
You may need to run `EmailValidation.objects.all().delete()` in a shell to reset validation state for your existing users.

Fix the error printing for failed requests

---

authentication/management/commands/validate_user_emails.py

N/A
The command was validating inactive accounts, all of which didn't have an email address to validate since we scrubbed spammer accoutns, so we should just skip those accounts because it can be a lot to process.
Disable a `User` Account, remove any `EmailValidation` records for them, and then verify no new `EmailValidation` record is created for them when you run `./manage.py. validate_user_emails start`

Only validate active user emails

---

keycloak_user_export/management/commands/migrate_users_to_keycloak.py

Fixes https://github.com/mitodl/hq/issues/6385
This fixes a regression I created when I [removed these attributes in a previous PR](https://github.com/mitodl/open-discussions/pull/4370/files#diff-3c7da601b7ac6ddc426c2a3ca6a64796843e7e09259b9bd786462fa7190dfe5aL156-L163) that are declared as optional in the API and we were passing what I would've thought were defaults but apparently without these Keycloak ignores `emailVerified` and `groups`. No idea why. 
Run the migration command and pass `--keycloak-group-path`. The imported user(s) should be marked as email verified and be part of the group.

Add back in keycloak user attributes

---

.github/workflows/ci.yml

https://github.com/mitodl/open-discussions/issues/4375
It looks like previous github action runs ran on ubuntu 22.04 which worked. `ubuntu-latest` now points to `ubuntu-24.04`, but this isn't reflected in https://github.com/actions/runner-images/?tab=readme-ov-file#available-images, so I'm not really sure what's going on there, something is possibly botched.
I tried multiple attempts at trying to get the most recent xmlsec/lxml versions to work but none of them did. This is blocking us so I'm simply going to pin to `ubuntu-22.04` as a short term solution.
- The first commit in this branch illustrates the failure.
- The code changes fix this and the tests should pass.

Fix error with xmlsec library
