- themes/api.py
- themes/api_test.py
Fixes #11 
Adds api and tests for posts
Verify this happy-path shell script behaves as expected and that tests pass:
```python
from themes.api import Api()
api = Api()
post1 = api.create_post('askhistorians', 'Post 1', text='Text1')
post2 = api.create_post('askhistorians', 'Post 1', url='https://google.com')
assert post1.selftext == 'Text1'
assert post2.url == 'https://google.com'
post1 = api.update_post(post1.id, 'Text2')
assert post1.selftext == 'Text2'
```
> Add posts api

- webpack_dev_server.sh
Fixes #22 
Updates `webpack_dev_server.sh` to use environment variables from `scripts/envs.sh`.
You should be able to start the webpack dev server. Everything should still work (I think this is just the checkbox and blue border at this point).
> Update webpack_dev_server.sh for changes from cookiecutter

- themes/api.py
- themes/api_test.py
None
Fixes asserts in `themes/api_test.py` and fixes a bug in `list_themes`. The `assert mock.called_once_with(...)` syntax isn't valid since `called_once_with` isn't a method, so it evaluates to a mock which is always true.
`list_themes` should return the right results for anonymous users
> Fixed API tests

- themes/api.py
- themes/api_test.py
Part of #29 
Adds `list_posts` to the `Api` class. It uses the `hot` algorithm to list posts in a channel
In a shell run `list(api.list_posts("subreddit"))` and verify that you see a list of posts
> Added list_posts to Api

- package.json
- scripts/test/js_test.sh
none
just adds tooling to run mocha in 'watch' mode, which re-runs the tests whenever a file is touched. very handy!
unfortunately mocha doesn't have the chops to figure out which files are relevant to re-run if a particular file is changed (we'd need to switch to a fancy, newer runner like AVA to get that) but this is still pretty nice :)
running tests in the normal way should still work, but you should also be able to do `npm run watch` instead of `npm run test`, and it should run the tests in watch mode.
> add a command for running JS tests in watch mode

- cassettes/channels.views_test.test_create_channel.json
- cassettes/channels.views_test.test_get_channel.json
- cassettes/channels.views_test.test_list_channels.json
- cassettes/channels.views_test.test_patch_channel.json
- channels/api.py
- channels/api_test.py
- channels/conftest.py
- channels/serializers.py
- channels/serializers_test.py
- channels/urls.py
- channels/urls_test.py
- channels/views.py
- channels/views_test.py
- open_discussions/settings.py
- open_discussions/urls.py
- requirements.in
- requirements.txt
Part of #29 
Implements rest API for channels
You can go to `/api/v0/channels/` and play around with it using the DRF HTML view. You should also be able to go to `/api/v0/channels/<subreddit>/` to view a particular channel or to patch it
> REST API for channels

- static/js/components/PostList.js
- static/js/components/PostList_test.js
- static/js/components/PostSummary.js
- static/js/components/PostSummary_test.js
- static/js/containers/ChannelPage.js
- static/js/containers/HomePage.js
- static/js/factories/posts.js
- static/js/factories/posts_test.js
- static/js/flow/discussionTypes.js
- static/js/reducers/frontpage.js
part of #15 
This adds, to the frontpage UI, a link for each post to the channel page for the channel on which the post originated.
Go to the homepage, you should see something like this:
on a subreddit page you should not see the link to the subreddit (just the author link).
> add frontpage subreddit links

- open_discussions/betamax_config.py
- requirements.in
- requirements.txt
None
Configures betamax to write pretty printed JSON for cassettes
Start `./manage.py shell` and run this code:
from open_discussions.recorder import record
user = User.objects.get(username='some username here')
with record('pretty_printed', user) as api:
list(api.list_channels())
The cassette created in `cassettes/` should have pretty printed JSON
> Human readable cassettes

- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/reducers/frontpage.js
- static/js/reducers/index_test.js
Part of #15 
Integrates the existing frontpage ui with the backend api
Be sure you are subscribed. You may need to:
```python
from channels.api import Api
user  = User.objects.get(username='you')
api = Api(user)
api.reddit.subreddit('micromasters').subscribe()
```
Go to http://localhost:8063/ and verify you see data.
> Integrate with frontpage api

- static/js/components/PostDisplay.js
- static/js/components/PostDisplay_test.js
none
this basically sets the title display in `PostDisplay` to do the right thing. basically, if it's a text post, it links to the detail view (`/channel/${channel}/${postID}`). if it's a URL post, it's an anchor tag with `target="_blank"` pointing to `post.url`.
If you're on any page that shows lists of posts, you should be able to click on the title to open a URL post or visit a text posts' detail view.
> add proper post title link

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/containers/PostPage.js
- static/js/factories/comments.js
- static/scss/comment.scss
- static/scss/layout.scss
part of #27 
this adds a very bare-bones display for showing the comments on a post
right now the comments reducer is not yet hooked up to the API, so every post will have a randomly generated comment tree. so you should be able to just navigate to a post and see a bunch of replies of varying depth. The first comment should always have two levels of replies.
> basic comment display

- static/js/containers/PostPage.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/reducers/comments.js
- static/js/reducers/index_test.js
part of #18 
This adds support for creating comments (replies to a post) and replies to comments. 
You could open up `PostPage.js` and add a line like `actions = window.actions`, and then try calling `actions.comments.post(postId, commentText, ?commentId)` to try things out.
> connect comments reducer to API

- app.json
- open_discussions/settings.py
None
- Removes `ALLOWED_HOSTS` which is always `['*']` in all cases
- Removes unused `ADWORDS_CONVERSION_ID`
- Adds `GA_TRACKING_ID`, `OPEN_DISCUSSIONS_REDDIT_CLIENT_ID`, `OPEN_DISCUSSIONS_REDDIT_SECRET`, `OPEN_DISCUSSIONS_SUPPORT_EMAIL` to `app.json`
- Marks a bunch of other environment variables as required in `app.json`
Deployment should work
> Updated app.json

- static/js/containers/CreatePostPage_test.js
- static/js/reducers/comments_test.js
- static/js/reducers/index_test.js
- static/js/util/integration_test_helper.js
N/A
Refactors `IntegrationTestHelper` to stub out all the API methods.
Test should pass
> Updated IntegrationTestHelper to mock all api functions

- static/js/containers/ChannelPage_test.js
N/A
Fixes a failing test due to random channel name collision
I was seeing about a 1% failure rate in master for this, so apply this patch locally and verify you see no failures:
```
diff --git i/static/js/containers/ChannelPage_test.js w/static/js/containers/ChannelPage_test.js
index df96b0b..dccfab6 100644
--- i/static/js/containers/ChannelPage_test.js
+++ w/static/js/containers/ChannelPage_test.js
@@ -40,10 +40,12 @@ describe("ChannelPage", () => {
assert.deepEqual(wrapper.find(PostList).props().posts, postList)
})
-  it("should handle missing data gracefully", async () => {
+  for (const x of new Array(1000)) {
+  it.only("should handle missing data gracefully", async () => {
let otherChannel = makeChannel()
otherChannel.name = …
```
> Fix a failing test due to random channel name collision

- flow-typed/npm/redux-asserts_v0.x.x.js
- static/js/actions/channel.js
- static/js/components/ChannelBreadcrumbs.js
- static/js/components/PostDisplay.js
- static/js/components/SubscriptionsSidebar.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/HomePage.js
- static/js/containers/HomePage_test.js
- static/js/factories/channels.js
- static/js/factories/posts.js
- static/js/flow/reduxTypes.js
- static/js/global_init.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/redux_rest.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/js/reducers/channels.js
- static/js/reducers/index_test.js
- static/js/reducers/subscribedChannels.js
- static/js/util/integration_test_helper.js
- static/scss/layout.scss
- static/scss/subscriptions.scss
Part of #83
Shows the list of channels the user is subscribed to
View the front page. You should see a new sidebar on the left with your channels. Click on a channel and you should be directed to the page for that channel. Press the back button then click on another channel. You should see the posts for that channel.
> Added UI to list channels

- package.json
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/HomePage.js
- static/js/containers/HomePage_test.js
- static/js/factories/channels.js
- static/js/factories/posts.js
- static/js/lib/api_test.js
- static/js/lib/redux_rest.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/js/reducers/subscribedChannels.js
- travis/js_tests.sh
none
runs `prettier-eslint` with the `--list-different` flag, which will basically error if there are any files that `prettier` _would_ change, if it were called. this means in order to get your code to pass CI you will have to call `npm run fmt`.
This should fail CI initially. then, after a review, I will introduce a commit that is just the result of calling `npm run fmt`, after that, it should pass CI.
> add prettier to things we check on CI

- package.json
- scripts/repl.js
none
Adds a `package.json` script (`repl`) which opens `node.js` with Ramda, Moment, chai/assert, Sanctuary, and Sinon required as globals. This makes it just a little easier to experiment with these libs in the repl.
There's a script (`scripts/repl`) where these are declared.
you can `npm run repl` and play with ramda n stuff.
> add an easy way to open a nodejs repl with common libraries required

- package.json
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/PostDisplay.js
- static/js/components/PostDisplay_test.js
- yarn.lock
this closes #105 
this adds the [react-markdown](https://github.com/rexxars/react-markdown) package and uses it to render comment and post text.
make a comment or text post containing some markdown stuff, make sure it works! you should be able to do fun stuff like this:
> render markdown posts and comments

- static/js/components/Loading.js
- static/js/components/Loading_test.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/PostPage.js
- static/js/lib/util.js
Fixes #102 
Updates `<Loading />`
- Exercise the channel and post pages and verify they load correctly including over a full page refresh.
- Verify the page doesn't flash when adding a comment to a post
I reimplemented `<Loading/>` as the HOC `withLoading`. This new design has a few benefits:
- The wrapped component is simpler and implements only a `render()` method instead of the previous design with both a `render()` and `renderContent()` implementation.
- The wrapped component now determines if it is loaded or not in its `mapStateToProps` implementation
Some design tradeoffs to achieve this:
- We need to pass two functions to `withLoading`: 
- `shouldUpdateRequirements`: this function is pass the previous and current props and returns true if the difference in values indicates the …
> Refactored loading component

- open_discussions/settings.py
- profiles/views.py
- profiles/views_test.py
Closes #113 
This adds staff user permissions as required for user 
- `curl -v localhost:8063/api/v0/users/` should fail with a 401
- Create a token for a non-staff user and `curl -H "Authorization: Token TOKEN" localhost:8063/api/v0/users/` should fail with a 403
- Create a token for a staff user and `curl -H "Authorization: Token TOKEN" localhost:8063/api/v0/users/` should succeed
> Added authorization and token authentication for staff API

- channels/views.py
- channels/views_test.py
- conftest.py
- open_discussions/permissions.py
- open_discussions/permissions_test.py
- open_discussions/settings.py
- open_discussions/urls.py
- profiles/views.py
- profiles/views_test.py
- requirements.in
- requirements.txt
Part of mitodl/micromasters#3479
Adds JWT authentication to APIs, requires a staff role for admin APIs
In a django shell (n.b. token is good for an hour):
```python
from rest_framework_jwt.settings import api_settings
jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
payload = jwt_payload_handler(user)
payload['roles'] = ['staff']
token = jwt_encode_handler(payload)
```
In a bash shell:
```bash
TOKEN=<PASTE TOKEN VALUE>
curl -H "Authorization: Bearer $TOKEN" localhost:8063/api/v0/users/
curl -H "Authorization: Bearer BAD" localhost:8063/api/v0/users/
curl localhost:8063/api/v0/users/
curl -H "Authorization: Bearer $TOKEN" localhost:8063/api/v0/channels/ -X POST -d '{"name":"testchan","title":"testchan","channel_type":"public", …
```
> Added JWT auth to API

- package.json
- static/js/components/Loading.js
- static/js/components/Loading_test.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/HomePage.js
- static/scss/layout.scss
- static/scss/loader.scss
- yarn.lock
part of #127 
this adds a spinner component to the `Loader` component that we have, so we show something a little nicer to look at than just the `Loading` text. I also added the `withLoading` HOC to the home page component, where it hadn't yet been added.
Visit a post page, a channel page, and the front page. you should see a spinner-ey thing there (when the requests are in flight) instead of some text that just says 'Loading'.
> add spinner to loader component

- static/js/components/CommentVoteForm.js
- static/js/components/PostDisplay.js
- static/js/components/PostDisplay_test.js
- static/js/containers/PostPage.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/scss/comment.scss
- static/scss/post.scss
part of #125 
this does everything except moving the 'reply' button, which is a little more complicated (so I'm putting it off for now).
- fixes the PostDisplay layout, so that it shows the voting buttons in the right place and doesn't show comments when on the post detail view page
- show the comment count on the post page in the gutter between the post and the first comment
- add the navigation sidebar to the post page
- some small CSS layout cleanups / tweaks, moving a few things that were manually positioned to use flexbox instead.
Just make sure everything looks good and is cleanly laid out, on a phone and on the desktop. We should be getting closer to the mocks for the post page. There should be no style regressions on the frontpage or the channel page display.
> post page tweaks

- static/js/components/PostList.js
- static/js/components/PostList_test.js
- static/scss/layout.scss
- static/scss/post-list.scss
closes #127 
This implements a little 'hey there's nothing here' placeholder if a `PostList` is handed an empty array (i.e. the channel is empty, the frontpage is empty, etc).
Create a fresh empty channel, or visit an existing channel which lacks any posts. you should see this:
On a 'populated' channel you should see the normal display of posts.
> empty post list display

- static/js/components/CreateCommentForm.js
- static/js/components/CreateCommentForm_test.js
Fixes #134 
Hides the cancel button for post reply and uses preventDefault so that clicking the link won't result in the `#` showing up in the URL
Go to the post detail page. You shouldn't see a cancel link for the post reply, just the submit button. Go to a comment and click 'Reply'. You should see 'Submit' and 'Cancel' buttons. Click the 'Cancel' button and it should close the box. Verify that the URL does not have a `#` at the end.
> Hide cancel button for post reply, and also use preventDefault

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CreateCommentForm.js
- static/js/components/CreateCommentForm_test.js
- static/js/containers/PostPage.js
- static/scss/comment.scss
- static/scss/post.scss
closes #125 
This makes the changes necessary to move the 'Reply' button to be next to the voting buttons for comments.
Replying to comments, posts, etc should work as normal.
> move reply button

- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/containers/Drawer.js
- static/js/hoc/withNavSidebar.js
- static/js/lib/url.js
- static/js/lib/url_test.js
Fixes #142
Uses the react-router URL parsing to get the channel name. The regex in the function didn't account for underscores which caused the link to be incomplete
Create a channel with an underscore in the name. Go to the channel page and click 'Submit a new post'. Verify that creating a new post works properly
> Use channelName parsed via react-router

- README.md
Fixes #144
Updates section 5b of the README to be consistent with the new JWT authentication.  The old instructions no longer work.
> Updated step 5b of Docker configuration in README

- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/containers/Drawer.js
- static/js/hoc/withNavSidebar.js
- static/js/lib/url.js
- static/js/lib/url_test.js
#147 
see the issue, this adds the 'create post' button back on mobile by reverting an earlier change which removed it.
If you open the application in chrome's mobile device mode you should be able to see and use a 'create post' button in the mobile side nav menu.
> fix mobile post submit

- cassettes/channels.views_test.test_add_contributor.json
- cassettes/channels.views_test.test_detail_contributor.json
- cassettes/channels.views_test.test_detail_contributor_error.json
- cassettes/channels.views_test.test_list_contributors.json
- cassettes/channels.views_test.test_remove_contributor.json
- cassettes/channels.views_test.test_remove_contributor_moderator.json
- channels/api.py
- channels/api_test.py
- channels/exceptions.py
- channels/serializers.py
- channels/serializers_test.py
- channels/urls.py
- channels/views.py
- channels/views_test.py
closes #132 
Adds a REST API to add and remove contributors in a channel
if you disable the `JwtIsStaffOrReadonlyPermission` in the views, you can use the django rest framework UI to perform the requests and you can go to `http://reddit.local/r/<channel_name>/about/contributors/` and verify that the action you perform via rest API correspond to what you see in the UI
> Added Rest APIs to add/remove contributors in a channel

- channels/api.py
- channels/api_test.py
- profiles/serializers.py
- profiles/serializers_test.py
- profiles/views_test.py
Fixes #155
Adds the user using the refresh token plugin when the user is created using the `/api/v0/users/` REST API
Create a user using `/api/v0/users/`, then go to reddit and verify that the user exists there (go to `/u/username`
> Add user on reddit when user is added via REST API

- open_discussions/views.py
- open_discussions/views_test.py
- static/js/flow/declarations.js
- static/js/lib/api.js
- static/js/lib/auth.js
- static/js/lib/auth_test.js
Fixes #153 
Fixes mitodl/micromasters#3479
Adds code to renew JWT session and redirect to MM if logged out
Follow configuration steps in mitodl/micromasters#3523 and verify in the chrome inspector that when your JWT token expires it queries MM for a new token at `/api/v0/discussion_token` and retries the failed API request(s).
Use this setting in MM  `.env` to lower your JWT lifespan to 30s:
```
OPEN_DISCUSSIONS_JWT_EXPIRES_DELTA=30
```
> Added JWT session renewal

- static/js/components/CreatePostForm.js
- static/js/containers/CreatePostPage_test.js
closes #151 
the cancel button in the create post form didn't have `e.preventDefault()`, so the form was issuing an unintentional POST.
go to the create post page, and click cancel. there shouldn't be any errors in the console, and it should instead just take you back to the subreddit. Also it's probably a good idea to confirm that you can reproduce the error (on `master`) by following the same steps.
note: I had trouble writing a regression test for this in enzyme, I think because of React's event system vs the browser one or something like that. Not sure exactly, but if the reviewer has ideas about strategies for that that would be :100:
> add preventDefault for cancel button on create post page

- static/js/Router.js
- static/js/components/ScrollToTop.js
- static/js/components/ScrollToTop_test.js
- static/js/entry/root.js
closes #157 
This fixes the scroll position behavior on react-router route changes to be, well, normal. The normal way that this should work is this:
1. when you click on an `<a>` tag you open the new page, scrolled to the top, regardless of whether you've visited it before
2. if you use the forward / backward buttons to navigate around the scroll position on any pages you visit should be preserved.
This adds a little component (called `ScrollToTop`) which wraps the whole app and gives us this behavior. Basically, we can check that the location has changed by checking that the `location` prop from the `withRouter` HOC is different, and we can look at `history.action` to figure out why it has changed. If the user clicked on a `<Link />` the `history.action` will be `'PUSH'`, so in this …
> fix scroll position on route change

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CreateCommentForm.js
- static/js/components/CreateCommentForm_test.js
- static/js/components/CreatePostForm.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/PostPage.js
- static/scss/form.scss
closes #150 
closes #175
this disables the 'submit' button on the create post form when the request is in-flight, and it also adds a `.disabled` class to the button so we can grey it out a little bit.
If you go to the create post form you should be able to create a post as normal. when you click the button it should get greyed out, and you should not be able to click multiple times and create duplicate posts.
> disable post submit while it is in progress

- static/js/components/CreateCommentForm.js
- static/js/components/CreatePostForm.js
- static/js/containers/CreatePostPage_test.js
- static/js/lib/util.js
- static/js/lib/util_test.js
closes #179 
It makes it so the user can't submit a post which doesn't have a title and either a text body or a URL.
Make sure you can't submit an empty post. So for a text post you shouldn't be able to submit until you have a title and a body, and for a URL post you shouldn't be able to submit until you have a title and a URL. Make sure you can submit posts normally otherwise.
> prevent submission of empty posts

- static/js/lib/auth.js
- static/js/lib/auth_test.js
Fixes #181
Changes behavior to redirect only on a 401 status code
Add a `raise Exception()` to the frontpage API to simulate an error case. Add another `raise Exception()` to the `discussions_token` function on Micromasters. Check out master on open-discussions and go to `/discussions/` on micromasters. You should see a redirect loop. Check out this PR and the loop should not happen anymore.
> Only redirect to auth on a 401 response

- open_discussions/envs.py
- open_discussions/envs_test.py
- open_discussions/settings.py
- requirements.in
- requirements.txt
none
this basically copy-pastes the stuff we do in MM to have a CORS whitelist. we need to have this because we want to make a request to OD from the MM frontend app. I also copied over the `get_list_of_str` thingy too.
Open up MM and do this in the console:
```js
fetch("http://localhost:8063/api/v0/frontpage/", { credentials: "include" })
```
confirm that you get a CORS error.
Then, add a line like this to your `.env` file:
```
OPEN_DISCUSSIONS_CORS_ORIGIN_WHITELIST=['localhost:8079']
```
(replacing with your URLs for OD and MM as needed). after making that change you should be able to issue an authenticated request for the frontpage (or any other API) from the MM frontend.
other stuff should be normal.
> add cors stuff

- static/js/components/CreatePostForm.js
- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/containers/App.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
closes #126 
this refactors some aspects of the create post page so that we can put a link to it on any page.
You should be able to see the 'create post' link on any page. If you click on it from the home page it should not have a subreddit pre-selected, and if you click on it from a subreddit it should have the right subreddit pre-selected.
You should be able to submit a post to a subreddit. You shouldn't be able to submit a post until you've selected a subreddit.
> refactor create post form

- repl.py
None
Add repl script which imports Django models before running Django shell
Run `docker-compose run web ./repl.py`, type `User` and verify that there's no error
> Add script to import models for Django shell

- cassettes/channels.views_test.test_add_contributor.json
- cassettes/channels.views_test.test_add_contributor_again.json
- cassettes/channels.views_test.test_add_moderator.json
- cassettes/channels.views_test.test_add_moderator_again.json
- cassettes/channels.views_test.test_add_subscriber.json
- cassettes/channels.views_test.test_add_subscriber_again.json
- cassettes/channels.views_test.test_add_subscriber_forbidden.json
- cassettes/channels.views_test.test_detail_subscriber.json
- cassettes/channels.views_test.test_detail_subscriber_missing.json
- cassettes/channels.views_test.test_remove_contributor.json
- cassettes/channels.views_test.test_remove_contributor_again.json
- cassettes/channels.views_test.test_remove_moderator_again.json
- cassettes/channels.views_test.test_remove_subscriber.json
- cassettes/channels.views_test.test_remove_subscriber_again.json
- channels/api.py
- channels/api_test.py
- channels/views.py
- channels/views_test.py
Fixes #187 
- Changes is_subscriber to look through the list of subscribed channels to see if a user is a subscriber. The channel info API will return 403 if the user is not a contributor so this is unreliable.
- Handles double adds and deletes for moderator, subscriber and contributor. The status code should be 201 for an add and a 204 for a delete.
Make a private channel and have a user who is not on the list of contributors for that channel. Go to `/api/v0/channels/<channel>/subscribers/<username>/` and verify that it returns a 404. A DELETE to that API should return a 204, though it may not make a change since this is inaccessable in the reddit API.
> Change is_subscriber to return correct result if the user is a subscriber but not a contributor to a private channel

- package.json
- static/js/containers/App.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/containers/admin/CreateChannelPage.js
- static/js/lib/title.js
- static/js/lib/title_test.js
- yarn.lock
#174 
this uses the [react-document-title](https://github.com/gaearon/react-document-title) lib to set `document.title` for the various pages in OD.
There should be a sensible title set on every page. In particular, they should correspond to what is laid out in the linked issue:
```
Home Page:
MIT Open Discussions
Create a channel:
Create a Channel | MIT Open Discussions
Submit a Post:
Submit a Post | MIT Open Discussions
Channel:
[Channel Name] | MIT Open Discussions
Post
[Post Title] | MIT Open Discussions
```
> set page title

- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
Fixes #223 
Uses `history.replace` to preserve the history stack
Open the create post page. Change the channel a few times. Click the cancel button and you should be back where you were before.
> Update URL in place instead of adding a new URL when new channel is selected

- channels/serializers.py
- channels/views.py
- channels/views_test.py
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/PostDisplay.js
- static/js/components/PostDisplay_test.js
- static/js/factories/comments.js
- static/js/factories/comments_test.js
- static/js/factories/posts.js
- static/js/factories/posts_test.js
- static/js/flow/discussionTypes.js
#188 
this adds the `.name` from the user's profile to the results returned by both the comment and post APIs, and makes the changes in the UI to display that information.
If you look at a post or a channel you should see names instead of usernames, same with comments on a post.
> add profile name to post and comment APIs

- open_discussions/settings.py
Related to https://github.com/mitodl/micromasters/pull/3591
Turns off `disable_existing_loggers` which allows celery exceptions to be displayed on the console
At the bottom of `open_discussions/celery.py` add:
@app.task
def faketask():
raise Exception("message")
Check out master, restart open-discussions. In a Django shell run `faketask.delay()` and verify that you do not see an exception in the console. You will see information about the task being executed but no exception message.
Check out this branch, restart open-discussions. In a Django shell run `faketask.delay)(` and verify that you do see the exception in the console now.
See this PR where the logging was originally added: https://github.com/mitodl/lore/pull/58
> Fix logging configuration

- static/js/components/CreateCommentForm.js
- static/js/components/CreateCommentForm_test.js
#212 
This fixes a little UI quirk, where upvoting a comment would prevent the user from submitting a new top-level comment or replying to an existing comment. This uses the same pattern we're using on the upvote / downvote buttons to get around that (using `this.state` to track whether that particular instance was clicked on or not).
If you upvote or downvote a comment the `submit` button for both post replies (top-level comments) and comment replies should not be grayed out. you should be able to submit a comment just after upvoting or downvoting something.
> submit button disable

- Dockerfile
- app.json
- docker-compose.yml
- travis-docker-compose.yml
- travis/Dockerfile-travis-web
Related to https://github.com/mitodl/cookiecutter-djangoapp/pull/92
Moves the `./manage.py collectstatic` command to docker-compose to match the cookiecutter and to allow validation of `settings.py` at runtime
> Move collectstatic into docker-compose to match cookiecutter

- channels/serializers.py
Related to https://github.com/mitodl/micromasters/issues/3581
Make `public_description` not required
Should be able to create a channel with empty description.
> Make public_description not required when creating a channel

- open_discussions/settings.py
- open_discussions/settings_test.py
- tox.ini
Related to https://github.com/mitodl/micromasters/issues/3599
Validates the presence of `MAILGUN_KEY` and `MAILGUN_URL` (currently unused)
N/A
> Add check for presence of mailgun variables

- static/scss/comment.scss
none
This makes the user avatars in the comments section smaller. It also makes the replies indentation bigger, that that replies align better with the parent comment above them.
(See that it looks correct and the css is valid)
> Decrease the size of avatars in comments

- static/js/components/CreatePostForm.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/flow/discussionTypes.js
- static/js/flow/formTypes.js
- static/js/lib/test_utils.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
- static/js/reducers/forms.js
- static/scss/_variables.scss
- static/scss/createPost.scss
- static/scss/form.scss
closes #251 
closes #243 
This makes the title input for a Post into a `<textarea />` (instead of `<input type="text" />`), and also writes some code for validation the form inputs on the post create page. I wrote some general, somewhat abstract validation code which should be useful for validating other things as well.
1. Go to the create post page.
2. try to submit an empty text post. it should show validation messages.
3. fill in the fields one at a time, and re-submit. the validation messages should go away, until it finally lets you submit the post when they are all resolved.
4. do the same for the URL post
5. also confirm that you can write a really long title for your post, and that if you do more than 300 character you get a validation message for that.
> add validation for create post, make title a textarea

- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/components/SubscriptionsList.js
- static/js/components/SubscriptionsList_test.js
- static/scss/_variables.scss
- static/scss/navigation.scss
closes #214 
this highlights the current channel in the navigation sidebar, following the mocks.
check that, for both the mobile sidenav and the desktop sidenav, the following are true:
- on the homepage no channel is highlighted
- navigating to a channel causes that channel to be highlighted
- changing channels switches which one is highlighted
and that it looks reasonable, etc
> highlight current channel in the navbar

- static/js/containers/Drawer.js
closes #295
this adds a little hacky thing (see the linked issue) which works around a bug with the MDC Drawer. Basically, the drawer component was blowing away all `onclick` handlers inside of it, so our react-router `<Link />` components we working as normal `<a>` tags and not as SPA links. This fixes that.
Check out master and confirm that the navigation links in the mobile navigation drawer are always causing full-page refreshes. Then check out this and confirm that they are SPA links, as they should be. In both cases the links in the desktop sidebar should be unaffected.
> fix a bug where the MDC drawer was obliterating onclick handlers

- static/js/components/PostDisplay.js
- static/js/components/PostDisplay_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/scss/post.scss
#270 
this adds a little display next to the title link for a URL post which just shows what domain the link is from.
if you look at the frontpage or a channel page with link posts you should see something like:
the same thing should show up if you look at the comments for the post.
> show link post domain after the link

- README.md
- docker-compose.yml
Prerequisite to #279, sister to mitodl/reddit-config#14
This PR fixes the `OPEN_DISCUSSIONS_REDDIT_CLIENT_ID` and `OPEN_DISCUSSIONS_REDDIT_SECRET` values. 
Clear the two keys above from your `.env`.
Test in tandem with the sibling PR, verify you can still make calls using `channels.api.Api` (one is sufficient since it tests both).
> Switched to static reddit OAuth for local

- static/js/components/CreateCommentForm.js
- static/js/components/CreateCommentForm_test.js
closes #237 
this sets the `autoFocus` prop on the textarea for replying to comments, so that we you click the 'reply' button the focus automatically goes into the text box (and you can compose your comment without having to click or tab into it first).
I also added an `onKeyDown` to the reply form, which listens for the ctrl-enter key combo and submits the form when you press that (for that power user life).
go to a post. the focus should not be automatically into the 'top level' reply box. click 'reply' to a comment, the focus should automatically go to that text box. in both a comment and a post reply you should be able to submit your comment by pressing ctrl+enter.
> set focus on comment reply things, add key combo to submit form

- static/js/components/CreatePostForm.js
closes #297
this just fixes the little placeholder text for the link post creation form
go to create a post, you should see `https://www.example.com` instead of `www.example.com`.
> add https to placeholder for create post form

- app.json
None
Marks AWS environment variables as not required. We do not use AWS in this app currently, these were just copied from the cookiecutter. We need to mark it not required so that the review apps can deploy
N/A
> Mark AWS environment variables as not required

- app.json
- package.json
- webpack.config.dev.js
- webpack.config.prod.js
- webpack.config.shared.js
- yarn.lock
Related to https://github.com/mitodl/micromasters/pull/3637
Splits off CSS for production instances into separate file. This lets the browser cache the CSS and load it in parallel to the JS
Go to PR build's page, verify that CSS loads correctly. You should also see no changes locally.
> Use ExtractTextPlugin to split CSS into separate file

- cassettes/channels.views_test.test_add_moderator_again.json
- channels/api.py
- channels/views_test.py
Fixes #290 
Fixes a race condition where the moderator was getting added twice in rapid succession and there was a difference in state between the if expression and the code to add the moderator. This changes it so that if reddit says the user already is a moderator the API returns a success.
Not sure if there's an easy way to test this except pushing it to CI and looking for sentry errors
> Handle ALREADY_MODERATOR error

- Procfile
- app.json
- docker-compose.yml
https://github.com/mitodl/cookiecutter-djangoapp/pull/103
Uses application log level for Celery
Currently no tasks do logging and the PR build is not properly set up anyway
> Use application log level for Celery

- channels/api.py
N/A
Makes everything go faster by having praw ignore the rate limiting headers coming back from reddit. It does so by monkey patching [this method](https://github.com/praw-dev/prawcore/blob/master/prawcore/rate_limit.py#L37-L44) in `prawcore` to be a no-op instead of sleeping.
Use the app, create a post, etc.
> Monkey patch prawcore's rate limit to not limit

- cassettes/channels.views_test.test_api_exception.json
- cassettes/channels.views_test.test_create_channel_already_exists.json
- cassettes/channels.views_test.test_create_comment_forbidden.json
- cassettes/channels.views_test.test_create_comment_not_found.json
- cassettes/channels.views_test.test_create_post_forbidden.json
- cassettes/channels.views_test.test_create_post_not_found.json
- cassettes/channels.views_test.test_delete_post.json
- cassettes/channels.views_test.test_get_channel_forbidden.json
- cassettes/channels.views_test.test_get_channel_not_found.json
- cassettes/channels.views_test.test_get_post_forbidden.json
- cassettes/channels.views_test.test_get_post_not_found.json
- cassettes/channels.views_test.test_list_comments_forbidden.json
- cassettes/channels.views_test.test_list_comments_not_found.json
- cassettes/channels.views_test.test_list_posts_forbidden.json
- cassettes/channels.views_test.test_list_posts_not_found.json
- cassettes/channels.views_test.test_patch_channel_forbidden.json
- cassettes/channels.views_test.test_patch_channel_not_found.json
- cassettes/channels.views_test.test_update_comment_forbidden.json
- cassettes/channels.views_test.test_update_post_forbidden.json
- cassettes/channels.views_test.test_update_post_not_found.json
- channels/conftest.py
- channels/exceptions.py
- channels/utils.py
- channels/views.py
- channels/views_test.py
- static/js/containers/PostPage_test.js
Fixes #319 
Converts PRAW exceptions to DRF exceptions so that we get the 403 or 404 responses. This PR will only handle this for the cases where we are relying on reddit to do these permission checks.
Open up the network tab in your browser and make sure these return these results:
- Go to `/channel/missing` and verify that the API errors are all 404s
- For a channel you are subscribed to go to `/channel/channel_name/missing/` and verify the API errors are 404s
- Create a private channel your user is not subscribed to. Go to `/channel/<channel_name>/` and verify the API errors are all 403s
There are many other cases which may not be worth testing manually, but in general you should never see a 500 error from an API call.
> Handle Forbidden exception

- .gitattributes
- cassettes/channels.views_test.test_get_channel.json
- cassettes/channels.views_test.test_list_channels.json
- channels/factories.py
- channels/models.py
- channels/views_test.py
- conftest.py
- factory_data/channels.views_test.test_get_channel.json
- factory_data/channels.views_test.test_list_channels.json
- open_discussions/factories.py
- profiles/models.py
- profiles/views_test.py
Fixes #317
Adds factories for reddit objects and utilities to store and use generated factory data.
Run the factories and be sure that they create matching objects in reddit.
Example:
```python
from channels.api import Api
from channels.factories import *
u = User.objects.first()
api = Api(u)
channel = ChannelFactory.create(channel_type='public', api=api)
post = TextPostFactory.create(channel=channel, api=api)
comment = CommentFactory.create(post_id=post.id, api=api)
```
Then go over to `reddit.local//comments/{post.id}` and ensure it is in the expected channel with comments.
Also, delete the cassette and factory_data for one of the updated tests and be sure you can run the tests and it generates new files and a second run of the tests passes …
> Added factories for reddit objects

- channels/conftest.py
- channels/views_test.py
- open_discussions/factories.py
- profiles/factories.py
- profiles/serializers_test.py
- profiles/views_test.py
N/A
This PR makes `ProfileFactory` a `RelatedFactory` of `UserFactory` and removes the reverse relationship. This aligns better with how these records actually get created (your can't have a `Profile` without a `User` and simplifies some test code.
Travis tests should pass.
> Refactored User/Profile factories to be UserFactory-centric

- channels/factories.py
- channels/views_test.py
- factory_data/channels.views_test.test_add_contributor.json
- factory_data/channels.views_test.test_add_contributor_again.json
- factory_data/channels.views_test.test_add_moderator.json
- factory_data/channels.views_test.test_add_moderator_again.json
- factory_data/channels.views_test.test_add_subscriber.json
- factory_data/channels.views_test.test_add_subscriber_again.json
- factory_data/channels.views_test.test_add_subscriber_forbidden.json
- factory_data/channels.views_test.test_create_channel.json
- factory_data/channels.views_test.test_create_channel_already_exists.json
- factory_data/channels.views_test.test_detail_subscriber.json
- factory_data/channels.views_test.test_patch_channel.json
- factory_data/channels.views_test.test_patch_channel_forbidden.json
- factory_data/channels.views_test.test_patch_channel_not_found.json
- factory_data/channels.views_test.test_remove_contributor.json
- factory_data/channels.views_test.test_remove_contributor_again.json
- factory_data/channels.views_test.test_remove_moderator.json
- factory_data/channels.views_test.test_remove_moderator_again.json
- factory_data/channels.views_test.test_remove_subscriber.json
- factory_data/channels.views_test.test_remove_subscriber_again.json
N/A
Refactors the factory models into classes so we can move the creation of posts into a `post_generation` hook and posthumously set both `id` and `created`. It also modifies the `FactoryStore` to only write the `factory_data` 
Delete `cassettes/channels.views_test.test_list_channels.json` and rerun tests. Ensure the cassette is recreated and the `factory_data` file updated.
Also, if you run this you should see an ISO formatted `created` date:
```python
from channels.factories import *
from channels.api import Api
u = User.objects.first()
api = Api(u)
p = TextPostFactory.create(api=api)
p.created  # -> '2017-11-14T16:20:14+00:00'
```
> Switched factories to class-based model and added created field

- open_discussions/views.py
- open_discussions/views_test.py
- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/containers/PostPage.js
- static/js/flow/declarations.js
- static/scss/comment.scss
#232 
This adds UI to be able to edit a comment. 
If you look at comments that you wrote you should see an 'Edit' button right next to where the 'Reply' button currently is. Clicking on this button should replace the comment text display with a form containing the current text for the comment. Saving this form should update the comment with your changes. Canceling should return you to the normal UI.
> edit comments

- channels/serializers.py
Fixes #349
Makes the `description` field on creating a channel optional.
Following the instructions in the README to get a token and create a channel: https://github.com/mitodl/open-discussions#5b-set-up-initial-channelpost-data
(Optional)
> Default to empty description for new channel if not provided (#349)

- channels/serializers.py
- channels/views_test.py
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/factories/comments.js
- static/js/factories/comments_test.js
- static/js/factories/posts.js
- static/js/factories/posts_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/reddit_objects.js
- static/js/lib/reddit_objects_test.js
#232  and #231 
this adds an 'edited' field to the post and comment APIs, based on what Reddit returns. this also adds some logic to display a little _[edited by author]_ message in the UI when `.edited === true`.
Use the API or the UI to edit a post or comment. Afterwards, you should see the message appear after it.
> add edited to comments, posts

- static/js/actions/channel.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/reducers/channels.js
closes #323
This PR will basically clear the `channels` error object when trying to load data on the `ChannelPage`. This fixes the bug that was occurring in the linked issue, which was happening becuase the error from visiting a non-existant subreddit was sticking around even after the URL had been changed to an existing one. Since the UI just looks for the presence of the `error` property to see if it should show UI or not this was preventing the actually existing subreddit from showing up.
Go to `/channel/not-found`, ensure you see an error page. Then navigate to one of the channels in the sidebar by clicking on it. Ensure you can navigate there and you see the posts, instead of just continuing to see the error page.
Also probably confirm you can repro the bug on master.
> fix channel error issue

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/containers/PostPage.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/reducers/posts.js
- static/scss/post.scss
#231 
This adds UI for editing discussions posts (text posts). If the user is viewing the detail page for their own post there should be a an 'edit' button that opens a text box for editing the post.
You should be able to edit your own post, and you shouldn't be able to edit others! The edit button shouldn't show up on a url post.
> Add post editing

- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/factories/channels.js
- static/js/factories/channels_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/js/lib/channels.js
- static/js/lib/channels_test.js
- static/js/lib/redux_rest.js
- static/js/reducers/channel_moderators.js
- static/js/reducers/channel_moderators_test.js
Prerequisite to all moderator-related UI, e.g. #279, #263, etc
Adds a request to the channel moderators endpoint and adds some utils around it.
Go to a channel and post page and verify the pages load correctly and load the moderator list.
To support moderator tasks in the UI, we need to have an idea if the current user is a moderator on the channel. This PR adds the api calls to retrieve that list as well as a util to see if a user is a moderator.
> Added requests for channel moderators

- cassettes/channels.views_test.test_get_post_stickied.json
- cassettes/channels.views_test.test_list_posts_stickied.json
- cassettes/channels.views_test.test_update_post_nonmoderator_cant_sticky.json
- cassettes/channels.views_test.test_update_post_stickied.json
- cassettes/channels.views_test.test_update_post_unsticky.json
- channels/api.py
- channels/serializers.py
- channels/views_test.py
- factory_data/channels.views_test.test_get_post_stickied.json
- factory_data/channels.views_test.test_list_posts_stickied.json
- factory_data/channels.views_test.test_update_post_nonmoderator_cant_sticky.json
- factory_data/channels.views_test.test_update_post_stickied.json
- factory_data/channels.views_test.test_update_post_unsticky.json
- static/js/factories/posts.js
- static/js/factories/posts_test.js
- static/js/flow/discussionTypes.js
closes #194 
this adds a field ('stickied') to the Post API which can be toggled to make a post 'pinned' / 'sticky'.
You should be a moderator on your channels, so you should be able to toggle the boolean using the DRF web interface (just type `{"stickied": true}` and make sure it saves).
> add pin post api

- static/scss/_variables.scss
- static/scss/channel.scss
- static/scss/layout.scss
#359
This PR fixes spacing and margin issues with the About this Channel card. The card needs to have margins to the right of it. Also, decrease the margins between columns. There will also be subtle changes with the font in the card, and increased padding inside the card.
See that the channel page matches the screenshot below. Less margins between columns, and the right column should always have margin to the right of it.
> fixed styling of channel page

- package.json
- static/js/actions/ui.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/components/material/Snackbar.js
- static/js/containers/App.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/factories/posts.js
- static/js/factories/posts_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/channels.js
- static/js/lib/redux_rest.js
- static/js/reducers/index_test.js
- static/js/reducers/post_removed.js
- static/js/reducers/post_removed_test.js
- static/js/reducers/ui.js
- static/js/util/api_actions.js
- static/js/util/api_actions_test.js
- static/scss/layout.scss
- yarn.lock
Fixes #279 
Adds the UI for a moderator to remove posts
- As a regular user, verify you see no option to remove posts
- As a moderator verify you see the option to remove posts
- Remove a post, it should no longer show up in the listing
- As a moderator, you should be able to see the post content
- As a regular user you should see a message that the post has been removed
- As a moderator, you should be able to re-approve the post and it should return to a non-removed state  (shows up in channel listing and regular users can see the content)
> Added UI to remove posts as a moderator

- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/PostList.js
- static/js/components/PostList_test.js
- static/js/containers/ChannelPage.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/scss/_variables.scss
- static/scss/post.scss
closes #236 
This adds UI for pinning posts on a channel. There's a special display for the 'pinned' post, and then also a little button for pinning / unpinning a post. This button should only show up for moderators.
The frontpage should look the same as it does on master. On a subreddit, if your user is a moderator you should see an option (on text posts only) to 'pin' a post. When you select this option the pinned post should change it's display, and after a quick refresh of the post data it should appear at the top of the list. Unpinning it should reverse this.
These buttons shouldn't show up for a non-moderator, but a non-moderator should still see pinned posts on the channel page. A post which is pinned on a subreddit shouldn't look any different on the homepage.
> add pinning ui

- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
#389
This changes the helper function in `ChannelPage` for pinning the post to just post `{stickied: true | false}` instead of the whole post object. 
You should, as a channel moderator, be able to pin a post which you did not write.
> fix post pinning issue

- static/scss/comment.scss
- static/scss/post.scss
Closes #395
This PR fixes layout problem where long URLs are causing the page layout to break. (see screenshot below).
See that a long URL will not cause the URL to break as shown.
Broken:
Fixed:
> This fixes a layout problem where long URLs are causing the page layout to break.

- static/js/actions/ui.js
- static/js/reducers/index_test.js
- static/js/reducers/ui.js
- static/js/reducers/ui_test.js
working on this as part of #234 and #233 
this adds a new field to the UI reducer, a `Set<string>` called `dialogs` and actions to handle adding and removing keys from it. Then we can just check `dialogs.has(key)` to see if our dialog should be open or not.
It's not yet being used for anything, so just read the code and confirm the tests are passing and all that.
> add support for managing dialogs to the UI reducer

- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/auth.js
- static/js/lib/auth_test.js
- static/js/reducers/posts.js
closes #234 
This adds UI so that a user can delete their own posts.
If you look at the detail view for one of your own posts you should see a little 'delete' button.
- clicking this button should open a confirmation dialog
- canceling the dialog, hitting 'escape', or clicking outside should close it
- confirming the dialog should redirect you to the channel page.
If you delete your post it's, like, _really_ deleted (forever...) so don't delete a post that is special, I guess?
> add user post deletion

- Dockerfile-node
- package.json
- static/js/components/CommentForms_test.js
- static/js/components/SpinnerButton_test.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/PostPage_test.js
- static/js/containers/admin/EditChannelPage_test.js
- static/js/global_init.js
- travis/Dockerfile-travis-watch
- travis/Dockerfile-travis-watch-build
- travis/update-docker-hub.sh
- webpack_dev_server.sh
closes #321 
This upgrades our node.js version to 9.3 everywhere, and also does a healthy bump to our yarn version.
It seems that in the time since we last upgraded node it started throwing warnings for unhandled promise rejections, so I went through the tests to fix all of the examples that I could find (mostly things related to our API stub functions). Most of the code changes (other than just changing node.js version numbers) have to do with that.
I also refactored some of the node.js Dockerfiles to be more inline with how we have them in MM now.
Everything should work normally. You should be able to check out this branch, build the docker container, and run things in development mode. The tests should pass on travis, and the build should work alright on the CI.
> upgrade node version

- static/scss/content-policy.scss
Fixes the styling for the Community Guidelines page. There were no left-right margins, and the header font was too big.
See that it looks ok.
Before: 
After:
> Css tweaks to community guidelines page

- static/js/actions/posts_for_channel.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/reducers/index_test.js
- static/js/reducers/posts_for_channel.js
- static/js/reducers/posts_for_channel_test.js
Fixes #403 
Evicts channel post data when navigating away from the channel listing page.
Navigate back and forth between a channel page, homepage, post page, and other channel pages. You should always see a spinner when going to the channel page.
> Fixed loading spinner on channel page

- travis/update-docker-hub.sh
None
Make `update-docker-hub.sh` provide hash values for the new docker images, and update the references in our dockerfiles
Update the docker images
> Have update-docker-hub update local dockerfiles

- static/js/components/404.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/util/rest.js
- static/js/util/rest_test.js
- static/scss/layout.scss
- static/scss/not-found.scss
#215 
This implements a 'not found' component and makes some changes so we can show it on the post page, when we get a 404 back from Reddit.
Go to a post that doesn't exist, and you should see a nice 404 page instead of just a generic error.
You should be able to do anything else you would normally be able to do with a post
> add a 404 page to the post

- scripts/test/check_pip.sh
- tox.ini
None
Add script to check whether the python docker image is up to date, and have it run with tox
- Add a package to `requirements.txt`, for example `tornado`
- `rm -rf .tox`, then run `docker-compose run web tox`
- You should see a diff listing the new `tornado` package as a missing requirement
> Add check_pip.sh

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/components/ReportForm.js
- static/js/components/ReportForm_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/redux_rest.js
- static/js/lib/util.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
- static/js/reducers/focus_test.js
- static/js/reducers/post_removed.js
- static/js/reducers/reports.js
Fixes #235 
Adds link and confirmation dialog to report posts and comments
Go to a post, verify that you can report both posts and comments and that the validation on the input displays and doesn't let you submit until you've fixed it.
>  Added post/comment reporting UI

- cassettes/channels.views.channels_test.test_get_short_channel.json
- channels/views/channels.py
- channels/views/channels_test.py
- factory_data/channels.views.channels_test.test_get_short_channel.json
- static/js/actions/post.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/reducers/posts.js
closes #408 
closes #393 
This adds a 404 page to the channel, which you should see if you try to visit a channel that doesn't exist. I also moved stuff around so we no longer raise an unhandled exception when the request comes back with a 404.
Additional, there was previously an issue where if you visited a post that doesn't exist and then tried to navigate to a channel, the 404 error from the post would prevent the channel data from showing itself. To fix this I just added an action to the post reducer to clear out the error state, which we can call on the channel page if we need to.
Go to something like `/channel/flflasdfajsdf` (well unless you have a channel called that :P). You should see a 404 message, like what we have now on the post page. Then if you visit another channel all …
> add a 404 message to the channel page

- cassettes/channels.views.reports_test.test_list_reports.json
- cassettes/channels.views.reports_test.test_list_reports_empty.json
- cassettes/channels.views.reports_test.test_patch_channel_noauth.json
- cassettes/channels.views.reports_test.test_patch_channel_nonstaff.json
- channels/api.py
- channels/api_test.py
- channels/serializers.py
- channels/serializers_test.py
- channels/urls.py
- channels/views/reports.py
- channels/views/reports_test.py
- conftest.py
- factory_data/channels.views.reports_test.test_list_reports.json
- factory_data/channels.views.reports_test.test_list_reports_empty.json
- factory_data/channels.views.reports_test.test_patch_channel_noauth.json
- factory_data/channels.views.reports_test.test_patch_channel_nonstaff.json
- open_discussions/permissions.py
- open_discussions/permissions_test.py
Fixes #398 
- Adds the API to list reported posts/comments
- Refactored some of our permissions to reduce duplicity and add a new `StaffOrModeratorPermission` and made sure our moderator logic is tested
- Report some posts and comments under different users
- Login as a moderator and go to `/api/v0/channels/:channel_name/reports/` and verify you see the data.
- Try for a different channel that has no reports and verify you see an empty list
- Try as a nonmoderator user and verify you get a 403
> Added API for listing reported content (#398)

- cassettes/channels.views.comments_test.test_get_comment.json
- cassettes/channels.views.comments_test.test_get_comment_404.json
- channels/views/comments.py
- channels/views/comments_test.py
- factory_data/channels.views.comments_test.test_get_comment.json
- factory_data/channels.views.comments_test.test_get_comment_404.json
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/containers/App.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/js/lib/util.js
- static/js/reducers/comments.js
- static/js/reducers/comments_test.js
- static/scss/layout.scss
- static/scss/post.scss
closes #272 
This adds a 'permalink' to each comment. Basically, we have to do the following:
- add a new API endpoint for GET-ing a single comment and it's children
- modify the `PostPage` to look for a comment parameter in the URL and, when present, show some different UI and fetch just that comment instead of all comments
- make a slight change to the comments reducer to support handling a top-level comment whose parent we do not have (which we need if the comment we're 'focused' on is a nested comment, since it's parents will not be returned from the API).
I think those are the major changes.
Every comment should have a little 'permalink' button. If you click on it you should see a special UI, basically a little 'hey you're looking at one comment' thingy and the post display should …
> add comment permalink

- cassettes/channels.views.comments_test.test_update_comment_ignore_reports.json
- cassettes/channels.views.comments_test.test_update_comment_ignore_reports_forbidden.json
- cassettes/channels.views.posts_test.test_update_post_ignore_reports.json
- cassettes/channels.views.posts_test.test_update_post_ignore_reports_forbidden.json
- channels/api.py
- channels/api_test.py
- channels/serializers.py
- channels/views/comments_test.py
- channels/views/posts_test.py
- factory_data/channels.views.comments_test.test_update_comment_ignore_reports.json
- factory_data/channels.views.comments_test.test_update_comment_ignore_reports_forbidden.json
- factory_data/channels.views.posts_test.test_update_post_ignore_reports.json
- factory_data/channels.views.posts_test.test_update_post_ignore_reports_forbidden.json
Fixes #427 
Adds functionality to comment/post APIs to ignore future reports on the items
- Report a comment and a post
- Verify the reports show up on `/api/v0/channels/:channel_name/reports/`
- Go to `/api/v0/posts/:post_id` and `/api/v0/comments/:comment_id` and patch with `{"ignore_reports": true}`
- Verify the reports no longer show up on `/api/v0/channels/:channel_name/reports/`
- Report the comment and post again under a **different user**
- Verify the reports still don't show up on `/api/v0/channels/:channel_name/reports/`
> Updated post/comment APIs to enable ignoring future reports

- static/js/components/Card.js
- static/js/components/PostSortPicker.js
- static/js/components/PostSortPicker_test.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/HomePage.js
- static/js/containers/HomePage_test.js
- static/js/lib/api.js
- static/js/lib/posts.js
- static/js/lib/sorting.js
- static/scss/post-list.scss
closes #228 
This adds a UI for sorting posts for both the frontpage and the channel page. There will be a little drop-down in the upper-right corner which will let you choose from 'hot', 'top', and 'new'. Selecting from these will probably only change the output for you if you have a lot of posts and users, with some posts commented and upvoted a lot and others not.
Make sure that you can pick the sorting method. It should add a `sort` url query param when you pick it (it defaults to 'hot'). If you have pagination params in the url the `sort` param should be cleanly added to the existing params. This should all work on the frontpage and any channel page.
If the post listing isn't changing when you pick the different sorting methods it is probably enough to just confirm that the param …
> add post sorting UI

- package.json
- static/js/components/ChannelSidebar.js
- static/js/components/ChannelSidebar_test.js
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/Markdown.js
- static/js/components/Markdown_test.js
- yarn.lock
closes #440 
We wanted to automatically render URLs as links, when the user puts them in without any markdown formatting. I looked and the most recent version of the React markdown renderer we are using ('react-markdown') supports doing this automatically now. So I:
- bumped us up to the latest version
- fixed a little issue with it treating sequences like `[ foo ]` as Markdown anchor tags for some reason
- made a new `Markdown` component we can use for both posts and comments
so it should be good now.
All should work as before, markdown should render and so on. Additionally, if you make a comment or a text post which includes a URL pasted directly into the markdown source (i.e. not in the form `[text](url)`) the markdown renderer should render it as an anchor tag, so you can click on it …
> fix link issues in markdown display

- codecov.yml
See https://github.com/mitodl/micromasters/pull/3811
Turns off status checks for code coverage so that it doesn't block releases
The checks should not be present in this PR
> Omit status check for code coverage to prevent blocking of deploys

- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/scss/post.scss
closes #458 
this just adds an `<img>` tag to the compact post display which displays the profile image associated with the post (the profile image of the author).
Make sure that it puts the image on the post list on the channel page and the homepage.
> add profile images to CompactPostDisplay

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
closes #476
This PR fixes an error that was occurring for non-moderator users when editing comments. Basically, we were patching the whole comment object, which includes fields which are read-only for non-moderators. So when the backend tried to save the object, the user would get a 403 because they do not have the ability to modify e.g. the 'removed' field.
This changes the comment editing so that we only post the things we need to.
As a moderator you should be able to create and edit comments as usual. As a non-moderator you should also be able to edit comments, but with the added bonus of not seeing an error page!
> fix edit comment 403 error

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
closes #482 
Similar to the comment editing issue. We were posting the whole `Post` object, but for non-moderator users there are a few read-only fields on the object. So, when they tried to edit a post, they would get a 403 error. Unlike the comment issue, the edit wouldn't even go through (the comment edit would go through but then show an error page).
Anyway, this applies the same fix I did for the comment issue.
You should be able to edit posts successfully, without any network or UI errors, as both a moderator and non-moderator user.
> fix non moderator post edit issue

- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
closes #442 
this just adds the preventDefaultAndInvoke wrapper to two callbacks for the report post dialog. this should mean that it no longer puts a little '#' at the end of the URL.
Fiddle around with the report post dialog (on the post page), and just make sure you never see a '#'! Functionality should all be normal.
> fix report dialog preventDefault issue

- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
closes #393 
This PR does 2 things:
- fixes the issue in #393, which is that, on the Post page, we were still issuing the request to get moderators for the channel even if the post and channel came back with 404 or 403 errors.
- I also noticed that if you visited a post on a channel which does not exist the 404 page was not rendering (because we checked first if the `channel` was nil), so I changed it so that we would render the 404 component in such a case.
- visit a post, that exists, which your user does not have permission to view. If you look in the network tab you should not issue a request to the moderators backend.
- visit a nonsense url (like `/channel/asdfasdfasdf/1020`) and make sure you get a 404 page. Maybe confirm that, on the current `master`, visiting the same URL just …
> fix post page 403

- channels/serializers.py
- channels/test_constants.py
- channels/views/comments_test.py
- channels/views/frontpage_test.py
- channels/views/posts_test.py
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/components/PostList.js
- static/js/components/PostList_test.js
- static/js/containers/ChannelModerationPage.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/factories/posts.js
- static/js/flow/discussionTypes.js
- static/js/hoc/withCommentModeration.js
- static/js/hoc/withPostModeration.js
Fixes #495 
Adds the report counts to the frontpage and removes no longer needed calls to fetch the reports.
Verify that the counts still show up and you don't see report counts for channels you're not a moderator of.
> Added report counts to frontpage

- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/util/rest.js
- static/js/util/rest_test.js
closes #499 
This fixes the logic for when we show the 404 component on the post page, so that the case when we visit a comment permalink for a non-existent comment is taken into account.
Confirm that viewing the post page and viewing an individual comment works as it should. Then confirm that going to a nonexistent post works as it should, and also that going to a comment permalink for a non-existent comment shows a 404 page.
> fix comment permalink 404

- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/PostList.js
- static/js/components/PostList_test.js
- static/js/containers/ChannelPage.js
- static/js/containers/HomePage.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/hoc/withPostModeration.js
- static/js/lib/reports.js
closes #486 
what it says on the tin. I refactored the `withPostModeration` HOC to include the reporting functionality (and the relevant `Dialog` and so on) in there. Then it was pretty easy to just add the functionality to the channel page and the frontpage.
Moderation on the post page (for both comments and the post) should work totally as before. There should now be a 'report' link on the frontpage and on the channel page for each post - clicking this should bring up the same dialog as on the post page. There should be no issues with reporting a post from the channel page.
> add report post links to the frontpage and channel page

- static/js/containers/PostPage.js
closes #514
this fixes a bug that I introduced, where making a comment would cause the whole post page to be taken over by a spinner. Uh instead, we shouldn't do that.
confirm that, on master, if you make a comment you see that the whole post page becomes a spinner. then, checkout this branch and confirm that it no longer does that!
also confirm that the 404 page behavior for the post page (for both a post 404 and a comment permalink 404) works as it should.
> fix how we calculate loaded and notFound for the post page

- open_discussions/urls.py
- static/js/containers/App.js
- static/js/containers/App_test.js
- static/js/containers/SettingsPage.js
- static/js/factories/settings.js
- static/js/factories/settings_test.js
- static/js/factories/util.js
- static/js/flow/settingsTypes.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/auth.js
- static/js/lib/auth_test.js
- static/js/lib/redux_rest.js
- static/js/lib/url.js
- static/js/reducers/settings.js
- static/scss/layout.scss
- static/scss/settings.scss
closes #451 
This adds a notifications page at `/settings` where the user can adjust their notification preferences.
If the user is logged in, it works as any other page in the app. However, it also supports authenticating to the API with a stateless token, which we can use to authenticate only with the notification settings API.
Basically, if the user visits `/settings/${TOKEN]/` the application will include the `TOKEN` value in the headers for the HTTP requests it issues, so that the user can fetch their current notification preference values and also issue a `PATCH` request. If the `TOKEN` supplied is not a valid token (i.e. if we get a 401 back) it will redirect the user to the 'sign in' page.
First you'll need to create a `NotificationSettings` for yourself for the `frontpage` …
> add email settings page

- open_discussions/views.py
- open_discussions/views_test.py
- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/components/UserInfo.js
- static/js/components/UserInfo_test.js
- static/js/flow/declarations.js
- static/scss/_variables.scss
- static/scss/layout.scss
- static/scss/navigation.scss
- static/scss/user-info.scss
closes #230 
This adds the users profile image and full name to the OD UI. We show it in the upper corner, and in the top of the nav thingy on mobile.
If you go to open-discussions you should see something like this:
If your user lacks either a name or a profile image it should not show anything.
> add profile picture and name of user to UI

- Procfile
- docker-compose.travis.yml
- docker-compose.yml
Fixes #335 
Fixes error output in travis for when celery starts up
Verify no error output in celery process on travis python job and that you can start celery locally. See this run on master that has stracktraces in it: https://travis-ci.org/mitodl/open-discussions/jobs/350342875
> Fix travis errors

- conftest.py
- open_discussions/templatetags/render_bundle.py
- open_discussions/urls.py
- pytest.ini
- requirements.in
- requirements.txt
None
- Upgrade Django to 1.11
- Change pytest filtering to be more specific with deprecation warnings
- Update django-webpack-loader and related templatetags
- Update Django REST framework and django-server-status
> Upgrade Django to 1.11, other upgrades

- notifications/management/commands/populate_notification_settings.py
Fixes #539 
Fixes an obvious error in the query filter
Run `./manage.py populate_notification_settings` in master, it should error. Run it in this branch and it should not error.
> Fixed query error on populate command

- channels/serializers.py
- channels/views/frontpage.py
- channels/views/posts.py
- channels/views/reports.py
- notifications/notifiers/frontpage.py
- notifications/notifiers/frontpage_test.py
Fixes #544 
Updates `PostSerializer` to take an explicit current user on the context instead of looking it up on the request, which we don't have in certain contexts like email sending.
See instructions in #504
> Fixed issue with request KeyError on email send

- static/js/containers/App_test.js
- static/js/containers/SettingsPage.js
- static/js/containers/SettingsPage_test.js
- static/js/factories/settings.js
- static/js/factories/settings_test.js
- static/js/reducers/settings.js
closes #552 
The UI before assumed that the list of `NotificationSettings` objects would only include the frontpage one, and didn't account for there being others (uh, oops). So, now it does.
I also added a regression test, which really probably should have been there in the first place. Ah well, c'est la vie.
Make sure your user has a `comments` and `frontpage` notification setting object created, and go to `/settings/`. The Radio menu for the frontpage setting should reflect the DB value, and you should be able to save it and have the UI change (when you refresh the page I mean).
> fix settings page

- static/js/components/PostList.js
- static/js/components/PostList_test.js
- static/js/containers/ChannelPage.js
closes #567 
this adds the remove post button to the channel view.
Go to the channel page as a moderator, make sure the button shows up! It should do what you expect. The button shouldn't show up if you're not a moderator (that logic is in the `CompactPostDisplay` and not in this PR though).
> add remove post link to channel view

- static/scss/comment.scss
- static/scss/post.scss
closes #565
This fixes an issue where images where being squeezed on the channel page. I added flex-shrink: 0; to the images on the channel page and also in comments.
This bug is a bit hard to reproduce. I could not reproduce it on local. Looking on production, I see it occasionally.
> This fixes an issue where images where being squeezed on the channel page

- mail/templates/email_base.html
- mail/templates/frontpage/body.html
(none)
This issue fixes some problems with the width and padding in the email template. It makes the emails fit in the email body container without overflowing, and also tightens up the padding. Also removes the gray background color.
Send some emails and see if the layout looks correct.
> Fixes some layout issues with the email template

- channels/serializers.py
- channels/views/posts_test.py
closes #576 
This just does a little bit of work to make the default profile picture URL included in the email into an absolute URL, so that it will actually work when the html is rendered in an email client. Previously we were just shipping a relative URL, which obviously didn't work.
OK! So the following code will render the frontpage email template with your user's current frontpage:
```py
from mail.api import render_email_templates
from channels.utils import ListingParams, get_pagination_and_posts
from channels.api import Api
from channels.serializers import PostSerializer
from profiles.models import Profile
p = Profile.objects.get(name='asdf Pote')
user = p.user
api = Api(user)
lp = ListingParams(None, None, 0, 'hot')
pagination, posts = get_pagination_and_posts(api.front_page(lp), …
```
> fix missing profile picture in email

- mail/api.py
- mail/api_test.py
Fixes #588
Switches to use `email.utils.formataddr` so we safely escape email address display names.
Put a `"` or `\` character in your user's name, follow the test instructions detailed in the earlier PR: https://github.com/mitodl/open-discussions/pull/527
and verify the email still sends OK
> Fixed safe_format_recipients to quote display name

- mail/templates/email_base.html
- mail/templates/frontpage/body.html
None
Fixes wonkiness in outlook rendering of the frontpage email.
Send an email and make sure it looks ok in outlook webmail.
What it was looking like before:
Button background was wrong:
Default profile image sizing was off:
> Fix button styles on frontpage digest

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/containers/PostPage.js
- static/js/factories/comments.js
- static/js/factories/comments_test.js
- static/js/factories/posts.js
- static/js/factories/posts_test.js
- static/js/flow/discussionTypes.js
- static/js/util/api_actions.js
- static/js/util/api_actions_test.js
- static/scss/_variables.scss
- static/scss/comment.scss
- static/scss/post.scss
closes #469 
This adds follow / unfollow buttons to both posts and comments. Following should create a subscription object, and unfollowing should destroy it. Having a subscription doesn't yet do anything.
Go to one of your posts, you should be able to follow and unfollow it. Same with comments. The UI should change to say 'unfollow' if you are already following (in line with the design).
I wrote this code a few weeks ago and uhh forgot to open a PR >_<
> add follow button to posts and comments

- package.json
- scripts/test/js_test.sh
- static/js/containers/App_test.js
- static/js/containers/SettingsPage.js
- static/js/containers/SettingsPage_test.js
- static/js/factories/settings.js
- static/js/factories/settings_test.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/reducers/settings.js
- static/scss/layout.scss
- static/scss/settings.scss
- yarn.lock
closes #474 
This adds a setting to the settings page (`/settings`) for managing post / comment replies (basically, it's a checkbox which toggles the value of the comments notification setting between 'never' and 'immediate').
First you'll need to make sure you have a `NotificationSetting` with type `comment` created for your user. Then if you go to the settings page you should see  a checkbox. Checking or unchecking the checkbox should save the value between page loads, and a checked checkbox should correlated with the frequency setting for the `NotificationSetting` being 'immediate' and an unchecked box with 'never'.
> add comment / post settings

- notifications/api.py
- notifications/api_test.py
Fixes #631 
Removes logic checking `email_optin` to disable default notifications
- Remove all your notification settings, set `email_optin` to `False`
- Run `./manage.py population_notification_settings --username USERNAME` and verify you get the right defaults and not 'never' anymore
> Remove email_optin logic (#631)

- notifications/notifiers/email.py
- notifications/notifiers/email_test.py
Fixes #609 
Fixes a race condition where we queue an email to be sent but the user changes their settings prior to the actual send
This is a bit tricky to test, but the fix here is very simple so I think passing tests and code review should be sufficient.
> Fixed race condition with NotificationSettings trigger_frequency

- embedly/admin.py
- embedly/api.py
- embedly/api_test.py
- embedly/apps.py
- embedly/models.py
- embedly/urls.py
- embedly/views.py
- embedly/views_test.py
- open_discussions/settings.py
- open_discussions/urls.py
- static/js/lib/api.js
- static/js/lib/api_test.js
for #604 
This adds an API which proxies requests to the [embed.ly embed API](http://docs.embed.ly/docs/oembed).
You should be able to test it out by going to `/api/v0/embedly/${url}`. `url` has to be an encoded URI component. I found that I had to call `encodeURIComponent` twice in order to get it to properly escape all the slashes in a URL.
For now I have defined a function in `lib/api.js` which should allow you to test it, if you open up the discussions app you can find it at `window.getEmbedly`, you can inspect the response in the Chromium network tab. Alternatively, you can try a URL like this one:
http://localhost:8063/api/v0/embedly/https%253A%252F%252Fen.wikipedia.org%252Fwiki%252FArnaldur_Indri%2525C3%2525B0ason/
> add embed.ly proxy API

- notifications/notifiers/comments.py
- notifications/utils.py
- notifications/utils_test.py
Fixes #639 
This PR adds a decorator/contextmanager that is used to translate praw errors to notification cancellation errors instead. These errors can happen when the user no longer has permissions to certain objects in Reddit, so sending a notification for them isn't useful.
Most of the translation logic was inspired by `channels.utils.translate_praw_exceptions()`, so this covers a bit more than just the error reported by Sentry so we don't have to revisit this for edge cases we've already hit in other areas.
Only added this to comment notifications because we haven't seen it for the frontpage yet and that situation would be more complicated anyway.
- Stop your celery worker: `docker-compose stop celery`
- Ensure your notification settings for comments are set to "immediate"
- Subscribe …
> Added handling for praw errors in email notifications

- requirements.in
- requirements.txt
Part of #641 
Upgrades celery. In 4.1 there is automatic exponential backoff for tasks
> Upgrade celery

- mail/templates/comments/body.html
- mail/templates/comments/subject.txt
- mail/templates/email_base.html
- mail/templates/frontpage/body.html
closes #633
This PR removes the MIT and Micromasters logos, and left aligns the notification email.
Test it in various email clients
(Optional)
> Simplified layout for notification email

- mail/templates/comments/subject.txt
- mail/templates/frontpage/subject.txt
- notifications/notifiers/frontpage_test.py
Fixes #611 
Ensures the frontpage digest subject lines aren't html escaped
This is pretty simple so the test coverage should be sufficient (the `'` would be escaped to `&apos;` in master branch).
> Don't HTML escape subject lines for frontpage emails

- static/js/components/Embedly.js
- static/js/components/Embedly_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/factories/embedly.js
- static/js/lib/api.js
- static/js/lib/redux_rest.js
- static/js/reducers/embedly.js
- static/scss/_breakpoints.scss
- static/scss/embedly.scss
- static/scss/layout.scss
- static/scss/post.scss
closes #604 
When viewing a Link-type post this will make a request to the Embedly API and then display the results. Here's a few examples of what that looks like:
You'll need an embedly API key set up to test this, and you'll need to set the `EMBEDLY_KEY` env var with it. Then, if you add a link post, you should see some sort of content get pulled out, as shown in the screenshots.
There are two small other tweaks which should be tested. From the post index (a channel or the frontpage) Link-type posts now link directly to the post detail view, not to the external resource. Also, the domain name of the external link is now put below the content, instead of up by the title, on the detail page.
> add embedly frontend

- open_discussions/templates/index.html
- open_discussions/views.py
- open_discussions/views_test.py
- static/js/entry/zendesk.js
- webpack.config.shared.js
closes #549 
This adds the Zendesk support widget to open discussions. I copied the implementation we have in MM over, and removed the parts which it didn't seem to me like we would need over here. I also added a little thing to hide the MM program selector, and also added the user's email address to the SETTINGS object in order to fully pre-fill the widget form.
Make sure that the widget shows up. It should look roughly the same as in MM. Your user's name and email should be pre-filled in the form, and the form shouldn't have a (visible) drop-down for selecting the program. Also, there shouldn't be any zendesk-related console errors.
> add zendesk widget

- README.md
Closes #697
Updates the OSX instructions in the README: removes docker-machine specific instructions and updates the required settings to get micromasters and open-discussions working together on OSX
- Follow the instructions on OSX and verify that you can register/login to open-discussions by way of micromasters.
> README for OSX without docker-machine

- package.json
- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/reducers/embedly.js
- static/js/store/configureStore.js
- static/scss/createPost.scss
- yarn.lock
part of #604 
closes #694 
This adds a preview display to the link post creation form, which shows you what the embedly embed (ha) for your link will look like when it's posted.
Making a text post should work like normal. If you make a link post, when you add a URL to the form, or change the URL, a rich embed thingy like this should pop up:
changing the URL should cause the preview to change.
> add link preview to link post creation

- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/flow/declarations.js
- static/js/lib/channels.js
- static/js/lib/util.js
- static/js/lib/util_test.js
closes #659 
closes #657
This hides the settings link in the navigation component if the user is anonymous.
If you're not an anonymous user you should see the settings link in the left-hand-side nav, as before. If you are anonymous, you shouldn't see it!
> remove settings and post link for anonymous users

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/global_init.js
closes #686 
This hides the report buttons for comments and posts for anonymous users.
Check that a report button shows up when you're logged in, and is absent when you're not, in these three places:
- a post in an index view (frontpage or channel view)
- a post in a detail view
- a comment on a post
> hide reporting UI for anonymous users

- uwsgi.ini
Fixes #529 
Increases the uwsgi buffer size. Same change we did over in MM: https://github.com/mitodl/micromasters/pull/3887/commits/91e820c5a3a14d9b0586fb3f5c8b127847c9e637
Ensure that uwsgi starts without error and that you can still use the app.
> Increased uwsgi buffer size

- channels/api.py
- channels/api_test.py
- channels/constants.py
- channels/serializers.py
- docker-compose.yml
- fixtures/common.py
- open_discussions/features.py
- open_discussions/features_test.py
- search/connection.py
- search/indexing_api.py
- search/indexing_api_test.py
- search/task_helpers.py
- search/task_helpers_test.py
- search/tasks.py
- search/tasks_test.py
Closes #605
- Adds the elasticsearch document mapping, as well as a function that clears and creates the index in ES
- Wraps various channel API methods to make changes to the index when there are changes made to the information that we index for posts (and only posts)
- Enable the `INDEX_UPDATES` feature (i.e.: add `FEATURE_INDEX_UPDATES=true` to your `.env`)
- Run `search.indexing_api.clear_and_create_index` in a Django shell
- Create posts and alter posts in different ways (changing text, adding comments, upvoting/downvoting)
- Query the index and confirm that those changes are reflected in the indexed document (or that the document was created if it's a new post)
An easy curl command to inspect the documents in the index:
```bash
curl -XGET -s …
```
> Added Elasticsearch document and added indexing handlers for posts

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
closes #689 
closes #690 
This hides the follow / unfollow and reply buttons if the user is anonymous. I decided to just throw those in one PR since they were both very small changes.
Make sure that you can follow / unfollow a comment or post as normal, and that the reply button allows you to reply to a comment. Then make sure that the follow and reply buttons are hidden, on both posts and comments.
> hide reply and follow buttons for anonymous users

- static/js/containers/App.js
- static/js/containers/App_test.js
closes #684 
This fixes an issue with the logic (in `App.js`) for when to fetch the channel subscriptions. The way this affected the user was that, if you entered the site from the `/settings` page and then navigated, without doing a full-page refresh, from there to the homepage the channel subscriptions would not be fetched, so the UI would look like this:
You can reproduce this by:
1. visiting `/settings`
2. clicking on the 'Discussions' link in the top bar
The issue was because we don't want to fetch the channels on `/settings`, because on `/settings` we allow the user to authenticate with a token as well as a normal JWT session. So in `App.js` we had logic to not fetch the subscribed channels if we were on the settings page. I added a bit of logic which runs on `componentDidUpdate` …
> fix issue with not fetching subscriptions when navigating from settings

- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
closes #688 
This PR hides the comment form (`ReplyToPostForm`) when the user is anonymous.
Ensure that logged-in users get the normal experience. Ensure that anonymous users don't see a form for leaving a comment under the post, so it should look like this:
> hide comment UI from anonymous users

- static/js/components/Embedly.js
- static/js/components/Embedly_test.js
- static/scss/embedly.scss
closes #717 
This just makes the embedly rendering code a little more foolproof. It turns out that embedly will sometimes (not realiably) return an 'html' value on link-type posts. Previously, the code assumed that the 'html' key would only have a usable value in it on video-type posts, so if a link returned html it would display in a weird squished video aspect-ratio box. This fixes that, so that we only put videos in the `.video-container` div, and we render the `.html` content for links if it's there.
You may have to try a few different links before you get one that returns `html` with the `link` type. Wikipedia pages sometimes do, but for reasons I don't understand sometimes the same page will return different things two times in a row.
Anyway, on master a wikipedia link that returns …
> fix html embeds

- static/js/containers/AuthRequiredPage.js
- static/js/containers/ChannelModerationPage.js
- static/js/containers/ChannelPage.js
- static/js/containers/ContentPolicyPage.js
- static/js/containers/CreatePostPage.js
- static/js/containers/HomePage.js
- static/js/containers/PostPage.js
- static/js/hoc/withNavAndChannelSidebars.js
- static/js/hoc/withNavSidebar.js
none
just adds a unique CSS class (like `.post-page`, `.channel-page`, etc) to each page, so we can do page-specific styling if we want.
Read the code, make sure it makes sense. Check that on each page in the SPA there's a unique class applied to the `.main-content` div.
> add a unique CSS class for every page in the app

- package.json
- static/js/components/CommentVoteForm.js
- static/js/components/CommentVoteForm_test.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/js/lib/util.js
- yarn.lock
closes #687 
This PR basically adds a little tooltip to the post and comment voting buttons, which we show when an anonymous user clicks on or hovers over the voting buttons.
If you're not anonymous, then voting on posts and comments (in the post detail view and the channel / frontpage views) should work as normal.
If you're anonymous, you should instead see a friendly lil' tooltip, like this one:
The buttons also shouldn't do anything when you click them, if you're anonymous (previously you would get redirected to the 'auth required' page).
> add little 'sign in' tooltips on voting buttons for anons

- search/indexing_api.py
None
Switches mapping for post_link_url from `text` to `keyword` since `text` will assume its input is tokenizable, disrupting search
N/A
> Use keyword so post_link_url won't be tokenized

- open_discussions/test_utils.py
- open_discussions/test_utils_test.py
- open_discussions/utils.py
- open_discussions/utils_test.py
- search/tasks_test.py
None
Fixes invalid import caused by #651 which was blocking the heroku deploy. Heroku does not install test_requirements.txt so files using pytest were failing to import.
N/A
> Fix heroku deploy

- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/factories/embedly.js
- static/js/lib/embed.js
- static/js/lib/embed_test.js
closes #744
This fixes the bug with embedded tweets not showing up, but ensuring that the twitter JS is on the page and calling its little bootstrap function when necessary.
I think the issue came about because we don't put the twitter HTML on the page at page-load, but afterwards, whenever the embedly request comes back. 
Make sure that if you embed a tweet it will show up in a nice normal tweet embed sort of fashion.
> fix issue with twitter embeds

- static/scss/comment.scss
- static/scss/post.scss
Closes #754
Discussion posts and comments can be formatted as code elements using markdown. There is a bug where code elements are not wrapping, which causes all the other text to overflow.
Create a comment or a post and enter some code. Around the code add markdown for code which is ```.
The text should wrap normally.
For example:
```  
curl "$1" --max-time 30 -L \
-H 'Connection: keep-alive' \
-H 'Cache-Control: max-age=0' \
-H 'Upgrade-Insecure-Requests: 1' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3381.0 Safari/537.36' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Accept-Language: …
> Fix for non-breaking code text in discussions

- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
closes #734 
If we get an error response from Embedly we don't want to show the little 'this is a preview of your post' message that we normally shown above the embedly preview on the post create screen.
Go to the link post creation screen and try to make a post with a URL that won't work, like 'http://localhost/foo/bar' or something. You shouldn't see the 'this is a preview...' message. If you do a twitter or youtube url or something you should see it as normal.
> don't show the 'this is a preview' message if embedly returns an error

- open_discussions/views.py
- open_discussions/views_test.py
Closes #772 
Removes the superuser authentication requirement for viewing the SAML metadata URL.
Go to http://localhost:8063/saml/metadata without being logged in, you should see some XML.
> Remove authentication requirement for viewing SAML metadata

- app.json
N/A
Puts the apt buildpack first in the list in app.json
Heroku PR builds shouldn't break
> Apt buildpack should be first

- open_discussions/utils.py
- open_discussions/utils_test.py
- search/serializers.py
- search/serializers_test.py
- search/tasks.py
- search/tasks_test.py
Fixes #760 
Fixes #762 
Fixes a None error with missing reddit authors. Error handling for tasks is also refactored to not rely on Celery propagating the error correctly through groups.
In `serialize_comment` add some code which will fail for a particular comment. Something like `if comment.id == 'abc': raise Exception()` would work. Run `./manage.py recreate_index`. It should fail and show you the comment id on which it failed.
Remove the exception code and run it again. It should succeed.
> Fix comment serialization error, Celery error handling

- fixtures/users.py
- profiles/models.py
- profiles/models_test.py
- profiles/serializers.py
- profiles/utils.py
- profiles/views_test.py
- Makes some backend modifications to prepare for #682
- Modifies the Profile model/serializer/api to resize an uploaded image to different sizes.
- Use the API to update the `image_file` field of your profile:
- Get a `jwt_token`:
```python
from fixtures.users import staff_jwt_token
user = User.objects.get(username=<your_username>)
staff_jwt_token(None, user)
```
- Send an API PATCH request to update your profile image:
```
curl --request PATCH -H "Authorization: Bearer  <jwt_token>" -F 'image_file=@<image_name.jpg>'  http://od.odl.local:8063/api/v0/profiles/<username>/
```
-  The response JSON should include populated URL's for `image_file`, `image_small_file`, and `image_medium_file`.  Open them in a browser to verify that the images load and …
> Backend modifications for resizing an uploaded image

- channels/api.py
- channels/api_test.py
- channels/views/comments.py
- channels/views/posts.py
- fixtures/common.py
- fixtures/reddit.py
- search/indexing_api.py
- search/indexing_api_test.py
- search/serializers.py
- search/serializers_test.py
- search/task_helpers.py
- search/task_helpers_test.py
- search/tasks.py
- search/tasks_test.py
Closes #606
Adds logic to create/update comment documents in Elasticsearch
- Set `FEATURE_INDEX_UPDATES=True` in your `.env`
- Create/update comments and check to see if those changes are reflected in the ES index
- Set a post to removed, then check to see that all comments associated with that post are also set to removed
- Delete a comment and check to see that the parent post's `num_comments` is decremented
Probably `search/task_helpers.py`
There are comments that say as much, but we are going ahead with an approach where we will log information about version conflicts in document updates and let the app continue to function as normal.
> Added ES comment document indexing

- app.json
None
Adds `MAILGUN_SENDER_DOMAIN` to environment variables listed in app.json so it gets used by the review app
N/A
> Add MAILGUN_SENDER_DOMAIN to app.json so it gets used by review apps

- open_discussions/settings.py
#763
Adds `"requestedAuthnContext": False` to SAML configuration, which should cause Touchstone to show the 'login via certificate' option.
> Set requestedAuthnContext to False for SAML

- search/indexing_api.py
- search/serializers.py
- search/serializers_test.py
- search/task_helpers_test.py
Closes #787 
Adds a user's name to the ES index and renames the existing `author` field to `author_id`
- Restart your `celery` container at the very least after you check out this branch
- Run `docker-compose run web ./manage.py recreate_index`
- Check the search index to make sure that `author_id` and `author_name` are in the indexed documents and that the values are what you expect.
Easy curl command to look at documents in the index: `curl -XGET -H "Content-Type: application/json" -s 'http://localhost:9101/discussions_local_default/_search?pretty=true'`
Two things to note:
1. Unsurprisingly, some code was added that is very similar to `PostSerializer` and `CommentSerializer`. There is an open tech debt issue to use those classes when serializing for the ES index (#790)
1. For every …
> Added user full name to ES document

- package.json
- static/js/components/Embedly.js
- static/js/components/Embedly_test.js
- static/scss/embedly.scss
- yarn.lock
part of #777 
This adds a fancy animated placeholder loading UI element, which we show on link posts while awaiting a response from Embed.ly. It looks like this:
I'm using this thing: http://danilowoz.com/create-content-loader/ to make it.
You'll need to have the embedly API key set up on your machine. Once you've got that, you'll need to just try to look at a link post. You should see the animation thingy for just like half a second or so when the embedly response is still loading. It should display ok on both desktop and mobile views.
> add a fancy loading animation to the post detail page

- open_discussions/settings.py
- requirements.in
- requirements.txt
- search/tasks.py
Fixes #811 
- Adds `sentry` to the list of logging handlers and to the root logger so that all `log.error` or `log.exception` are logged correctly from the web server
- Replace `get_task_logger` with `logging.getLogger` because the celery one doesn't work and I can't figure out what I need to change to fix it.
- Upgrade some dependencies
You can shell into the PR build and run `logging.getLogger().error("test error")` to test that the error gets reported to sentry.
For celery you can shell into heroku and run `search.tasks.index_post_with_comments.delay(123456)` (123456 is invalid). You should see an error appear in sentry.
> Fix logging of errors and exceptions to sentry

- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
none
This makes sure we're dealing with a URL post before we display the Embedly component. I recently changed the Embedly component to include a loader placeholder. Previously, it had its own logic that would only display when it got a result, so it was safe to just leave it on the page at all times. After I changed it to have a 'loading' placeholder it was no longer safe! oops.
This just checks to make sure we're dealing with a link post before we put the component on the page.
You, uh, shouldn't see a link post loader on the text post page anymore...
Embed.ly link posts should work as normal.
> fix a stupid bug

- channels/api.py
- channels/api_test.py
- channels/serializers.py
- channels/serializers_test.py
- channels/utils.py
- channels/views/channels.py
- channels/views/comments.py
- channels/views/contributors.py
- channels/views/moderators.py
- channels/views/posts.py
- channels/views/reports.py
- channels/views/subscribers.py
- open_discussions/middleware/channel_api.py
- open_discussions/middleware/channel_api_test.py
- open_discussions/settings.py
Related to #790 (this essentially addresses some tech debt behind that tech debt)
Moves channel API imports out of channel serializers. Channel API is now attached to each request as a lazy object
Tests should pass, normal app functionality should work
> Moved channel API imports out of channel serializers

- static/scss/channel.scss
closes #835 
This just puts a `max-width` on the description container to fix the layout bug.
Edit the channel description for one of your channels to be pretty long (a few paragraphs). Then confirm on master you see the layout bug. Then check out this branch and confirm it fixes it.
> fix issue with large channel descriptions

- search/indexing_api.py
- search/indexing_api_test.py
https://sentry.io/mit-office-of-digital-learning/discussions/issues/585134656/?environment=production
Delete indices one by one instead of using `_all` in order to work around complications with readonlyrest Elasticsearch plugin
N/A, we will need to test this in CI
> Delete indices one by one to avoid use of _all

- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
None
Fixes a regression from #816. The feature flag for profile UI will be used to determine whether to show the red dot showing profile incompleteness
If your profile is incomplete and the `PROFILE_UI` feature flag is on, you should see the red dot in the profile icon. You should be able to turn off the feature flag and see the red dot go away.
> Use feature flag to determine whether to show profile incompleteness red dot

- conftest.py
- open_discussions/exceptions.py
None
Adds a fixture preventing HTTP requests from being made via the requests library when unit tests are running
Checkout `master`, go to `test_more_comments` in `channels/api_test.py` and remove `mock_client` from the list. Run that test, it should pass locally (or possibly fail due to some reddit error).
Check out this PR and run the same test, with `mock_client` removed. You should see a `NoRequestException` somewhere in the stack trace.
> Add autouse fixture to prevent requests from executing during tests

- Dockerfile
N/A
Pins this to 3.6.4 since we've seen broken pack issues in micromasters with 3.6.5. See mitodl/micromasters#4031
`docker-compose build --no-cache web` should work
> Pin dockerfile python version to 3.6.4

- authentication/pipeline/user_test.py
- open_discussions/test_utils.py
- open_discussions/test_utils_test.py
- profiles/models.py
- profiles/models_test.py
- profiles/utils.py
- static/js/containers/ProfileImage.js
- static/js/containers/ProfilePage_test.js
- static/scss/profile-image.scss
- Closes #833 
- Checks the user's gravatar URL when a new profile is saved without images; if found the image fields are updated with the gravatar URL's.
- Login/Register with a new user that has a gravatar account associated with the user's email.  The profile image should be the same as the gravatar image.
- Go to the profile page, and upload an image.  The uploaded image should replace the gravatar.
- Login/Register with a new user that does not have a gravatar account associated with the user's email.  The profile "image" should be a circle with the user's initials.
> Use gravatar for new profiles without images

- static/js/hoc/withCommentModeration.js
- static/js/hoc/withPostModeration.js
none
I needed to use `React.Fragment` before, but with the version of flow we were on threw an error if you just used `<React.Fragment>` directly in JSX. To get around the error I added a qualified import, like `import React, { Fragment } from "react"`, which silenced the error. The newer version of flow we recently upgraded to no longer has this issue, so we can remove the workaround now.
Everything should work as before.
> remove flow workaround

- static/js/components/Toolbar.js
- static/js/components/Toolbar_test.js
None
Adds a `preventDefault()` call to the click handler for the hamburger menu click handler
Click the menu. You should not see a `#` appear in the URL
> Add preventDefault to toolbar click handler

- channels/serializers.py
- channels/serializers_test.py
- channels/views/channels_test.py
- static/js/components/CreatePostForm.js
- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/Drawer.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/js/lib/channels.js
- static/js/lib/channels_test.js
Fixes #832 
Adds moderator and contributor status to the channel API, then uses it to determine whether the post button is displayed, or whether the channel is shown in the list of options in the create post page.
Create a new public channel and subscribe the user to it. Unsubscribe the user from all other channels.
In the home page you should see a submit post button. Click on the channel in the sidebar. You should still see a create post button. Click on the button and verify that there is one channel in the channel list, the one you created for testing this PR.
Alter the channel to be `restricted` via Django shell then refresh the page. There should be no options in the channel dropdown. Go to the homepage. There should be no button shown. Click on the channel tab. You should still see …
> Hide post button for channels not allowing it

- search/serializers.py
- search/serializers_test.py
No ticket
Adds link URL serialization to the search serializer for posts. I forgot to include this key in the PR for #790
Create a link post and check the corresponding document in ES
> Added link url to search serializer

- static/js/components/Toolbar.js
- static/js/components/Toolbar_test.js
Fixes #885 
Hides this ui if you're logged out
Test that you still see it if logged in and don't if logged out.
> Hide user menu if user is not logged in

- authentication/templates/register.html
- static/js/components/ExternalLogins.js
- static/js/components/ExternalLogins_test.js
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/RegisterPage.js
- static/js/containers/auth/RegisterPage_test.js
- static/js/lib/url.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
- static/scss/basic.scss
- static/scss/form.scss
- Closes #672 
- Partially addresses #771
- Adds Touchstone login buttons to the Login and Register pages
- Requires users with MIT email addresses to use that button on both pages
- Tweaks the login/register form a bit to more closely resemble the Invision design:
- https://projects.invisionapp.com/d/main#/console/14224393/298626344/preview
- https://projects.invisionapp.com/d/main#/console/14224393/298626353/preview
- Go to `/register`.  Click the `Touchstone@mit.edu` button and you should be redirected to `/login/saml?idp=default` (and then, [depending on your `.env` setup](https://github.com/mitodl/open-discussions/#7-testing-integration-with-saml-via-ssocircle), perhaps to SSOCircle or TestShib).
- Go back to `/register`.  Enter an MIT email (try a combo of lower and uppercase in the …
> Touchstone login UI

- static/scss/post.scss
none
two things:
- tighten up the profile image and name display:
before:
after:
- flip the icon for the 'share' button to match the mocks:
before:
after:
just check that it looks good and nothing is weird
> a few CSS tweaks for the post detail page

- static/js/components/auth/PasswordResetConfirmForm_test.js
- static/js/components/auth/PasswordResetForm_test.js
None
Fixes a warning
Travis output should not include any warnings
warnings should fail the javascript tests, but it looks like we check stderr for that and these particular warnings were in stdout... if that becomes an issue later on maybe we can figure out a more robust solution for it
> Change sandbox.create to createSandbox

- static/js/containers/ChannelModerationPage.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/containers/admin/EditChannelAppearancePage_test.js
- static/js/containers/admin/EditChannelBasicPage_test.js
- static/js/hoc/withPostModeration.js
- static/js/lib/channels.js
- static/js/lib/channels_test.js
Fixes #900 
Removes requests that fetch the moderators list. To check if the user is a moderator `user_is_moderator` is used instead.
Log in as a regular user and verify that you don't see the edit channel button on the channel page. Log in as a mod and verify that you do see this button. Also verify that the moderation tools in the post page look correct.
I didn't delete the reducer or API functions because we will need this soon for the moderator list page.
> Don't fetch from moderators list to check whether user is mod

- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/components/Embedly.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
- static/scss/createPost.scss
closes #870 
This updates the submit post form to match the latest designs (see linked from the issue). There are a few changes which necessitated re-writing some of the logic.
the user interaction now looks like 'adding' a text or url component to the form, rather than select a text post or link post tab. this means that we don't default to having one of those two things selected anymore. before we always had to have one of the two selected, which meant some complicated logic (especially when dealing with changing between subreddits, which might have different posting poermissions). with the new design, though, we default to having neither of the options selected, so things got a little easier.
make sure that things work smoothly and there are not issues! especially test edge cases …
> update submit post form

- static/js/containers/App.js
- static/js/containers/App_test.js
- static/js/containers/auth/PasswordResetPage.js
- static/js/lib/auth.js
- static/js/lib/auth_test.js
- static/js/lib/test_utils.js
Fixes #912
Refactors front-end redirect/load logic (including tests) and adds the touchstone link to the password reset page to agree with the MIT address form validation error
- Use the password reset page
- Try to get to the settings page and any channel page with a non-logged-in user with the `ANONYMOUS_ACCESS` feature on and off. Make sure it redirects as expected
> Fixed password reset UI and refactored redirect/load logic

- static/js/components/admin/EditChannelContributorsForm.js
- static/js/components/admin/EditChannelContributorsForm_test.js
- static/js/components/admin/EditChannelModeratorsForm.js
- static/js/components/admin/EditChannelModeratorsForm_test.js
- static/js/components/admin/EditChannelNavbar.js
- static/js/components/admin/EditChannelNavbar_test.js
- static/js/components/admin/MembersNavbar.js
- static/js/components/admin/MembersNavbar_test.js
- static/js/containers/admin/AdminPage.js
- static/js/containers/admin/EditChannelBasicPage.js
- static/js/containers/admin/EditChannelContributorsPage.js
- static/js/containers/admin/EditChannelContributorsPage_test.js
- static/js/containers/admin/EditChannelModeratorsPage.js
- static/js/containers/admin/EditChannelModeratorsPage_test.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/js/lib/channels.js
- static/js/lib/channels_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/scss/admin.scss
Part of #864 
Adds a members tab with moderator and contributor tabs inside it. These list the current moderators and contributors respectively. There is no UI to edit or delete moderators and contributors yet, that will be next PR.
As a moderator, click the edit channel link. Click on the members tab then each of the two tabs inside it. You should see a list of moderators and contributors.
Note that you will see a blank row for the system user which created the channel. At some point we should remove it but it's out of scope of this issue: #891
> Add readonly moderator and contributor tabs

- channels/api.py
- channels/views/moderators.py
- channels/views/moderators_test.py
Part of #864 
I originally assumed that a 403 wouldn't happen except in rare cases and that forwarding it from reddit breaks idempotent behavior if the user removes the moderator twice. However we need this status to have the frontend know if certain moderator operations failed.
N/A, no UI yet
> Don't silence 403 status for reddit moderator API

- authentication/api.py
- authentication/api_test.py
- authentication/backends/base_jwt.py
- authentication/backends/base_jwt_test.py
- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/strategy.py
- open_discussions/factories.py
- open_discussions/settings.py
- profiles/api.py
- profiles/api_test.py
- profiles/models.py
- profiles/models_test.py
- profiles/serializers.py
- profiles/serializers_test.py
- profiles/views.py
- profiles/views_test.py
Two for the price of one since they're both highly related to the refactor done here:
Fixes #871 
Fixes #841
- Ensures duplicate accounts don't happen (either via register or the user api)
- User API now creates `UserSocialAuth` objects (hardcoded to the MicroMasters provider)
- Test duplicate account creation
- Go to `/register` and start registration twice for the same email (so your receive two confirmation emails)
- Confirm clicking on the each link only allows creation of 1 account
- Test that creating a new MM user creates a `UserSocialAuth` record for them
> Standardize creating users and social auth

- authentication/api.py
- authentication/api_test.py
- authentication/backends/base_jwt.py
- authentication/backends/base_jwt_test.py
- authentication/management/commands/backpopulate_social_auth.py
- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/strategy.py
- open_discussions/factories.py
- open_discussions/settings.py
- profiles/api.py
- profiles/api_test.py
- profiles/models.py
- profiles/models_test.py
- profiles/serializers.py
- profiles/serializers_test.py
- profiles/views.py
- profiles/views_test.py
Based on #887, so it includes code form that, but the code for this is https://github.com/mitodl/open-discussions/pull/899/commits/9ad761b21e3ad28919b8725dabec55a6dedc78d1
Fixes #840 
Adds a command to backpopulate MM social auth for all users who don't have it. This code assumes (as is the case in production), that all users who exist only came in through MM up until now.
Run `./manage.py backpopulate_social_auth` and verify it creates `UserSocialAuth` records for those that don't have it.
> Backpopulate MM social auths

- open_discussions/views.py
- open_discussions/views_test.py
- static/js/components/ExternalLogins.js
- static/js/components/ExternalLogins_test.js
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/PasswordResetPage.js
- static/js/containers/auth/RegisterPage.js
- static/js/containers/auth/RegisterPage_test.js
- static/js/flow/declarations.js
- static/js/global_init.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
Closes #919 
Invalidates MIT emails and displays the Touchstone login button only if `FEATURE_SAML_AUTH=True`
- Set `FEATURE_SAML_AUTH=True` in your `.env` file
- The Touchstone login button should appear on login and register pages, and emails ending with `mit.edu` should be invalidated on those pages.
- Set `FEATURE_SAML_AUTH=False` in your `.env` file
- The Touchstone login button should not appear on login and register pages, and emails ending with `mit.edu` should be considered valid for registering.
> Make touchstone button & MIT email invalidation contingent on FEATURE_SAML_AUTH flag 

- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/lib/posts.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
closes #923 
closes #909 
This makes the changes necessary on the frontend to allow for empty text posts to go through, and also makes the change to only show the inputs for the allowed post type on channels which are not `LINK_TYPE_ANY`.
On channels which allow all types (or text posts) you should be able to submit an empty post (i.e. just a title) and you should be able to submit a link or text post as normal.
On channels which only allow one or the other type of post you should see just the input for the corresponding post type when you go to submit a post. You should not be allowed to submit an 'empty' post (without url) on a link-only subreddit.
also, if on a link or text only subreddit, you shouldn't see the little 'x' button that normally appears on the upper right of the post …
> make post body optional (frontend)

- channels/views/contributors.py
- channels/views/moderators.py
- open_discussions/permissions.py
- open_discussions/permissions_test.py
Part of #864 
Adds a check that users who are moderators can't moderate a channel which is managed by micromasters. Also some permissions refactoring
N/A
> Check on server that channels are not managed before letting users moderate them

- cassettes/channels.views.contributors_test.test_add_contributor_email.json
- cassettes/channels.views.moderators_test.test_add_moderator_email.json
- channels/serializers.py
- channels/serializers_test.py
- channels/views/contributors_test.py
- channels/views/moderators_test.py
- factory_data/channels.views.contributors_test.test_add_contributor_email.json
- factory_data/channels.views.moderators_test.test_add_moderator_email.json
Part of #864 
The REST API to add contributors and moderators by email wasn't working. This adds a fix for those cases and some tests which exercise the REST API view rather than just the serializer.
N/A, no UI yet
> Fix adding contributors and moderators by email

- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/components/SortPicker.js
- static/js/components/SubscriptionsList.js
- static/js/components/SubscriptionsList_test.js
- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
- static/js/containers/ChannelPage.js
- static/scss/_variables.scss
- static/scss/drawer.scss
- static/scss/layout.scss
- static/scss/navigation.scss
- static/scss/post-list.scss
- static/scss/profile-image.scss
- static/scss/sort-picker.scss
- static/scss/user-menu.scss
none
this makes a variety of little tweaks:
- profile image layout (in the toolbar up top) changed so that it is always a fixed 30px from the right edge of the screen, and also centered vertically (there was some `float: left` on there for some reason).
- add a little up or down arrow to the profile image menu
- make the drawer 300px wide, instead of 240px
- highlight 'home' in the left-side navigation sidebar the same way we do the current channel
- add 15px padding below the post list title and sort selector
- remove the channel breadcrumbs from the channel page
- remove the `"Sort:"` copy from the sort selector
...I think that should be it. Mostly cosmetic changes, not a whole lot that is functionally different.
Make sure all the things listed above work well, and nothing is broken. …
> layout tweaks

- static/js/components/admin/MembersNavbar.js
- static/js/components/admin/MembersNavbar_test.js
- static/js/hoc/withMemberForm.js
Part of #864 
Hides the contributors tab if the channel is public
For a public channel go to the members tab in the edit channel page. You should only see a tab for moderators.
> Add membership notice and alert tab visibility based on channel type

- open_discussions/permissions.py
- open_discussions/permissions_test.py
Fixed by #961 
Allows readonly view for the contributors API for moderators for channels managed by micromasters. Currently it forbids moderators from viewing the list of contributors but we only want to forbid the editing of the list.
Find a channel you are a moderator of. Mark a channel as managed by micromasters in the database. View the contributor list and verify that you don't get an error message (which you should see on master).
> Allow readonly contributor view for moderators for managed channels

- cassettes/channels.views.contributors_test.test_list_contributors.json
- cassettes/channels.views.moderators_test.test_list_moderators.json
- channels/views/contributors.py
- channels/views/contributors_test.py
- channels/views/moderators.py
- channels/views/moderators_test.py
- factory_data/channels.views.contributors_test.test_list_contributors.json
- factory_data/channels.views.moderators_test.test_list_moderators.json
Fixes #891 
Remove channel creator from contributor and moderator list in UI. No changes are made to the REST API, though it won't matter since no user will have permission to remove that user as moderator, and their contributor status doesn't matter if they are a moderator.
View the contributor and moderator list. You should not see any user with `<missing>`.
> Filter out indexing user from moderator and contributor lists

- static/js/components/ExternalLogins.js
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/RegisterPage.js
- static/js/containers/auth/RegisterPage_test.js
- static/scss/auth.scss
Closes #917 
Closes #930
- Adds a login link to the signup pages
- Adds a signup link to the login pages
Visit `/login` and `/signup`
Seemed pretty easy & sensible to combine these 2 issues into 1 PR
> Added login & signup links to the signup & login pages

- static/js/components/Embedly.js
- static/js/components/Embedly_test.js
- static/js/lib/embed.js
- static/js/lib/embed_test.js
- static/scss/embedly.scss
none
this fixes the 'rich' type embed display a little bit. basically, this just changes things so that, if the 'rich' type is an iframe, we do the same responsive iframe thingy we do for videos currently. sometimes, notably with wikipedia articles, 'rich' type embeds are *not* iframes, so we don't always want to do this.
Check that `<iframe>`-using 'rich' embeds render in a nice, full-width responsive container that looks like this:
(google docs are a good thing to test with)
Also test that the `.iframe-container` class (and associated styling) is *not* applied for rich embeds which are not iframes. Wikipedia articles are the main example of this that I know of, but there may be others. A wikipedia article should still look something like this:
> fix 'rich' embed display

- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
- static/js/containers/ProfileImage.js
- static/scss/profile-image.scss
closes #988 
closes #1003 
moves the profile dot to where it should be and also increases the size of the click area (just to encompass the little dropdown basically).
check that it appears in the bottom left of the user menu, and check that clicking on the little arrow opens the user menu too.
> fix location of profile dot

- static/js/lib/url.js
- static/js/lib/url_test.js
Closes #995 (Note: the issue title no longer reflects the actual issue being solved, read the comments).
Removes `www.` from the domain in a URL, unless the domain is something like `www.org`
Create some link posts, with urls like `http://www.nytimes.com`, `http://store.nytimes.com`, and `http://www.org`.  The domain listed next to each post title should be `nytimes.com`, `store.nytimes.com`, and `www.org` respectively.
> Update the urlHostname function to remove www. from beginning of domains

- mail/templates/comments/body.html
- mail/templates/frontpage/body.html
- notifications/notifiers/frontpage_test.py
- open_discussions/urls.py
- open_discussions/urls_test.py
Closes #994
Updates the links in the mail templates to include post slugs in the link URLs.  
- Create some new posts and comments.  
- In a shell:
```
from notifications.api import *
api.send_daily_frontpage_digests()
api.send_unsent_email_notifications()
```
- You should get some new emails, check that the post and comment links contain the post slugs and that they load the correct pages.
- Old URL's without the post slug should still work, example:
- `http://od.odl.local:8063/c/<channel_name>/<post_id>/` (post URL without post slug)
- `http://od.odl.local:8063/c/<channel_name>/2t/comment/2e/` (post comment URL without slug)
> Use urls with post slugs in emails

- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
Closes #1001 
Hides the comment section header (count + sort control) when there no comments on a post
Open the post detail page for a post with no comments
> Hide comment section header when post has no comments

- static/js/components/SharePopup.js
- static/js/components/SharePopup_test.js
Closes #1000 
Notifies a user via snackbar when URL is copied from the Share popup
Copy a URL in the Share popup, which can be seen on the post detail page
> Notify user via snackbar when URL is copied

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/scss/post.scss
closes #993 
This just adds links from the profile and comment displays to our profile page, so that users can look at each other's profiles and stuff.
Make sure that you can navigate to the users profile by clicking on the username shown in the post list, post detail page, and on a comment.
Styling and so on should look like it did before.
> link names to profile in comment and post displays

- authentication/views.py
- authentication/views_test.py
- open_discussions/factories.py
- static/js/components/ExternalLogins.js
- static/js/containers/AccountSettingsPage.js
- static/js/containers/AccountSettingsPage_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/scss/basic.scss
- static/scss/form.scss
- static/scss/settings.scss
Closes #922
Displays the 'saml' social auth provider type in the account settings page and makes some basic stylistic changes to that page based on various bits of feedback
Authenticate via Touchstone, or just hardcode a list of provider types that includes `'saml'` and return it in the `authentication.views.get_social_auth_types` view function
From a UI perspective, we decided we no longer care about the email associated with each particular auth type
> Touched up account settings UI and added SAML auth type

- authentication/exceptions.py
- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/serializers.py
- authentication/serializers_test.py
- authentication/utils.py
- authentication/views_test.py
- cassettes/authentication.views_test.test_login_register_flows[login_email_mm_only].json
- factory_data/authentication.views_test.test_login_register_flows[login_email_mm_only].json
- open_discussions/settings.py
#673 
Backend changes to require users with MM-only social auth to login via that method.
You could try to login with a micromasters-only user and verify you see the expected response from the backend. Dealing with the UI piece in a separate PR.
> Added API change to support prompting the user to login via MM

- cassettes/channels.views.moderators_test.test_add_moderator.json
- cassettes/channels.views.moderators_test.test_add_moderator_again.json
- cassettes/channels.views.moderators_test.test_add_moderator_email.json
- cassettes/channels.views.moderators_test.test_list_moderators.json
- cassettes/channels.views.moderators_test.test_list_moderators_many_moderator.json
- cassettes/channels.views.moderators_test.test_list_moderators_moderator.json
- cassettes/channels.views.moderators_test.test_list_moderators_staff.json
- channels/api.py
- channels/api_test.py
- channels/serializers.py
- channels/serializers_test.py
- channels/views/moderators.py
- channels/views/moderators_test.py
- factory_data/channels.views.moderators_test.test_add_moderator.json
- factory_data/channels.views.moderators_test.test_add_moderator_again.json
- factory_data/channels.views.moderators_test.test_add_moderator_email.json
- factory_data/channels.views.moderators_test.test_list_moderators.json
- factory_data/channels.views.moderators_test.test_list_moderators_many_moderator.json
- factory_data/channels.views.moderators_test.test_list_moderators_moderator.json
- factory_data/channels.views.moderators_test.test_list_moderators_staff.json
Part of #1004
Adds a field to the moderators REST API showing who can and can't be removed by the logged in user (who must also be a moderator)
View `/api/v0/channels/<channel_name>/moderators/` and verify that the `can_remove` field is True for you and other moderators, and False for older moderators
> Add can_remove field to serializers

- static/js/actions/ui.js
- static/js/components/admin/MembersList.js
- static/js/components/admin/MembersList_test.js
- static/js/containers/PostPage_test.js
- static/js/containers/ProfileImage_test.js
- static/js/containers/admin/EditChannelContributorsPage.js
- static/js/containers/admin/EditChannelContributorsPage_test.js
- static/js/containers/admin/EditChannelModeratorsPage.js
- static/js/containers/admin/EditChannelModeratorsPage_test.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/js/reducers/ui.js
- static/js/reducers/ui_test.js
- static/scss/admin.scss
Fixes #1004 
Fixes #971 
Fixes #938 
- Adds "Can't remove" text if the moderator is not removable due to being older than logged in user
- Adds confirmation dialog for removing a user
- Changes in text when the user you're removing is yourself
Go to the moderators page. You should likely see some moderator which says "Can't remove" instead of a "Remove" link. If not, add a new moderator, log in as that moderator and view the list again.
You should also see `You are a moderator of this channel` in the list, and `Leave` instead of `Remove` in the text. Click the link and you should see a dialog "Remove yourself?"
Find a user you can remove and remove them via the dialog to confirm that behavior still works. You should also be able to dismiss the dialog without anyone getting removed.
All of …
> Improvements to moderator/contributor UI

- authentication/serializers.py
- authentication/views_test.py
- cassettes/authentication.views_test.test_login_register_flows[login_email_not_exists].json
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/RegisterPage.js
- static/js/containers/auth/RegisterPage_test.js
Closes #931 
Changes the unrecognized email UX so a validation message is shown instead of redirecting the user to the signup page where they would click a button to continue signing up.
Enter an unrecognized email address in the login page
Back-end errors for the auth pipeline are essentially considered non-field errors. Getting the unrecognized email address to show up directly beneath the email input (as it does for normal front-end validation errors) would require some extra work. If we want to put in that extra work, that could be done in a different issue.
> Changed unrecognized email UX to a validation message

- static/js/components/material/Snackbar.js
- static/js/containers/App.js
- static/scss/_variables.scss
- static/scss/banner.scss
- static/scss/createPost.scss
- static/scss/form.scss
- static/scss/layout.scss
- static/scss/snackbar.scss
Fixes #1012 
Fixes various snackbar UI bugs (see the issue)
Check that the snackbar shows up correctly at various screen widths, with/without drawer, with long text, etc. 
The patch in this
gist adds a button to the content window that brings up a snackbar on click: https://gist.github.com/gsidebo/ea013f645e04a25f9e3518751aa99c7a
I simply set overflow to hidden, so any very long text will just be partially hidden
> Fixed snackbar UI bugs

- static/js/components/ProfileForm.js
- static/js/components/ProfileForm_test.js
None
Sets `value` to an empty string instead of null to silence warnings on uncontrolled React components
Edit the profile and make `bio` and `headline` empty. Save and refresh, then edit the profile. On master you should see an exception in the browser and a warning when running the tests. On this branch you shouldn't see any warning.
> Silence warning with empty profile fields

- authentication/views.py
- authentication/views_test.py
- profiles/serializers.py
- static/js/containers/auth/LoginPasswordPage.js
- static/js/containers/auth/LoginPasswordPage_test.js
- static/js/flow/authTypes.js
- static/js/lib/api.js
- static/js/lib/auth.js
- static/js/reducers/auth.js
- static/scss/form.scss
- static/scss/profile-image.scss
Closes #934
Changes the login UI to show a profile image and a greeting which includes the user's name when they enter a recognized email into the login form
Enter an email into the `/login` page that is associated with some email-authed user. Check that the profile image and name match. Also enter an email that doesn't exist and make sure that works as before
> Changed login UI to show image & name when email entered

- channels/views/channels.py
- channels/views/moderators.py
- channels/views/reports.py
- channels/views/subscribers.py
- fixtures/reddit.py
- fixtures/users.py
- open_discussions/permissions.py
- open_discussions/permissions_test.py
- profiles/permissions.py
Fixes #929 
Adds support for `user.is_staff`on our permission checks.
Go to `/manage/c/new` and verify you can create a channel in this branch but not in master.
> Updated staff permission to check user.is_staff for authenticated users

- static/js/components/ProfileForm_test.js
- static/js/containers/ProfilePage.js
- static/js/containers/ProfilePage_test.js
Closes #1048
Removes edit button from the profile image on the profile view page
- View your profile.  The image should not have an edit button (pencil icon) on it.
- Edit your profile.  The image should have a working edit button.
> Remove edit button from profile image on profile view page

- static/js/components/ProfileForm.js
- static/js/containers/ProfileImage.js
- static/js/containers/ProfileImage_test.js
- static/scss/basic.scss
Fixes #1080
Modifies the form layout and css so `ProfileImage` is not contained inside another form.
- On master branch, if you click on the profile image edit button on the profile edit form, one of several things may happen:
- the form will close immediately and return you to the profile page; or 
- the upload dialog will appear, but clicking on it closes the dialog
- On this branch, you should be able to upload a new profile image without any of the above issues.
> Fix profile image upload bug

- scripts/envs.sh
- webpack_dev_server.sh
Similar to https://github.com/mitodl/micromasters/pull/4112
Removes the env variable `IS_OSX` which was used to configure certain settings. With Docker for OSX we don't need this anymore.
Nothing should break on OS X
> Remove IS_OSX since it's unnecessary with Docker for Mac

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- Closes #911
If anything goes wrong with creating a new post or comment on reddit, a banner message should be displayed with the text "Something went wrong creating your <post|comment>. Please try again or contact us at <support_email>"
- Temporarily add a line to `channels.models.api.Api.create_post` to make it always raise an Exception:
```
raise ValueError('Fake Error')
```
- Go to the the post creation page, enter valid values, and submit the form.  The banner message should appear.
- Remove the modification to `Api.create_post` and resubmit the post form.  You should be redirected to the new post's detail page.
- Temporarily add a line to `channels.models.api.Api.create_comment` to make it always raise an Exception
- Go to the a post detail page, enter a comment, and submit the …
> Banner message if creating a post on reddit fails

- static/js/components/Embedly.js
- static/js/components/Embedly_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
Closes #1022 
Instead of displaying the embedly thumbnail url directly, makes another call to the embedly image api to resize it if necessary (max 500 or 600 pixels, based on embedly CSS styles `.photo img` and `.link .thumbnail img`).
Create some new link posts for links with images of various sizes; try direct links to images as well as links to URL's containing images.  Embedly should appear to work the same as before.  Inspect the URL of the displayed image; it should be in the form of `https://i.embed.ly/1/display/resize/?key=<key>&url=<source_url>&height=<500|600>&grow=false&errorurl=http://od.odl.local:8063/static/images/blank.png`
> Use embedly image api to resize thumbnails in Embedly component

- static/js/components/ExpandedPostDisplay_test.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/scss/post.scss
Closes #1052
On the post detail page for a link post, adds the domain and link icon in parentheses next to the title.
View a detail page for a link post, it should look similar to the [invision design](https://projects.invisionapp.com/share/DQNIO5IG2XA#/screens).
> Show domain and link icon next to post title

- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/components/SubscriptionsList.js
- static/js/components/SubscriptionsList_test.js
- static/js/components/admin/EditChannelAppearanceForm.js
- static/js/containers/ChannelAvatar.js
- static/js/containers/ChannelAvatar_test.js
- static/js/containers/ChannelBanner.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/scss/admin.scss
- static/scss/channel.scss
- static/scss/navigation.scss
Fixes #928 
Fixes #1061 
Adds channel avatars to sidebar and does some refactoring to make it look more like the mockup
View the channel sidebar and verify that the channels are grouped according to moderator status. Channels you're moderator of should have gear buttons which open the corresponding settings page for that channel
> Add channel avatar to sidebar

- static/js/components/admin/MembersList.js
- static/js/components/admin/MembersList_test.js
- static/js/containers/admin/EditChannelContributorsPage.js
- static/js/containers/admin/EditChannelContributorsPage_test.js
- static/js/containers/admin/EditChannelModeratorsPage.js
- static/js/containers/admin/EditChannelModeratorsPage_test.js
- static/js/hoc/withSingleColumn.js
Fixes #1068 
Shows the snackbar with an appropriate success message when the user adds or removes a moderator or contributor
Add and remove moderators and contributors
The PR is split in two commits, the first which adds the functionality and the second larger one which adds tests and does refactoring to move away from integration tests
> Show snackbar when user adds/removes a moderator/contributor

- package.json
- static/js/components/Grid.js
- static/js/components/Grid_test.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/PostPage_test.js
- static/js/hoc/withChannelSidebar.js
- static/js/hoc/withSingleColumn.js
- static/scss/layout.scss
closes #1007
This PR redoes our layout to use the material grid for column widths, instead of our own custom stuff. I added two react components, `<Grid />` and `<Cell />`, which are basically just divs with the right classes set on them. These can be used to make a material grid wherever we want. I went ahead and replaced the existing layout in our `singleColumn` and `withChannelSidebar` components with this setup.
Basically everything should look the same throughout the app, and things should behave at all screenwidths and so on. Code should make sense.
> add material grid

- static/js/components/Loading.js
- static/js/components/Loading_test.js
- static/js/containers/ChannelModerationPage.js
- static/js/containers/ChannelPage.js
- static/js/containers/HomePage.js
- static/js/containers/PostPage.js
- static/js/containers/ProfileEditPage.js
- static/js/containers/ProfilePage.js
- static/js/containers/auth/RegisterConfirmPage.js
- static/js/containers/auth/RegisterConfirmPage_test.js
Part of #1045 
Refactors `withLoading` to be a separate component, making it easier to write tests for #1045 
Nothing should break. Specifically you should be able to navigate to and from these pages:
- home page
- profile page
- profile editing page
- channel page
- channel moderation page
- post page
> Replace withLoading with Loading component

- static/scss/navigation.scss
Fixes #1113 
Tweaks CSS to enable sidebar scrolling
Try out different browser window sizes and make sure the sidebar scrolling looks good.
If there is enough room for everything the channel links should be on the top and the footer should be on the bottom. There should be no scroll bar visible and scrolling should not have any effect on the sidebar.
If there isn't enough room the channels should be right above the footer and you should see a scrollbar. If you scroll up or down it should act as expected
> Fix sidebar scrolling

- static/js/containers/Drawer.js
- static/scss/navigation.scss
address this additional scrolling issue:
this fixes an issue with the `flex` property, which seems to only show up in Chrome. I changed it to use `justify-content` to space things out instead.
> remove problematic CSS to fix scrolling

- channels/views/channels_test.py
- channels/views/comments_test.py
- channels/views/contributors_test.py
- channels/views/frontpage_test.py
- channels/views/moderators_test.py
- channels/views/posts_test.py
- channels/views/reports_test.py
- channels/views/subscribers_test.py
- embedly/views_test.py
- fixtures/users.py
- open_discussions/constants.py
- open_discussions/exceptions.py
- open_discussions/permissions.py
- open_discussions/permissions_test.py
- open_discussions/settings.py
- profiles/permissions_test.py
- profiles/views.py
- profiles/views_test.py
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/lib/fetch_auth.js
- static/js/lib/fetch_auth_test.js
- static/js/util/rest.js
- static/js/util/rest_test.js
Fixes #1100
- Swaps the order of the authentication classes
- This caused a change to status code handling for unauthenticated users: status codes that used to be 401 changed to 403 as the first authentication class error handling is used if no auth is provided and a 401 does not make sense for session auth (See https://github.com/encode/django-rest-framework/issues/5968#issuecomment-386519574 and http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses)
- Added an `error_type` field to error responses that serializes the value of `exc.__class__.__name__`
- Updated frontend checks against status codes of 401 and 403 to use this new field (`PostPage.js` and `fetch_auth.js` primarily).
- Verify the app works as usual as a logged in user
- …
> Make Session auth take priority over JWT tokens

- static/js/actions/ui.js
- static/js/containers/PasswordChangePage_test.js
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/LoginPasswordPage.js
- static/js/containers/auth/LoginPasswordPage_test.js
- static/js/containers/auth/PasswordResetConfirmPage_test.js
- static/js/containers/auth/PasswordResetPage_test.js
- static/js/containers/auth/RegisterDetailsPage_test.js
- static/js/containers/auth/RegisterPage_test.js
- static/js/reducers/auth.js
- static/js/reducers/ui.js
Fixes #1085 
Fixes a bug where entering an incorrect password removed the greeting, profile image, and email from the password login UI
Enter a bad password using the email auth flow, make sure that the profile image/greeting/email address are all still visible
I made several changes to JS test files that are not directly related to the bugfix. @rhysyngsun and I discovered that our tests for form submission events were not properly accounting for asynchronous requests, and that usage was preventing the testing of the action I added in this PR. It was an easy enough fix for the rest of the test cases so I went ahead and did that as part of this PR
> Fixed incorrect password UI bug

- package.json
- static/js/components/SortPicker.js
- static/js/components/SortPicker_test.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/HomePage_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/lib/sorting.js
- static/scss/channel.scss
- static/scss/comment.scss
- static/scss/form.scss
- static/scss/layout.scss
- static/scss/post-list.scss
- static/scss/post.scss
- static/scss/sort-picker.scss
- yarn.lock
this closes #987
This uses a material dropdown for picking how posts and comments are sorted, instead of the native browser `<select>` we were using before.
Make sure you can pick how things are sorted, and that everything works as it should. It should be nice to look at and so on.
> add material dropdown for picking sort method

- authentication/exceptions.py
- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/serializers.py
- authentication/views.py
- authentication/views_test.py
- cassettes/authentication.views_test.test_login_register_flows[login_email_saml_exists].json
- factory_data/authentication.views_test.test_login_register_flows[login_email_saml_exists].json
- open_discussions/factories.py
- open_discussions/settings.py
- static/js/components/ExternalLogins.js
- static/js/components/ExternalLogins_test.js
- static/js/components/auth/LoginGreeting.js
- static/js/components/auth/LoginGreeting_test.js
- static/js/components/auth/TouchstoneLoginButton.js
- static/js/containers/auth/LoginPasswordPage.js
- static/js/containers/auth/LoginPasswordPage_test.js
- static/js/containers/auth/LoginProviderRequiredPage.js
- static/js/containers/auth/LoginProviderRequiredPage_test.js
- static/js/containers/auth/RegisterPage.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
Closes #1058
Changes the login flow so that emails that match micromasters- or touchstone-authenticated users are shown a personalized greeting after the email is submitted
On the `/login` page...
- Enter an email for a user that has _only_ authenticated via Micromasters
- Enter an email for a user that has authenticated via Touchstone at any time (if you're running locally, you may have to fudge this - ask me for details if you need to do that)
In both cases, the name, email, and profile image should be shown to the user after submission, just like we do for users that have an email authentication
> Configured login flow to show greeting for external auth providers

- static/js/components/AddLinkMenu_test.js
- static/js/components/ChannelSidebar_test.js
- static/js/components/CloseButton_test.js
- static/js/components/CommentRemovalForm_test.js
- static/js/components/CommentVoteForm_test.js
- static/js/components/CreatePostForm_test.js
- static/js/components/ExternalLogins_test.js
- static/js/components/LoginPopup_test.js
- static/js/components/Navigation_test.js
- static/js/components/PostListNavigation_test.js
- static/js/components/PostList_test.js
- static/js/components/ReportForm_test.js
- static/js/components/SortPicker_test.js
- static/js/components/SubscriptionsList_test.js
- static/js/components/UserMenu_test.js
- static/js/lib/test_utils.js
none, just a little refactor I wanted to do
We do a lot of testing of simple components using enzyme's `shallow`. A common pattern is to declare a method that looks something like this:
```js
const renderComponent = (props = {}) => shallow(
<Component firstProp="hey" secondProp={someStub()} {...props} />
)
```
I think it's a good pattern, but we also do some other things in a few places. This PR basically just creates a new method, `configureShallowRenderer`, which lets you easily setup a simple test function which works like `renderComponent` above. You call it with your component and a default props object, and it returns a function which accepts optional extra props and returns an enzyme shallow wrapper. So using it looks like:
```js
let renderComponent
beforeEach(() => { …
```
> standard test pattern for 'shallow' rendered tests

- static/js/lib/fetch_auth.js
- static/js/lib/fetch_auth_test.js
- static/js/util/rest.js
- static/js/util/rest_test.js
Fixes #1149
Additionally checks for an `error_type` of `"AuthorizationFailed"` for expired JWTs and other JWT failure modes
Test the following in master and this branch:
- In MM `.env` set:
- `OPEN_DISCUSSIONS_JWT_EXPIRES_DELTA=30` (30 seconds).
- `OPEN_DISCUSSIONS_REDIRECT_URL=http://od.dev.local:8063/`
- Login to MM and click the "view all" link for discussions
- Logout from MM
- Wait for your JWT to expire, reload the page:
- This should give you the error page in master and the /auth_required/ page in this branch
- If you don't see the expected behavior, you may need to delete your sessionid cookie, which production users encountering this issue would not have
> Add handling for AuthorizationFailed on expired JWTs

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/components/CommentTree.js
- static/js/components/ReplyButton.js
- static/js/components/ReplyButton_test.js
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/lib/util.js
- static/scss/form.scss
- static/scss/popup.scss
Closes #1051
- Adds the `LoginPopup` to comment Reply buttons and the post reply text area.
- When logged in, the comment reply buttons and post reply form on a post detail page should work the same as before.
- When not logged in, the comment reply buttons and post reply form should still be rendered.  Clicking on a reply button or the text area of the post reply form should cause the `LoginPopup` to appear (just under the clicked Reply button, or over the post reply text area).  Clicking again outside the popup or text area should make the popup disappear.
> LoginPopup for comment reply buttons and post reply form

- package.json
- static/js/entry/root.js
- yarn.lock
Fixes #1140
Adds a polyfill for `toBlob`
Image uploads (profile, banner) should still work on Mac/Linux
To test on Edge:
- [Download, import, and run the Edge Virtualbox VM from Microsoft](https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/)
- In your `.env` file, set `WEBPACK_DEV_SERVER_HOST=10.0.2.2` and restart docker containers
- In the Edge VM, start Edge and navigate to `http://10.0.2.2:8063`
- Log in with an email account, then upload an image for your profile and save.  It should work.
> Fix image uploads on Edge and iOS

- static/js/actions/comment.js
- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/containers/PostPage.js
- static/js/reducers/comments.js
- Fixes #1069
- Adds a `clearCommentError` dispatch action, similar to `clearPostError`, to prevent an error page being shown after an error occurs creating a comment.
- Go to a post detail page.
- Make comment posting certain to fail by turning off the reddit vagrant box; or adding `raise Exception()` to the beginning of the `channels.api.create_comment` method.
- Reply to the post or an existing comment with a new comment and click Submit.
- An error banner should appear at the top of the page and the post page should still display correctly.
- The same should happen if you edit one of your existing comments and click Submit.
> Don't show an error page if comment posting fails

- static/js/components/Embedly.js
- static/js/components/Loading.js
- static/js/components/Loading_test.js
- static/js/containers/ChannelModerationPage.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/js/containers/HomePage.js
- static/js/containers/PostPage.js
- static/js/containers/ProfileEditPage.js
- static/js/containers/ProfilePage.js
- static/js/lib/constants.js
- static/js/util/integration_test_helper.js
- static/scss/embedly.scss
Closes #1050
Adds a loading animation that shows some dummy empty post elements while posts are being loaded
Visit the home page or any channel page and observe the loading behavior. If you want to render the loading animation permanently, you can change `static/js/components/PostLoading.js` line 63 to: `if (true) {`
`static/js/components/PostLoading.js`
- ~~Some of the `PostLoading.js` code was copied over from `Loading.js`. I figured this was small, isolated, and unlikely to be repeated~~ No longer relevant
- I was thinking about possibly rendering this animation HTML by default and hiding/revealing it instead of rendering it fresh every time a list of posts needs to load. I figured any performance penalty would be small enough that it wasn't worth spending a lot of time on for this PR, …
> Added empty post loading animation when posts are being loaded

- package.json
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- yarn.lock
Closes #1156
Installs the [validator.js](https://www.npmjs.com/package/validator) module and uses its `isURL` function to validate a new link post's URL before calling embedly.
Create a new link post and enter different values for the URL.  Embedly should not be called until a valid URL is entered, such as `http://reddit.com` or `reddit.com`.
> Validate a new link post URL before calling embedly

- static/js/components/CompactPostDisplay.js
- static/js/containers/ChannelModerationPage.js
- static/js/containers/ChannelModerationPage_test.js
- static/js/containers/PostPage_test.js
- static/js/hoc/withCommentModeration.js
- static/js/hoc/withPostModeration.js
Fixes #1118 
Fixes #1157 
- Adds tests for `ChannelModerationPage`, also touching functionality in `withCommentModeration` and `withPostModeration`
- Filter on the event type to prevent double execution
Remove a post and verify that no console error is caused. Note that the post will still be there, that is not changed in this PR.
> Add tests for ChannelModerationPage, fix remove post error

- authentication/middleware.py
- authentication/middleware_test.py
- open_discussions/settings.py
- static/js/actions/index.js
- static/js/containers/App.js
- static/js/containers/App_test.js
Fixes #1057
This fixes this issue by displaying a banner with the PSA error message in it. To do so, it also removes the `django.contrib.messages` app, since that causes PSA to write the messages to a cookie, which is more complex to handle and we're not actually using messages in any way elsewhere anyway.
- Login to discussions as one user via email (User A)
- Login to discussions as another user via MM (User B)
- You should remained logged in as User A, but see a banner message indicating the MM account was already linked.
> Added banner message for PSA error messages

- open_discussions/urls.py
- static/js/components/ChannelBreadcrumbs.js
- static/js/components/ChannelBreadcrumbs_test.js
- static/js/components/ChannelSidebar.js
- static/js/components/ChannelSidebar_test.js
- static/js/components/CommentRemovalForm.js
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/components/ReportCount.js
- static/js/components/admin/EditChannelNavbar.js
- static/js/components/admin/EditChannelNavbar_test.js
- static/js/containers/App.js
- static/js/containers/admin/AdminPage.js
- static/js/containers/admin/ChannelModerationPage.js
- static/js/containers/admin/ChannelModerationPage_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/scss/_variables.scss
- static/scss/admin.scss
- static/scss/comment.scss
- static/scss/dropdown-menu.scss
- static/scss/post.scss
- static/scss/reports.scss
Fixes #1125 
Moves the moderation page into a tab in the edit channel pages, and makes modifications to the look and feel specified by the mockups
View the moderation page and interact with it
> Move channel moderation page

- cassettes/channels.views.subscribers_test.test_add_subscriber_mod.json
- channels/views/subscribers.py
- channels/views/subscribers_test.py
- factory_data/channels.views.subscribers_test.test_add_subscriber_mod.json
- static/js/containers/admin/EditChannelModeratorsPage.js
- static/js/containers/admin/EditChannelModeratorsPage_test.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/js/lib/redux_rest.js
- static/js/reducers/channel_contributors.js
- static/js/reducers/channel_moderators.js
- static/js/reducers/channel_subscribers.js
- static/js/reducers/channel_subscribers_test.js
Fixes #1168 
The UI for adding a moderator now also makes a call to add the user as a subscriber also. 
The permissions for adding a subscriber are altered slightly so moderators can add other moderators for the channels they moderate as a subscriber. *Note*: this means that via the REST API any moderator can add any user as a subscriber to their channel, even if they are not also adding the user as a moderator.
Add a moderator and view the network tab. You should see a successful addition of the moderator user as a subscriber.
Log in as the moderator user and verify that they have the channel listed on the left side.
> Add subscriber when a moderator adds another moderator

- static/js/components/admin/EditChannelBasicForm.js
- static/js/components/admin/EditChannelBasicForm_test.js
- static/js/containers/admin/EditChannelBasicPage.js
- static/js/containers/admin/EditChannelBasicPage_test.js
Closes #1188 
Fixes #1198
Adds `description` (different from `public_description`) to the basic channel form, and tweaks the `onUpdate` function to fix a bug (#1198)
- Go to the basic tab of the channel edit page. 
- Uncheck one or both of the `Allowed post type` checkboxes.
- Change the 'Type' option (public, reserved, private).  `Allowed post type` should not change as a result.
- Enter text for the description.  `Allowed post type` checkboxes should not change as a result.
- Save the form.  There should be no errors.  Reload the page.  Your changes should still be in effect.
> Add description to basic channel form

- authentication/api.py
- authentication/api_test.py
Closes #1162 
This avoids creating the situation in #1162 by removing error catching around a reddit API and allowing that error to rollback the user transaction and avoid the user ending up in a partial state. 
In practice this means we're effectively adding a 500, but that is a valid response for what happened and we want to know because it means the backend is down and MM should retry the request later.
- Start, OD and MM, but make sure the reddit backend is stopped
- Register a new user and verify that the result fails with a 500 instead of a 200 and no user was created.
> Allow reddit errors to fail user creation

- cassettes/channels.views.posts_test.test_post_anonymous[False].json
- cassettes/channels.views.posts_test.test_post_anonymous[True].json
- channels/views/posts_test.py
No ticket - related to #1192 and relevant to the pytest tech talk
Groups into a class some similar tests that test a single endpoint and need similar test data setup.
Test suite should pass, and tests should make sense
- This finishes some refactoring work that was started in #1192
- This PR (hopefully) provides a good example for fixture-ization, using named properties for related test data, and general reduction of boilerplate
> Grouped channel post view tests together w/ common test scenario

- static/scss/navigation.scss
closes #1200
this fixes the `z-index` on the toolbar (top nav bar thingy) so that the comment menu can't show up on top of it. the dropdown menus have a `z-index` of 10, so that they show up on top of everything around them. the toolbar previously had 4, I set it to 40 (somewhat arbitrarily).
make sure you can reproduce the bug described in the linked issue, then make sure this fixes it
> fix toolbar z-index

- static/scss/navigation.scss
we took one approach to this in #1153, this changes out for another
changes the line breaking behavior of the titles in the navigation drawer, just so that lines with long words aren't broken in the middle of the word (as often).
Make some longer channel names, with long words in them, and make sure that things aren't all wacky.
> fix issue with over-eager linebreaks

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
closes #1216 
this fixes the comment share url, so that it is an absolute URL and not a relative one.
check that the URL in the comment share popup is an absolute one.
> fix comment share url

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/scss/popup.scss
Fixes #1182
Fixes #1228
- Shows the LoginPopup in the comment textarea via onChange and onFocus events instead of onClick.
- Fixes CSS for the LoginPopup login button
- Go to a public post detail page as an anonymous user
- Use the tab key to navigate to the comment form.  The LoginPopup should appear you tab into it.
- Close the popup, then click inside the textarea.  The popup should appear again.
> Show LoginPopup in comment textarea via focus/change events

- static/js/components/auth/AuthEmailForm.js
- static/js/components/auth/AuthEmailForm_test.js
- static/js/components/auth/AuthPasswordForm.js
- static/js/components/auth/AuthPasswordForm_test.js
- static/js/components/auth/PasswordResetForm.js
- static/js/components/auth/PasswordResetForm_test.js
- static/js/containers/ImageUploader.js
- static/js/containers/admin/EditChannelContributorsPage.js
- static/js/containers/admin/EditChannelModeratorsPage.js
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/LoginPasswordPage.js
- static/js/containers/auth/LoginPasswordPage_test.js
- static/js/containers/auth/PasswordResetPage.js
- static/js/containers/auth/PasswordResetPage_test.js
- static/js/containers/auth/RegisterPage.js
- static/js/flow/formTypes.js
- static/js/hoc/withForm.js
- static/js/hoc/withForm_test.js
- static/js/lib/forms.js
- static/js/lib/forms_test.js
Fixes #1129 
Fixes #1130 
- Changes our form component (HOC) to accept some optional functions that detect HTTP response errors and 'coerce' them to form validation errors
- Example case: a user enters an unrecognized email in a form, and the HTTP response indicates that the email doesn't exist. You can now define a function that inspects that response and returns an object mapping that error message to the 'email' field of the form
- Updates several components to define these functions
- Removes some behavior that treated HTTP endpoint state as UI state (more on that in the background context section)
Try both of these cases and check to see if the given error shows up like a validation message
- Enter an unrecognized email on the login page (/login), password reset page …
> Changed HTTP response error handling to behave like form validation

- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/components/ReportCount.js
- no migrations
- no settings changes
Fixes #
Changes the text "Reported 2 times" to "2 Reports" 
1. Report a post
2. As a moderator, view the post summary card for the reported post. 
3. The text should read "1 Report" 
4. As another user, report the post again. 
5. The text should read "2 Reports" 
1. Report a comment
2. As a moderator, view the reported comment
3. The text should read "1 Report"
You can also view this on the reports tab of the channel settings. 
I'll add one if I can get the review build to work.
> ## Reports instead of Reported ## times

- static/js/containers/policies/ContentPolicyPage.js
fixes #1173 
removes mention of MicroMasters-specific text from the Community Guidelines page
take a look at /content_policy and command-find for 'MicroMasters'
> remove 'MicroMasters' from community guidelines

- static/js/components/ChannelSidebar.js
- static/js/components/Grid.js
- static/js/components/Grid_test.js
- static/js/components/Loading.js
- static/js/components/admin/EditChannelAppearanceForm.js
- static/js/containers/ChannelAvatar.js
- static/js/containers/ChannelPage.js
- static/js/containers/ChannelPage_test.js
- static/scss/_variables.scss
- static/scss/admin.scss
- static/scss/channel-banner.scss
- static/scss/channel.scss
- static/scss/layout.scss
- static/scss/loader.scss
- static/scss/profile-image.scss
closes #989 
this adds the channel avatar and the banner to the channel page. it also shows the channel title and the headline up there (the headline only if it's been set).
make sure that the things described above show up. it should look ok and so on. everything should work decently well on mobile as well.
here's what it looks like with the gradient:
here's with an image:
one possible concern is that certain images will make the headline and channel title text pretty hard to read (as the one above does, for instance).
> add channel header to channel page

- static/scss/_variables.scss
- static/scss/comment.scss
- static/scss/post.scss
Closes #1241
Increases comment text size and introduces variables to standardize 
Look at posts and comments in different views, compare to designs like [this](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4f573f5019c5726109435)
Even though they are set to the same value right now, I created two different values for the author font size and the post/comment font size in case we want those to be different in the future.
> Increased comment text size

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/scss/comment.scss
- static/scss/post.scss
Closes #1225 
Converts the "X days ago" text on comment cards and compact post cards to links that should bring that user to the post detail page (and particular comment).
- Go to a channel page.  The "X days ago" text for each post should look the same as before (gray color).  Clicking on it should bring you to the post detail page.
- Click on the "X days ago" text next to a comment.  It should load the post detail page with that comment/thread only showing.
> Convert "days ago" text to post/comment link

- static/js/components/Markdown.js
- static/js/components/Markdown_test.js
- static/scss/editor.scss
- static/scss/extensions.scss
- static/scss/layout.scss
- static/scss/markdown.scss
closes #1208 
this fixes the styling for blockquotes in posts, both when display and when editing.
Make a new post, or edit an existing post, which includes a blockquote. It should look like what's shown here: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4f573f5019c5726109435
it should look the same in the editor component and when it's being displayed.
> fix appearance of quoted text in posts

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
~Blocked: Should not be merged until after #1234 is merged.~
Closes #1224
- Removes the "show thread" option from the comment dropdown menu
- Hides the icon for displaying the dropdown if user is anonymous (because there's nothing to select)
- While logged in, click the icon to open the dropdown menu for a comment. "Show this thread" should not be one of the options.
- While anonymous, the icon for the comment dropdown menu should not be visible.
> Remove "Show thread" from comment dropdown 

- static/scss/profile-image.scss
- static/scss/user-menu.scss
Fixes #1238
Fixes styling for incomplete profile indicator so that it no longer pushes up the profile image
Check the profile image with a user that has an incomplete profile (or just edit the `static/js/components/UserMenu.js` code to always show the icon)
Dotted border added as a visual aid – compare with screenshots in the issue
> Fixed styling for incomplete profile indicator

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/containers/PostPage.js
- static/js/containers/admin/ChannelModerationPage.js
- static/js/lib/channels.js
- static/js/lib/channels_test.js
Closes #1231 
Hides social sharing buttons for private channel comments (those buttons were already hidden for private channel posts)
Click the 'share' icon under a private channel comment. You should only see the clipboard copying UI
> Hid social sharing buttons for private channel comments

- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/lib/validation.js
Fixes #1215 
Alters the `CreatePostPage.componentDidUpdate` logic so that if the new post form is switched to a channel that accepts both text and link posts, and both the text and url form values are null, those input fields will be hidden if visible and the post type buttons will be displayed instead.
- Create a few channels, one that accepts any post types, one that accepts only link posts, one that accepts only text posts.
- From the home page, click 'Compose' to create a new post. Select the links-only channel.  The URL field should appear. Don't put anything in it, and switch to the 'any' channel.  The URL field should disappear and you should see the post type buttons.
- Select the link post type.  Don't put anything in the URL field.  Switch to the links-only channel.  The URL …
> Show post type buttons after switching channels if empty

- static/scss/auth.scss
closes #1267 
fixes the display for the auth cards at all page widths
Look at various auth pages and make sure that the display bug shown in the attached issue doesn't crop up anywhere. make sure you're testing in the chrome device simulator or a mobile device emulator.
> fix display of auth cards at all screen widths

- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/scss/_breakpoints.scss
- static/scss/post.scss
closes #1255 
Fixes the display of the author name, profile image, headline, and date on the post page, specifically to avoid the case where longer headlines could cause the date, headline, and author name to wrap in an ugly way on narrower screen widths.
Give yourself a good long headline and / or name, and make sure that things look alright on all screenwidths.
Note that because of the squeezing of the main page content by the nav drawer on desktop widths I had to use the 'mobile' display for screen widths up to 1150px. Otherwise there's a sort of twilight zone between where we switch over to the desktop nav and the point where the screen gets wide enough for things not to run into each other in the 'desktop' configuration (around 1150px).
> fix author line display on post card

- authentication/serializers.py
- authentication/utils.py
- authentication/views_test.py
- open_discussions/settings.py
- static/js/containers/auth/AuthRequiredPage.js
- static/js/containers/auth/AuthRequiredPage_test.js
- static/js/containers/auth/LoginPage.js
- static/js/containers/auth/LoginPage_test.js
- static/js/containers/auth/RegisterPage.js
- static/js/containers/auth/RegisterPage_test.js
- static/js/flow/authTypes.js
- static/js/lib/api.js
- static/js/lib/auth.js
- static/js/lib/fetch_auth.js
- static/js/lib/fetch_auth_test.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/js/reducers/auth.js
Fixes #709 
Adds support in the frontend and backend for redirecting the user back to the `next` url as per normal djanog conventions. PSA already supports this so MM and touchstone logins are already covered. The backend changes support it for email login. PSA stores this all on the session cookie, so this behavior won't work cross-browser/device in the case of registration.
As a logged out user, try to navigate to a private channel and verify you end up there through the login flows.
> Add support for the next param for login/register

- static/js/components/Embedly.js
- static/js/components/Loading.js
Fixes #1171 
Fixes console warning by replacing invalid percent in `viewBox` with a dimension.
Edit `Embedly` in `Embedly.js` to always display `EmbedlyLoader` instead of only displaying it while the content is loading. In `Loading.js` edit the `WithLoading` render method to always render `<LoadingComponent />`.
Check out master and view a post. Resize the browser to various dimensions and note what the loader looks like. Go to the channel page and note that there are 5 post loaders and another small loader at the top. Resize the browser and note what they look like.
Switch to this branch and refresh the page. Resize the browser to various dimensions and make sure that the loaders on the channel page and the one on the post page match what you saw in master. Also note that the console …
> Replace percent with viewport dimensions

- channels/serializers.py
- channels/utils.py
- channels/utils_test.py
- channels/views/posts_test.py
- open_discussions/urls.py
- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
- static/js/lib/url_test.js
Closes #1278 
- Modifies `channels.utils.get_reddit_slug ` to replace underscores in the slug with dashes 
Click on links posts that have spaces in their titles, and links to comments for those posts.  The post slug in each URL should have dashes but no underscores.
> Replace underscores with dashes in post slugs

- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/lib/util.js
- static/js/lib/validation.js
Closes #1264 
Refactors some potentially confusing logic around updating the post creation form when the selected channel changes
Click through channels of different types while looking at the post creation page. Make sure the form updates as expected
- I already wrote most of the code for this in a previous PR review, so it was easy enough to put together this PR
- The test parameters I deleted in `static/js/containers/CreatePostPage_test.js` were impossible scenarios
> Refactored form update logic on post creation page

- static/js/components/Dialog.js
- static/js/components/admin/EditChannelMembersForm.js
- static/js/components/admin/MembersList.js
- static/js/components/admin/MembersList_test.js
- static/js/containers/admin/EditChannelContributorsPage.js
- static/js/containers/admin/EditChannelContributorsPage_test.js
- static/js/containers/admin/EditChannelMembershipPage.js
- static/js/containers/admin/EditChannelModeratorsPage.js
- static/js/containers/admin/EditChannelModeratorsPage_test.js
- static/scss/admin.scss
- static/scss/button.scss
- static/scss/form.scss
- static/scss/layout.scss
- static/scss/link.scss
closes #1246 
this just fixes some styling issues (see the list on the attached issue) for the channel members page. while I was in there I did some refactoring to remove duplicated and / or unnecessary code.
make sure that the channel moderators pages look good, and that all functionality is retained (i.e. you should be able to add and remove moderators and contributors, the dialogs should all work, etc). Things should implement the changes listed on the issue as well.
here's a basic screenshot:
> fix styling for channel members tab

- static/js/components/CommentForms.js
- static/js/components/CommentVoteForm.js
- static/js/components/FollowButton.js
- static/js/components/LoginPopup.js
- static/js/components/LoginPopup_test.js
- static/js/components/PostUpvoteButton.js
- static/js/components/ReplyButton.js
- static/js/components/SharePopup.js
- static/js/lib/util.js
- static/scss/_variables.scss
- static/scss/popup.scss
Closes #1222 
Changes the contents and styling of the login tooltip/popup for anonymous users ([example design in Zeplin](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5baa6eca6d1346b3722eae78))
Go to a post page as an anonymous user. 
The issue wasn't very clear about which popups should be updated, so I only updated the popups for the cases where users focus on the post reply textarea and where they click the 'Reply' link under a comment. I left the contents for all other popups untouched
(unchanged)
> Updated login tooltip prompt for anon users

- static/js/components/SubscriptionsList.js
- static/js/components/SubscriptionsList_test.js
- static/js/containers/ChannelBanner.js
- static/js/containers/ChannelBanner_test.js
- static/js/containers/ChannelPage.js
- static/scss/channel-banner.scss
- static/scss/channel.scss
closes #1271 
closes #1291 
This moves the edit icon up to the channel banner on the channel page, and removes it from the nav sidebar.
To get this to work I had to fiddle with the styling of the channel banner and the stuff that goes above it a little bit - I think it's cleaner now, in any case.
If you are looking at a channel you should see an edit icon up top, provided you're a moderator. If you're not, you shouldn't see it. The layout should also do alright with resizing the screen horizontally - the stuff in the channel banner up top should always be justified to the same width as the post list and everything else on the page.
desktop:
mobile:
> move the channel edit button to channel banner

- channels/management/commands/set_channel_allow_top.py
N/A
Fixes a silly mistake in filtering the channels by name in the command. `options['name']` is a list, so we needed `name__in=?`.
Run the command against a single channel name
> Fixed the --name arg to the set_channel_allow_top command

- static/js/components/LoginPopup.js
- static/js/components/Navigation.js
- static/js/components/Navigation_test.js
- static/js/containers/Drawer.js
- static/js/containers/Drawer_test.js
- static/js/factories/util.js
- static/scss/drawer.scss
- static/scss/popup.scss
Closes #1227 
Adds the compose button back into the drawer for anonymous users and shows the signup prompt when it's clicked
Click the "Compose" button as an anonymous user
> Added login popup/tooltip to drawer compose button

- hot-reload-dev-server.js
- package.json
- static/js/storybook/addons.js
- static/js/storybook/config.js
- static/js/storybook/index.js
- static/js/storybook/webpack.config.js
- webpack.config.dev.js
- yarn.lock
none
This just hacks together a storybook configuration that we can use to develop our components in an isolated way.
It needed a bit of hacking to get it to work. In particular, I had to use our existing webpack configuration for storybook, instead of the one it ships with. Some info about that here: https://storybook.js.org/configurations/custom-webpack-config/
This also just sets up the bare minimum to get it working: a config dir in `static/js/storybook`, a file with a few super basic stories to get us started, and an import for `layout.scss` so our components are styled.
I think there's a lot more we can add, but I thought it might be good to just merge this so people can play around with it and see what they think. I'm going to try using it to simplify our `<a>` and `<Link />` …
> try out using Storybook for component development

- static/js/components/CommentRemovalForm.js
- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/UserMenu.js
fixes #1301
Shortens "Remove Content" and "Approve Content" in the overflow menus of post summary cards and comment cards to "Remove" and "Approve"
1. Channel Listing page: post summary card overflow menu should have item "Remove" instead of "Remove Content"
2. Post Detail page: overflow menu should have item "Remove" instead of "Remove Content"
3. After removing the post, the overflow menu should update with "Approve" instead of "Approve Content"
4. Comment card overflow menu should have item "Remove" instead of "Remove Content"
3. After removing the comment, the overflow menu should update with "Approve" instead of "Approve Content"
Did tests pass?
> Shorten menu options

- static/js/hoc/withChannelTracker.js
- static/js/hoc/withChannelTracker_test.js
Fixes #1306
Triggers a channel-specific pageview to Google Analytics when a channel/post URL is loaded without navigating to it from within the app.
- Set `GA_TRACKING_ID` to any value in your `.env` file.
- In django admin, enter a fake google analytics tracking id for a channel (different from above).
- Manually enter the URL for that channel, and a URL for any post in that channel, into a browser tab, with network console open.  For each URL, two `collect` calls to Google Analytics should be made, one of which should be for the above tracking id, the other for the main tracking id.
- Navigate to Home, then navigate back to the channel, and then a post in that channel.  Two calls should be made for each of that channel's URLs.
> Channel-specific analytics should trigger on direct URL load

- static/js/components/ImageUploaderForm.js
closes #1127 
This changes the text we display in the image upload dialog box, to match what is on the mockups (see the linked issue).
Go to one of the image upload things, and make sure that you see something along the lines of the mockups there.
> change the message shown in the image upload dialog box

- static/js/components/ImageUploaderForm.js
none, something I forgot about when working on #1338 
just puts `type="button"` on a button in the dialog box, to avoid an issue with default button behavior (see #1322 for details)
look at the image upload thing, and click the button. it should just open the file upload dialog, instead of sending you back to the channel page.
> make the button on the image uploader form have type="button"

- static/js/components/Loading.js
- static/scss/channel.scss
none
fixes a little style regression. when I made changes to add the channel banner to the top of the channel page I also changed things to set `margin-top: 0;` on the channel page. This had the side-effect of getting ride of the top padding when the loader animation was playing, so it looked like this:
I meant to scope the `margin-top: 0;` to just when the page had loaded. This PR does just that, so it looks like this:
reload the channel page, make sure the change described above is there.
> fix spacing for top of channel loading component

- channels/serializers.py
- channels/views/frontpage_test.py
- channels/views/posts_test.py
- channels/views/reports_test.py
- channels/views/test_utils.py
- mail/api.py
- mail/api_test.py
- mail/templates/comments/body.html
- mail/templates/email_base.html
- mail/templates/frontpage/body.html
- mail/templates/frontpage/subject.txt
- mail/templates/password_reset/body.html
- mail/templates/verification/body.html
- mail/views.py
- notifications/notifiers/comments_test.py
- notifications/notifiers/email_test.py
- notifications/notifiers/frontpage_test.py
#1325 
Updates email templates and fixes a bug where `{{ site_name }}` is not being set in the email context. Also updated quite a few tests to use the default response data stuff @gsidebo wrote to cut down on the amount of code.
Go to `/__emaildebugger__/` and test render the frontpage email and verify it matches the mockup (sans thumbnail images which we're still skipping)
> Third pass of email templates

- authentication/pipeline/user.py
- channels/api_test.py
- channels/serializers.py
- open_discussions/settings_test.py
- pylintrc
- search/indexing_api.py
- search/task_helpers.py
- test_requirements.txt
Closes #1349
Prevents asteroid warnings (deprecations, etc) from showing up after running tests locally.
Run `docker-compose run web tox`.  There should not be a huge stream of asteroid warnings afterward.
> Hide useless asteroid warnings when running tests

- static/scss/home-page.scss
closes #1359 
adds some phone-specific styling for the welcome card, so it doesn't get cut off on narrow widths.
Use chrome or something that can simulate the width of an iphone 5 / 5s / SE and make sure that the welcome card looks alright.
The iphone 5 screen is 320px wide. I looked on our google analytics, and looking through the top 40 screen sizes (by number of users) we've seen that is the narrowest screen width, so I don't think we need to worry about anything smaller than 320px.
> fix styling of intro card on mobile

- static/js/components/CreatePostForm.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
closes #1366 
fixes two issues:
- Adds URL validation to check that a URL is valid to the post create form. We already use the same library to validate URLs before we submit the URL to embedly.
- adds `type="button"` to the 'cancel' button on the create post form. not having this was creating a strange issue, where hitting 'enter' in the 'url' field would trigger the `onClick` handler on this button, so you would go back to the previous page. Adding `type="button"` fixes this.
Go to the 'create post' page, and try adding a link post. If you type in an invalid url, like `ffff`, and try to click the 'Post' button, you should see an error like in the screenshot below. If you add a valid URL you should be able to go ahead and make the post.
Also, try to reproduce the error described above …
> fix post form validation for URL validity

- authentication/views.py
- mail/templates/comments/body.html
- mail/templates/frontpage/body.html
- mail/templates/password_reset/body.html
- mail/templates/verification/body.html
Fixes #1361
Fixes #1360
Fixes some font sizing issues that crop up in OSX and friends.
Also adds `use_new_branding` to the context for password reset to fix #1360
Test the frontpage email in the debugger and verify it looks ok
@pdpinch @Ferdi, this is the PR for the test email I sent both you
> Added fixes for email template font issues

- mail/api.py
- mail/api_test.py
- mail/verification_api.py
- mail/verification_api_test.py
- notifications/notifiers/email.py
Fixes #1381
Adds `context_for_user` to the verification api call so the template gets this common data.
> Fixed template context for email confirmation emails

- authentication/serializers.py
- authentication/utils.py
- authentication/views_test.py
- cassettes/authentication.views_test.test_login_register_flows[register_mm_exists].json
- factory_data/authentication.views_test.test_login_register_flows[register_mm_exists].json
- static/js/containers/auth/LoginPage.js
- static/js/flow/authTypes.js
- static/js/lib/api.js
- static/js/lib/auth.js
- static/js/lib/auth_test.js
Fixes #1364 
Fixes the register API so it doesn't error and instead causes the UI to prompt the user to login with MM.
Also refactored the `extra_data` code so it is a little cleaner and standard across all responses and in the frontend.
Try to register with an email for an account that already exists and only has a MM social auth. You should see no error and instead be prompted to login with MM.
> Fix registration for MM-only accounts

- static/scss/post.scss
This reverts commit 03870aac2432432e21eec882f277882001f73400.
The hover effect just isn't working.
> Revert "Added hover highlight on post card"

- static/js/components/CompactPostDisplay.js
- static/js/storybook/index.js
- static/scss/link.scss
closes #1367 
gets rid of the underline on `:hover` for the post title in compact post display.
make sure that the post title on the compact post display doesn't have an on-hover underline going on.
> add new link style, put it on post-title

- static/js/components/CommentTree.js
- static/scss/comment.scss
Fixes #1321 
Adjusts the `left` value of the css for the dropdown menu to fix alignment
-Open the dropdown for a comment in a channel's 'Reported Content' tab, it should be in the right place.
-Open the dropdown for a comment on a post detail page, it should be in the right place.
> Fix placement of reported comment dropdown

- static/scss/markdown.scss
Fixes #1319 
Includes `word-break: break-word` on styling for links inside elements with the `markdown` style class.
Create a text post and insert a very long URL.  The URL should be wrapped inside the card, and not extend in a single line beyond it.
> Post detail page: improve wrapping of long URLs

- static/scss/channel.scss
Fixes #1387 
Hides the channel avatar on mobile
Verify the UI is unchanged for desktop and the avatar is hidden at mobile widths
> Hid channel avatar on mobile

- fixtures/reddit.py
- search/indexing_api.py
- search/serializers.py
- search/serializers_test.py
Closes #1411 
Adds `post_slug` to post and comment documents in the search index
- Run `docker-compose run web python manage.py recreate_index`
- Query elasticsearch.  Posts and comments returned by ES should include `post_slug`.
> Add `post_slug` to post and comment docs in Elasticsearch index

- static/scss/post-list.scss
Fixes #1414
Aligns sort menu to the right in Mac Chrome/Safari browsers (and hopefully all others).
Check the home page and channel listing page on a Mac: Chrome, Safari, FF.  The sort menu should be aligned to the right.
> Always align sort menu to the right

- static/js/components/auth/AuthEmailForm.js
- static/js/containers/auth/RegisterPage.js
Fixes #1423 
Parameterizes the form submit button label with the old default of "Next", parameterizes as "Sign Up" for that page.
Go to /login and /signup and verify you see appropriate labels.
> Fix login page button label

- static/js/components/ChannelHeader.js
- static/js/components/ChannelHeader_test.js
- static/js/components/SortPicker.js
- static/js/components/SortPicker_test.js
- static/js/containers/ChannelPage.js
- static/js/storybook/index.js
- static/scss/channel.scss
- static/scss/post-list.scss
Part of #1316 
Refactors the channel header to make it a separate component. In a future PR this will be reused on the channel search page. There is also a slight font size change to better match Zeplin:
Before (in master):
After (in this PR):
Click around, nothing should break. Except for the slight font size change everything should look like it did before.
> Refactor channel header

- cassettes/channels.views.channels_test.test_create_channel.json
- cassettes/channels.views.channels_test.test_create_channel_already_exists.json
- cassettes/channels.views.channels_test.test_create_channel_no_descriptions.json
- cassettes/channels.views.channels_test.test_create_channel_noauth.json
- cassettes/channels.views.channels_test.test_create_channel_nonstaff.json
- channels/factories.py
- channels/management/commands/add_index_user_to_channels.py
- channels/serializers.py
- channels/serializers_test.py
- channels/views/channels_test.py
- factory_data/channels.views.channels_test.test_create_channel.json
- factory_data/channels.views.channels_test.test_create_channel_already_exists.json
- factory_data/channels.views.channels_test.test_create_channel_no_descriptions.json
- factory_data/channels.views.channels_test.test_create_channel_noauth.json
- factory_data/channels.views.channels_test.test_create_channel_nonstaff.json
- fixtures/reddit.py
- fixtures/users.py
- profiles/serializers_test.py
Closes #1369
- Creates every channel as the indexing user, then adds the user who is submitting the new channel as a moderator for that channel.
- Adds a management command `add_index_user_to_channels` that will iterate over every `Channel` object and insert the indexing user into the moderators list if not already present.
- On the master branch, while logged in as anyone besides the indexing user, create some channels at `/manage/c/new`.  Add another user or two as moderators to some of the channels.
- Switch to this branch and run `docker-compose run web python manage.py add_index_user_to_channels`.  You should see a bunch of messages like `Channel <name> SUCCESS: Indexing user added or already present`
- There may be errors if you have `Channel` objects that don't actually exist in …
> Add indexing user as first moderator to every channel if not already a moderator

- static/js/components/SearchTextbox.js
- static/js/components/SearchTextbox_test.js
- static/js/storybook/index.js
- static/scss/form.scss
- static/scss/layout.scss
- static/scss/search.scss
Part of #1316 
Adds a search textbox component
Run storybook: `docker-compose run -p 9001:9001 watch npm run storybook` then go to localhost:9001. View the search textbox.
Desktop:
Mobile:
> Add search textbox component

- profiles/admin.py
fixes #1475 
- add an admin view for profile
- search on username, email
- user is a raw field, to avoid the long load time that comes from getting a full list of all users
- thumbnail images are read-only, which I hope will make it easier to save changes to a profile without getting a validation error 
go to /admin/profiles/profile/
> add profile admin

- channels/tasks.py
- channels/tasks_test.py
- search/exceptions.py
Part of #1316 
When the `backpopulate_subscriptions_roles` command is run and it is unable to access a channel, an exception is raised. However Celery assumes the first argument of an exception is a string so this causes another exception, swallowing the original error. 
Add a `Channel` object with a nonexistent name, then run the `backpopulate_subscriptions_roles` management command. You should see an exception raised with a stacktrace and a channel name
> Handle PRAW errors during backpopulate

- static/js/components/DropdownMenu.js
- static/js/components/Toolbar.js
- static/js/components/Toolbar_test.js
- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
- static/js/containers/App.js
- static/js/containers/ProfileImage.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/scss/drawer.scss
- static/scss/dropdown-menu.scss
- static/scss/navigation.scss
- static/scss/post.scss
- static/scss/user-menu.scss
Closes #1404
- Updates navbar and mobile drawer header styling 
- Removes navbar login button and replaces it with an anonymous profile image with dropdown
- Updates some styling in the navbar at desktop widths to match the designs
Look at the app at mobile and desktops widths, compare with the designs: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5bb6295275c1ab10c74353ba
> Updated mobile navbar and drawer header styling

- static/scss/banner.scss
- static/scss/user-menu.scss
closes #1405 
This changes the z-index on two things, the banner and the user menu, so that some stacking order stuff is fixed.
Basically, before there was an issue that caused some of the buttons on the post list view cards to show up on top of the banner (see linked issue for a screenshot). this was easily fixed by setting a sufficiently high `z-index` on the banner, but that then caused some issued with the user menu (specifically, it would appear under the banner...)
So, to get around that, I also added a `z-index` to the user-menu dropdown, so it should float above the banner.
Do something to get a banner to appear. I often change line 18 in `components/material/Banner.js` to look like this:
```js
const activeClass = true ? "banner--active" : ""
```
which makes the banner always …
> fix comment button floating through banner

- mail/templates/email_base.html
Fixes #592 (the last two checkboxes)
Replaces the "MITx MicroMasters" logo with a combination of the "MIT red" logo and site name. Also changes the ALT text to be the site name. 
1. You may need to set `FEATURE_USE_NEW_BRANDING=False` in .env
2. go to http://od.odl.local:8063/__emaildebugger__/ to see if the logic is correct.
3. If you can, send yourself an email to your phone to see if the layout looks ok. 
In my testing, the `__emaildebugger__` view was not sufficient to test the layout for mobile. 
This should not make any changes to the "New" branding, which we haven't turned on in Production yet.
> remove micromasters logo & text in email

- open_discussions/urls.py
- static/js/components/Toolbar.js
- static/js/components/Toolbar_test.js
- static/js/containers/App.js
- static/js/lib/url.js
- static/js/lib/url_test.js
- static/scss/navigation.scss
Fixes #1397 
Adds support for site search with a separate page and a search link on the toolbar (only visible with the feature flag)
Do some searches. You should see results from all channels you have access to
Inactive:
Active:
> Site search

- search/indexing_api.py
- static/js/lib/search.js
- static/js/lib/search_test.js
Fixes #1497 
Fixes #1333 
Adds a field using the [english](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#english-analyzer) analyzer for every `text` field in the mapping. Searches would then use these specific fields for search to make use of stemming and other english-specific analysis. This does not include phonetic or synonym analysis which looks complicated to configure properly (though we can at some later date if we want).
Also changes `author_name` from `keyword` to `text`
Search will be broken after the PR is merged but before the reindex finishes. However the search UI is not yet enabled on production so it shouldn't matter.
Do a search for the plural variation of a word, or a verb with a different tense for example.
> Add english analyzer to Elasticsearch mapping, and update search to use it

- static/js/components/HamburgerAndLogo.js
- static/js/components/Toolbar.js
- static/scss/navigation.scss
closes #1467 
This PR basically adds the site name to the top of the mobile navigation drawer. We have it in the top of the toolbar already, and it was supposed to be on the mobile drawer the same way, but it didn't get added.
Look at the app in a mobile simulator or on a phone and make sure the site name appears at the top of the mobile nav drawer. The toolbar at the top of the page should look as it did before, as should the desktop drawer.
> add the site name to mobile nav drawer

- static/scss/home-page.scss
closes #1484
This just hides the MIT logo on the little greeting card when on a phone.
make sure that the logo disappears on a phone-like device width, and that it appears otherwise.
> CSS tweaks to hide image in greeting card

- cassettes/channels.views.subscribers_test.test_list_subscribers.json
- cassettes/channels.views.subscribers_test.test_list_subscribers_allowed.json
- channels/models.py
- channels/serializers.py
- channels/serializers_test.py
- channels/views/subscribers.py
- channels/views/subscribers_test.py
- factory_data/channels.views.subscribers_test.test_list_subscribers.json
- factory_data/channels.views.subscribers_test.test_list_subscribers_allowed.json
- factory_data/channels.views.subscribers_test.test_list_subscribers_not_allowed.json
Closes #1466
- Allows a list of subscribers to be returned by the API
- Changes serializer and API views for subscribers to query django instead of reddit.
Subscriber API:
- Go to `/api/v0/channels/<channel_name>/subscribers/`.  You should get a list of usernames back on this branch, and a 405 on master.
- Go to `/api/v0/channels/<channel_name/subscribers/<subscriber_name>/`.  You should get the same result on this branch and on master: `{"subscriber_name":  <username>}`
> API to retrieve channel followers (subscribers)

- channels/api.py
- channels/api_test.py
- profiles/models.py
- profiles/serializers_test.py
- search/task_helpers.py
- search/task_helpers_test.py
Fixes #1520 
Modifies `search.task_helpers.update_author` to take a `User` object instead of `Profile` as the input parameter, and tries to update the profile index only if that user is not the indexing user.
- In micromasters, set `OPEN_DISCUSSIONS_API_USERNAME` to a user without a profile.  In discussions, set `INDEXING_API_USERNAME` to the same user.
- Log into micromasters as someone who can create channels.  Create a channel.  No exceptions should occur.
> Do not try to update the profile index for the indexing user

- static/js/lib/picker.js
- static/js/lib/search.js
- static/js/lib/search_test.js
Fixes #1513 
Adds profile search. Users should be able to search profile headlines, bios and names. If a user searches within a channel they should only see profiles associated with that channel in some way. They should be able to search all profiles in site search.
Search various names and click on the link on the profiles. Make sure things look right.
> Enable profile search

- channels/api.py
- channels/api_test.py
- open_discussions/recorder.py
- search/task_helpers.py
- search/task_helpers_test.py
Closes #1358 
- Updates all the post and comment ES index docs for a channel when the channel is changed.
- Search ES for posts and comments within a certain channel, note the values for 'channel_title' and 'channel_type'
- Change the title of the channel.  Search ES again, the values for 'channel_title' should equal the new title.
- Change the type of the channel. Search ES again, the values for 'channel_type' should equal the new type.
> Update index when channel is updated

- static/scss/_variables.scss
- static/scss/comment.scss
Fixes #1462
Updates comment style colors to match Zeplin
View some comments and inspect the styling of the comment author, date, and text.  They should match the colors in [zeplin](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4f573f5019c5726109435).
Mobile:
Desktop:
> Update comment style colors

- static/js/components/SearchResult.js
- static/js/components/SearchResult_test.js
- static/js/containers/SearchPage.js
- static/js/containers/SearchPage_test.js
Partially fixes #1539
Makes the upvote button work for posts in search results.  It does this by adding `toggleUpvote` and `upvotedPost` props to the `SearchResult` component.  `toggleUpvote` is the standard upvote function.  `upvotedPost` is the result returned after the `toggleUpvote` function is dispatched.  An `upvotedPosts` map has also been added to the state of `SearchPage` to keep track of all the posts that have been voted on.
This allows for the upvote buttons to be rendered correctly (black if upvoted, gray if upvote removed) with updated scores after they are clicked.  However, all the buttons will initially be rendered as gray because ElasticSearch has no way of knowing if the current user has already upvoted that post or not.  
- Do a channel-specific search and a global …
> Enable post voting in search results

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/SearchResult.js
Fixes #1551 
Fixes #1541 
- Hides the reply button on search comment cards
- Hides the overflow menu icon on search cards (posts, comments)
Search for posts and comments.  The results should not have overflow menu icons or reply buttons.
On the frontpage and channel pages, post cards should still have overflow menus.
On post pages, replies should still have overflow menus and reply buttons.
Mobile:
Desktop:
> Hide reply and menu icons on search post/comment result cards

- static/js/components/CommentTree.js
- static/js/components/CommentTree_test.js
Fixes #1553
- Hides the share button on comment cards in search results
- Do a global and a channel-specific search.  The comment cards should not display the 'Share' link.
- View a post detail page with comments.  The comment cards should display a working 'Share' link.
> Hide comment share button in search results

- cassettes/channels.views.channels_test.test_patch_title_non_superuser_forbidden.json
- cassettes/channels.views.channels_test.test_update_title_non_superuser_forbidden[patch].json
- cassettes/channels.views.channels_test.test_update_title_non_superuser_forbidden[put].json
- channels/factories.py
- channels/views/channels.py
- channels/views/channels_test.py
- factory_data/channels.views.channels_test.test_update_title_non_superuser_forbidden[patch].json
- factory_data/channels.views.channels_test.test_update_title_non_superuser_forbidden[put].json
- open_discussions/views.py
- open_discussions/views_test.py
- static/js/components/admin/EditChannelAppearanceForm.js
- static/js/containers/admin/EditChannelAppearancePage.js
- static/js/containers/admin/EditChannelAppearancePage_test.js
- static/js/containers/admin/EditChannelBasicPage.js
- static/js/containers/admin/EditChannelBasicPage_test.js
- static/js/flow/declarations.js
- static/js/global_init.js
- static/js/lib/test_utils.js
Closes #1537 
Prevents non-superusers from editing a channel title. Non-superusers will see a disabled title field in the channel appearance settings page, and any request to the API to change the title with a non-superuser will be denied
- Log in as a superuser and a non-superuser. Confirm that the channel title field is enabled and disable (respectively) on the channel appearance settings page
- Try to send a patch request to update a channel in a django shell using the django client. If the client is logged in with a non-superuser and the request data includes a `title` key, it should result in a 403
> Prevent non-superusers from editing a channel title

- search/task_helpers.py
- search/tasks_test.py
- static/js/components/SearchResult.js
- static/js/components/SearchResult_test.js
- static/js/containers/SearchPage.js
- static/js/containers/SearchPage_test.js
Fixes #1539 
Fixes #1559
- Makes comment voting work in search results
- Updates comment scores in the ES index (bug fix)
- Do a channel-specific search and a global search
- Upvote and downvote multiple comments in the search results.  The button styles and comment scores should update appropriately (scores may not change on the first vote if you've already voted on that comment previously - ES doesn't track who voted for what).
- Check the ES doc for a comment before and after voting.  The score should change correctly.
A reindex should probably be done again after this is merged to make sure comments have correct scores.
> Enable comment voting in search results

- static/scss/embedly.scss
closes #1356 
For the 'compact' version of the link display, this just adds a little more padding between the text and the image, and bumps up the font size for the text.
Grab a link (like a nytimes story or something like that), and then make this code change to make it display in the 'compact' mode:
```diff
diff --git a/static/js/components/Embedly.js b/static/js/components/Embedly.js
index 4667bf0c..29ca3e1a 100644
--- a/static/js/components/Embedly.js
+++ b/static/js/components/Embedly.js
@@ -67,9 +67,9 @@ export default class Embedly extends React.Component<Props> {
)
}
-    const compactView =
-      embedly.thumbnail_url &&
-      (embedly.thumbnail_height < 400 || embedly.thumbnail_width < 400)
+    const compactView =true
+      // embedly.thumbnail_url &&
+      // …
```
> small tweaks to embedly 'link' display

- static/js/components/widgets/EditWidgetForm.js
- static/js/components/widgets/EditWidgetForm_test.js
- static/js/components/widgets/NewWidgetForm.js
- static/js/components/widgets/NewWidgetForm_test.js
- static/js/components/widgets/WidgetList.js
- static/js/components/widgets/WidgetList_test.js
- static/js/flow/widgetTypes.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/widgets.js
- static/js/lib/widgets_test.js
Part of #1460 
- Remove errorHandling prop and convert methods referencing it into promises. Unresolved promise rejections will be shown in the console.
- Remove fetchData prop, add functions to `api.js` and replace fetch calls with calls to those functions. There are no tests for the api functions yet because I'm expecting some backwards incompatible changes with the REST API
Nothing to do yet
> Remove errorHandling, use async/await, refactor API functions

- channels/management/commands/backpopulate_missing_posts.py
Closes #1566 
Adds a new command for adding missing `Post` objects to Django. 
- Manually delete a few of your `Post` objects, both text and link types.
- Try to go to a detail page for one of those posts, you should get an error.
- Reindex and verify that they no longer show up in Elasticsearch results.
- Run `docker-compose run web python manage.py backpopulate_missing_posts`
- Your deleted posts and their associated `Comment` and `Metalink` objects should be recreated and added back to the ES index.
> Django management command to create missing `Post` objects

- static/js/components/ArticleEditor.js
- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/scss/article.scss
closes #1549
this adds the ability to edit an 'article' type post.
you should be able to edit an article post. to be able to edit articles, you can follow the setup instructions on the PR that added it, here: https://github.com/mitodl/open-discussions/pull/1557
then you should be able to navigate to an article post and edit it. you should also be able to edit existing text posts as normal, and you should be able to make comments and reply to comments.
> add editing for 'article' type posts

- channels/management/commands/backpopulate_missing_posts.py
Fixed #1585 
Rewrites the logic used to determine if a post type should be `self` or `link`
Follow the same steps as in PR #1567 and make sure that the missing posts are assigned the correct post type.
> Fix post type assignment in backpopulate_missing_posts command

- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/components/admin/EditChannelBasicForm.js
- static/js/components/admin/EditChannelBasicForm_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/admin/EditChannelBasicPage.js
- static/js/containers/admin/EditChannelBasicPage_test.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/js/lib/channels.js
- static/js/lib/channels_test.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
Closes #1517 
Updates the frontend to use `allowed_post_types` for managing channels and which types a user is allowed to post.
- Go to channel settings, verify you can enable/disable article types and the settings are saved
- Go to create a new post, verify the available post types per channel respect their respective channel's settings
Desktop:
Mobile:
> Added support for configuring article post types in the frontend

- channels/proxies.py
Related to #1604 
Fixes an n+1 query for `Article`s that was happening on channel pages/home page
Load one of the pages mentioned above and check your docker log output. You should not see a n+1 warning. You will still see as many HTTP requests as there are posts on the page (that can be addressed in a different PR)
> Fixed article n+1 query

- channels/api.py
- channels/api_test.py
- channels/proxies.py
- channels/serializers.py
Part of #1604 
Attempts to improve performance by eliminating an extraneous call to reddit triggered by a combination of proxy objects and praw's magic missing property logic that triggers a fetch. It appears `PostProxy.article_content` implementation was triggering praw to re-fetch the submission.
See the trace [here](https://rpm.newrelic.com/accounts/1698630/applications/34990656/profiles/2026308) and drill into the frontpage call until you see the `article_content` trigger a `Submission._fetch()`
Performance difference between master and this branch is marginal locally since there's no network latency at play between discussions and reddit.
I couldn't determine a way to test to ensure praw's internals weren't being caused - there's a lot of indrection going on here due to the …
> Fixed performance issues around proxies and DB queries

- channels/admin.py
Possible fix for #1606 
This is a theoretical fix for the 500 errors, there is a cursor error on the page in RC, and the only field that could plausibly cause this is the widget list selector.
Ensure you can view the channel admin detail page and that the widgetlist option is gone.
> Remove the widget list from the channel admin

- static/js/actions/ui.js
- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/ProfileEditPage_test.js
- static/js/lib/api.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/js/lib/test_utils.js
part of #1583 
This adds a confirmation dialog if the user tries to remove the post content from their post (click the little 'x') and they have already added some input. If they haven't made any input (typed in a url, text post, or article) we don't put up the confirmation.
I just did my best guess as to what the copy should be.
Go to the post creation page. If you click the post-type buttons you should be able to click the 'x' and it should clear away the input straightaway. If you click a post-type button and then add some input, it should confirm before it clears it away. Cancelling with the dialog should not clear away your input.
> require confirmation when the user switches post types

- static/js/hoc/withSingleColumn.js
Closes #1357
Sets content page width to 8 columns instead of 12 for all pages that use the `withSingleColumn` HOC.
View all pages that use `withSingleColumn` in desktop and mobile mode and verify that they look correct as described in the issue.
**Create a post desktop:**
**Create a post mobile:**
**Channel page desktop**
**Channel page mobile**
**Post detail page desktop**
**Post detail page mobile**
**Home page desktop**
**Home page mobile**
**Profile page desktop**
**Profile page mobile**
> Change page width from 12 to 8

- search/management/commands/recreate_index.py
None
Exceptions raised in the `start_recreate_index` task are being caught and returned as strings to workaround a celery exception handling limitation. This adds code to fail the management command if an error is received.
Change the mapping to have some incorrect syntax so that Elasticsearch errors right away when reindexing. Run `recreate_index` on master and note that the management command succeeds. Switch to this branch, restart celery and rerun the management command. You should see an error in the command line.
On both master and this PR, you should see the exception stack trace in the celery output, and this exception will get logged to sentry.
> Fix recreate_index error handling

- channels/api.py
- channels/proxies.py
- channels/utils.py
- channels/utils_test.py
- fixtures/reddit.py
- search/api.py
- search/api_test.py
- search/indexing_api.py
- search/serializers.py
- search/serializers_test.py
- search/task_helpers.py
- search/task_helpers_test.py
- static/js/lib/search.js
- static/js/lib/search_test.js
Fixes #1519 
Adds `cover_image` and `article_content` fields to the profile documents in the search index. The `article_content` field is also parsed to be searchable.
Create an article then view it in search. It should look exactly the same as it does on the post list page.
> Article search

- static/js/components/widgets/WidgetInstance.js
- static/js/components/widgets/WidgetList.js
- static/js/containers/widgets/WidgetListContainer.js
- static/js/containers/widgets/WidgetListContainer_test.js
- static/js/factories/channels.js
- static/js/factories/comments.js
- static/js/factories/posts.js
- static/js/factories/util.js
- static/js/factories/widgets.js
- static/js/flow/widgetTypes.js
- static/js/lib/util.js
- static/js/lib/widgets.js
- static/js/lib/widgets_test.js
Fixes #1626 
Fixes #1637 
- Adds a new temporary widget id for new widgets
- Adds a function to create a key based on the new widget id, or the widget's own id for existing widgets
- Fixes the `WidgetInstance` key value to be based on the widget instance key instead of the index value. This fixes the reordering bug which was due to click handlers not being reattached after the widget instances moved. We were using the index value in the list as the key because that's how it worked in the draghandler example code here: https://github.com/clauderic/react-sortable-hoc/blob/master/examples/drag-handle.js
- Start editing widgets and make sure you have at least three. You should be able to reorder the widgets arbitrarily, as many times as you want. When you click 'Done' the new order should …
> Fix handling of widget ids

- static/js/components/SearchTextbox.js
- static/js/components/SearchTextbox_test.js
Fixes #1538
Sets the focus to the search textbox input when it is displayed.
- Click the search icon for a channel.  The focus should move to the search text input field after it is rendered.  Run a search, then click the X to clear the search text.  The focus should still be on the input field.
- Do the same for the global search icon.
> Search text input focus

- package.json
- static/js/components/ArticleEditor.js
- static/js/components/CreatePostForm.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
- static/js/storybook/index.js
- static/scss/article.scss
- static/scss/form.scss
- yarn.lock
this does most of #1583  
closes #1572 
This makes a few UI tweaks to the post creation page, specifically with reference to the article post type.
- the title field is renamed to 'headline', and is styled to more closely resemble how it will be styled on the post detail page
- the top menu for the article editor is now 'sticky', so it should stick to the top of the viewport if you scroll down on a long post
- these is now a placeholder when the article editor is empty
- the article editor should focus right away when you open it
- some styling tweaks to the article editor, the size of the icons in the bar, etc
- when you open the article editor, the navigation drawer should close, if open
I think that's about it
poke at the article editor a bunch and make sure nothing is weird. I think …
> Ckeditor / create post page appearance tweaks

- channels/serializers/posts.py
- channels/views/posts_test.py
- channels/views/test_utils.py
- fixtures/reddit.py
- search/indexing_api.py
- search/serializers.py
- search/serializers_test.py
- static/js/factories/posts.js
- static/js/factories/search.js
- static/js/flow/discussionTypes.js
- static/js/flow/searchTypes.js
- static/js/lib/search.js
- static/js/lib/search_test.js
fixes https://github.com/mitodl/open-discussions/issues/1635
fixes #1636
Adds `post_type` and `article_text` to the REST API so we can use this information in the post summary card
> Add article_text and post_type to REST API

- static/js/babelhook.js
- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/flow/discussionTypes.js
- static/js/lib/api.js
- static/js/lib/api_test.js
- static/js/lib/forms.js
- static/js/lib/forms_test.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/scss/create-post.scss
closes #1594 
This PR implements an initial version of the cover image for the article post type, which lets you upload a photo to use with the article type post.
Basically, there is a new input on the create post post, which we show alongside the article editor, which lets the user select an image to upload. I also added stuff to have some basic validation (just that the thing is an image and not, say, a PDF).
I think just mess around on the create post page and make sure all existing functionality works as it should. Make sure that if you make an article post you can add a cover image, and that this cover image gets returned by the post API afterwards.
> add cover image to create post form

- static/js/lib/api_test.js
none
fixes a flakey thing in a JS test. basically when there is a value of -0 `JSON.stringify` will turn that into just 0, which is sensible. However, it seems that sometimes our post factories set a value of -0 for a score. this was causing a flaky test on something I changed for #1660 (see this test failure for an example: https://travis-ci.org/mitodl/open-discussions/jobs/477491161#L2383).
tests should pass and changes should look legit. If you want check out the branch and run the test a few hundred times to assure yourself it isn't flakey any longer.
> fix JS flakeyness

- widgets/serializers/markdown.py
- widgets/serializers/rss.py
- widgets/serializers/url.py
- widgets/serializers/utils.py
- widgets/serializers/widget_instance.py
- widgets/views_test.py
Fixes #1592 
Adds a description field to the widget types. Some labels are adjusted too. No frontend changes are made in this PR, that will be handled in #1654 
View a channel page. Widgets should load correctly. Open the network tab and look at the `/api/v0/widget_lists/...` and look at the response. You should see a `description` field in the `available_widgets` for each item in the list.
> Add description for widget instances

- open_discussions/urls.py
- open_discussions/urls_test.py
Fixes #1683
Fixes our post slug URL pattern to accept unicode characters
The test cases that were added should be sufficient
The alternation in the regex (`|`) makes the match slower, but I don't think it should have any real performance impact. I used `timeit` to compare the new regex with the old. The results for 100,000 runs were ~0.5 and ~0.2 respectively
> Fixed URL patterns to match post slugs with special characters

- channels/tasks.py
- channels/tasks_test.py
Closes #1670
Creates `ChannelGroupRole` objects when running the `populate_user_roles` task used by the `backpopulate_subscriptions_roles` command
Delete any existing `ChannelGroupRole` and `Group` objects in your database.  Run the `backpopulate_subscriptions_roles` command. Your count of `ChannelGroupRole` objects should be 2x your count of `Channel` objects.
> Create ChannelGroupRoles in populate_user_roles function

- static/js/components/CreatePostForm.js
- static/scss/button.scss
closes #1644 
This makes a few adjustments to the post type buttons on the post create form to make them fit a little better on mobile (especially when the article UI flag is turned on).
Basically before, with the article post type button, some of the buttons could get squashed too much on a phone, so that the text in them would be forced on to two lines, like this:
This removes the icons and adjusts the font-size and padding to fix this issue.
The create post page should look nice and be usable at all screen widths, things should always be spaced out nicely and the button text shouldn't be forced on to two lines at any screen width.
> remove icons from post type buttons on create post page

- static/js/components/CommentForms.js
- static/js/components/CommentForms_test.js
- static/js/components/CoverImageInput.js
- static/js/components/CoverImageInput_test.js
- static/js/components/CreatePostForm.js
- static/js/components/CreatePostForm_test.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/components/admin/EditChannelAppearanceForm_test.js
- static/js/containers/CreatePostPage.js
- static/js/factories/posts.js
- static/js/factories/search.js
- static/js/flow/discussionTypes.js
- static/js/flow/searchTypes.js
- static/js/lib/api/posts.js
- static/js/lib/api/posts_test.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/js/lib/search.js
- static/js/lib/search_test.js
- static/js/lib/test_utils.js
- static/scss/button.scss
- static/scss/cover-image.scss
- static/scss/create-post.scss
- static/scss/layout.scss
closes #1492 
closes #1664 
A few things. Basically this adds:
- the ability to remove a cover image you've already added when creating a new post (like if you clicked the wrong picture accidentally or something).
- displaying the cover image on the post detail page, if one has been added for the article post in question
- editing the cover image for an article post that you've already created
I think just make sure that all the functions mentioned above work as they should, and that existing editing / post creation function works correctly for all kinds of posts.
> round out article cover image UI

- cassettes/channels.views.posts_test.test_update_article_cover.json
- channels/api.py
- channels/serializers/posts.py
- channels/views/posts_test.py
- factory_data/channels.views.posts_test.test_update_article_cover.json
Closes #1691
- Removes an article cover image if `article_cover` is not sent with a patch request.
- Prevents an exception from occurring if `article_cover` in the patch request is a URL instead of an uploaded file (which happens on master when editing an existing article but leaving the cover as is).
- Edit an article with a cover image.  Change the text but not the cover image.  Save.  You should not see an exception when the post detail page reloads, and the cover image should still exist.
- Edit the article again.  Remove the cover image.  Save.  You should not see an exception when the post detail page reloads, and the cover image should be gone.
> Allow article cover images to be deleted

- static/js/components/auth/AuthPasswordForm.js
- static/js/components/auth/AuthPasswordForm_test.js
closes #1665 
this just sets the `autoFocus` prop on the password page input tag, which causes it to grab focus when it mounts. This makes it so that if you're logging in to the app the password field will be focused automatically after you type in your email and hit enter :tada: 
make sure that the behavior described above works as advertised, and that nothing is weird or broken because of it.
> add autoFocus prop to password input

- static/scss/post.scss
none
small tweak to cover image CSS (just setting `width: 100%`).
make sure that article posts with cover images added them display consistently at all widths, with images of all different sizes, on the post detail page. it should basically always constraint the image width to the width of the post, and the image should retain it's natural aspect ratio (not get squished at all) at any width.
> small adjustment to cover image styling

- package.json
- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
- static/scss/_variables.scss
- static/scss/comment.scss
- static/scss/post.scss
- yarn.lock
Partially addresses #1426
Adds a preview for post/article text content to the post summary card, and truncates it with an ellipsis if it has more than 2 lines of text.
- Check that a post/article with a lot of text is truncated in the post summary card
- Check that a post/article less than 2 lines of text is not truncated
- Check that a link post renders as normal
Design reference: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4e6e6c699e4552e267660
> Added truncated post content preview to post summary card

- package.json
- yarn.lock
closes #1696 
upgrades our prosemirror-markdown package.
tests should pass and you shouldn't be able to reproduce the issue on the linked issue.
> fix prosemirror-markdown issue

- static/js/lib/api/posts.js
- static/js/lib/api/posts_test.js
closes #1727 
makes post pinning work again. I goofed when I was working on https://github.com/mitodl/open-discussions/pull/1676. this fixes it.
you should be able to:
- pin a post
- subscribe to a post
- 'ignore reports' on a post
> fix post pinning

- static/js/components/CommentForms.js
- static/js/components/CompactPostDisplay.js
- static/js/components/ExpandedPostDisplay.js
- static/js/components/ExpandedPostDisplay_test.js
- static/js/containers/PostPage_test.js
- static/js/flow/discussionTypes.js
- static/js/flow/searchTypes.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
closes #1652 
Basically this just uses the relatively-new `post_type` value to decide what UI to show or which logic to use in a few places where we need to do different things based on the post type. I went through and changed everywhere that I could think of, but if I missed somewhere where it would make sense to do this refactor as well plz point it out.
Everything should be working as it was before.
Additionally, 'title only' posts (essentially empty text posts) should now be editable, whereas before they were not (because we used the value of `post.text` to figure out if a post should be editable or not).
> use the `post_type` field for post-type specific UI

- static/js/components/Loading.js
- static/js/containers/SearchPage.js
- static/js/containers/SearchPage_test.js
Closes #1552
Uses a new `SearchLoading` function to ensure the loader displays correctly on initial load of channel search pages.
Go to the search page for a channel.  The loader should briefly appear and not take up the full width of the page.  Perform a search, the loader should appear again and still not take up the full width of the page.
> loading width fix for search pages

- static/scss/dropdown-menu.scss
closes #1728 
a little CSS tweak to make sure that the click areas for the dropdown menus are not so small.
you should be able to more comfortably click the elements in the dropdown menus. The menu that shows this the most clearly is the post menu, which includes the pin option (which is quite narrow).
before the click target where you could actually trigger the action was only the text itself. now it's sort of that whole row (read the issue for details).
> fix dropdown menu click targets

- static/js/containers/PostPage.js
- static/js/containers/PostPage_test.js
closes #1686
This fixes an issue where we were not closing the post delete dialog on the post page when we should have been.
confirm you can reproduce the problem described on the linked issue on master, then confirm that this branch fixes it.
> fix issue with post dialog staying open

- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/Loading.js
- static/js/lib/posts.js
- static/scss/post-list.scss
- static/scss/post.scss
Closes #1733 
Updates post summary card styling (see issue for details)
- Load a post listing page (channel page, front page, profile post feed)
- Check that the buttons and report count appear on the left side with no styling weirdness
- Check that the card looks good at various screen widths
Uploaded cover images for articles have hardcoded dimensions of 201px x 103 px, so they cannot expand vertically to fill the space. We decided to increase the size of link thumbnails from embedly in such a way that they appear larger with the same aspect ratio (and thus occupy more vertical space) and just increase the displayed width of user thumbnails. For that reason, the two different types of thumbnails will have different heights, but should have the same width
> Updated post summary card styling

- static/js/containers/SearchPage.js
- static/js/containers/SearchPage_test.js
Closes #1505
Sets the `initialLoad` setting of the `InfiniteScroller` component to `true` if `from` === 0
- Make your browser window as tall as possible.  Then run a search that you know will return a decent number of results.  On the master branch, the `Loading` component will display until you move the page.  On this branch, it should appear only very briefly before loading the next set of results.
- Make your browser too short to display the initial results, and open the network tab.  Reload the page.  The search API should only be called once.
> Fix search loading height issue

- package.json
- yarn.lock
None
Upgrades some dependencies to fix a warning: `caniuse-lite is outdated. Please run next command yarn upgrade caniuse-lite browserslist`
> Upgrade dependencies to fix browserslist warning

- static/js/factories/widgets.js
None
The widget factory sometimes creates a RSS feed widget with zero entries. This changes it to have at least one entry so that the tests don't fail.
N/A
> Fix flaky test

- static/js/lib/api/api.js
- static/js/lib/api/api_test.js
- static/js/lib/api/comments.js
- static/js/lib/api/comments_test.js
- static/js/reducers/comments.js
- static/js/util/integration_test_helper.js
part of #1667 
just moves some code around, moving the comment-related functions out into a separate API module.
I think just make sure that you can do all of the comment actions that should be supported, like creating, deleting, editing, etc.
> split comments API functions off of `lib/api/api.js`

- static/js/components/ArticleEditor.js
- static/js/components/ArticleEditor_test.js
- static/js/lib/embed.js
closes #1457
This adds support for using embedly to display media embeds instead of CKEditor's built-in support (which supports only a very limited number of sites, like youtube and so on).
Basically now any site that is supported by embedly should work just fine. You can either add media embeds to the editor by using the button in the paragraph menu, or you can just paste in a link.
Make sure that if you are making an article you can add media to it. it should show up as an embedly card.
Make sure everything works equally well on the create post page, the post detail page, and editing an existing post.
> add embedly support to the Article editor

- channels/serializers/channels.py
- channels/serializers/channels_test.py
- channels/views/channels_test.py
- channels/views/test_utils.py
- static/js/components/Arrow.js
- static/js/components/ChannelHeader.js
- static/js/components/ChannelHeader_test.js
- static/js/components/Picker.js
- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
- static/js/containers/ChannelFollowControls.js
- static/js/containers/ChannelFollowControls_test.js
- static/js/containers/ChannelSettingsLink.js
- static/js/factories/channels.js
- static/js/flow/discussionTypes.js
- static/js/util/api_actions.js
- static/js/util/api_actions_test.js
- static/scss/_variables.scss
- static/scss/button.scss
- static/scss/channel.scss
Closes #1663
Adds button to follow channel and controls to unfollow or leave channel to the channel header
Try the follow button and both "following" menu options, and test the UI at different screen widths
The [design](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5bd9df8815d2791b648ee414) shows a "Following" button that looks like it has white text with a transparent background, but I was concerned that depending on the channel header image it wouldn't be visible. I kept the same styling as the "Follow" button [here](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4e7e0a4dc98a7608ee6b5)
> Added button to follow/unfollow channel

- static/js/components/widgets/MarkdownWidget.js
- static/js/components/widgets/MarkdownWidget_test.js
- static/js/components/widgets/RssWidget.js
- static/js/components/widgets/RssWidget_test.js
- static/js/components/widgets/UrlWidget.js
- static/js/components/widgets/UrlWidget_test.js
- static/js/components/widgets/WidgetInstance.js
- static/js/components/widgets/WidgetInstance_test.js
- static/js/components/widgets/WidgetList.js
- static/js/components/widgets/WidgetList_test.js
- static/js/containers/widgets/ManageWidgetHeader.js
- static/js/containers/widgets/ManageWidgetHeader_test.js
- static/js/containers/widgets/WidgetListContainer.js
- static/js/containers/widgets/WidgetListContainer_test.js
- static/js/flow/widgetTypes.js
- static/js/storybook/index.js
- static/scss/widget.scss
Fixes #1661 
Implements expanding and collapsing widgets. 
Click 'manage widgets'. All of the widgets should be editable and in a collapsed state. You should be able to delete, reorder, and edit widgets.
Click the 'Expand all' link. You should see all widget instances be expanded. The link should become 'Collapse all'. Click it again and it should collapse all widgets.
Click the downward arrow icon next to a single widget. You should be able to toggle whether that widget instance is collapsed or not, without affecting any of the others.
Click '+ Add Widget'. Add a new widget. It should show up at the bottom in a collapsed state. You should be able to expand and collapse it just like the other widget instances, and the 'Collapse all'/'Expand all' link should also affect it.
Also verify …
> Collapse and expand widgets

- channels/views/subscribers.py
- open_discussions/permissions.py
- open_discussions/permissions_test.py
No ticket - fixes bug w/ #1754 
Changes subscriber permission to allow users to add/remove their own channel subscriptions
Log in as a non-staff, non-mod user and try to follow/unfollow a public channel on the channel detail page. Also try this with a mod user
> Fixed subscriber permission to allow self-editing of channel subs

- channels/api.py
- channels/backpopulate_api.py
- channels/backpopulate_api_test.py
- channels/management/commands/backpopulate_posts.py
- channels/tasks.py
- channels/tasks_test.py
- fixtures/common.py
Fixes #1756 
Adds a command that walks all posts and comments and populates them based on values in reddit. It is intended that this operation is fairly idempotent, although there are probably some unavoidable race conditions around certain operations like voting where we don't have strict guarantees of atomicity across all our storage mediums.
Note: the script ignores posts in channels that aren't in the DB.
Run `./manage.py backpopulate_posts` and ensure the resulting data and reported numbers in the output match what you'd expect based on your local environment.
> Backpopulate all posts and comments

- static/js/components/EmbedlyCard.js
- static/js/components/EmbedlyCard_test.js
- static/js/components/widgets/MarkdownWidget_test.js
- static/js/components/widgets/RssWidget_test.js
- static/js/components/widgets/UrlWidget_test.js
- static/js/components/widgets/WidgetEditDialog.js
- static/js/components/widgets/WidgetEditDialog_test.js
- static/js/components/widgets/WidgetField.js
- static/js/components/widgets/WidgetField_test.js
- static/js/factories/widgets.js
- static/js/factories/widgets_test.js
- static/js/lib/constants.js
- static/js/lib/embed.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/js/lib/validation.js
- static/js/lib/validation_test.js
- static/js/lib/widgets.js
- static/js/lib/widgets_test.js
- static/js/storybook/index.js
- widgets/factories.py
- widgets/serializers/widget_list.py
- widgets/serializers/widget_list_test.py
Fixes #1791
Adds front-end validation for URL for the RSS URL field and the Embedly URL field. Also updates the URL validation to require the protocol prefix so that the Django URLField will not fail validation.
Try to add or edit an embedly widget to have "mit.edu" as the URL, without any "http" part. You should not see any embedly rendering for that, and you should see a validation error saying the URL is invalid.
Change the URL to a different one with the "http" prefix. You should now see some embedly rendering. Save the dialog, then click "Done". The changes should persist correctly.
> Add validation to widget configuration inputs, fix URL validation

- channels/tasks.py
- channels/tasks_test.py
Fixes #1807 
Forces a fetch so nonexistent submissions don't fail the whole task
Run the backpopulate for a post that doesn't exist (use a high value id). Example that will probably work for your local: `./manage.py backpopulate_posts --post "zzzzzz"`
It should break the task on master, but only log a warning in this branch.
> Fixed exception with lazy submissions

- channels/views/contributors.py
- channels/views/contributors_test.py
- open_discussions/permissions.py
- open_discussions/permissions_test.py
- static/js/components/ChannelHeader.js
- static/js/components/ChannelHeader_test.js
- static/js/containers/ChannelFollowControls.js
- static/js/containers/ChannelFollowControls_test.js
Fixes #1769 
- Changes permissions so non-mod users can remove themselves as channel contributors
- Changes the logic for showing the channel "Leave" button so that it shows up only for non-moderators
- With a non-mod user, go to a channel detail page where the user is a contributor and click the "Leave Channel" option in the "Following" dropdown. You should no longer be a contributor and you should be sent back to the home page.
- With a mod user, make sure the "Leave" option isn't available
Reddit doesn't seem to like the idea of a contributor being removed by a non-moderator, even if it's the user doing it on their own behalf. That's the reason for the admin API usage. The fact that reddit doesn't allow this makes me wonder if we need to think about this a little more...
> Fixed contributor delete permissions and changed logic for showing leave channel option

- static/scss/close-button.scss
closes #1777
this adjusts the z-index on the `CloseButton` component so that it doesn't appear to be spookily floating above the dialog box any longer.
Make sure you can reproduce the problem described in the linked issue, then confirm that this fixes it.
> fix the thing

- static/js/components/Editor.js
- static/js/components/Editor_test.js
- static/scss/add-link-menu.scss
Fixes #1805 
It seems like there's a race condition between the `setState` and the creating of the form via redux. To workaround this the visibility check is updated to make sure the form exists before rendering it.
Start managing widgets. Add a new rich text widget. In the interface add a link. On master this will cause an exception but it should work fine on this PR.
There's a CSS change I needed to make so that all the items in the link dialog fit within it on Firefox. There are some changes with the width of the text fields, see the screenshots below.
Chrome + PR + create post
Chrome + PR + widget edit
Firefox + PR + create post
Firefox + PR + widget edit
Chrome + master + create post
Chrome + master + widget edit
Broken
Firefox + master + create post
Firefox + master + widget edit …
> Fix link menu when editing rich text widget

- channels/backpopulate_api.py
- channels/backpopulate_api_test.py
Fixes #1812 
Backpopulate was previously only walking top-level comments
- Delete all comments for a post that has nested comments
- Run `./manage.py backpopulate_posts` and ensure you see all the records reappear
> Switch backpopulate over to the list() api

- static/js/components/CompactPostDisplay.js
- static/js/components/CompactPostDisplay_test.js
- static/js/components/TruncatedText.js
- static/js/components/TruncatedText_test.js
- static/js/lib/posts.js
- static/js/lib/posts_test.js
Fixes https://github.com/mitodl/internal/issues/13
Fixes bug with preview text for posts including a base64-encoded image.
- Go through the steps to reproduce in the linked issue. The bug behavior should no longer happen on this branch
- Make sure that all of your posts look correct in the post listing views (channel pages, front page, profile page)
> Fixed bug with preview text for posts including a base64-encoded image

- docker-compose.yml
Closes #1810 
Bumps our Elasticsearch docker image version to 6.5.4
- Run the `recreate_index` management command
- Search for some posts/comments on the search page and check that results are as expected
- Perform some index-updating tasks (e.g.: creating a new post), then run a search that will yield the new/updated document(s) and make sure those changes have been reflected in the index
- The latest version of ES is 6.6, but [there isn't a published docker image for that version yet](https://hub.docker.com/_/elasticsearch)
- @blarghmatey: Merging this will probably require some ops magic on your end
- I'm pretty sure we'll need everyone to run `recreate_index` after this merges
> Bumped Elasticsearch docker image version to 6.5.4

- open_discussions/exceptions.py
- open_discussions/exceptions_test.py
Fixes #1793 
Logs api validation errors to sentry
You could configure sentry locally and try to submit an invalid API request (e.g. create a post with an empty payload). Or this is simple enough and you can see a test one I triggered in sentry here: https://sentry.io/mit-office-of-digital-learning/discussions/issues/874913945/?query=is%3Aunresolved
> Added reporting of validation errors to sentry

- course_catalog/tasks.py
Fixes #1831 
Replaces `@task` with `@app.task`
Everything should still work, including `manage.py backpopulate_edx_data`
> replace @task with @app.task

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/ISSUE_TEMPLATE/rfc_template.md
- .github/pull_request_template.md
- docs/rfcs/0000-template.md
N/A, but implemented an RFC template (plus a bug and feature on based on how we often write those) based on the writings in this blog post: https://blog.pragmaticengineer.com/scaling-engineering-teams-via-writing-things-down-rfcs/
Adds some templates for issues and moves the existing PR template into the `.github/` directory to keep clutter down.
N/A
> Added a few issue templates

- static/js/components/widgets/WidgetEditDialog.js
- static/js/components/widgets/WidgetEditDialog_test.js
Fixes #1814 
Sets focus to the submit button so that the default focus is not on the radio button.
Start managing widgets and then click '+ Add Widget'. You should not see any radio buttons highlighted at all.
> Remove automatic focus from dialog radio buttons

- Dockerfile-nb
- README.md
- app.ipynb.example
- docker-compose-notebook.yml
Checklist isn't relevant for this PR
No ticket
What the title says. Now you can run the app in a Jupyter notebook!
- Go through the steps in the README to run a notebook
- Try to fetch a post via `channels.api.Api#get_post`
- Try to create a post via `channels.api.Api#create_post`
- Not crazy about adding another top-level file but I couldn't think of another place to put it
- `.ipynb` files are already gitignore'd
- It will be possible to get around the annoying step of copying the notebook server URL from the docker container logs. Figured that could be done separately
> Created docker container config for running the app in a Jupyter notebook

- docs/rfcs/0002-indexing-embedly-link-preview.md
[Rendered](https://github.com/mitodl/open-discussions/blob/c9a2fc6bf95bafb417801490ac57b36c30726594/docs/rfcs/0002-indexing-embedly-link-preview.md)
RFC for #1811 
Adds an RFC for indexing preview content from Embedly to make link posts searchable.
> RFC: Embedly link preview indexing

- static/js/components/widgets/WidgetEditDialog.js
- static/js/components/widgets/WidgetEditDialog_test.js
Fixes bug from #1848 
Fixes a bug which removes focus every time the dialog changes state, instead of just during radio button selection.
In master you should notice that you can't type in the widget text field. On this PR that should work fine.
> Limit widget dialog focus to widget type selection

- static/js/components/ScrollToTop_test.js
- static/js/containers/CreatePostPage.js
- static/js/containers/CreatePostPage_test.js
- static/js/containers/admin/EditChannelBasicPage_test.js
- static/js/containers/admin/EditChannelContributorsPage_test.js
- static/js/containers/admin/EditChannelModeratorsPage_test.js
closes #1796
This adds a little bit of scrolling to the create post page. Basically the issue is that, if you're editing a very long post or you're working on a short screen, you can scroll down so that the title or channel validation errors are not visible. It won't be clear to the user in that case why the post isn't going through.
What I decided to do to fix the issue is to check when the user submits the post if there is a `title` or `channel` validation error and, if so, do a smooth scroll to the top. This should only be minimally disruptive in cases where you can already see the validation message.
Basically go to the create post page and mess around with very long text and article posts. If you leave the title off, make a very long post, and try to submit it, it should scroll you …
> scroll validations errors into view on post create page
